tests/ci/run_benchmark_build_tests.sh

https://github.com/google/boringssl/commit/2d7f6c6e65a49c04b5ef545f1f3b979a74f89c2c changed how BoringSSL handles installing targets, update our small patch to use the latest way to install libdecrepit
This is to unblock the failing CI. 

Always install libdecrepit for BoringSSL benchmark

---

crypto/stack/stack.c
crypto/stack/stack_test.cc
crypto/x509/x509_req.c
include/openssl/ssl.h
include/openssl/stack.h
include/openssl/x509.h
ssl/ssl_x509.cc

Addresses `V1073444663`
MySQL 8.3 depends on some minor symbols that wrap around our existing functionality. 
1. `sk_X509_unshift`: https://github.com/mysql/mysql-server/blob/mysql-cluster-8.3.0/storage/ndb/src/common/util/NodeCertificate.cpp#L1167-L1173
2. `X509_REQ_get0_pubkey`: https://github.com/mysql/mysql-server/blob/824e2b4064053f7daf17d7f3f84b7a3ed92e5fb4/storage/ndb/src/common/util/NodeCertificate.cpp#L526
3. `SSL_CTX_set1_cert_store`: https://github.com/mysql/mysql-server/blob/824e2b4064053f7daf17d7f3f84b7a3ed92e5fb4/storage/ndb/src/common/util/TlsKeyManager.cpp#L204
There are more symbols incoming, these only encapsulate the less complicated ones.
N/A
Build still needs to be fixed for MySQL 8.3, along with a couple more symbols.
By submitting this pull request, I confirm that …

Various minor functions to support mysql 8.3

---

crypto/x509/internal.h
crypto/x509/x509_vfy.c
crypto/x509/x_crl.c
crypto/x509v3/v3_purp.c
include/openssl/x509.h
include/openssl/x509v3.h

Merging from Upstream considering commits from https://github.com/google/boringssl/commit/3e28180d3a337a524c07c9301a967aaa739a10ec (Nov 17, 2023) to https://github.com/google/boringssl/commit/a4851dd8c67a2b311403d67270e02e7296d31157 (Nov 20, 2023).
See internal document as well as "AWS-LC" notes inserted in some of the commit messages for additions/deviations from the upstream commit.

Upstream merge 2024 03 18

---

tests/ci/integration/python_patch/3.10/aws-lc-cpython.patch
tests/ci/integration/python_patch/3.12/aws-lc-cpython.patch
tests/ci/integration/python_patch/main/aws-lc-cpython.patch

Fix needed after upstream [PR #117351][1].
[1]: https://github.com/python/cpython/pull/117351
- CI checks on PR
---

Fix CPython patches

---

crypto/fipsmodule/rsa/rsa.c

This commit reverts a change done in:
c8bdf891e4d2c276ba0c27efc78b219a56606c6a,
where the RSA PWCT was implemented using RSA_sign/verify API.
According to our FIPS lab we ought to use the approved
EVP_DigestSign/Verify API, which is what we do in this commmit.

RSA key pair-wise consistency test with approved APIs

---

crypto/fipsmodule/digest/digest.c

Resolves P125068189
Add NULL checks to EVP_MD_CTX_cleanse/cleanup.

Add NULL checks to EVP_MD_CTX_cleanse/cleanup

---

include/openssl/ssl.h
ssl/ssl_cipher.cc
ssl/ssl_test.cc

MySQL deprecated the usage of weaker ciphers in their test suite: https://github.com/mysql/mysql-server/commit/bc14366ba3d1127ee6b1e0c84c21033e01b67a36 This brought an additional gap to light, where OpenSSL allows the setting of empty strings in the Ciphersuite string configuration. This is known behavior [since 1.1.1](https://github.com/openssl/openssl/blame/OpenSSL_1_1_1/ssl/ssl_ciph.c#L1311-L1315) and still [exists today](https://github.com/openssl/openssl/blob/master/ssl/ssl_ciph.c#L1348C27-L1353).
I've reconfigured the behavior for `SSL_[CTX]_set_cipher_list` which is our OpenSSL compat layer, but kept the same behavior for `SSL_[CTX]_set_strict_cipher_list`.
N/A
Test tweaking
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

allow empty lists in SSL_CTX_set_ciphersuites

---

.github/workflows/aws-lc-rs.yml

* The aws-lc-rs CI step must use CMake to perform the build.

aws-lc-rs CI step must use CMake to build

---

crypto/rand_extra/rand_extra.c
include/openssl/asn1.h
include/openssl/bio.h
include/openssl/cipher.h
include/openssl/conf.h
include/openssl/dh.h
include/openssl/digest.h
include/openssl/ec.h
include/openssl/ec_key.h
include/openssl/evp.h
include/openssl/ex_data.h
include/openssl/pkcs7.h
include/openssl/rand.h
include/openssl/ssl.h
include/openssl/thread.h
include/openssl/x509.h
include/openssl/x509v3.h
tool/speed.cc

Update porting guide for AWS-LC. This is the second phase which includes updated function documentation.
Originally, this was to include links to the corresponding functions/sections in the new tables as well, but we can't actually provide correct links until we have the correct commit hash in main.
A third phase will link the tables to the corresponding section.

Document no-op functions and flags in AWS-LC

---

tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml

Did a quick audit and these jobs are consistently the slowest and take over an hour to run. 
This is a new bigger instance type for CodeBuild.
This CI. 

Use larger ARM hosts for long CodeBuild jobs

---

.github/workflows/abidiff.yml
.github/workflows/actions-ci.yml
.github/workflows/aws-lc-rs.yml
.github/workflows/cmake.yml
.github/workflows/codecov-ci.yml
.github/workflows/cross-test.yml
.github/workflows/integrations.yml
.github/workflows/windows-alt.yml

* Align our GitHub workflows/jobs so that they all run on the same conditions.
* Avoid costly CI runs when on non-"aws" repos.
* The "General CI Tests sanity-test-run" and "Code Coverage codecov-ci" jobs will still run on any repo that has GitHub actions enabled.

Align GitHub workflow/job run conditions

---

tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
tests/ci/docker_images/linux-x86/build_images.sh
tests/ci/docker_images/linux-x86/push_images.sh
tests/ci/docker_images/linux-x86/ubuntu-22.04_gcc-10x/Dockerfile

Addresses `P125414272`
This change adds a new CI dimension for gcc-10 with non-fips/fips.
N/A
New CI for gcc-10

Add non-fips/fips ci for gcc-10

---

crypto/rand_extra/forkunsafe.c

The `g_buffering_enabled` can not be changed on Windows.  Removes unnecessary locking for this platform.

`rand_fork_unsafe_buffering_enabled` always 0 on Windows

---

.github/workflows/windows-alt.yml
crypto/bytestring/cbs.c
crypto/fipsmodule/ecdsa/ecdsa.c
crypto/fipsmodule/rsa/rsa.c

Resolves: 
* https://github.com/aws/aws-lc-rs/issues/397
* Perform "release" build for MinGW in the CI.
* Address several GCC 12/13 warnings

Release build for MinGW CI; Fix GCC 12/13 warnings

---

util/fipstools/delocate/delocate.go
util/fipstools/delocate/delocate_test.go
util/fipstools/delocate/testdata/x86_64-FourArg/in.s
util/fipstools/delocate/testdata/x86_64-FourArg/out.s

P125414272
Instead of generating portable code, gcc can be configured with e.g. `march=cpu-type` that allows it to generate code using instructions from instruction sets supported on up-to `cpu-type`.
In one of these cases, we for example saw:
```
[ 62%] Generating bcm-delocated.S
error while processing "\tvpinsrq\t$1, EVP_PKEY_CTX_dup@GOTPCREL(%rip), %xmm1, %xmm0\n" on line 27676: "GOT access must be source operand, instrOther"
```
In this case, the compiler tries to be smart and get the necessary memory addresses for `EVP_PKEY_CTX_free` and `EVP_PKEY_CTX_dup` to populate `EVP_MD_pctx_ops ` e.g.:
```
vmovq   EVP_PKEY_CTX_free@GOTPCREL(%rip), %xmm1
vpinsrq $1, EVP_PKEY_CTX_dup@GOTPCREL(%rip), %xmm1, %xmm0
vmovdqa %xmm0, -16(%rbp)
```
This fails because `vpinsrq` is not supported in the …

Support vpinsrq in delocater

---

tests/ci/integration/run_ntp_integration.sh

N/A
Fix the NTP integration test (NTP website changed).
Here is how the webpage looked like previously: https://web.archive.org/web/20240104114229/https://www.ntp.org/downloads/.
Here is the new one: https://downloads.nwtime.org/ntp/

Fix the NTP integration test (NTP website changed)

---

crypto/fipsmodule/self_check/fips.c
crypto/fipsmodule/self_check/self_check.c

* Add SHA3-256 KAT to FIPS self-test
* The KAT was taken from here: https://github.com/aws/aws-lc/blob/52834938a5d709bcd8b838b249ee8e5a3954c5d0/crypto/fipsmodule/sha/testvectors/SHA3_256ShortMsg.txt#L65

Add SHA3-256 KAT to FIPS self-test

---

.github/workflows/actions-ci.yml

* Adds basic CI build/test with all GH available GCC/Clang compilers on Ubuntu.
* This a supplement to the more exhaustive testing done in CodeBuild for many (but not all) of the same compilers.

Basic GH CI build/test with full range of gcc/clang

---

docs/porting/configuration-differences.md
docs/porting/functionality-differences.md
include/openssl/ssl.h
include/openssl/x509.h

This finalizes the changes for the previous two documentation PRS: https://github.com/aws/aws-lc/pull/1463 and https://github.com/aws/aws-lc/pull/1473. Now that these two PRs are in, we have a commit to link the header documentation from the table.
N/A
N/A

Link porting guide table to header documentation

---

.github/workflows/actions-ci.yml
.github/workflows/integrations.yml

Fix Github actions to work with Ubuntu 24.04
Ubuntu 24.04 does not provide the Python package six by default, contrary to previous Ubuntu versions. This causes issues with the integrations:grpc action.
N/A
N/A (just a change in dependencies in integrations tests)

Add dependency to python3-six in github action grpc

---

include/openssl/x509.h

Resolves https://github.com/aws/aws-lc/issues/1556
Remove the duplicate X509_OBJECT_new and X509_OBJECT_free declarations from https://github.com/aws/aws-lc/pull/1506.
I'm still looking into why our CI didn't catch this and what we can add that would catch this in the future. 

Remove duplicate X509_OBJECT_new and X509_OBJECT_free declarations

---

crypto/curve25519/x25519_test.cc

Resolves V1360237371
Avoid a [GCC 13 bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114826) by initializing the test vector separately.  This test still needs the `= {}` to zero initialize the entire array. 
This isn't tested in the CI because we don't want to test all march/compiler combinations at this time, this support is best effort for now. 
```
docker run -v `pwd`:`pwd` -w `pwd` -it gcc:13
apt update && apt install cmake ninja less -y
export CFLAGS='-march=haswell -mcrc32'
export CXXFLAGS='-march=haswell -mcrc32'
cmake -GNinja ../
ninja run_tests
```

Update x25519_test.cc array initialization to avoid a bug with a GCC 13 warning

---

CMakeLists.txt
crypto/evp_extra/internal.h
crypto/fipsmodule/cpucap/cpu_intel.c
crypto/fipsmodule/evp/evp.c
crypto/fipsmodule/evp/evp_ctx.c
crypto/fipsmodule/sha/sha1-altivec.c
third_party/s2n-bignum/include/s2n-bignum_aws-lc.h

Addresses https://github.com/aws/aws-lc/issues/1556
Fix a few other cases of duplicate definitions and turn this on so the CI can catch this in the future. 
We own this s2n-bignum header file.
We have GCC CI for x86/ARM.

Cleanup remaing duplicate symbol definitions and turn Wredundant-decls on

---

crypto/fipsmodule/rand/urandom.c

Resolves https://github.com/aws/aws-lc/issues/1557
[`__FreeBSD__`](https://docs.freebsd.org/en/books/porters-handbook/porting-dads/#porting-versions) doesn't seem to be as well supported (or as accurate) as `__FreeBSD_version`. This change migrates to [`__FreeBSD_version`](https://docs.freebsd.org/en/books/porters-handbook/versions/#versions) which appears to be the recommended way to check for versions. 
`__FreeBSD_version` is defined in [`sys/param.h`](https://cgit.freebsd.org/src/tree/sys/sys/param.h#n76)
We don't have FreeBSD in our CI, a similar but not exactly the same change was tested by the requester in https://github.com/aws/aws-lc/issues/1557.

Migrate from __FreeBSD__ to __FreeBSD_version

---

crypto/fipsmodule/FIPS.md
crypto/fipsmodule/rand/rand.c

AWS-LC does not overread entropy sources in FIPS mode. This commit is to clarify this and remove/rephrase comments mentioning overread.
Only changes documentations & comments. No code change.
Only changes documentations & comments. No code change.

Remove comments about overread for entropy generation

---

crypto/CMakeLists.txt
crypto/cipher_extra/derive_key.c
crypto/decrepit/obj/obj_decrepit.c
crypto/fipsmodule/bn/bn.c
crypto/fipsmodule/cipher/cipher.c
crypto/pkcs8/internal.h
include/openssl/bn.h
include/openssl/cipher.h
include/openssl/evp.h
include/openssl/obj.h

First round of minor APIs for Ruby support. These encapsulate the APIs needed to build Ruby's cipher module.
* https://github.com/ruby/ruby/blob/ruby_3_1/ext/openssl/ossl_cipher.c
* https://ruby-doc.org/stdlib-2.4.0/libdoc/openssl/rdoc/OpenSSL/Cipher.html
1. `PKCS5_SALT_LEN` was exposed from our existing internal definitions.
2. `OBJ_NAME_do_all_sorted` already existed in AWS-LC prior to our decrepit removal: https://github.com/aws/aws-lc/commit/abbbd0045c9dc3a6f7de0fa29efaf298f44b7852. This directly adds back the original implementation.
3. `EVP_CIPHER_name` follows an identical pattern to the existing `EVP_MD_name`: 
https://github.com/aws/aws-lc/blob/0541314f0c8ab0e6e4955e70cb31747732797a9c/crypto/fipsmodule/evp/evp.c#L227-L236
N/A
Ruby script in draft PR
By submitting this pull …

Minor functions to build with Ruby's cipher module

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

d52018b0f Minor functions to build with Ruby's cipher module (#1564)
364d28bb3 Changed SSL_client_hello_get0_ciphers to align with OpenSSL behavior (#1542)
e8eb7de79 ppc64le: EVP_has_aes_hardware is false w/ no-asm (#1566)
d726d0616 OpenBSD 7.4 and 7.5 Support (#1437)
a66c66efb Remove comments about overread for entropy generation (#1551)
f8a575feb Migrate from __FreeBSD__ to __FreeBSD_version (#1562)
c31d1ce42 Centralize handling of s2n-bignum alt/non-alt function selection (#1547)
00f3c4583 CI for other MacOS versions (#1558)
0541314f0 Cleanup remaing duplicate symbol definitions and turn Wredundant-decls on (#1561)
4d280eb7b Fix ec2 CI testing framework (#1541)
9a4b43ec3 Update x25519_test.cc array initialization to avoid a bug with a GCC 13 warning (#1555)
388cbe7f3 Remove duplicate …

v1.26.0 Release Preparation

---

crypto/fipsmodule/rsa/rsa.c
include/openssl/rsa.h

[AWS-LC][3] and [OpenSSL 3][4] implement various RSA control functions
as concrete functions, but OpenSSL 1.1.1 [implements][1] them as macros
calling `RSA_pkey_ctx_ctrl`. This commit provides an implementation of
`RSA_pkey_ctx_ctrl` [directly cribbed][1] from OpenSSL 1.1.1, and
identical to OpenSSL 3's implementation [today][2].
[1]: https://github.com/openssl/openssl/commit/e5e04ee3983dcf5283c99ce63f3fe37093921747
[2]: https://github.com/openssl/openssl/blob/067fbc01b9e867b31c71091d62f0f9012dc9e41a/crypto/rsa/rsa_lib.c#L734
[3]: https://github.com/aws/aws-lc/blob/2c03113451b5f84f61c8ed283b289a6db87b3397/include/openssl/evp.h#L796
[4]: https://github.com/openssl/openssl/blob/067fbc01b9e867b31c71091d62f0f9012dc9e41a/include/openssl/rsa.h#L125
- CI
By submitting this pull request, I …

Implement DEPRECATED RSA_pkey_ctx_ctrl

---

.github/workflows/abidiff.yml
.github/workflows/actions-ci.yml
.github/workflows/aws-lc-rs.yml
.github/workflows/cmake.yml
.github/workflows/codecov-ci.yml
.github/workflows/cross-test.yml
.github/workflows/integrations.yml
.github/workflows/windows-alt.yml

* Group actions by `github.ref_name` which is applicable to both pushes and pulls. See [docs](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context).
* Don't fail entire "matrix" when one job fails.  See [docs](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures).

Minor GitHub Action cleanup

---

cmake/go.cmake
go.mod

The version specified in go.mod isn't enforced and users can hit weird issues when building AWS-LC with old versions of go:
```
long build output
util/embed_test_data.go:81:16: undefined: os.ReadFile
more build output
...
make: *** [Makefile:117: all] Error 2
BUILD FAILED 
```
This is confusing because the go error can be easily overlooked.
This change isn't changing what version of Go builders need, just making the requirement more clear. 
Built locally and verified output `-- Go compiler 1.21.3 found` I also tried raising the minimum version to 1.180 and verified it failed: 
```
CMake Error at cmake/go.cmake:28 (message):
Go compiler version must be at least 1.180.  Found version 1.21.3
Call Stack (most recent call first):
CMakeLists.txt:26 (include)
```
And if you disable go the …

Enforce minimum go version when runnign cmake if go is not disabled

---

crypto/fipsmodule/cpucap/cpu_aarch64_linux.c

Backport ARM CPUID guard for Android platforms.
This does not change the integrity check result for validated platforms.
(Cherry picked from commit 24cb055cb48ae15b9b924ec939f4b993380723f7)

Backport ARM CPUID guard for Android

---

crypto/kyber/pqcrystals_kyber_ref_common/indcpa.c
crypto/kyber/pqcrystals_kyber_ref_common/indcpa.h
crypto/kyber/pqcrystals_kyber_ref_common/kem.c
crypto/kyber/pqcrystals_kyber_ref_common/kem.h

N/A
Implement low-level derand API for Kyber.
Based on: https://github.com/pq-crystals/kyber/commit/289b852daf192c3af655a6272dfa79d13fc0c83a

Implement low-level derand API for Kyber

---

.github/workflows/windows-alt.yml
CMakeLists.txt
tests/ci/run_cross_mingw_tests.sh
tests/ci/run_cross_tests.sh

* Cross-compile and test MinGW on Ubuntu.
* Some versions of MinGW set `_WIN32_WINNT` for [compatibility with Windows Server 2003](https://stackoverflow.com/questions/75873115/min-gw-gcc-cant-link-winsock2-h).
* Set compatibility to "Windows 7" when building with MinGW.
* The following build failure occurs when building w/o setting `_WIN32_WINNT`:
```
/home/justsmth/repos/aws-lc/crypto/bio/bio_test.cc:147:7: error: ‘inet_pton’ was not declared in this scope; did you mean ‘inet_ntoa’?
147 |   if (inet_pton(AF_INET6, "::1", &sin6.sin6_addr) != 1) {
|       ^~~~~~~~~
|       inet_ntoa
```

Cross-compile w/ MinGW; set `_WIN32_WINNT`

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

* Backport vpinsrq delocate support to AWS-LC-FIPS-2.x by @skmcgrail in https://github.com/aws/aws-lc/pull/1571
* Backport ARM CPUID guard for Android by @skmcgrail in https://github.com/aws/aws-lc/pull/1579

AWS-LC-FIPS-2.0.10 release preparation

---

.github/workflows/codecov-ci.yml
util/codecov-ci.sh

Resolves P126361289
[V4 was released at the start of February](https://github.com/codecov/codecov-action/releases/tag/v4.0.0) and is the latest release. 
I'm just hoping this fixes the issue. 
In this CI. 

Migrate to v4 of the codecov/codecov-action action

---

crypto/bio/bio.c
crypto/bio/bio_test.cc
include/openssl/bio.h
tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml
tests/ci/integration/mysql_patch/pending_size_t.patch
tests/ci/integration/mysql_patch/test_wl13075-off.patch
tests/ci/integration/run_mysql_integration.sh

MySQL 8.4 has been released, this updates our CI to run against the latest version. This time we only need two missing APIs from OpenSSL.
* `BIO_read_ex`
* `BIO_write_ex`
* Removed disabled tests were removed from mysql's test suite, so I removed them from `mysql_run_tests`
* Original patch needed to be updated, new patch is needed for `int` to `size_t` mismatch for `BIO_pending`
* I considered switching our `BIO_pending` to `int` instead, but our version has been using the `size_t` signature for a decade now, so this doesn't seem easily convertible.
* New tests for `BIO_read/write_ex`
* Update MySQL build for 8.4

Add support for BIO_read/write_ex; Update MySQL CI to 8.4;

---

tests/ci/integration/run_mysql_integration.sh

Resolves `V1379971621`
We got a false alarm when we updated the mysql version tag strategy. Apparently my ubuntu box and the docker image had different versions of git and this caused a behavioral difference when running `git tag --sort=-taggerdate`.
The docker image has a newer version (`2.34.1`) and gives the tag date in ascending order. This caused us to compare against the oldest version of mysql instead and triggers the alarm. This PR fixes that.
More data: https://gist.github.com/rponte/fdc0724dd984088606b0?permalink_comment_id=3169553
N/A
In docker image:
```
/home/ubuntu/workplace/MYSQL_BUILD_ROOT/mysql-server /home/ubuntu/workplace/MYSQL_BUILD_ROOT
+ mysql_patch_reminder
++ git tag --sort=-taggerdate
++ tail -1
+ LATEST_MYSQL_VERSION_TAG=mysql-cluster-8.4.0
+ [[ …
```

Fix MySQL version tag alarm

---

crypto/bio/bio_test.cc
crypto/crypto_test.cc
crypto/test/test_util.cc
crypto/test/test_util.h
crypto/x509/internal.h
crypto/x509/x509_lu.c
crypto/x509/x509_test.cc
include/openssl/x509.h

Resolves `CryptoAlg-1648`
X509_STORE has an ex_data upstream and Ruby happens to consume this. This is mostly following the work done in https://github.com/aws/aws-lc/pull/1328
N/A
New test for ex_data

Give X509_STORE an ex_data

---

crypto/fipsmodule/cpucap/cpu_intel.c
crypto/fipsmodule/cpucap/cpu_ppc64le.c

CryptoAlg-2425
* Architectures for which we have custom assembly implementations need to provide a mechanism for the environment to alter the CPU capabilities that are detected at runtime.
* This PR adds support for setting a `OPENSSL_ppccap` environment variable for this purpose.
* Without setting the environment variable: 55ms
```
[ RUN      ] AESTest.TestVectors
[       OK ] AESTest.TestVectors (55 ms)
```
* After setting `export OPENSSL_ppccap=0x0000000000000000`: 216ms
```
[ RUN      ] AESTest.TestVectors
[       OK ] AESTest.TestVectors (216 ms)
```

ppc64le: support OPENSSL_ppccap ENV variable

---

crypto/x509/name_print.c
crypto/x509/x509_test.cc
include/openssl/x509.h

This reverts commit b6082af174881079096aad9661e505be6ba0c5e7.
Ruby [is dependent](https://github.com/ruby/ruby/blob/ruby_3_1/ext/openssl/ossl_x509name.c#L596) on `XN_FLAG_MULTILINE`. We removed the flag in b6082af174881079096aad9661e505be6ba0c5e7 during the upstream merge, this reverts the change.
N/A
Original tests

Revert "Trim some unused XN_FLAG_* values"

---

README.md

This change updates the formal verification section in the README. It adds a table briefly describing algorithms that are currently verified. In addition, it mentions our use of formally verified assembly routines from s2n-bignum.

Update the formal verification section in README

---

crypto/asn1/tasn_dec.c
crypto/asn1/tasn_fre.c
crypto/x509/internal.h
crypto/x509/v3_conf.c
crypto/x509/v3_lib.c
crypto/x509/v3_prn.c
crypto/x509/x509_test.cc

Resolves `V1391929042`
This backports more of the changes done in https://github.com/aws/aws-lc/commit/736a28388873faa25d892197e5777d32356c5084 to reintroduce the "old-style" `X509V3_EXT_METHOD`s.
Although we're reintroducing the methods we discourage using, I've added checks to ensure that these are only used with `NID_id_pkix_OCSP_Nonce`. The assertion in `X509V3_EXT_add` is kept so that we continue to only allow |ASN1_ITEM|-based extensions for consumers that add their own.
I've abstracted out the freeing logic to `x509v3_ext_free_with_method`. This used to be all over the place.
New test case added 

fix X509V3_EXT_METHODs for ocsp nonce extension

---

tests/ci/integration/mariadb_patch/ssl_crl_expect.patch

MariaDB updated their patch with this commit: https://github.com/MariaDB/server/commit/d8368ae289c2d704e9df1fcb465208e925f1aba4. This updates our patch to be applicable with the new changes.

Fix mariadb ssl_crl patch

---

crypto/ocsp/internal.h
crypto/x509/x_all.c
include/openssl/base.h
include/openssl/ocsp.h
include/openssl/x509.h

Resolves `CryptoAlg-1648`
`X509_CRL_http_nbio` is the last API needed to support the AzureSDK after implementation of https://github.com/aws/aws-lc/commit/7ef93cb8b9305405f619ab7639e1e7d0d3d4614c. It's a simple wrapper around an existing API, so might as well add support so we can resolve the ticket.

add support for X509_CRL_http_nbio

---

crypto/asn1/a_gentm.c
crypto/asn1/a_time.c
crypto/asn1/a_utctm.c
crypto/asn1/asn1_test.cc
crypto/x509/internal.h
crypto/x509/x509_lu.c
crypto/x509/x509_test.cc
crypto/x509/x509_time_test.cc
crypto/x509/x509_vfy.c
crypto/x509/x509_vpm.c
include/openssl/asn1.h
include/openssl/x509.h

31d5dce: Stop using time_t internally. For publicly exposed and used
inputs that rely on time_t, _posix versions are added to
support providing times as an int64_t, and internal
use is changed to use the _posix version.
4e32cc5: When looking for the issuer of a certificate, if the current
certificate candidate is expired, X509_verify_cert will
continue searching for a valid cert. An expired certificate is
only returned if no valid certificates are found. This lets
AWS-LC gain feature parity with OpenSSL 1.1.1.
9bed1c9: Tweak test introduced by 4e32cc5.
All changes above reside outside our FIPS boundary and do not change
the integrity hash of our static build on validated platforms.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Backport X509 certificate verification optimizations to AWS-LC-FIPS-2.x

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

* Backport X509 certificate verification optimizations to AWS-LC-FIPS-2.x by @samuel40791765 in
https://github.com/aws/aws-lc/pull/1611
* https://github.com/aws/aws-lc/commit/31d5dce8836fe19acb60a72b4e2f487312ccec70
* https://github.com/aws/aws-lc/commit/4e32cc53a81d339567c83d163181fc4a590b59f0
* https://github.com/aws/aws-lc/commit/9bed1c987fb2ea954dfd3e706cbc59c20a90e85a

AWS-LC-FIPS-2.0.11 release preparation 

---

crypto/fipsmodule/digest/internal.h
crypto/fipsmodule/hmac/hmac.c

N/A
EVP_MAX_MD_BLOCK_SIZE is the block size in bytes. It is divided by 8 in a 64-bit word array initialisation in hmac.c
This partially reverts "Zeroize data immediately after use for FIPS (#911)", commit c7a9fd0dd20c0e35a5b7b98f22b78f16c8c34567, while keeping and correcting the cleansing.

Cleanse the right amount of bytes in HMAC.

---

tests/ci/common_posix_setup.sh

Resolves #P132890850
* Fix Valgrind test. The constants to configure static CPU capabilities on aarch64 are no longer needed.
* Tested on Ubuntu 24.04 and Amazon Linux 2023

Remove special aarch64 valgrind logic

---

crypto/asn1/a_dup.c
crypto/asn1/asn1_test.cc
include/openssl/asn1.h

Addresses `CryptoAlg-1717`
`ASN1_dup` was removed in https://github.com/aws/aws-lc/commit/419144adce049b5341bd94d355c52d099eac56e3 in favor of `ASN1_Item_dup`. This shouldn't normally be called directly, but Ruby happens to consume the API[ in several instances](https://github.com/search?q=repo%3Aruby%2Fruby%20ASN1_dup&type=code).
I've optimized the function to allocate memory with `i2d` directly, instead of the [ancient OpenSSL allocate](https://github.com/aws/aws-lc/commit/419144adce049b5341bd94d355c52d099eac56e3#diff-46888fde23260e66fc474ee241cefde06f5af3ec79856c2c45a491103e91739eL72-L78) and pass into behavior.
Also added some tests for verification along with a do-not-use warning.
N/A
New tests …

add back ASN1_dup with tests

---

.github/workflows/actions-ci.yml

Addresses V1387993904
Remove CI test for gcc-14/FIPS until delocator is updated.

Disable CI for gcc-14/FIPS until relocation issue is resolved

---

crypto/fipsmodule/FIPS.md

Resolves: CryptoAlg-2419
Updating the documentation about our FIPS module.
* You can see the markdown rendered here: https://github.com/justsmth/aws-lc/blob/fips-doc-update/crypto/fipsmodule/FIPS.md

Update for FIPS documentation

---

ssl/ssl_test.cc
ssl/ssl_x509.cc

This was discovered when taking https://github.com/google/boringssl/commit/5b3dc49c1271554f73b976c2c625600d6bd912b0 during the upstream merge.
`ERR_clear_error` is being called more eagerly with the new change, which led us to discover that `SSLTest.BuildCertChain` was actually testing against an error code propagated onto the stack by the previous call to `SSL_CTX_build_cert_chain`.
Upon further examination, we weren't propagating an error when calling `SSL_CTX_build_cert_chain` with `SSL_BUILD_CHAIN_FLAG_IGNORE_ERROR` . The correct behavior should be to push an error onto the stack regardless.
N/A
Slight test tweaks

Fix SSL_BUILD_CHAIN_FLAG_IGNORE_ERROR behavior

---

.gitignore
util/build_compilation_database.sh

* A [compilation database](https://clang.llvm.org/docs/JSONCompilationDatabase.html) is a JSON file that helps facilitate code assistance within a code/text editor.  This is typically via the editor's integration with [Clangd/LSP](https://clangd.llvm.org/).  It is supported by a variety of editors: [VSCode](https://code.visualstudio.com/docs/cpp/faq-cpp#_how-do-i-get-intellisense-to-work-correctly), [CLion](https://www.jetbrains.com/help/clion/compilation-database.html), [Neovim](https://neovim.io/), [Helix](https://helix-editor.com/) among others.
* This script simplifies the creation of this database for AWS-LC: `compile_commands.json`
* This adds the `compile_commands.json` file to `.gitignore`.
* I tested the script on both Linux and macOS.
```
❯ ls -lh *.json
-rw-rw-r-- 1 justsmth …
```

Script for creating compilation database

---

tests/ci/cdk/cdk/codebuild/ec2_test_framework_omnibus.yaml

Codebuild has upgraded their ARM containers to use gv3. This means we have to update our ec2 testing framework to test on gv2 instead.

Update ec2-test-framework to use gv2

---

.github/workflows/integrations.yml
tests/ci/integration/python_patch/3.13/aws-lc-cpython.patch
tests/ci/integration/python_tests/test_crt.py
tests/ci/integration/python_tests/test_cryptography.py
tests/ci/integration/python_tests/test_pyopenssl.py
tests/ci/integration/run_python_integration.sh

This change expands our python integration tests to load and exercise libcrypto-linking 3rd party modules. Cases covered include statically linked AWS-LC (default AWS CRT) and dynamically linked OpenSSL (AWS CRT, PyOpenSSL, PyCA). We also test these integrations with python's AWS-LC built in FIPS mode.
Due to the pre-release nature of python 3.13 and 3.14, there are a few caveats for later versions: 3.12 introduced [a change](https://github.com/python/cpython/issues/95299) to drop `setuptools` from default virtual environments, causing installation issues for PyCA and PyOpenSSL on 3.13+. To work around this, we allow installation failure for those dependencies on newer (currently both 3.13 and 3.14 are pre-release) and exit early from the relevant test cases. We also encountered some …

Add integration tests for OpenSSL-linking 3p modules

---

ssl/ssl_cipher.cc
ssl/ssl_test.cc

Resolves t-V1408365647
Addresses n/a
This change modifies `SSL_CIPHER_get_version` to return the relevant version for non-deprecated TLS versions, namely TLSv1.2 and TLSv1.3 (preferred). For older TLS versions, the previous behavior (return constant cstring `TLSv1/SSLv3`) is preserved.
- n/a
- CI

Implement SSL_CIPHER_get_version for recent TLS versions

---

crypto/CMakeLists.txt

Resolves https://github.com/aws/aws-lc-rs/issues/425
* CMake will attempt to use [the YASM assembler if found](https://github.com/Kitware/CMake/blob/cafa2986afb6eed3ba0318674c02e3a03ef34555/Modules/CMakeDetermineASM_NASMCompiler.cmake#L5).
* YASM is unable to handle our AVX-512 assembly:
```
...\aesni-xts-avx512.asm:136: error: undefined symbol `zmm25' (first use)
```
* This change has CMake locate the "nasm" executable, then sets that as the `CMAKE_ASM_NASM_COMPILER`.

Use 'nasm' not 'yasm'

---

ssl/ssl_test.cc

Resolves n/a (not needed for v1.29.0 release)
Addresses n/a
@andrewhop noticed that this test didn't cover TLSv1.3 although we'd expected it to. This is because the previous test case [guards against TLSv1.3][1] for unrelated reasons. So, we move the test to another case that does cover TLSv1.3.
[1]: https://github.com/aws/aws-lc/blob/main/ssl/ssl_test.cc#L7786-L7789
- n/a
- CI
- verified TLSv1.3 parameterized tests pass
```
$ cmake-build.sh && ./build/ssl/ssl_test --gtest_filter='WithVersion/SSLVersionTest.Version*' | grep TLS1_3
...
[ RUN      ] WithVersion/SSLVersionTest.Version/TLS1_3_BufferSize_0
[       OK ] WithVersion/SSLVersionTest.Version/TLS1_3_BufferSize_0 (1 ms)
[ RUN      ] WithVersion/SSLVersionTest.Version/TLS1_3_BufferSize_128
[       OK ] …
```

Move SSL_CIPHER_get_version test to SSLVersionTest.Version

---

crypto/fipsmodule/modes/gcm_test.cc

Resolves V1401987253
This key buffer is too small for the larger key sizes that the test uses. 
It might be worth adding a address sanitizer + ABI test dimension. So far we haven't hit this before so I didn't add a new docker image with everything installed for that. 
Ran locally and manually reviewed the change for memory safety. 

Fix AES key size for AES256 in ABI test

---

crypto/kyber/README.md
crypto/kyber/pqcrystals_kyber_ref_common/poly.c

Resolves V1399146249
Backports PR #1619. This change is isolated to the Kyber-round3 implementation
which is outside of the FIPS boundary.
The original PR applied the mitigation to both Kyber-r3 and ML-KEM-IPD
implementations. Only the former exists in this branch.
CI

[Backport] Prevent non-constant-time code in Kyber-R3 implementation

---

crypto/chacha/asm/chacha-armv4.pl
crypto/chacha/asm/chacha-armv8.pl
crypto/chacha/chacha.c
crypto/chacha/chacha_test.cc
crypto/chacha/internal.h
crypto/x509/internal.h
crypto/x509/t_req.c
crypto/x509/t_x509.c
crypto/x509/v3_purp.c
crypto/x509/x509_cmp.c
crypto/x509/x509_lu.c
crypto/x509/x509_req.c
crypto/x509/x509_test.cc
crypto/x509/x509_vfy.c
crypto/x509/x509spki.c
crypto/x509/x_pubkey.c
generated-src/ios-aarch64/crypto/chacha/chacha-armv8.S
generated-src/ios-arm/crypto/chacha/chacha-armv4.S
generated-src/linux-aarch64/crypto/chacha/chacha-armv8.S
generated-src/linux-arm/crypto/chacha/chacha-armv4.S
generated-src/win-aarch64/crypto/chacha/chacha-armv8.S
include/openssl/ssl.h
include/openssl/x509.h

Merging from Upstream considering commits
- then commits between https://github.com/google/boringssl/commit/5b6a9cf31d13d3b35a59fa674b566cfb553ef22d (Dec 19, 2023) and https://github.com/google/boringssl/commit/1749dc9a70fd9cbb3221c47ef30cffd6fda06846 (Jan 4 2023)
See internal document as well as "AWS-LC" notes inserted in some of the commit messages for additions/deviations from the upstream commit.

Upstream merge 2024 06 03

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

Resolves V1399146249
* [Backport] Prevent non-constant-time code in Kyber-R3 implementation by @geedo0 in https://github.com/aws/aws-lc/pull/1632

AWS-LC-FIPS-2.0.12 release preparation

---

tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml

Curl's tip of main is failing against a compiler warning specific to gcc-12 at the moment with `-Werror` enabled. This is causing errors in our integration CI. We enable the flag since Curl's CI enables it, but they run against [gcc-11 for their CI](https://github.com/curl/curl/actions/runs/9484140318/job/26132948154).
I've submitted an issue to curl to fix it (https://github.com/curl/curl/issues/13932), but we should use gcc-11 for our Curl CI to avoid with curl's main branch that are out of our control.

align gcc version with curl's CI

---

crypto/x509/x509_test.cc
crypto/x509/x509spki.c
include/openssl/x509.h

Resolves `CryptoAlg-1717`
Ruby [consumes NETSCAPE_SPKI_print](https://github.com/ruby/ruby/blob/0b31986909eaccb6b5f8f99f9ab2a458170a21af/ext/openssl/ossl_ns_spki.c#L167) for debugging purposes. This adds support for the symbol for easier integration.
N/A
Expected output test

Add support for NETSCAPE_SPKI_print

---

crypto/conf/conf.c
crypto/conf/conf_test.cc
crypto/pkcs8/pkcs12_test.cc
crypto/pkcs8/pkcs8_x509.c
docs/porting/configuration-differences.md
docs/porting/functionality-differences.md
include/openssl/conf.h
include/openssl/pkcs8.h
include/openssl/ssl.h

Addresses `CryptoAlg-1717`
This implements two minor symbols and a few no-op flags for Ruby support.
New symbols:
* PKCS12_new
* CONF_get1_default_config_file
No-op flags:
* SSL_OP_CRYPTOPRO_TLSEXT_BUG
* SSL_OP_SAFARI_ECDHE_ECDSA_BUG
* SSL_OP_TLSEXT_PADDING
All of these no-ops are following a precedent in AWS-LC. We may have to have a discussion on whether to support CONF modules further down the line, but exposing this as a no-op for now.
N/A

More minor symbols for Ruby support

---

crypto/x509/v3_purp.c
crypto/x509/x509_trs.c
crypto/x509/x509_vfy.c
crypto/x509/x_name.c
crypto/x509/x_x509a.c
include/openssl/x509.h

Upstream merge 2024-06-13

---

include/openssl/asm_base.h

Resolves: P135542828
* No use of `_CET_ENDBR` with old compilers.

Require newer assembler for _CET_ENDBR

---

.github/workflows/integrations.yml
crypto/digest_extra/digest_extra.c
crypto/digest_extra/digest_test.cc
include/openssl/digest.h
include/openssl/ssl.h
ssl/ssl_lib.cc
ssl/ssl_test.cc
tests/ci/integration/openldap_patch/OPENLDAP_REL_ENG_2_5/print-libcrypto-info.patch
tests/ci/integration/openldap_patch/master/print-libcrypto-info.patch
tests/ci/integration/run_openldap_integration.sh

Addresses CryptoAlg-2464
This commit adds two functions used by OpenLDAP 2.5.17+. Both functions are very straightforward.
From OpenSSL's [docs][1] for `EVP_md_null`:
>A "null" message digest that does nothing: i.e. the hash it returns is
of zero length.
From OpenSSL's [docs][2] for `SSL_set_ciphersuites`:
> SSL_set_ciphersuites() is the same as SSL_CTX_set_ciphersuites()
except it configures the ciphersuites for ssl.
[1]: https://www.openssl.org/docs/man1.1.1/man3/EVP_md_null.html
[2]: https://www.openssl.org/docs/man1.1.1/man3/SSL_set_ciphersuites.html
- n/a
- new integration test
- increased unit test coverage
---

Add EVP_md_null and SSL_set_ciphersuites

---

BUILDING.md
CMakeLists.txt
crypto/CMakeLists.txt
crypto/fipsmodule/bcm.c
crypto/fipsmodule/rand/rand.c
crypto/fipsmodule/rand/snapsafe_detect.c
crypto/fipsmodule/rand/snapsafe_detect.h
crypto/fipsmodule/rand/snapsafe_detect_test.cc
crypto/fipsmodule/rand/urandom_test.cc
crypto/internal.h
crypto/test/gtest_main.cc
ssl/test/bssl_shim.cc
ssl/test/handshaker.cc
tests/ci/run_fips_tests.sh
tests/ci/run_posix_tests.sh
util/all_tests.json

(cherry picked from commit f31fd3114a1f0cf8f01f6de4161e5f8a23df250a)
Backport of Snapsafe UBE detection change to the fips-2022-11-02 branch. Original PR is here: #1640 

Snapsafe-type uniqueness breaking event detection (#1640)

---

crypto/fipsmodule/rand/snapsafe_detect.c

* Close file-descriptor if `HAZMAT_init_sysgenid_file` fails to sync sysgenid test file.

Close FD in Snapsafe test function

---

crypto/fipsmodule/rand/snapsafe_detect.c

Backport of commit from main: https://github.com/aws/aws-lc/pull/1649
--------
* Close file-descriptor if `HAZMAT_init_sysgenid_file` fails to sync sysgenid test file.
--------

(FIPS Backport) Close FD in Snapsafe test function (#1649)

---

crypto/rsa_extra/rsa_asn1.c
crypto/x509/x509_test.cc

N/A
Set an appropriate RSA flag when stripped private keys are loaded.

Fix for loading JCA stripped private keys

---

crypto/fipsmodule/ec/ec_nistp.c
crypto/fipsmodule/ec/ec_nistp.h
crypto/fipsmodule/ec/p256.c
crypto/fipsmodule/ec/p384.c
crypto/fipsmodule/ec/p521.c

N/A
Add point add/dbl to ec_nistp_felem_meth and rename it to ec_nistp_meth.

Add point add/dbl to ec_nistp_felem_meth and rename it to ec_nistp_meth

---

crypto/constant_time_test.cc
crypto/internal.h

N/A
Added constant_time_select array and entry_from_table.

Added constant_time_select array and entry_from_table

---

util/build_compilation_database.sh

Propogates script parameters to cmake command
```
❯ ./util/build_compilation_database.sh -DFIPS=1 -DBUILD_SHARED_LIBS=1
...
+ mkdir -p /var/folders/bd/5rrlftjx2098f44h7jbj3n400000gr/T/tmp.69gTlsxzTf/AWS-LC-BUILD
+ cmake /Users/justsmth/repos/aws-lc -B /var/folders/bd/5rrlftjx2098f44h7jbj3n400000gr/T/tmp.69gTlsxzTf/AWS-LC-BUILD -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DFIPS=1 -DBUILD_SHARED_LIBS=1
...
...

Use params to build_compilation_database.sh

---

include/openssl/opensslconf.h
tests/ci/integration/python_patch/3.13/aws-lc-cpython.patch
tests/ci/integration/python_patch/main/aws-lc-cpython.patch

PR #1526 introduced the `OPENSSL_NO_TLS_PHA` directive mostly for the purposes of AWS-LC's compatibility with CPython, but in [cpython PR #117785](https://github.com/python/cpython/pull/117785) @encukou points out that detecting the absence of OpenSSL's own `SSL_VERIFY_POST_HANDSHAKE` directive is sufficient. This change removes AWS-LC's `OPENSSL_NO_TLS_PHA` directive in favor of detecting absence of `SSL_VERIFY_POST_HANDSHAKE`.
- existing CI integration tests
---

Replace OPENSSL_NO_TLS_PHA with SSL_VERIFY_POST_HANDSHAKE

---

crypto/dh_extra/dh_test.cc
crypto/fipsmodule/dh/check.c

CryptoAlg-2490
Previously, `DH_check` allowed only primes with certain
properties when the generator was equal to 2 or 5. We remove
this requirement to:
- be more consistent with OpenSSL that doesn't have these
checks. As a consequence, it was possible to generate DH
parameters with OpenSSL that wouldn't pass AWS-LC `DH_check`.
- not break customers who use one of the standard DH groups
from RFC's 3526 and 7919 and call `DH_check` on it (like s2n-tls).
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Make DH_check consistent with OpenSSL

---

include/openssl/ssl.h
ssl/extensions.cc
ssl/internal.h
ssl/ssl_lib.cc
ssl/ssl_test.cc

[main] Make SSL_select_next_proto more robust to invalid calls.

---

include/openssl/ssl.h
ssl/extensions.cc
ssl/internal.h
ssl/ssl_lib.cc
ssl/ssl_test.cc

[fips-2021-10-20-1MU] Make SSL_select_next_proto more robust to invalid calls.

---

include/openssl/ssl.h
ssl/extensions.cc
ssl/internal.h
ssl/ssl_lib.cc
ssl/ssl_test.cc

[fips-2021-10-20] Make SSL_select_next_proto more robust to invalid calls.

---

include/openssl/ssl.h
ssl/extensions.cc
ssl/internal.h
ssl/ssl_lib.cc
ssl/ssl_test.cc

[experimental-fips-refactoring] Make SSL_select_next_proto more robust to invalid calls.

---

include/openssl/ssl.h
ssl/extensions.cc
ssl/internal.h
ssl/ssl_lib.cc
ssl/ssl_test.cc

[fips-2022-11-02] Make SSL_select_next_proto more robust to invalid calls.

---

crypto/fipsmodule/cpucap/cpu_arm_freebsd.c
crypto/fipsmodule/cpucap/cpu_arm_linux.c
crypto/fipsmodule/cpucap/cpu_ppc64le.c

Addresses: https://github.com/aws/aws-lc-rs/issues/427
* Allow fallback when `AT_HWCAP2` is not defined (for older glibc).
> 
>       AT_HWCAP2 (since glibc 2.18)
>              Further machine-dependent hints about processor
>              capabilities.
>
* I've not yet been able to setup an environment that replicates [the failure seen downstream](https://github.com/rust-lang/rustup/actions/runs/9720503984/job/26831972336?pr=3898) for `arm-unknown-linux-gnueabihf`:
```
In file included from /cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.18.0/aws-lc/crypto/fipsmodule/bcm.c:81:
/cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.18.0/aws-lc/crypto/fipsmodule/cpucap/cpu_arm_linux.c: In function 'aws_lc_0_18_0_OPENSSL_cpuid_setup': …
```

AT_HWCAP2 not always defined

---

crypto/fipsmodule/hmac/hmac.c
crypto/hmac_extra/hmac_test.cc

CryptoAlg-2522
Currently, `NULL` passed as the value of `out` can result in a segmentation fault. This change adds checks to the HMAC one-shot API and HMAC_final function to handle scenarios where `NULL` is passed as a value to the `out` parameter to return from the functions and prevent further computation. 
Added additional test case in `crypto/hmac_extra/hmac_test.cc` to verify the behavior when `NULL` is passed as a value to `out` in both functions.
- OpenSSL supports this differently by allowing the computation to occur but allocating a throw-away array [OpenSSL implementation](https://github.com/openssl/openssl/blob/1977c00f00ad0546421a5ec0b40c1326aee4cddb/crypto/hmac/hmac.c#L233)
- We should also evaluate if this change should be back-ported to the FIPS branches …

Update HMAC to fail when null value is passed to out parameter

---

crypto/fipsmodule/ec/ec.c
include/openssl/ec.h

Addresses `CryptoAlg-1715`
Ruby exposes the `EC_GROUP` seed functions and allows you to set the seed with `EC_GROUP_set_seed`. It's one thing that are `EC_GROUP`s are static and immutable, but setting the seed is more prevalent to custom curves. We don't encourage using custom curves, so I've chose to mark it as a no-op and deprecated.
We could arguably support `EC_GROUP_get0_seed` and `EC_GROUP_get_seed_len` for our named curves, but the seed value is only used during the initial curve parameter generation. We've chosen to mark this as a no-op for now, implementing them creates additional complexity that doesn't really provide additional value to the consumer.
N/A
N/A
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and the …

Add EC seed functions as deprecated no-ops

---

tests/ci/cdk/cdk/ssm/general_test_run_ssm_document.yaml

ec2-test-framework is having failures due to the instance timeout we originally set. The ultimate goal is to parallelize this, but extending the timeout for now.
N/A
N/A

extend ec2-test-framework instance timeout

---

crypto/ec_extra/ec_asn1.c
crypto/fipsmodule/ec/ec_test.cc
include/openssl/ec.h

Addresses `CryptoAlg-1715`
Ruby happens to [consume this](https://github.com/ruby/ruby/blob/ruby_3_1/ext/openssl/ossl_pkey_ec.c#L1167-L1171). This is deprecated in OpenSSL 3.0 and I've marked it likewise in AWS-LC as well. Although Ruby has generally moved off of deprecated 3.0 APIs, they still depend on this and later versions like 3.2 and 3.3 have not removed support for this either.
N/A
Tests built upon original tests for `EC_POINT_point2bn`.

add support for EC_POINT_bn2point

---

crypto/fipsmodule/modes/asm/aesv8-gcm-armv8.pl
generated-src/ios-aarch64/crypto/fipsmodule/aesv8-gcm-armv8.S
generated-src/linux-aarch64/crypto/fipsmodule/aesv8-gcm-armv8.S
generated-src/win-aarch64/crypto/fipsmodule/aesv8-gcm-armv8.S

On AArch64 systems without support for EOR3, assembly kernels `aes_gcm_enc_kernel` and `aes_gcm_dec_kernel` from `aesv8-gcm-armv8.pl` are used for the bulk of AES-GCM processing. These kernels have dedicated tail code for handling inputs whose size is not a multiple of the block size (16 bytes).
However, the unique call-sites for `aes_gcm_enc_kernel` and `aes_gcm_dec_kernel` in `gcm.c` only invoke them with data of size a multiple of 16 bytes: See the masking here [here](https://github.com/aws/aws-lc/blob/98735a2f6723ba984a18b2f79e05173a61e0f869/crypto/fipsmodule/modes/gcm.c#L154) and [here](https://github.com/aws/aws-lc/blob/98735a2f6723ba984a18b2f79e05173a61e0f869/crypto/fipsmodule/modes/gcm.c#L191). This renders the tail code in `aesv8-gcm-armv8.pl` dead.
Simply removing the truncation …

Remove dead tail code from (non-SHA3) AES-GCM AArch64 kernel

---

crypto/ec_extra/ec_asn1.c
crypto/fipsmodule/ec/ec_test.cc

Resolves `P138896891`
Static analysis was complaining about us using the pointer after it was freed. I don't believe this is an actual "issue", but we might as well make the NULL explicit before returning.
N/A
N/A

Set ret to NULL before return in EC_POINT_bn2point

---

crypto/ec_extra/ec_asn1.c
crypto/fipsmodule/ec/internal.h
crypto/pem/pem_all.c
crypto/pem/pem_lib.c
crypto/pem/pem_test.cc
include/openssl/ec_key.h
include/openssl/pem.h

Addresses `CryptoAlg-1715`
Ruby depends on reading/writing PEM files that are defined as `EcpkParameters ` (See [RFC 3279](https://datatracker.ietf.org/doc/html/rfc3279#section-2.3.5) for more details).`EcpkParameters` actually just refer to potential different ways of serializing EC Groups and we already have basic support for this. OpenSSL's implementation of `d2i/i2d_ECParameters` actually [calls `d2i/i2d_ECPKParameters`](https://github.com/openssl/openssl/blob/fbd6609bb21b125c9454d07c484d166a33b4815b/crypto/ec/ec_asn1.c#L1088-L1114) internally.
* I've borrowed some of the logic for `d2i/i2d_ECParameters` and worked them into the new functions. Apparently we only support parsing named curves or explicitly encoded versions of them, so I've documented that and followed the same pattern. …

Add support for parsing ECPKParameter PEM files

---

crypto/ec_extra/ec_asn1.c
include/openssl/ec.h

Resolves `CryptoAlg-1715`
Ruby [consumes](https://github.com/ruby/ruby/blob/ruby_3_1/ext/openssl/ossl_pkey_ec.c#L1071-L1088) `ECPKParameters_print`. The entire function is a bit convoluted and not really beneficial unless you're using custom curves. We can expose this as a no-op until there's a more proper use case for this.
N/A
N/A

add ECPKParameters_print as no-op

---

crypto/fipsmodule/cpucap/cpu_aarch64_linux.c
crypto/fipsmodule/cpucap/cpucap.c
crypto/fipsmodule/cpucap/internal.h
include/openssl/arm_arch.h

Graviton 4 uses Neoverse V2 cores which we were previously not detecting which resulted in poor performing implementations being used. It still produced the correct answer, it just didn't take full advantage of the CPU's capabilities.
I thought about combining the ARM CPU capability flag for Neoverse V1 and V2 cores into one flag but we might have a future usecase that would need specific handling even though right now they behave the same. 
We also need to test Apple M2 and M3 CPUs which will probably also want the same optimizations as M1. This also might make sense to combine into a single Apple "M" ARM capability flag.
Built and ran locally. On a Graviton 4 instance:
|Algorithm|Before|After|
|---|---|---|
|RSA 2048 sign|929.6 ops/sec|1,397.5 ops/sec|
|ECDH P-384|3,541.2 …

Add support to detect Neoverse V2 cores

---

crypto/ocsp/internal.h
include/openssl/ocsp.h

Addresses `CryptoAlg-2420`
A few of the OCSP symbols Ruby uses were only in our internal header. This pulls them out for consumers to use.
N/A
N/A

Move OCSP functions for Ruby out of internal.h

---

crypto/cipher_extra/cipher_extra.c

`EVP_get_cipherbyname()` is deprecated. But cryptsetup use it to query for the implementation of XTS.
We already test `EVP_get_cipherbyname()`.

Add aes-256-xts to EVP_get_cipherbyname

---

CMakeLists.txt
crypto/CMakeLists.txt

* I found that some downstream consumers use upper-case "X86" ([for example](https://github.com/rust-lang/cmake-rs/blob/c4a60dd154dd90e469dffc41a1faa717704f90b3/src/lib.rs#L487)) which fails to match in our [CMakeLists.txt](https://github.com/aws/aws-lc/blob/main/CMakeLists.txt#L785).
* This change creates a `CMAKE_SYSTEM_PROCESSOR_LOWER` variable and uses that when matching.

Match using CMAKE_SYSTEM_PROCESSOR_LOWER

---

tests/ci/integration/run_mysql_integration.sh

Resolves `P138386170`
Update MySQL CI to 9.0.0. `libmysqlrouter_http` no longer links to `libssl.so`, so removing ldd checks against that.

Update MySQL to 9.0.0

---

crypto/fipsmodule/evp/evp_ctx.c
include/openssl/evp.h

N/A
Adds a const qualifier to the ciphertext parameter in the EVP_PKEY_decapsulate API. This seems to match the internal implementation of decapsulate. 
N/A
I didn't see any tests fail for this change? Maybe I missed something...

Adds const qualifier to ciphertext parameter in EVP_PKEY_decapsulate

---

crypto/fipsmodule/ec/ec_nistp.c

Previous change unified and simplified selecting a point from table by using constant_time_select_entry_from_table_8 function. Unfortunatelly, on x86 this function is significantly slower than constant_time_select_entry_from_table_w. This commit fixes the performance regression.
Measured on Intel(R) Xeon(R) Platinum 8488C:
P-384 scalar_mul from 4091 to 5461 ops/s,
P-521 scalar_mul from 2520 to 3731 ops/s.

Fix for select point from table in ec_nistp scalar_mul

---

tests/ci/cdk/cdk/aws_lc_analytics_stack.py
tests/ci/cdk/cdk/aws_lc_android_ci_stack.py
tests/ci/cdk/cdk/aws_lc_ec2_test_framework_ci_stack.py
tests/ci/cdk/cdk/aws_lc_github_ci_stack.py
tests/ci/cdk/cdk/aws_lc_github_fuzz_ci_stack.py
tests/ci/cdk/cdk/bm_framework_stack.py
tests/ci/cdk/cdk/codebuild/ec2_test_framework_omnibus.yaml
tests/ci/cdk/cdk/components.py
tests/ci/cdk/cdk/ssm/general_test_run_ssm_document.yaml
tests/ci/codebuild/common/run_ec2_target.yml
tests/ci/lambda/Cargo.lock
tests/ci/lambda/Cargo.toml
tests/ci/lambda/src/bin/purge-stale-builds.rs
tests/ci/run_ec2_test_framework.sh

Resolves `P131897680`
1. Some of our ec2 instances from the ec2-test-framework were failing to be properly stopped. This adds logic to the job pruner to stop hanging instances.
2. Also parallelizing the test runs. GV2 is significantly slower which causes the run to be much longer. This also makes it much easier for us to extend testing against new test scripts. 
3. Also added graviton 4 testing to the ec2-test-framework.
N/A
Local fork CI run: https://github.com/samuel40791765/aws-lc/pull/33

ec2-test-framework enhancements and graviton 4 testing 

---

.github/workflows/aws-lc-rs.yml

* Update the aws-lc-rs GH CI test for the FIPS-2.x branch.

Fix aws-lc-rs  GH CI for FIPS-2.x branch

---

tests/ci/lambda/src/bin/purge-stale-builds.rs
util/whitespace.txt

Small fix to show number of pruned instances in dashboard.
Test PR: https://github.com/samuel40791765/aws-lc/pull/34

Show number of pruned ec2 instances in dashboard

---

tests/ci/integration/run_mysql_integration.sh

Resolves `P143648158`
Bump MySQL CI version to 9.0.1

bump mysql CI to 9.0.1

---

crypto/ocsp/internal.h
crypto/ocsp/ocsp_server.c
crypto/ocsp/ocsp_test.cc
include/openssl/ocsp.h

Addresses `CryptoAlg-2420`
There are a few easier `OCSP_REQUEST` utility functions Ruby uses. We initially didn't support these as they made more sense as supporting functions for OCSP responders. 
`OCSP_id_issuer_cmp` was also pulled out of `internal.h` since it's needed.
N/A
Brief tests inserted in existing test suites.

Support utility OCSP request functions

---

.github/docker_images/cmake_build_versions/cmake_build.sh

While working on https://github.com/aws/aws-lc/pull/1729 I noticed the CMake builds took a while because it was all single threaded. The GitHub runners [have 4 cores](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) so this should speed it up a bit.
Waiting to see what happens here. 

Build CMake with multiple jobs to save time

---

crypto/ocsp/internal.h
crypto/ocsp/ocsp_extension.c
crypto/ocsp/ocsp_test.cc
include/openssl/ocsp.h

Addresses `CryptoAlg-2420`
Ruby consumes `OCSP_copy_nonce`, which copies the nonce from the request to the OCSP response.
OpenSSL's `OCSP_copy_nonce` directly appends the new OCSP nonce to the list of extensions in the response. This allows multiple OCSP nonces to exist the same response since the existing nonces are not deleted. It's a bit strange to allow multiple nonces to exist in a single response. To make things stranger, `OCSP_check_nonce` directly takes the first OCSP nonce in the list to compare, so any newer  nonces are ignored. 
We ultimately decided to follow OpenSSL's faulty implementation and document/test the behavior, there doesn't seem to be much value in diverging from the original and will only introduce more unanticipated behavioral changes.
N/A
Extend upon original …

add support for OCSP_copy_nonce

---

.github/docker_images/cmake_build_versions/cmake_build.sh

A previous PR (https://github.com/aws/aws-lc/pull/1735/files) broke the CI but was merged in since the failed checks were not required. This PR fixes these failures by explicitly setting the number of threads to parallelize the make command (as opposed to using -j to spin up as many processes as possible). 

Specifying CPU threads in cmake_build.sh to fix CI failures

---

crypto/dilithium/pqcrystals_dilithium_ref_common/ntt.c
crypto/dilithium/pqcrystals_dilithium_ref_common/poly.c
crypto/dilithium/pqcrystals_dilithium_ref_common/reduce.c
crypto/dilithium/pqcrystals_dilithium_ref_common/reduce.h

Resolves #P123931043
This PR addresses the multiplication and Montgomery reduction functionality within Dilithium. This refactor makes it simpler to re-implement the multiplication on targets where non-constant time behaviour is known, and has consistency with the code organisation of Kyber.

code refactor to add fqmul

---

tests/ci/setup.py

updating the pyyaml dependency from 6.0 to 6.0.1. Pyyaml 6.0 does not work with Python 3.12 and we should be able to support it: https://github.com/yaml/pyyaml/issues/756

Updating Pyyaml Dependency

---

crypto/bio/bio.c
include/openssl/bio.h

BIO_gets takes a len/size parameter which is of type int and can be negative. Previously, this param was passed into callback_ex without a check for len being positive. This is an issue since callback_ex defines this size/len param as a size_t var. Passing in a negative number to size_t could lead to unexpected behavior. 
A similar issue exists in BIO_read and BIO_write
This PR moves the check for len to before calling the callback and updates documentation for BIO_gets, BIO_read, and BIO_write.

Fix for BIO_gets and update documentation

---

crypto/obj/obj_dat.h
crypto/obj/objects.txt
include/openssl/nid.h

The OID values are taken from OQS's [openssl provider][1].
The only manual changes in this PR were to `crypto/obj/objects.txt`. The rest were generated by running `go run objects.go` in the `crypto/obj/` directory.
[1]: https://github.com/open-quantum-safe/oqs-provider/blob/acd7181ae34ff05261d30d111eb5102d4f8c623a/ALGORITHMS.md?plain=1#L253-L254
n/a
```
$ cat test.py
import ssl
import socket
assert "AWS-LC" in ssl.OPENSSL_VERSION
ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
ctx.set_ecdh_curve("X25519Kyber768Draft00")
ctx.load_verify_locations("/etc/ssl/certs/ca-certificates.crt")
host = "secretsmanager.us-east-1.amazonaws.com"
sock = socket.create_connection((host, 443))
ssock = ctx.wrap_socket(sock, server_hostname=host)
ssock.close()
print("success!")
$ ./python test.py
success!
``` …

Add PQ key exchange OIDs

---

crypto/test/test_util.h
tests/ci/run_openssl_comparison_tests.sh
tool-openssl/CMakeLists.txt
tool-openssl/dgst.cc
tool-openssl/dgst_test.cc
tool-openssl/internal.h
tool-openssl/md5_test.cc
tool-openssl/rsa_test.cc
tool-openssl/test_util.h
tool-openssl/tool.cc
tool-openssl/x509_test.cc

Resolves `CryptoAlg-2602`
OpenSSL's hmac command line tool uses `dgst` with a `-hmac` option. Supporting the entire functionality of `dgst` will take a bit more work, but we can support `-hmac` with the default `SHA256` for the time being.
Rearranged some of the header file function calls to make things cleaner
Basic functionality tests against single and multiple /tmp files.

add basic support for dgst hmac in tool

---

crypto/fipsmodule/cpucap/cpu_aarch64_linux.c

Addresses P147929287
Removes the `OPENSSL_ANDROID` guard around the aarch64 CPUID capability check and allows it for all aarch64 linux platforms. This is now inline with the original commit taken from main: https://github.com/aws/aws-lc/commit/24cb055cb48ae15b9b924ec939f4b993380723f7

Allow aarch64 CPUID capability check for all Linux platforms

---

include/openssl/ssl.h
ssl/internal.h
ssl/ssl_lib.cc
ssl/ssl_test.cc
ssl/ssl_transfer_asn1.cc
ssl/ssl_versions.cc
ssl/tls_transfer.asn

Addresses P147941517
Backports https://github.com/aws/aws-lc/pull/1322 and https://github.com/aws/aws-lc/pull/1337 to the fips-2022-11-02 branch.
This changes does not modify the FIPS module boundary.

[fips-2022-11-02] Backport Latest TLS Transfer Version

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

* Fix aws-lc-rs  GH CI for FIPS-2.x branch by @justsmth in https://github.com/aws/aws-lc/pull/1651
* Allow aarch64 CPUID capability check for all Linux platforms by @skmcgrail in https://github.com/aws/aws-lc/pull/1762
* [fips-2022-11-02] Backport Latest TLS Transfer Version by @skmcgrail in https://github.com/aws/aws-lc/pull/1764

[fips-2022-11-02] Prepare v2.0.15 release

---

crypto/ocsp/ocsp_extension.c
crypto/ocsp/ocsp_test.cc
include/openssl/ocsp.h

Addresses `CryptoAlg-2420`
Ruby happens to depend on `OCSP_basic_add1_nonce` which is identical to `OCSP_request_add1_nonce`, but does the operation on the `OCSP_BASICRESP` instead. This extends upon the same underlying function/logic as the identical function.
N/A
Add the same test coverage as what we had for `OCSP_request_add1_nonce`.

Support OCSP_basic_add1_nonce

---

crypto/crypto_test.cc
crypto/internal.h

Tighten descriptions and ensure return value assumptions can't just be changed.

Tighten up experimental pointer guard macro

---

crypto/asn1/asn1_test.cc
crypto/ecdh_extra/ecdh_test.cc
crypto/evp_extra/evp_test.cc
crypto/fipsmodule/evp/evp.c
include/openssl/evp.h

Addresses CryptoAlg-1716
* Provide a working implementation of the (deprecated) function `EVP_PKEY_get0`.

EVP_PKEY_get0 implementation

---

crypto/fipsmodule/aes/asm/aesv8-armx.pl
generated-src/ios-aarch64/crypto/fipsmodule/aesv8-armx.S
generated-src/ios-arm/crypto/fipsmodule/aesv8-armx.S
generated-src/linux-aarch64/crypto/fipsmodule/aesv8-armx.S
generated-src/linux-arm/crypto/fipsmodule/aesv8-armx.S
generated-src/win-aarch64/crypto/fipsmodule/aesv8-armx.S

Addresses #CryptoAlg-2498
The change in https://github.com/aws/aws-lc/pull/1690 showed a 0.01 usec more in EVP-AES-256-CTR on Graviton4. This change optimises the sequence of operations to make use of instruction fusion in the sequence CMP + B.cond.; that is, the `b.le` instruction is placed after the cmp instruction, also avoiding executing unneeded instructions if the jump is to be taken. 
Tested the performance on Graviton4.

Improving corner-case instruction flow in `aes_hw_ctr32_encrypt_blocks`

---

tool-openssl/CMakeLists.txt
tool-openssl/internal.h
tool-openssl/tool.cc
tool-openssl/version.cc
tool-openssl/x509.cc
tool-openssl/x509_test.cc

Add the -text option to the X509 tool which prints a certificate's contents in a human readable format. Also add the version tool which only supports printing the basic version information.
Added a new test for X509 -text with some minor caveats due to difference in between OpenSSL versions. I didn't add a test for the version as that will always be different:
```
AWS-LC:
OpenSSL 1.1.1 (compatible; AWS-LC 1.33.0)
OpenSSL:
OpenSSL 3.3.1 4 Jun 2024 (Library: OpenSSL 3.3.1 4 Jun 2024)
```

Add -text support to X509 tool, add Version tool

---

crypto/test/test_util.cc

Before:
```
$ ninja-build
[578/584] Linking CXX executable tool-openssl/tool_openssl_test
tool-openssl/CMakeFiles/tool_openssl_test.dir/__/crypto/test/test_util.cc.o: In function `createTempFILEpath(char*)':
/home/ec2-user/humble/aws-lc/awslc-build/../crypto/test/test_util.cc:114: warning: the use of `tmpnam' is dangerous, better use `
mkstemp'
[580/584] Linking CXX executable ssl/integration_test
crypto/test/libtest_support_lib.a(test_util.cc.o): In function `createTempFILEpath(char*)':
/home/ec2-user/humble/aws-lc/awslc-build/../crypto/test/test_util.cc:114: warning: the use of `tmpnam' is dangerous, better use `
mkstemp'
[582/584] Linking CXX executable crypto/crypto_test
crypto/test/libtest_support_lib.a(test_util.cc.o): In function `createTempFILEpath(char*)': …
```

Silence tmpname warning

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h
tests/compiler_features_tests/c11.c

Fix an issue with some old system that define ATOMIC_LONG_LOCK_FREE as an expression that uses runtime checks. These are invalid in preprocessor conditions such as how we swap between the pthread and c11 atomic implementation at compile time.
This could be made a runtime check and swap, but that would be a much larger refactor and that might introduce it's own performance overhead. Customers with this behavior are strongly encouraged to upgrade. 
Verified legacy build works, and modern compilers still get the performance improvement.

Handle systems defining ATOMIC_LONG_LOCK_FREE as expression

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
crypto/refcount_c11.c
include/openssl/base.h

Some other old compilers don't support the convince macro `static_assert` but do support the C11 keyword `_Static_assert` even though both should be in [assert.h](https://en.cppreference.com/w/c/error/static_assert). 
Built all old platforms internally. 

Use _Static_assert in refcount_c11.c to support old compilers that don't support the macro static_assert

---

crypto/fipsmodule/evp/evp_ctx.c
include/openssl/evp.h

Addresses: CryptoAlg-1716
* Added no-op implementations for several `EVP_PKEY_CTX` functions.

No-op impls for several EVP_PKEY_CTX functions

---

CMakeLists.txt
cmake/go.cmake
crypto/CMakeLists.txt
crypto/fipsmodule/bn/bytes.c
crypto/fipsmodule/bn/internal.h
crypto/internal.h
include/openssl/posix_time.h
include/openssl/time.h
util/doc.config

Upstream merge 2024 08 19

---

.clang-format
crypto/curve25519/curve25519_nohw.c
crypto/curve25519/curve25519_tables.h
crypto/curve25519/make_curve25519_tables.py

Related to CryptoAlg-2625
Using names such as `d` for global variables works if they are only ever used in small scope. However, Ed25519 is being moved under the fips module, which increase the scope by a lot. To allow this, reduce the likelihood of variable name collisions by prefixing variable names with some context information. In this case `k25519`, following convention in the rest of the file.
I removed the line `.clang-format` because the clang version I have is too old. `InsertBraces` was introduced in clang-format 15. A quite new version.

Reduce collision probability for variable names

---

crypto/fipsmodule/bn/asm/x86_64-mont.pl
crypto/fipsmodule/bn/bn_test.cc
crypto/fipsmodule/bn/internal.h
crypto/fipsmodule/bn/montgomery.c
generated-src/linux-x86_64/crypto/fipsmodule/x86_64-mont.S
generated-src/mac-x86_64/crypto/fipsmodule/x86_64-mont.S
generated-src/win-x86_64/crypto/fipsmodule/x86_64-mont.asm

-----
Take a step towards moving the OPENSSL_ia32cap_P usage out of x86_64-mont.pl. The MULX+ADX dispatching within |bn_sqr8x_mont| is deferred to a future change.
Bug: 673
Change-Id: I8768bb33d2c289fd7ccf8743b51721e55ab74f35
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/65527
Reviewed-by: Bob Beck <bbe@google.com>
Reviewed-by: David Benjamin <davidben@google.com>
(cherry picked from commit 7cb8df579329b70cd4ede09d6d228636b8e31e89)
-----

bn: Move x86-64 argument-based dispatching of bn_mul_mont to C.

---

crypto/CMakeLists.txt

* Addresses: https://github.com/aws/aws-lc-rs/issues/470
* NASM object files were previously setup to always contain debug information, including source file paths.
*  `-gcv8` produces the ["CodeView 8" format](https://www.nasm.us/doc/nasmdoc8.html#section-8.5.3).
* Simply using `-g` will produce the [default debug format](https://www.nasm.us/doc/nasmdoc2.html#section-2.1.14) for the target.
* For "release" and "minsizerel" builds, inclusion of debug information is not desirable.

NASM use default debug format

---

crypto/fipsmodule/kdf/kbkdf.c
crypto/fipsmodule/service_indicator/internal.h
crypto/fipsmodule/service_indicator/service_indicator.c
crypto/fipsmodule/service_indicator/service_indicator_test.cc

Add `KBKDF_ctr_hmac` FIPS service indicator with approved digest algorithms. ACVP KAT testing will come in a separate PR.

KBKDF_ctr_hmac FIPS Service Indicator

---

.github/workflows/opensslcomparison.yml
tests/ci/run_openssl_comparison_tests.sh
tool-openssl/internal.h
tool-openssl/x509.cc
tool-openssl/x509_test.cc

Previously only some output followed the user's request using `-out` to direct the output to a file. This change updates everything to use a common `BIO` which is `stdout` by default or the user provided file.
Added new tests that test writing to a file directly with `-out` we have existing tests that cover writing to `stdout` (and then getting redirected to a file with `>`) works as expected.

Update x509 tool to write all output to common BIO which is a file or stdout

---

include/openssl/base.h
tool/speed.cc

Bump AWSLC_API_VERSION to 30 so speed.cc can tell which library versions have ML-KEM support. Add the ML-KEM benchmark for all future versions of AWS-LC that support it.
Ran speed locally:
```
./tool/bssl speed -filter ML-KEM
Did 85000 ML-KEM-512 keygen operations in 1002430us (84794.0 ops/sec)
Did 84000 ML-KEM-512 encaps operations in 1008991us (83251.5 ops/sec)
Did 70000 ML-KEM-512 decaps operations in 1009795us (69321.0 ops/sec)
Did 48000 ML-KEM-768 keygen operations in 1014221us (47327.0 ops/sec)
Did 52000 ML-KEM-768 encaps operations in 1011926us (51387.2 ops/sec)
Did 44000 ML-KEM-768 decaps operations in 1012853us (43441.6 ops/sec)
Did 30000 ML-KEM-1024 keygen operations in 1004572us (29863.5 ops/sec)
Did 34000 ML-KEM-1024 encaps operations in 1012471us (33581.2 ops/sec)
Did 29000 …
```

Add ML-KEM to speed.cc, bump AWSLC_API_VERSION to 30

---

tests/ci/common_posix_setup.sh
tests/ci/integration/run_socat_integration.sh

V1497389456
On Amazon Linux we install into `lib64` and the Ninja executable is called `ninja-build`. Teach the integration script this.
`cmake --build` was introduced in 3.0. Hence, should be portable for our minimal requirements.
This worked for me when I ran it on Amazon Linux 2.

Improve portability of CI integration script

---

crypto/fipsmodule/kdf/sskdf.c
crypto/fipsmodule/service_indicator/internal.h
crypto/fipsmodule/service_indicator/service_indicator.c
crypto/fipsmodule/service_indicator/service_indicator_test.cc

Adds the FIPS service indicator APIs to `SSKDF_digest` and `SSKDF_hmac`.
**NOTE**: AWS-LC doesn't currently support using SHA3-* digest algorithms with our HMAC APIs. So that is why it is missing from the approved digest list for `SSKDF_hmac`.

Add KDA OneStep (SSKDF_digest and SSKDF_hmac) to FIPS indicator

---

crypto/CMakeLists.txt
crypto/evp_extra/internal.h
crypto/evp_extra/p_methods.c
crypto/fipsmodule/bcm.c
crypto/fipsmodule/evp/evp_ctx.c
crypto/fipsmodule/evp/internal.h
crypto/fipsmodule/evp/p_ed25519.c

Follow-up to https://github.com/aws/aws-lc/pull/1809. We forgot to move the EVP Ed25519 function table to the FIPs module. I didn't move the X25519 function table because that is not an approved function with respect to FIPS.

Move EVP ed25519 function table under FIPS module

---

crypto/internal.h

When building with `-DCMAKE_C_STANDARD=11` and using the MSBuild generator (e.g., `-DCMAKE_GENERATOR="Visual Studio 17 2022"`. The build fails with [numerous error messages](https://github.com/aws/aws-lc-rs/actions/runs/10701757878/job/29668443100#step:4:43850) related to an error parsing `vcruntime_c11_stdatomic.h`. 
```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\vcruntime_c11_stdatomic.h(122,1): error C2059: syntax error: '}' [D:\a\aws-lc-rs\aws-lc-rs\target\debug\build\aws-lc-sys-491cb29895f6cb6c\out\build\aws-lc\crypto\fipsmodule\fipsmodule.vcxproj]
```
This change updates out internal header so that it avoids `#include <stdatomic.h>` when the `__STDC_NO_ATOMICS__` macro is set.
I tested and verified it works on my Windows host. I didn't …

Avoid C11 Atomics on Windows

---

crypto/ocsp/ocsp_integration_test.cc
crypto/ocsp/ocsp_lib.c
crypto/ocsp/ocsp_server.c
crypto/ocsp/ocsp_test.cc
crypto/ocsp/test/aws/certs.txt
crypto/ocsp/test/aws/certs_revoked.txt
crypto/ocsp/test/aws/config/ca.cnf
crypto/test/test_util.cc
crypto/test/test_util.h
crypto/x509/x509_test.cc
sources.cmake

Now that we have support for OCSP responder functions, we can now do a round trip integration test with an OCSP request from an OCSP client <-> OCSP response from an OCSP responder. There were a couple bugs found along the way and this implements fixes along with the new tests.
1. `OCSP_cert_to_id` allows for a NULL `subject`, then passes a NULL `serialNumber` to `OCSP_cert_id_new`. OpenSSL allows the NULL parameter, but we disallow it. Changed to allow NULL for better interoptability.
2. Our implementation of `X509_gmtime_adj` happens to use UTC Time, but the producedAt field for OCSP `OCSP_RESPDATA` expects generalized time. This causes a parsing failure from OCSP responses we generated. This was pinned down to `X509_gmtime_adj` calling `ASN1_TIME_adj` internally, which allocates …

Add OCSP round trip integration test with minor fixes

---

crypto/pkcs7/internal.h
crypto/pkcs7/pkcs7.c
crypto/pkcs7/pkcs7_asn1.c
crypto/pkcs7/pkcs7_test.cc
crypto/pkcs7/pkcs7_x509.c

Resolves n/a
Addresses n/a
Other than some manual comment cleanups, this PR's diff is generated with `clang-format`. Run clang-format on pkcs7 code. Commands run:
```
$ clang-format -i crypto/pkcs7/*; echo $?
0
$ clang-format --version
Ubuntu clang-format version 14.0.0-1ubuntu1.1
```
n/a
- CI
---

Run clang-format on pkcs7 code

---

tests/ci/integration/run_socat_integration.sh

socat started cutting off the tests prematurely if the test hadn't finished yet with these commits:
* https://repo.or.cz/socat.git/commitdiff/74d03b37da1226f5d76d1503487d7cd8b90c4d80
* https://repo.or.cz/socat.git/commitdiff/b5b9ee0031eb0f38a71b44a45723d728265ee1bd 
```
+if [ -z "$val_t" ]; then
+    # Determine the time Socat needs for an empty run
+    $SOCAT /dev/null /dev/null         # populate caches
+    MILLIs=$(bash -c 'time socat /dev/null /dev/null' 2>&1 |grep ^real |sed 's/.*m\(.*\)s.*/\1/' |tr -d ,.)
+    while [ "${MILLIs:0:1}" = '0' ]; do MILLIs=${MILLIs##0}; done      # strip leading '0' to avoid octal
+    [ -z "$MILLIs" ] && MILLIs=1
+    [ "$DEFS" ] && echo "MILLIs=\"$MILLIs\" (1)" >&2
+
+    # On my idle development computer this value flaps from 0.001 to 0.004
+    # …
```

fix socat integration CI

---

.github/workflows/misc-tests.yaml
SANDBOXING.md
tests/ci/run_presandbox_tests.sh
tests/ci/test_apps/seccomp_app.c

https://github.com/aws/aws-lc/pull/1825 improved the sandbox mode. This PR adds a unit test to catch obvious sandbox configuration oversights.
It works by creating a small application that installs a seccomp filter. Any syscalls, except a small subset, invoked by AWS-LC will trigger the filter. We both check that the filter will trip on AWS-LC without configuration sandbox mode and that the filter doesn't trip when sandbox mode is configured.

Pre jail unit test

---

crypto/ec_extra/ec_asn1.c
crypto/fipsmodule/ec/ec_test.cc
crypto/fipsmodule/ec/internal.h
crypto/rand_extra/rand_extra.c
include/openssl/ec_key.h
include/openssl/rand.h

We noticed three missing symbols after testing where we were at with our support for Ruby. These are all pretty minor and are related to work we've already done.
* The underlying work for `d2i_ECPKParameters_bio` and `i2d_ECPKParameters_bio` was already completed with https://github.com/aws/aws-lc/commit/60569996e5c1c7d63b60e8339730177a44b3a303. Coverage for actually parsing is included in that PR, so I've only added brief tests to ensure that the same behavior applies to the BIO methods.
* `RAND_egd_bytes` is for querying the entropy gathering daemon EGD on the socket path. We already no-op `RAND_egd` (which directly calls `RAND_egd_bytes` in OpenSSL), so I've applied the same no-op behavior here as well.
N/A
Minor tests for `d2i_ECPKParameters_bio` and `i2d_ECPKParameters_bio`.
By …

More minor symbols Ruby depends on

---

crypto/fipsmodule/evp/digestsign.c
crypto/fipsmodule/evp/evp_ctx.c
crypto/fipsmodule/evp/p_kem.c
crypto/fipsmodule/service_indicator/internal.h
crypto/fipsmodule/service_indicator/service_indicator.c
crypto/fipsmodule/service_indicator/service_indicator_test.cc

* Fixes `EVP_DigestSign` to not set the indicator on size checks
* Adds service indicator for ML-KEM-{5127,768,1024} for `EVP_PKEY_keygen`, `EVP_PKEY_encapsulate`, `EVP_PKEY_decapsulate` functions.
* Adjusts the internal `pkey_kem_keygen` function to use `kem_key` union member for consistency when setting the generated keypair on the EVP_PKEY.

ML-KEM Service Indicator for EVP_PKEY_keygen, EVP_PKEY_encapsulate, EVP_PKEY_decapsulate

---

crypto/fipsmodule/curve25519/curve25519.c
crypto/fipsmodule/service_indicator/service_indicator.c
crypto/fipsmodule/service_indicator/service_indicator_test.cc

Support for Ed25519 FIPS Service Indicator for KeyGen, SigGen, and SigVer.

ED25519 Service Indicator

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

* Use OPENSSL_STATIC_ASSERT which handles all the platform/compiler/C s… by @andrewhop in https://github.com/aws/aws-lc/pull/1791
* ML-KEM refactor by @dkostic in https://github.com/aws/aws-lc/pull/1763
* ML-KEM-IPD to ML-KEM as defined in FIPS 203 by @dkostic in https://github.com/aws/aws-lc/pull/1796
* Add KDA OneStep testing to ACVP by @skmcgrail in https://github.com/aws/aws-lc/pull/1792
* Updating erroneous documentation for BIO_get_mem_data and subsequent usage by @smittals2 in https://github.com/aws/aws-lc/pull/1752
* No-op impls for several EVP_PKEY_CTX functions by @justsmth in https://github.com/aws/aws-lc/pull/1759
* Drop "ipd" suffix from ML-KEM related code by @dkostic in https://github.com/aws/aws-lc/pull/1797
* Upstream merge 2024 08 19 by @skmcgrail in …

prepare for v1.35.0 release

---

crypto/CMakeLists.txt
crypto/bn_extra/convert.c
crypto/evp_extra/p_dh.c
crypto/fipsmodule/evp/evp_ctx_test.cc
crypto/fipsmodule/evp/p_ec.c
crypto/fipsmodule/evp/p_hkdf.c
crypto/fipsmodule/evp/p_rsa.c

Implementation of `EVP_PKEY_CTX_ctrl_str` for various key types.

Implementation of EVP_PKEY_CTX_ctrl_str for various key types

---

crypto/pem/pem_pkey.c
crypto/pem/pem_test.cc
include/openssl/pem.h

Resolves `CryptoAlg-2546`
The main difference between `PEM_write_bio_PrivateKey_traditional` and the modern `PEM_write_bio_PrivateKey` is that `PEM_write_bio_PrivateKey` writes a PKCS#8 encoding, while the traditional one writes with DER encoding.
OpenSSL's `PEM_write_bio_PrivateKey_traditional` calls into `i2d_PrivateKey` which calls into another additional `old_priv_encode` EVP_PKEY_ASN1_METHOD hook. We also need to make the call into `i2d_PrivateKey`, but luckily for us BoringSSL removed the hook and let the call point to the corresponding `i2d_RSA/DSA/ECPrivateKey` methods instead. We can built on this directly to reimplement `PEM_write_bio_PrivateKey_traditional`.
* https://github.com/aws/aws-lc/blob/51d9a8d3b3270fc506fb039a1af0c6f3033f37b6/crypto/x509/i2d_pr.c#L65-L79
* OpenSSL
* …

add support for PEM_write_bio_PrivateKey_traditional

---

crypto/pem/pem_test.cc

Adds two new asserts to a test to prevent dereferencing a NULL ptr. This was called out by a Coverity alert. 

Add asserts in testing to fix Coverity alert

---

crypto/fipsmodule/cpucap/internal.h

* Fix CRYPTO_is_AVX512IFMA_capable

Disable CRYPTO_is_AVX512IFMA_capable

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

* More tweaks for Ruby integration by @samuel40791765 in https://github.com/aws/aws-lc/pull/1852
* Implementation of EVP_PKEY_CTX_ctrl_str for various key types by @justsmth in https://github.com/aws/aws-lc/pull/1850
* Add MLKEM768 Hybrid Groups to libssl by @alexw91 in https://github.com/aws/aws-lc/pull/1849
* add support for PEM_write_bio_PrivateKey_traditional by @samuel40791765 in https://github.com/aws/aws-lc/pull/1845
* Update s2n-bignum subtree  by @torben-hansen in https://github.com/aws/aws-lc/pull/1861
* Add asserts in testing to fix Coverity alert by @smittals2 in https://github.com/aws/aws-lc/pull/1864
* Disable CRYPTO_is_AVX512IFMA_capable by @justsmth in https://github.com/aws/aws-lc/pull/1858
**Full Changelog**: https://github.com/aws/aws-lc/compare/v1.35.0...v1.35.1
By …

preparing for v1.35.1 release

---

crypto/pem/pem_test.cc

Resolves P154590111
Static analysis found a few cases where these tests could fail due to dereferencing null, if a null pointer ever shows up here the test will still fail, but now more gracefully. 

Check for null return pointers in pem_test.cc

---

crypto/pkcs8/pkcs8.c

Addresses #1856
Clarify pkcs8 logic so it doesn't trip up static analysis.

Quell static-analysis concern about div-by-0

---

third_party/s2n-bignum/arm/fastmul/bignum_emontredc_8n_neon.S
third_party/s2n-bignum/arm/fastmul/bignum_kmul_16_32_neon.S
third_party/s2n-bignum/arm/fastmul/bignum_kmul_32_64_neon.S
third_party/s2n-bignum/arm/fastmul/bignum_ksqr_16_32_neon.S
third_party/s2n-bignum/arm/fastmul/bignum_ksqr_32_64_neon.S
third_party/s2n-bignum/x86_att/curve25519/bignum_madd_n25519.S
third_party/s2n-bignum/x86_att/curve25519/bignum_madd_n25519_alt.S

The list that tracks which files from s2n-bignum are used in AWS-LC was not complete. The list used for this PR:
```
PATHS_TO_KEEP="\
./arm/p384 ./x86_att/p384 ./arm/p521 ./x86_att/p521 \
./arm/fastmul/bignum_emontredc_8n.S \
./arm/fastmul/bignum_emontredc_8n_neon.S \
./arm/fastmul/bignum_kmul_16_32.S \
./arm/fastmul/bignum_kmul_16_32_neon.S \
./arm/fastmul/bignum_kmul_32_64.S \
./arm/fastmul/bignum_kmul_32_64_neon.S \
./arm/fastmul/bignum_ksqr_16_32.S \
./arm/fastmul/bignum_ksqr_16_32_neon.S \
./arm/fastmul/bignum_ksqr_32_64.S \
./arm/fastmul/bignum_ksqr_32_64_neon.S \
./arm/generic/bignum_ge.S \
./arm/generic/bignum_mul.S \
./arm/generic/bignum_optsub.S \
./arm/generic/bignum_sqr.S \
./arm/generic/bignum_copy_row_from_table.S \
./arm/generic/bignum_copy_row_from_table_8n_neon.S \ …
```

Update s2n-bignum subtree

---

crypto/evp_extra/evp_extra_test.cc
crypto/fipsmodule/ml_kem/ml_kem_ref/kem.c
ssl/ssl_test.cc

CryptoAlg-2620
ML-KEM encapsulation key modulus check as specified in FIPS 203 Section 7.2.
https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.203.pdf

ML-KEM encapsulation key modulus check

---

tests/docker_images/gcc/7.2/Dockerfile
tests/docker_images/gcc/build_images.sh

Provides an easy way to create docker image w/ GCC 7.2 for local testing.

Add docker image for gcc 7.2

---

crypto/evp_extra/evp_extra_test.cc
crypto/fipsmodule/ml_kem/ml_kem_ref/kem.c

CryptoAlg-2620
ML-KEM decapsulation key check as specified in Section 7.3 of FIPS 203: https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.203.pdf

ML-KEM decapsulation key hash check

---

CMakeLists.txt

n/a
The team that works on [awslabs/tough](https://github.com/awslabs/tough) wants to support using the aws-lc-rs Rust crate (https://github.com/awslabs/tough/issues/824). As one of several downstream consumers of tough outside of AWS, we were asked for feedback. Oxide uses tough as part of our product which runs on the illumos operating system.
When linking Rust code using aws-lc-rs, the linker cannot find several `aws_lc_*` symbols:
```
Undefined            first referenced
symbol                  in file
aws_lc_0_21_1_bn_gather5            /home/iliana/git/omicron/target/debug/deps/libaws_lc_sys-ff0ab07b18206e1f.rlib(bcm.c.o)
aws_lc_0_21_1_rsaz_1024_red2norm_avx2 /home/iliana/git/omicron/target/debug/deps/libaws_lc_sys-ff0ab07b18206e1f.rlib(bcm.c.o)
aws_lc_0_21_1_aesni_gcm_encrypt …
```

support building on illumos systems

---

crypto/fipsmodule/service_indicator/service_indicator.c
crypto/fipsmodule/service_indicator/service_indicator_test.cc

`CryptoAlg-2633`
The service indicator "update" functions were modified to check for the existence of custom crypto in RSA_METHOD and EC_KEY_METHOD structs. If custom crypto is utilized for a given operation, the service indicator should not be updated. The checks are conservative and do not update the service indicator for a signing operation for EC/RSA keys if either custom sign or sign_sig/sign_raw functionality is provided - regardless of whether these may be invoked. 
Tested both EC_KEY_METHOD and RSA_METHOD with custom crypto and ensured the service indicator was not updating. 

Update Service Indicator to handle custom crypto through *_METHOD structs

---

ssl/ssl_test.cc

N/A
The way the test was generating a public key that is not consistent with a secret key is by xor-ing the first byte of the key with 1. Such key modifications can inadvertently make the key invalid and thus fail the test.
For example, before performing encapsulation ML-KEM decodes the public key bytes to an array of 12-bit coefficients and checks that all coefficients are in the range [0, 3328]. If the first two bytes of the key encode the coefficient 3328 then xor-ing the first byte with 1 will make the coefficient equal to 3329. The call to encapsulate will then fail because 3329 is an invalid coefficient.
How is this change tested (unit tests, fuzz tests, etc.)? …

Fix flaky ssl BadKemKeyShare tests

---

crypto/fipsmodule/ml_kem/ml_kem_ref/kem.c

CryptoAlg-2620
PR #1868 implemented the encapsulation key modulus check
naively, as specified in FIPS 203 which introduced a significant
performance hit to encapsulation. In this change we optimize
encoding/decoding to/from bytes functions to reduce the performance
regression.
For example, encapsulation performance (ops/s) measured on M1 macbook:
```
| Variant | Before #1868 | After #1868 | After this change |
| 512     |    94738     |    68293    |       92494       |
| 768     |    58672     |    42083    |       55572       |
| 1024    |    38893     |    28536    |       36820       |
```
How is this change tested (unit tests, fuzz tests, etc.)? Are there any …

ML-KEM encaps key modulus check optimization

---

pkgconfig/libcrypto.pc.in
pkgconfig/libssl.pc.in
pkgconfig/openssl.pc.in

Discovered that our pkg-config description files had hard-coded libdir and includedir values that could differ from the actual installation directory values.

Fix pkg-config files

---

tests/ci/cdk/cdk/codebuild/ec2_test_framework_omnibus.yaml

c6g on the ec2-test-framework has been slowing down considerably with our recent FIPS changes.
N/A
N/A

Use larger instance for c6g fips

---

tests/ci/run_formal_verification.sh

Previously this script always used the head of aws-lc-verification which will have diverged from this branch since the code on the FIPS 2024 branch is a snapshot of AWS-LC. I picked https://github.com/awslabs/aws-lc-verification/commit/b19e155db93518ea1bf23eb40c38ad27c8899c7a since it's the most recent commit and known to be working.
This will hopefully get the CI to pass.

Pin the version of aws-lc-verification to a known working version

---

crypto/ocsp/ocsp_test.cc

Resolves https://github.com/aws/aws-lc/issues/1889
It turns out the first call to `OCSP_check_validity` in `TestGoodOCSP` will emit two additional errors on to the error stack once the "this update" field is outdated. Clearing the previous additional errors on the stack allows us to check for which specific errors were emitted more accurately. 

Fix OCSP timebomb in tests

---

include/openssl/ocsp.h

Ruby happens to expect these flags to exist with values, but doesn't necessarily use them. There were a few other flags that I missed, so I'm adding them here. These should also be within their own section.

Add and move OCSP no-op flags to own section

---

CMakeLists.txt
crypto/fipsmodule/CMakeLists.txt
tests/ci/common_posix_setup.sh
third_party/s2n-bignum/include/_internal_s2n_bignum.h

Symbols from s2n-bignum needed special build shenanigans because they essentially are "third-party" (although still AWS owned) in the context of what code AWS-LC repository can touch. Therefore they didn't have the special "prefix" header files. This corrupts the prefix build in two ways that needed to be handled:
- references to s2n-bignum files are prefixed, but the definitions are not. Obviously, this doesn't work...
- when we test the prefix build, we must take care to not assume s2n-bignum symbols are prefixed...
Removing these two corruptions, means it's now a bit easier to import s2n-bignum code. A small step closer to maybe switching to a submodule.
Should also make the rust build easier. Hopefully...
Originally I went with a method that required s2n-bignum source code changes. …

Remove special s2n-bignum symbol handling sauce from build

---

crypto/fipsmodule/ml_kem/ml_kem_ref/indcpa.c
crypto/fipsmodule/ml_kem/ml_kem_ref/kem.c

CryptoAlg-2616
FIPS 203 Section 3.3 requires destruction of intermediate values.
AWS-LC ML-KEM implementation allocates intermediate values
only on stack, so this destruction seems a bit silly, but we do it
anyway for compliance.

ML-KEM FIPS 203 destruction of intermediate values

---

tests/ci/run_formal_verification.sh

Talked with @pennyannn and they setup a specific branch in the verification repo so now that branch should always work with this 2024 FIPS branch and stay in sync with it.
Ran locally and verified it got the right branch and is a little faster.

Use aws-lc-verification branch spefically for the 2024 release, update submodules with depth 1

---

crypto/evp_extra/evp_extra_test.cc
crypto/fipsmodule/evp/evp_ctx.c
crypto/fipsmodule/evp/internal.h
crypto/fipsmodule/evp/p_rsa.c
include/openssl/evp.h

Resolves `CryptoAlg-1716`
Resolves `CryptoAlg-2698`
We tried to no-op these functions, but it turns out Ruby depends on them pretty extensively as the interruption mechanism for threads. One of[ Ruby's tests](https://github.com/ruby/ruby/blame/ruby_3_1/test/openssl/test_pkey_rsa.rb#L73-L77) depends on `EVP_PKEY_CTX_get_app_data` to return an actual value from the callback function, but we return NULL as a no-op. Ruby seems to depend on the `EVP_PKEY` callback function and relevant application data to correctly handle interruptions. Based on the relevant commit messages, the expectation is that the operation is interrupted, but AWS-LC continues resuming the operation and returns a generated RSA key. It looks like we may have to consider implementing functionality for these callback …

add support for EVP_PKEY_CTX callback functions

---

crypto/fipsmodule/CMakeLists.txt

Accidentally added the same option twice in https://github.com/aws/aws-lc/pull/1903 when invoking the pre-processor. Not fatal, but also not necessary... So, remove the duplicate option.

Remove duplicate s2n-bignum prefix include option

---

crypto/fipsmodule/CMakeLists.txt
third_party/s2n-bignum/include/s2n-bignum_aws-lc.h

CryptoAlg-2241
https://github.com/awslabs/s2n-bignum/pull/98 handles Windows not supporting static array dimensions. We have our own header files with function declarations for s2n-bignum. Hence that work was never ported automatically.
Adopt same detection approach as in referenced PR. MSVC doesn't support it, neither does C++. So, try to detect those cases as well as if variable-length arrays aren't supported.
Support it now but use our own macro `OEPNSSL_WINDOWS` to determine whether we are executing a Windows build. Take a dependency on `target.h` because this is minimal. Also teach the s2n-bignum file pro-processing where to find `target.h` even though I don't think this is strictly necessary; non of the pre-processed files include the header file and everywhere the header file is …

Handle Windows not supporting static array dimension

---

crypto/fipsmodule/rand/new_rand.c
crypto/fipsmodule/rand/new_rand_internal.h
crypto/fipsmodule/rand/new_rand_test.cc
crypto/ube/ube.c

This PR integrates protection of the thread-local state into the new randomness generation implementation. `rand_ensure_ctr_drbg_uniquness()` is the function that determines whether a randomization of the thread-local state is necessary. `rand_ensure_ctr_drbg_uniquness()` is called inline in the core randomness generation code path (in `RAND_bytes_core()` and invoked on every entry.
The only mechanism currently implemented that can force a randomization is the UBE mechanism implemented in https://github.com/aws/aws-lc/commit/bc7aeff2f5c12c62f17df71abdd0c7b55c3eb984. Note that if UBE is "unavailable" then a randomization is forced every time.
Some additional support code is implemented to mock the UBE detection and determine if correct behaviour occurred.
The failing tests are because the …

Integrate ube for rand engine

---

crypto/evp_extra/evp_extra_test.cc
crypto/evp_extra/p_dh.c
crypto/fipsmodule/evp/evp_ctx_test.cc
crypto/fipsmodule/evp/internal.h
include/openssl/evp.h

Addresses CryptoAlg-2363
* Support for EVP_PKEY_DH "paramgen".
* Implentation for `EVP_PKEY_CTX_set_dh_paramgen_prime_len` and `EVP_PKEY_CTX_set_dh_paramgen_generator`
* Support of these operations via `EVP_PKEY_CTX_ctrl` and `EVP_PKEY_CTX_ctrl_str`
* New test added.

Implement more EVP_PKEY_DH functionality

---

crypto/fipsmodule/ec/ec.c
crypto/fipsmodule/ec/ec_test.cc
crypto/fipsmodule/ec/internal.h
include/openssl/ec.h

Resolves `CryptoAlg-2547`
Following up on https://github.com/aws/aws-lc/pull/1860 which introduces an API to return a mutable `EC_GROUP`, this commit applies the same concept for custom curves. Custom curves are already dynamically allocated, but were logically immutable due to the strict enforcement of calling `EC_GROUP_new_curve_GFp` -> `EC_GROUP_set_generator`.
The reference call in `EC_GROUP` that was used for custom curves is no longer needed. We actually duplicate the structure instead.
N/A
Test using a custom generator identical to P-256.

Add EC_GROUP mutablility to custom curves

---

crypto/evp_extra/evp_extra_test.cc
crypto/fipsmodule/evp/evp_ctx.c
include/openssl/experimental/kem_deterministic_api.h
util/fipstools/acvp/modulewrapper/modulewrapper.cc

PQCrypto-103 
`EVP_PKEY_keygen_deterministic` allows callers to query the required
size for the `seed` parameter. This change avoids the unnecessary
allocation of memory for the `out_pkey` parameter to ensure that this
integer getter has no side effects.
Updated the unit tests.

Avoid allocating EVP_PKEY on size checks

---

CMakeLists.txt
cmake/JoinPaths.cmake
pkgconfig/libcrypto.pc.in
pkgconfig/libssl.pc.in
pkgconfig/openssl.pc.in

Currently the pkgconfig files are broken when aws-lc is built with Nix. 
See https://github.com/jtojnar/cmake-snips?tab=readme-ov-file#concatenating-paths-when-building-pkg-config-files, and the PR made to libfmt https://github.com/fmtlib/fmt/pull/1657
I'm not sure if bumping the minimum required CMake version is preferred. The alternative would be to add https://github.com/jtojnar/cmake-snips/blob/master/CMakeScripts/JoinPaths.cmake to the `cmake/` directory in the repository. However, most linux distributions have at least CMake 3.20, if not 3.25 so I don't see why this would be a problem.

build: fix pkgconfig files

---

crypto/x509/x509_test.cc
crypto/x509/x509_vfy.c

Resolves `V1533483320`
Some consumers noticed that a behavior difference between AWS-LC and OpenSSL when the trust store contains certificates that are issued by other certificates that are also in the trust store. A common example of this would be the trust store containing both the intermediate and the root for the cert chain (`leaf -> intermediate -> root`). The default settings of AWS-LC and OpenSSL require `root` to be self signed for the chain to be verified.
Many TLS implementations set the `X509_V_FLAG_PARTIAL_CHAIN` flag however, which allows non self signed certificates to be trusted in the trust store. When `X509_V_FLAG_PARTIAL_CHAIN` is set, OpenSSL 1.1.1 will only verify leaf and intermediate, since intermediate is a trusted certificate. However, AWS-LC will continue building …

Align X509 PARTIAL_CHAIN behavior with 1.1.1

---

crypto/x509/x509_test.cc
crypto/x509/x509_vfy.c

Some consumers noticed that a behavior difference between AWS-LC and OpenSSL when the trust store contains certificates that are issued by other certificates that are also in the trust store. A common example of this would be the trust store containing both the intermediate and the root for the cert chain (`leaf -> intermediate -> root`). The default settings of AWS-LC and OpenSSL require `root` to be self signed for the chain to be verified.
Many TLS implementations set the `X509_V_FLAG_PARTIAL_CHAIN` flag however, which allows non self signed certificates to be trusted in the trust store. When `X509_V_FLAG_PARTIAL_CHAIN` is set, OpenSSL 1.1.1 will only verify leaf and intermediate, since intermediate is a trusted certificate. However, AWS-LC will continue building a certificate chain …

Align X509 PARTIAL_CHAIN behavior with 1.1.1 (#1917)

---

include/openssl/base.h
tests/ci/cdk/cdk/codebuild/github_ci_linux_arm_omnibus.yaml
tests/ci/common_posix_setup.sh
tests/ci/run_benchmark_build_tests.sh
tool/speed.cc

P162016551
Firstly, when building multiple versions of `bssl` using the `main` branch as the base, builds on Arm will fail when using older versions of AWS-LC e.g. FIPS 2021 from the 2021 FIPS branch. The reason is that an internal header file `[...]/cpucap/nternal.h` is included into the compilation unit by `#include "..."`. The gcc search path will then, irrespective of any user-specified search paths via `-I`, pick up the `main` branch header files. This include identifiers such as `ARMV8_NEOVERSE_V2`. But the definition of this identifier is in `arm_arch.h`, which is transitively included into the compilation unit via `#include <..>` directives. The search path for these DO follow the user-specified search path from `-I` (at least on GCC) and use e.g. the FIPS 2021 include file …

Add 2024 FIPS and fix build issues on older arm FIPS

---

crypto/fipsmodule/kdf/kbkdf.c
crypto/fipsmodule/service_indicator/internal.h
crypto/fipsmodule/service_indicator/service_indicator.c
crypto/fipsmodule/service_indicator/service_indicator_test.cc

* KBKDF: Per SP 800-131Ar1, Section 8: "The length of the key-derivation key shall be at least 112 bits.” There must be a non-approved service indicator for KBKDF with KDK < 112 bits.

800-131Ar1: length of the key-derivation key shall be at least 112 bits.

---

crypto/dh_extra/dh_test.cc
crypto/evp_extra/evp_asn1.c
crypto/evp_extra/p_dh_asn1.c
crypto/evp_extra/p_methods.c
crypto/fipsmodule/evp/internal.h

Addresses: CryptoAlg-2696
* Support marshalling/unmarshalling of DH public keys.
Added test `DHTest.DHMarshalPubKey`

Marshalling/Unmarshalling DH public keys

---

tests/ci/cdk/cdk/components.py
tests/ci/common_ssm_setup.sh
tests/ci/lambda/Cargo.lock
tests/ci/lambda/Cargo.toml
tests/ci/lambda/src/bin/purge-stale-builds.rs

Resolves `P149524833`
There were some leaking SSM documents that weren't being pruned with the ec2 instances used. This adds the corresponding logic to remove them.
N/A
Tested on personal fork: https://github.com/samuel40791765/aws-lc/pull/35

Also prune SSM documents from ec2-test-framework

---

crypto/fipsmodule/kdf/kbkdf.c
crypto/fipsmodule/service_indicator/internal.h
crypto/fipsmodule/service_indicator/service_indicator.c
crypto/fipsmodule/service_indicator/service_indicator_test.cc

Cherry-pick https://github.com/aws/aws-lc/pull/1924

[fips-2024-09-27] Cherry-pick PR 1924, KBKDF kdk length indicator checks

---

ssl/ssl_key_share.cc
ssl/ssl_test.cc

* https://github.com/google/boringssl/commit/72a60506ded3407454d6ddc1d848c266020c0c82
This is extremely silly and a huge waste of everyone's time (I deeply regret disambiguating illegal_parameter and decode_error for RFC 8446), but so it goes. Technically these errors pass the TLS syntax and are an invalid value, so they should be illegal_parameter.
Note: TLS defines two generic alerts (see Section 6) to use upon
failure to parse a message.  Peers which receive a message which
cannot be parsed according to the syntax (e.g., have a length
extending beyond the message boundary or contain an out-of-range
length) MUST terminate the connection with a "decode_error" alert.
Peers which receive a message which is syntactically correct but
semantically invalid (e.g., a DHE share of p - 1, or an …

Use illegal_parameter instead of decode_error for invalid key shares

---

crypto/fipsmodule/sha/asm/sha1-586.pl
crypto/fipsmodule/sha/asm/sha256-586.pl
crypto/fipsmodule/sha/internal.h
crypto/fipsmodule/sha/sha1.c
crypto/fipsmodule/sha/sha256.c
crypto/fipsmodule/sha/sha512.c
crypto/pem/pem_lib.c
crypto/pem/pem_pk8.c
crypto/pem/pem_pkey.c
generated-src/linux-x86/crypto/fipsmodule/sha1-586.S
generated-src/linux-x86/crypto/fipsmodule/sha256-586.S
generated-src/mac-x86/crypto/fipsmodule/sha1-586.S
generated-src/mac-x86/crypto/fipsmodule/sha256-586.S
generated-src/win-x86/crypto/fipsmodule/sha1-586.asm
generated-src/win-x86/crypto/fipsmodule/sha256-586.asm
include/openssl/bio.h
include/openssl/ex_data.h
include/openssl/pem.h
include/openssl/x509.h
ssl/encrypted_client_hello.cc
ssl/internal.h
ssl/ssl_lib.cc
ssl/ssl_session.cc

Upstream merge 2024 10 17

---

crypto/x509/x509_test.cc
crypto/x509/x509_vfy.c

Some consumers noticed that a behavior difference between AWS-LC and OpenSSL when the trust store contains certificates that are issued by other certificates that are also in the trust store. A common example of this would be the trust store containing both the intermediate and the root for the cert chain (`leaf -> intermediate -> root`). The default settings of AWS-LC and OpenSSL require `root` to be self signed for the chain to be verified.
Many TLS implementations set the `X509_V_FLAG_PARTIAL_CHAIN` flag however, which allows non self signed certificates to be trusted in the trust store. When `X509_V_FLAG_PARTIAL_CHAIN` is set, OpenSSL 1.1.1 will only verify leaf and intermediate, since intermediate is a trusted certificate. However, AWS-LC will continue building a certificate chain …

[fips-2024-09-27] Align X509 PARTIAL_CHAIN behavior with 1.1.1

---

util/all_tests.go

Remove old and/or unsupported Intel CPU types from SDE tests.

Remove old Intel CPU types

---

crypto/fipsmodule/ec/ec_key.c
crypto/fipsmodule/rsa/rsa_impl.c
crypto/internal.h
crypto/rsa_extra/rsa_test.cc

Addresses #CryptoAlg-2756
FIPS review: The module should enter an error state if PCT fails in EC or RSA key generation, so there should be no retries and it aborts. This is to avoid that other threads would continue to use the module.
Death tests are testing aborting when keygen is in error.

Remove retries on PCT failure in EC and RSA key generation.

---

crypto/fipsmodule/ec/ec_key.c
crypto/fipsmodule/rsa/rsa_impl.c
crypto/internal.h
crypto/rsa_extra/rsa_test.cc

Addresses #CryptoAlg-2756
FIPS review: The module should enter an error state if PCT fails in EC or RSA key generation, so there should be no retries and it aborts. This is to avoid that other threads would continue to use the module.
(cherry picked from commit 90d2a34ead8d51c3a97be33f1e6eff751707807c on main, PR #1938)

Remove retries on PCT failure in EC and RSA key generation. (#1938)

---

tests/ci/integration/run_mysql_integration.sh

Addresses P162082038
Bump the CI to use MySQL 9.1.0

bump mysql CI to 9.1.0

---

.github/workflows/integrations.yml
crypto/bio/pair.c
crypto/cipher_extra/cipher_extra.c
include/openssl/bio.h
include/openssl/err.h
tests/ci/integration/nmap_patch/aws-lc-nmap.patch
tests/ci/integration/run_nmap_integration.sh

CryptoAlg-2552
This PR adds Nmap tip of main to our CI. It includes: 
1. A patch to Nmap
2. Adding an include for <errno.h> to <err.h>, OpenSSL does this but we previously did not
3. Adding BIO_destroy_bio_pair (the functionality was already implemented, we are simply exposing that through a new func)
4. Creating a new alias for "DES" in the EVP_CIPHER API. The "default" mode used in OpenSSL 1.1.1 and 3.1 with DES is CBC [(link)](https://docs.openssl.org/1.1.1/man1/enc/#supported-ciphers:~:text=des%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Alias%20for%20des%2Dcbc).
Locally built and ran nmap tests with AWS-LC and verified they pass. Conducted a dry run with the extra included file to ensure it doesn't break any consumers in live (refer to CryptoAlg-2552 for the dryrun link).
By …

Missing functionality + Adding Nmap to our CI

---

crypto/fipsmodule/ec/ec_test.cc
crypto/fipsmodule/ec/oct.c

Addresses `CryptoAlg-2697`
Ruby [has tests](https://github.com/ruby/ruby/blob/ruby_3_1/test/openssl/test_pkey_ec.rb#L373-L378) asserting that OpenSSL encodes and decodes infinity points to 0. This doesn't quite make sense, but our hand is sort of forced here. It does show that there's dependence on this subtle behavior and we might as well support it since we're trying to gain better compatibility.
```
assert_equal false, point.infinity?
point.set_to_infinity!
assert_equal true, point.infinity?
assert_equal 0.to_bn, point.to_bn
assert_equal B(%w{ 00 }), point.to_octet_string(:uncompressed)
assert_equal true, point.on_curve?
```
Tweak against changes from these commits;
* https://github.com/aws/aws-lc/commit/d9e27021e171d5f8c790b282315a07bde735da97
* …

Support encode or decode ∞ like OpenSSL

---

crypto/fipsmodule/evp/evp_ctx_test.cc
crypto/fipsmodule/evp/internal.h
crypto/fipsmodule/evp/p_hmac.c
crypto/hmac_extra/hmac_test.cc

Addresses CryptoAlg-2695
* Expands support for `EVP_PKEY_HMAC`
* Support for "keygen" operations
* Support for `EVP_PKEY_CTX_ctrl_str`.
* Support for `EVP_PKEY_CTRL_SET_MAC_KEY` operation w/ `EVP_PKEY_CTX_ctrl`
* New tests added.

Expand support for EVP_PKEY_HMAC

---

crypto/CMakeLists.txt
crypto/pkcs7/bio/bio_deprecated_test.cc
crypto/pkcs7/bio/bio_md_test.cc
crypto/pkcs7/bio/md.c
crypto/pkcs7/internal.h

Addresses CryptoAlg-2494
This change introduces a new filter BIO, `BIO_f_md` for use in PR 1816.
- n/a
- new unit tests
---

Add PKCS7-internal BIO_f_md

---

crypto/dsa/dsa.c
crypto/dsa/internal.h

Ruby test-cases expect to be able to set the digest for the DSA paramgen operation.

Ruby Support - DSA custom md

---

crypto/fipsmodule/ec/ec.c
crypto/fipsmodule/ec/ec_test.cc
crypto/fipsmodule/ec/oct.c
include/openssl/ec.h

Resolves `CryptoAlg-2697`
This is the first time it has come up, but Ruby depends on the `POINT_CONVERSION_HYBRID` format in its tests and expects the underlying libcrypto to support it. 
* https://github.com/ruby/ruby/blob/ruby_3_1/test/openssl/test_pkey_ec.rb#L358-L366
There's not too much a difference between `POINT_CONVERSION_HYBRID` and `POINT_CONVERSION_UNCOMPRESSED` except that the first bit contains information about the quadratic equation y is at. We have the building blocks to support and can get this working with some tweaking around.
`POINT_CONVERSION_HYBRID` works very similar to `POINT_CONVERSION_UNCOMPRESSED` so we're reusing a lot of code. Most of this change is working with the first byte `POINT_CONVERSION_HYBRID` does differently and point the encoding to the right …

Add support for POINT_CONVERSION_HYBRID

---

crypto/pkcs7/bio/bio_md_test.cc
crypto/x509/v3_lib.c

Added null check to mitigate alert by coverity. Changed two tests to account for negative return value. 

Fixes for Coverity Alerts

---

.github/docker_images/gcc-4.8/Dockerfile
.github/docker_images/gcc-4.8/awslc_build.sh
crypto/evp_extra/evp_extra_test.cc

* GCC v4.x compilers lack support for multiline C++11 raw string literals: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55971
* We have one test file that has string literals that fail to compile on GCC 4.8.  Otherwise, all of our tests compile and run successfully using GCC 4.8.
* Preprocessor guard placed around section of test that uses multiline C++11 raw string literals so that compilation does not fail using GCC v4.x.

Also test w/ gcc 4.8

---

include/openssl/ssl.h
ssl/extensions.cc
ssl/handshake_client.cc
ssl/handshake_server.cc
ssl/internal.h
ssl/ssl_key_share.cc
ssl/ssl_lib.cc
ssl/ssl_test.cc
ssl/tls13_client.cc
ssl/tls13_server.cc

Addresses `CryptoAlg-2699`
Ruby has a dependency on `SSL_get_server_tmp_key` which we've exposed as a no-op in the past. Ruby has[ a couple of tests ](https://github.com/ruby/ruby/blame/ruby_3_1/test/openssl/test_ssl.rb#L1601-L1653) that expect the function to actually return a value however, which means we'll have to actually support this.
The relevant information about the server key was saved in a `tmp` structure in `SSL3_STATE` (originally `ssl3_state_st` in OpenSSL). This `tmp` structure has been removed by Boring, with its contents moved either to `SSL_HANDSHAKE` or the state machine. `peer_key` seems to contain the relevant information we want and it's been moved to `SSL_HANDSHAKE` in this case. The issue is any information in `SSL_HANDSHAKE` is shed immediately after the …

Actually add support for SSL_get_server/peer_tmp_key

---

crypto/x509/t_req.c
crypto/x509/x509_att.c
include/openssl/x509.h

`X509_ATTRIBUTE_count` dereferences `a` without a NULL check, added it in. 

Coverity Fix Null Check

---

crypto/fipsmodule/ml_kem/ml_kem_ref/kem.c

N/A
This change implements the ML-KEM Pairwise Consistency Test (PCT)
for key generation as required by FIPS 140-3 Implementation Guidance.

ML-KEM keygen Pairwise Consistency Test

---

crypto/fipsmodule/curve25519/curve25519.c

Cherry-pick of #1968 
Per 10.3.A, Ed25519 needs a PCT. Only implement for FIPS build type and make it a simple sign-verify cycle. Abort on failure.

EDDSA PCT (#1968)

---

crypto/fipsmodule/cipher/internal.h
include/openssl/aes.h

Moved the `AES_cfb1_encrypt` and `AES_cfb8_encrypt` to the `openssl/aes.h` header to be exposed similarly too `AES_cfb128_encrypt`.

Expose AES_cfb1_encrypt and AES_cfb8_encrypt

---

crypto/fipsmodule/rand/new_rand.c
crypto/fipsmodule/rand/new_rand_test.cc

As per FIPS, something equivalent to sensitive memory must not be kept around in the clear. Often the sensitive stuff we produce is then handed off to a linked application. But we do have some memory we control, namely the thread-local CTR-DRBG states. It's not clear why CTR-DRBG states are actually sensitive for the purpose of zeroization; the primary security property of a DRBG is backtracking resistance, so someone would need to break the security of the scheme to take advantage of the state. Obviously, one can generate future outputs from a DRBG state, since it's deterministic. But that's not the purpose of zeroization. Regardless, zeroization is what we must do.
But when a process exists, all threads might not have been gracefully exited. To ensure this doesn't leave around sensitive …

Globally clear thread-local states

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

* 800-131Ar1: length of the key-derivation key shall be at least 112 bits. by @skmcgrail in https://github.com/aws/aws-lc/pull/1924
* Marshalling/Unmarshalling DH public keys by @justsmth in https://github.com/aws/aws-lc/pull/1916
* Also prune SSM documents from ec2-test-framework by @samuel40791765 in https://github.com/aws/aws-lc/pull/1925
* Use illegal_parameter instead of decode_error for invalid key shares by @justsmth in https://github.com/aws/aws-lc/pull/1923
* Add null check in dh testing by @torben-hansen in https://github.com/aws/aws-lc/pull/1937
* DH paramgen callback by @justsmth in https://github.com/aws/aws-lc/pull/1928
* Upstream merge 2024 10 17 by @torben-hansen in https://github.com/aws/aws-lc/pull/1934
* Remove old Intel CPU types by @justsmth in …

Prepare v1.38.0 release

---

CMakeLists.txt
crypto/rand_extra/windows.c

Resolves #1971
- silence `-Werror,-Wcast-function-type-mismatch` in `crypto/rand_extra/windows.c`.
- extend `-Wno-cast-function-type` to clang versions supporting it.
Should address https://gitlab.gnome.org/GNOME/gnome-terminal/-/issues/96 also for clang builds.
Ref: #155
I build-tested both changes.

fix `-Wcast-function-type` build issues

---

crypto/bytestring/internal.h
ssl/ssl_asn1.cc
ssl/ssl_test.cc

Addresses `CryptoAlg-2700`
`i2d_SSL_SESSION` wasn't exactly following the correct behavior of the legacy `i2d` functions when `pp` is non-NULL, but `*pp` is NULL. This caused issues with functions expecting a newly allocated buffer when calling `i2d_SSL_SESSION` with the recommended documented behavior. See `i2d_SAMPLE` for more details.
https://github.com/aws/aws-lc/blob/48a40573eae3b09ef9b0c3d2d0180506fb214b0c/include/openssl/asn1.h#L254-L266
N/A
New test below usage of `i2d_SSL_SESSION` to verify the behavior.

Fix i2d behavior for i2d_SSL_SESSION

---

ssl/ssl_session.cc
ssl/ssl_test.cc

Addresses `CryptoAlg-2700`
While debugging the Ruby tests using an external session cache for TLS 1.2, there was an issue found where we were bumping up the `SSL_CTX_sess_hits` counter even when there wasn't a session found in the cache. We bump `sess_hits` in three places, due to it's broader implied meaning in OpenSSL. @WillChilds-Klein has an older commit with a nice description of the counter: https://github.com/aws/aws-lc/commit/4b180651d7ea71626126f597c29b7367c063cc6e
Apparently session could be a nullptr, which means a session wasn't found. In the original code, this meant that we would be updating the cache hit counter regardless of a session being found or not. This should only be updated when a session was found. Changing it to check for an existing pointer in session fixes …

Fix sess_hits counter on the server

---

.github/docker_images/gcc-4.8/Dockerfile

The CI job started [failing in the last few days](https://github.com/aws/aws-lc/actions/runs/11782211980/job/32818623601?pr=1979).
```
...
> [ 1/12] FROM docker.io/library/gcc:4.8@sha256:43c6eaefe26ad414b2eefbee68688d1467823424cacbbd1703da4a50ce2c7654:
------
Dockerfile:4
--------------------
2 |     # SPDX-License-Identifier: Apache-2.0 OR ISC
3 |     
4 | >>> FROM gcc:4.8
5 |     
6 |     VOLUME ["/awslc"]
--------------------
ERROR: failed to solve: no signatures
Error: Process completed with exit code 1.
```

CI gcc-4.8 - use 4.8.5 tag

---

crypto/fipsmodule/modes/gcm.c

Addresses aws/aws-lc-rs#574
The compiler cannot always confirm that the array indices used are within the required bounds.  On certain platform, specifically powerpc64le in this case, the compiler may generate a warning about it.  For our build, warnings are treated as errors thus causing compilation to fail.
Adds sanity checks to several locations in `gcm.c` that abort if the logic would reference an out-of-bounds index of an array.

Avoid compiler warning

---

crypto/fipsmodule/rand/internal.h
tool/speed.cc

Add two new benchmarks by refactoring the existing RNG benchmark to support multiple functions. 
Looking at the tree DRBG PR got me interested in the performance impact of calling CRYPTO_sysrand. These benchmarks will be very OS dependent. 
On an M1 mac:
```
./tool/bssl speed -filter RNG
Did 2572000 RNG (16 bytes) operations in 1000160us (2571588.5 ops/sec): 41.1 MB/s
Did 2323000 RNG (256 bytes) operations in 1000233us (2322458.9 ops/sec): 594.5 MB/s
Did 1714000 RNG (1350 bytes) operations in 1000052us (1713910.9 ops/sec): 2313.8 MB/s
Did 631000 RNG (8192 bytes) operations in 1000242us (630847.3 ops/sec): 5167.9 MB/s
Did 360000 RNG (16384 bytes) operations in 1001003us (359639.3 ops/sec): 5892.3 MB/s
./tool/bssl speed -filter CRYPTO_sys
Did 4014000 CRYPTO_sysrand (16 bytes) operations in …
```

Add CRYPTO_sysrand benchmarks to speed.cc

---

tool/speed.cc

Addresses: P169365635
* Allocate large value on the heap instead of stack.

Allocate 16k scratch on heap

---

ssl/extensions.cc
ssl/internal.h
ssl/ssl_privkey.cc
ssl/ssl_test.cc
ssl/ssl_x509.cc

Addresses `CryptoAlg-2699`
Ruby has a dependency on the multiple certificate slot mechanisms that OpenSSL allows for. We've already done the work to support this, but [another Ruby 3.1 test](https://github.com/ruby/ruby/blame/ruby_3_1/test/openssl/test_ssl.rb#L137-L178) has exposed a gap in our support. We were only depending on the negotiated signature algorithms to retrieve the right certificate for the server to send back, but the cipher authentication scheme was [also checked in OpenSSL](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/ssl/t1_lib.c#L2576-L2593) as well. Ruby's tests happen to only depend on configuring the authentication scheme which brought this to light.
We happen to do only do this when checking private keys for TLS 1.0/1.1 , this also fixes it to check …

Account for cipher auth with multiple cert slots

---

crypto/test/file_util.cc
crypto/test/file_util.h

Addresses: P168988559
* Only use move semantic for `TemporaryFile` and `ScopedFD`.
* Set umask prior to creating temporary file.

Cleanup test File utilities

---

crypto/fipsmodule/rand/new_rand.c
crypto/fipsmodule/rand/new_rand_test.cc
tests/ci/run_posix_tests.sh

Default generation number value should be the current value to avoid an immediate reseed.
The function used in the randomness generation test for no-thread was missing an argument. Not caught because no build in CI exercise that code path (apparently). Can invoke that by defining `OPENSSL_NO_THREADS_CORRUPT_MEMORY_AND_LEAK_SECRETS_IF_THREADED`.

Fix no-thread test and default generation value

---

.github/workflows/integrations.yml
tests/ci/integration/run_cyrus_sasl_integration.sh

`CryptoAlg-2554`
Add Cyrus-SASL to our CI
There is no general testing suite for Cyrus. To test the GSSAPI with Kerberos, we can use provided sample_client and sample_server applications. However, this requires a working Kerberos setup with a KDC and another script to support communication between the sample_client and server programs. This is not being added as of now. 

Add Cyrus-SASL to our CI

---

tool-openssl/CMakeLists.txt
tool-openssl/crl.cc
tool-openssl/crl_test.cc
tool-openssl/internal.h
tool-openssl/tool.cc

`CryptoAlg-2679`
Added the `crl` tool to the openssl cli with `-hash`, `-fingerprint`, `-help`, `-in`, `-noout`
Option and OpenSSL comparison tests

Added CRL tool to CLI

---

crypto/asn1/asn1_lib.c
crypto/asn1/asn1_test.cc
crypto/asn1/internal.h
crypto/asn1/tasn_dec.c
crypto/bytestring/cbs.c
crypto/bytestring/internal.h

Addresses: CryptoAlg-2693
* Loosen the restrictions on ASN1 parsing on calls made to `ASN1_get_object`. Other places that parse ASN1 should be unaffected.

Allow ASN1_get_object to parse indefinite and universal

---

crypto/conf/internal.h
crypto/lhash/internal.h
crypto/lhash/lhash.c
include/openssl/conf.h
include/openssl/lhash.h

Resolves `CryptoAlg-2449`
This extends upon https://github.com/aws/aws-lc/pull/1986.
We do have all the necessary support for "LHASH", it's just been renamed and made internal by upstream: https://github.com/aws/aws-lc/commit/b8441aced4090488a31375af81c4f7e5014fe791. Ruby's CONF module happens to have a [dependency](https://github.com/ruby/ruby/blob/ee1cd1656fc667840282a4e9c3f2cc5e3154e50e/ext/openssl/ossl_config.c#L255) on a couple of LHASH macros OpenSSL created and the non-opaqueness of `CONF`.
Although we aren't likely to be supporting CONF files for the time being, this change seems to reasonable for enough us to maintain so we can get a better build/patch for Ruby. We still fail most CONF related tests in Ruby, so we'll have to work around those. But this commit lets us gracefully …

Expose a bit of lhash/conf for Ruby

---

crypto/asn1/asn1_test.cc
crypto/pkcs7/pkcs7.c
crypto/pkcs7/pkcs7_test.cc

A few minor test issues to clean up.

Test cleanup

---

.github/workflows/actions-ci.yml

* Add clang-19 to our CI.
* Switch the pedantic test from clang-18 to clang-19.

Add Clang 19 to CI

---

crypto/fipsmodule/evp/evp_ctx_test.cc
crypto/fipsmodule/evp/p_rsa.c

* FIPS only allows 0x10001 for public exponent.  We will fail any attempt to change that when in FIPS mode.
Updated tests to provide better coverage for FIPS.

Fail FIPS rsa_keygen_pubexp on change

---

crypto/asn1/tasn_dec.c
crypto/x509/x509_test.cc

Addresses CryptoAlg-2494
This change relaxes a prior restriction forbidding constructed strings when parsing ASN.1 BER. We modify relevant tests accordingly and fix two small errors in PEM fixtures.
`kConstructedBitString` contained a bit string with invalid padding. We fixed this by zeroing out the final padding byte of each constructed bit string component. `kConstructedOctetString`' constructed string components were typed as integers (type `0x02`) instead of octet strings (type `0x04`). For that, we simply change the types to `0x04`.
- n/a
- existing tests updated to exercise constructed string parsing
---

Allow constructed strings in BER parsing

---

tests/ci/integration/python_patch/3.13/aws-lc-cpython.patch

A [recent commit](https://github.com/python/cpython/commit/b1051577dec26d4b30e3786cfcfd56e1a49d9855#diff-89879be484d86da4e77c90d5408b2e10190ee27cc86337cd0f8efc3520d60621L4927) in python 3.13 broke our patch. This fixes it.
- n/a
- CI

Fix python 3.13 patch

---

crypto/pkcs7/pkcs7_test.cc

Fix segfault in PKCS7 test

---

crypto/fipsmodule/bn/bn.c
include/openssl/bn.h
tests/ci/integration/run_openssh_integration.sh

Addresses `CryptoAlg-1477`
We're currently leaning towards continuing to not support `BN_FLG_CONSTTIME`. It's a problematic flag that's poorly documented and could lead to constant time violations if we aren't careful.
We can expose `BN_set_flags` as a no-op however. Ruby has logic to get around the `BN_FLG_CONSTTIME` flag, but not around `BN_set/get_flags`. Exposing the set symbol would allow for a cleaner patch/build.
N/A
N/A

Expose BN_set_flags as a no-op

---

tests/ci/integration/run_strongswan_integration.sh

Resolves #V1600301204
strongSwan-6 released today and AWS-LC's job [started failing](https://github.com/aws/aws-lc/actions/runs/12141153061/job/33852603406?pr=2027). This is due to the new dependency on strongSwan's DRBG plugin to make their test vector plugin (i.e. KATs) run during a unit test run. A similar change to support this was added to the upstream CI job [here](https://github.com/strongswan/strongswan/commit/ec982171d94201065636be38199226cb57a2d45a#diff-52afcc694c0ff8ff253441f42ff44d6b4734fe30ae9070f2ba07a668a10e7baaL220)
Assert that the strongSwan CI passes now.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Fix strongSwan CI

---

crypto/err/err.c

Addresses:
* aws/aws-lc-rs#610
`strdup` was only officially [added to libc in C23](https://en.cppreference.com/w/c/string/byte/strdup). Platforms we support may require the `__STDC_WANT_LIB_EXT2__` or `_POSIX_C_SOURCE` macros to be defined prior to the inclusion of the "string.h" header.
* Reference: https://en.cppreference.com/w/c/experimental/dynamic/strdup

strdup is not C99

---

crypto/dilithium/ml_dsa.h

Resolves CI failures with ML-DSA
Added `OPENSSL_EXPORT` to the problematic functions.

Fix CI issues with ML-DSA

---

include/openssl/ssl.h
ssl/handshake_client.cc
ssl/internal.h
ssl/s3_both.cc
ssl/ssl_lib.cc
ssl/test/runner/runner.go
ssl/test/test_config.cc
ssl/test/test_config.h
ssl/tls13_server.cc

Upstream merge 2024 11 18

---

.github/workflows/misc-tests.yaml
.github/workflows/windows-alt.yml
crypto/CMakeLists.txt
crypto/cipher_extra/asm/chacha20_poly1305_armv8.pl
crypto/fipsmodule/ec/asm/p256-armv8-asm.pl
crypto/fipsmodule/ec/asm/p256_beeu-armv8-asm.pl
crypto/fipsmodule/md5/asm/md5-armv8.pl
crypto/fipsmodule/modes/asm/aesv8-gcm-armv8.pl

Build was failing when the source path contained spaces. This is due to there not being quotes around the `$xlate` and `$output` at the start of the script.
* Although this change alters a few Perl scripts, no changes are made to the assembly files they produce.
Added a test that sets up the paths for both the source and build directories to contain spaces.

Fix perl handling of paths w/ spaces

---

crypto/fipsmodule/rsa/rsa_impl.c
crypto/rsa_extra/rsa_test.cc
tests/ci/run_fips_tests.sh

We've been getting abort failures when building with FIPS mode against [Ruby's break tests](https://github.com/ruby/ruby/blob/d5de1a57893b16aff7bc3336b34fa2e9acefb3d2/test/openssl/test_pkey_rsa.rb#L80-L85). The issue happens to be related to the abort call we do when calls to `RSA_generate_key_ex` fail.
In the original commit where this was introduced (https://github.com/aws/aws-lc/commit/6bdd4c3403a17f85cf8cee0a245f220c5c0c28e5), it's mentioned that "It's required that the FIPS module aborts when PCT tests fail in `RSA_check_fips()`." Our current behavior fails regardless of a regular RSA failure or a PWCT failure, which causes regular RSA failures to unintentionally abort as well.
This changes aborting to only happen during failures in `RSA_check_fips`. Our existing death tests were …

Only abort when RSA PWCT fail in FIPS

---

crypto/fipsmodule/self_check/self_check.c

Addresses aws/aws-lc-rs#623
* The size for arrays initialized with string literals should include the null-terminator.  The arrays should instead be initialized like arrays are chars.

Initialize arrays as arrays

---

crypto/cipher_extra/cipher_extra.c
crypto/cipher_extra/cipher_test.cc

Support for the blowfish cipher was [added][1] a few years ago, but was is not addressed in `EVP_get_cipherbyname`. This commit adds that support and some testing.
[1]: https://github.com/aws/aws-lc/commit/6effbf24bc483b5f62add56129925ffe06b80b4a
- CI

Add blowfish names to EVP_CIPHER API

---

CMakeLists.txt

Allow build on Solaris

---

crypto/cipher_extra/cipher_test.cc
crypto/fipsmodule/cipher/cipher.c
include/openssl/cipher.h

P177717548
Just make sure to prevent null-dereference.

Prevent accidental null dereference

---

crypto/dilithium/pqcrystals_dilithium_ref_common/README.md
crypto/dilithium/pqcrystals_dilithium_ref_common/ntt.c
crypto/dilithium/pqcrystals_dilithium_ref_common/packing.c
crypto/dilithium/pqcrystals_dilithium_ref_common/poly.c
crypto/dilithium/pqcrystals_dilithium_ref_common/polyvec.c
crypto/dilithium/pqcrystals_dilithium_ref_common/rounding.c
crypto/dilithium/pqcrystals_dilithium_ref_common/sign.c

Resolves CryptoAlg-2799
This PR addresses the following:
**Documentation:**
- addition of documentation for FIPS 204. To maintain a clearer implementation of the specification, I have added call outs in the function descriptors that describe the respective algorithm identifiers (name and algorithm number) in FIPS 204.
- For functions that were missing documentation, this has been added.
**Clean up:**
- DBENCH internal benchmarking within `poly.c` has been removed.
- Migrated the files touched over to AWS-LC style "loop" guidelines, that are encased in brackets.
**New addition intermediate value cleanse:**
- FIPS 204 states: "Implementations of ML-DSA shall ensure that any potentially sensitive intermediate data is destroyed as soon as it is no longer needed." Two particular cases in which …

Added FIPS 204 documentation, cleanse intermediate values

---

third_party/s2n-bignum/arm/fastmul/bignum_emontredc_8n_neon.S
third_party/s2n-bignum/arm/generic/bignum_copy_row_from_table_16_neon.S
third_party/s2n-bignum/arm/generic/bignum_copy_row_from_table_32_neon.S
third_party/s2n-bignum/arm/p384/p384_montjadd.S
third_party/s2n-bignum/arm/p384/p384_montjscalarmul.S
third_party/s2n-bignum/arm/p521/Makefile
third_party/s2n-bignum/arm/p521/bignum_inv_p521.S
third_party/s2n-bignum/arm/p521/p521_jadd.S
third_party/s2n-bignum/arm/p521/p521_jdouble.S
third_party/s2n-bignum/arm/p521/p521_jscalarmul.S
third_party/s2n-bignum/arm/p521/p521_jscalarmul_alt.S
third_party/s2n-bignum/x86_att/p521/bignum_inv_p521.S
third_party/s2n-bignum/x86_att/p521/p521_jscalarmul.S
third_party/s2n-bignum/x86_att/p521/p521_jscalarmul_alt.S
util/fipstools/delocate/delocate.peg
util/fipstools/delocate/delocate.peg.go

N/A
s2n-bignum update 2024-12-10

s2n-bignum update 2024-12-10

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

Prepare release v1.41.1
* Forgot version bump for [v1.41.0](https://github.com/aws/aws-lc/releases/tag/v1.41.0). 😬

Prepare release 1.41.1

---

.github/docker_images/alpine-linux/Dockerfile

Alpine Linux has started using gcc-14 as the default compiler. This is broken with our FIPS build which has started causing CI failures. See https://github.com/aws/aws-lc/issues/2010

Use older image with gcc-13 for alpine linux ci

---

crypto/CMakeLists.txt
crypto/fipsmodule/CMakeLists.txt
crypto/fipsmodule/cpucap/cpu_aarch64_linux.c
crypto/fipsmodule/cpucap/internal.h
crypto/fipsmodule/rand/asm/rndr-armv8.pl
crypto/fipsmodule/rand/entropy/entropy_source_tests.cc
crypto/fipsmodule/rand/entropy/entropy_sources.c
crypto/fipsmodule/rand/entropy/internal.h
crypto/fipsmodule/rand/internal.h
crypto/fipsmodule/rand/rand.c
crypto/fipsmodule/rand/urandom_test.cc
crypto/rand_extra/rand_test.cc
generated-src/ios-aarch64/crypto/fipsmodule/rndr-armv8.S
generated-src/linux-aarch64/crypto/fipsmodule/rndr-armv8.S
generated-src/win-aarch64/crypto/fipsmodule/rndr-armv8.S
include/openssl/arm_arch.h
util/fipstools/delocate/delocate.go

Adds Arm as a hardware source for prediction resistance, if supported. This covers Linux+Armv8.5-A that impements `rndr`. For exmaple, this should be enabled on Graviton3/Graviton4+Amazon Linux.
Note, only multiples of 8 are supported. That's what we need now and I don't see that need changing.
Wrap the libcrypto inlined functions to workaround the Arm capability vector having internal linkage.
Apple doesn't implement `FEAT_RNG` on any of their M's. Might be able to implement for Windows. But I don't see a way to probe for the instruction here https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-isprocessorfeaturepresent.
Added `s3_3_c2_c4_0` as a known symbol to the delocator to avoid it from interpreting the string as an external symbol that needs a …

Support Armv8.5 RNDR as prediction resistance

---

crypto/bio/bio_test.cc
crypto/bio/file.c

Resolves i/CryptoAlg-2805
Upstream commit [`5ee4e95`][1]'s source changes are almost identical to our
addition of `BIO_FP_TEXT` in [PR 1153][2]. The only difference in behavior is
that we will call `_setmode` w/ `_O_BINARY` on windows when no flags are
specified, where BoringSSL will simply no-op and leave the underlying file's
mode alone.
Upstream's commit has some nice tests, though, so we crib those and change a
single line of expectation to account for our difference in behavior.
[1]: https://github.com/google/boringssl/commit/5ee4e9512e9a99f97c4a3fad397034028b3457c2
[2]: https://github.com/aws/aws-lc/pull/1153
[3]: https://github.com/openssl/openssl/blob/dc10ffc2834e0d2f5ebc1c3e29bd97f1f43a0ead/crypto/bio/bss_file.c#L235-L237
In the interests of maximizing compatibility, I initially …

Bring in testing changes from upstream commit 5ee4e95

---

.github/docker_images/alpine-linux/Dockerfile
tests/ci/integration/nginx_patch/aws-lc-nginx.patch
tests/ci/integration/python_patch/3.13/aws-lc-cpython.patch
tests/ci/integration/run_strongswan_integration.sh
tests/ci/integration/run_tcpdump_integration.sh

Taking
https://github.com/aws/aws-lc/commit/d6a4786e655c979eb339ce935117b99e53cd7246
https://github.com/aws/aws-lc/commit/a47d28b95f9deedfa6d0af3ad7d9c9cb3ed56d66
https://github.com/aws/aws-lc/commit/9d62ff26746ee3c92ea2445734d1e4e993e84249
https://github.com/aws/aws-lc/commit/a89cb97573b3c0233f59c3e897c9afb2350c77ca
https://github.com/aws/aws-lc/commit/850af98235851dca40acae72537a4d8f97265606

Ci fixes from main 13122024

---

tests/ci/cdk/cdk/ssm/general_test_run_ssm_document.yaml
tests/ci/lambda/src/bin/purge-stale-builds.rs

Resolves `P178122942`
Some ec2 instances aren't successfully terminated along with the pruned commits/jobs and we don't have any additional retry logic to handle that. This adds logic to the job pruner to terminate any ec2-test-framework instances hanging longer than a couple hours. There were also some inconsistent failures with the instance wanting to be restarted, removing `needrestart` from the instance should solve that.
N/A
Tested in local fork: https://github.com/samuel40791765/aws-lc/pull/36

Prune hanging instances longer than 2 hours

---

tests/ci/run_benchmark_build_tests.sh

BoringSSL now requires C++17 after https://github.com/google/boringssl/commit/9ff849165a4b6c33efc2e1b10b71400ce2257fed. When we build speed.cc with BoringSSL's headers we need to specify our our build to use C++17. This is blocking all of our CI with failures like [this](https://us-west-2.codebuild.aws.amazon.com/project/eyJlbmNyeXB0ZWREYXRhIjoiWk5IUWJGRGxBcTJ2Mkp4WGF3dnBwYjc5V0ZZYSt5SVVGbkwvODkydTNTaVQ2V2FMN3hwa0tjSWNFemw2QWtCWW5welFWV3lpRFpKVitwejgvelhpRWh3NDNqcWhKalpPYW9hL2tLMDlJSDFPT1NkNyIsIml2UGFyYW1ldGVyU3BlYyI6Ilp4VXRNQXFGM1BZYVlaRkIiLCJtYXRlcmlhbFNldFNlcmlhbCI6MX0%3D/build/73b9a032-23e0-493c-b4f2-08fce7df7798). 
This does not change AWS-LC's normal C++11 requirement.
The CI will build this.  …

Update BoringSSL benchmark to use C++17

---

crypto/pkcs7/pkcs7_asn1.c
crypto/pkcs7/pkcs7_test.cc
include/openssl/pkcs7.h

Ruby's mainline branch has added support for printing the contents for a PKCS7 structure:https://github.com/ruby/ruby/commit/841b45a4421a7f103b0312f84c14ece522833617 The hooks to print ASN1_items have been removed from AWS-LC, so this would require a lot for us to add back and support. 
This is only a print function though, I think we can no-op this for a better build and indicate we don't support printing the contents.
N/A
Minor test

Add PKCS7_print_ctx as a no-op

---

include/openssl/bn.h

CryptoAlg-1477
Calls out assumptions on input to basic arithmetic `BN_foo` functions.

Extend documentation for basic BN_foo functions

---

crypto/dilithium/pqcrystals_dilithium_ref_common/sign.c
tests/ci/run_posix_sanitizers.sh
tests/ci/run_posix_tests.sh

Addresses #P175809809
As we prepare ML-DSA and the removal of the `enable_dilithium` flag, we prepare our builds to all enable dilithium. This should also catch addition bugs in the CI.
One such bug has already been found by testing this addition, that has also been addressed in this PR:
```
In file included from /crypto/dilithium/ml_dsa.c:20:
/crypto/dilithium/./pqcrystals_dilithium_ref_common/sign.c: In function ‘crypto_sign_keypair_internal’:
/crypto/dilithium/./pqcrystals_dilithium_ref_common/sign.c:54:9: error: ‘s1’ may be used uninitialized [-Werror=maybe-uninitialized]
54 | s1hat = s1;
| ~~~~^~
crypto/dilithium/./pqcrystals_dilithium_ref_common/sign.c:35:12: note: ‘s1’ declared here
35 | polyvecl s1, s1hat;
| ^~
```
Found through testing for linux builds/
By submitting this pull …

Modified posix builds to enable dilithium by default

---

tests/ci/integration/python_patch/main/aws-lc-cpython.patch

n/a
Upstream PR 128036 added a new `ssl.HAS_PHA` boolean property and allows CPython's tests to account for lack of post-handshake authentication support. This allows us to delete relevant patch sets.
n/a
- CI

Fix python tests for upstream PR 128036

---

.github/workflows/aws-lc-rs.yml

Recently merged change in aws-lc-rs switched the toolchain used by scripts: 
* aws/aws-lc-rs#641

aws-lc-rs scripts now use nightly

---

tests/ci/integration/ruby_patch/ruby_patch_common/net-http.patch
tests/ci/integration/ruby_patch/ruby_release_backport/Fix-wrong-certificate-version.patch
tests/ci/integration/run_ruby_integration.sh

Follow up from https://github.com/aws/aws-lc/pull/1563#discussion_r1880802258 where we add more test coverage for the Ruby/OpenSSL gem. 
* `ruby_release_backport` is for any commits that are already on the main branch and are required for some tests on older releases to pass through.
* `ruby_patch_common` is for commits that all branches should need for additional tests to pass. These are outside of the ruby/openssl gem boundary, so I chose to consolidate the logic in a separate patch. Patches in this folder would be submitted to their respective repos instead of https://github.com/ruby/openssl.
N/A
CI

Add more test coverage for Ruby/OpenSSL gem

---

ssl/test/bssl_shim.cc

Addresses V1370176317
Attempt to get more information about SSL test failures. In the event of [SSL_ERROR_SYSCALL](https://github.com/aws/aws-lc/blob/main/include/openssl/ssl.h#L578-L583) errno might have more information about the issue.
I can't reproduce the failures locally, but hopefully this prints more information that might help.

Add more logging for SSL_ERROR_SYSCALL errors in bssl_shim.cc

---

CMakeLists.txt

* Libunwind is only needed when building tests.

Only need libunwind for testing

---

CMakeLists.txt
crypto/CMakeLists.txt

CMake condition on `UNIX` should instead be `NOT WIN32` b/c some unix-like operating systems do not identify with "UNIX". 
The "UNIX" variable appears to not be set on illumos, which leads to build failures like this: https://github.com/rust-lang/rustup/actions/runs/12384929706/job/34570334451#step:17:584
I verified locally that with this change the build of `aws-lc-sys` for `x86_64-unknown-illumos` succeeds.
<details>
```
❯ cargo clean && cross build --target x86_64-unknown-illumos
Removed 215 files, 74.6MiB total
[+] Building 7.1s (8/8) FINISHED …
```

CMake, use 'NOT WIN32' instead of 'UNIX'

---

crypto/fipsmodule/rand/urandom_test.cc
crypto/rand_extra/rand_test.cc
crypto/test/test_util.cc
crypto/test/test_util.h
crypto/ube/fork_detect.c
crypto/ube/fork_detect.h
crypto/ube/fork_detect_test.cc
tests/ci/run_benchmark_build_tests.sh
tests/ci/run_formal_verification.sh
util/all_tests.json

Two things are happening in this PR:
- Refactor code in `fork_detect.c` to make is more readable and amendable
- Add new sufficient method for fork detection on FreeBSD and OpenBSD.
The new method uses `minherit`, tagging a memory page with a special value. The semantics are equivalent to the existing case with `madvise`. 
We still need some more testing to increase test coverage for fork detection. This is an upcoming task.

FreeBSD and OpenBSD fork detection

---

crypto/crypto_test.cc
crypto/fipsmodule/self_check/fips.c
include/openssl/crypto.h

Addresses: CryptoAlg-2814
* Provides `FIPS_is_entropy_cpu_jitter()` for consumers to confirm build is using CPU jitter.

Provide FIPS_is_entropy_cpu_jitter()

---

crypto/fipsmodule/ml_kem/README.md
crypto/fipsmodule/ml_kem/ml_kem_ref/cbd.h
crypto/fipsmodule/ml_kem/ml_kem_ref/indcpa.h
crypto/fipsmodule/ml_kem/ml_kem_ref/ntt.h
crypto/fipsmodule/ml_kem/ml_kem_ref/params.h
crypto/fipsmodule/ml_kem/ml_kem_ref/poly.h
crypto/fipsmodule/ml_kem/ml_kem_ref/polyvec.h
crypto/fipsmodule/ml_kem/ml_kem_ref/reduce.h
crypto/fipsmodule/ml_kem/ml_kem_ref/symmetric.h
crypto/fipsmodule/ml_kem/ml_kem_ref/verify.h

Inspired by the issues in https://github.com/aws/aws-lc/pull/2072 this PR update's ML-KEM's include guards to use unique names to avoid any future issues.
Future PRs could also prefix more of the functions.
Existing tests will cover any issues. 

Update ML-KEM's internal header files to use unique include guards

---

crypto/cipher_extra/aead_test.cc

* Addresses: CryptoAlg-2718
* When targeting arm, GCC 7.2 claims to not support `alignas(16)` in C++ code.
```
...
.../arm-unknown-linux-musleabi/crypto/cipher_extra/aead_test.cc:835:54: error: requested alignment 16 is larger than 8 [-Werror=attributes]
alignas(16) uint8_t key[EVP_AEAD_MAX_KEY_LENGTH + 1];
^
/home/justsmth/workspace/CrossAWS-LC-FIPS/src/CrossAWS-LC-FIPS/build/private/buildroot/arm-unknown-linux-musleabi/crypto/cipher_extra/aead_test.cc:836:58: error: requested alignment 16 is larger than 8 [-Werror=attributes]
alignas(16) uint8_t nonce[EVP_AEAD_MAX_NONCE_LENGTH + 1];
^
/home/justsmth/workspace/CrossAWS-LC-FIPS/src/CrossAWS-LC-FIPS/build/private/buildroot/arm-unknown-linux-musleabi/crypto/cipher_extra/aead_test.cc:837:39: error: requested alignment 16 is larger than 8 …
```

alignas(16) unsupported w/ GCC 7.2 for ARM32

---

tests/ci/run_benchmark_build_tests.sh
tool/speed.cc

AWS-LC uses `jent_read_entropy` which should be reflected in the benchmark. Also turn on Jitter as the entropy source so the CI actually builds/runs this code path and ensures it continues to work. 
This doesn't affect the performance results, before:
```
./tool/bssl speed -filter Jitter
Did 253 Jitter (16 bytes) operations in 1081577us (233.9 ops/sec): 0.0 MB/s
Did 30 Jitter (256 bytes) operations in 1021729us (29.4 ops/sec): 0.0 MB/s
Did 6 Jitter (1350 bytes) operations in 1097450us (5.5 ops/sec): 0.0 MB/s
Did 1 Jitter (8192 bytes) operations in 1087014us (0.9 ops/sec): 0.0 MB/s
Did 1 Jitter (16384 bytes) operations in 2187891us (0.5 ops/sec): 0.0 MB/s
```
After:
```
./tool/bssl speed -filter Jitter
Did 230 Jitter (16 bytes) operations in 1013691us (226.9 ops/sec): 0.0 MB/s
Did 30 …
```

Update speed.cc to use the same jitter function as rand.c

---

ssl/handshake_server.cc
ssl/ssl_privkey.cc
tests/ci/integration/python_patch/main/aws-lc-cpython.patch

While we currently support TLS [pre-shared keys (PSKs)][1] for TLS 1.2, our
python integration tests have shown that we don't currently support TLS 1.2
PSKs on the server side unless a certificate has been configured. PSKs can be
used for both secret establishment and authentication, so there likely exist
legitimate use-cases for establishing PSK connections without certificates.
CPython's integration tests [expect this][2] behavior.
This gap appears to be incidental, not intentional. Unrelated [OCSP work][3]
introduced a requirement that a valid certificate public key is loaded on the
server before we sort out handshake parameters. If that load fails, the
hanshake is aborted before PSK can be negotiated for secret establishment. To
fix this, we simply check whether the server has a PSK …

Allow TLS PSK without server certificate

---

crypto/fipsmodule/bcm.c
crypto/fipsmodule/cpucap/internal.h

Addresses aws/aws-lc-rs#655
* The criteria for invoking `OPENSSL_cpuid_setup` should align with the criteria for defining `OPENSSL_cpuid_setup`.
Consumers building `aws-lc-fips-sys` for `s390x` were seeing the following failure:
```
.../boringssl_prefix_symbols.h:20:26: error: implicit declaration of function 'aws_lc_fips_0_13_1_OPENSSL_cpuid_setup'; did you mean 'aws_lc_fips_0_13_1_OPENSSL_sk_set'? [-Werror=implicit-function-declaration]
```
I verified this fix works for the `aws-lc-fips-sys` build for `s390x-unknown-linux-gnu`.

Align guard macros for OPENSSL_cpuid_setup

---

crypto/fipsmodule/ec/ec_montgomery.c

Previous discussion here: https://github.com/aws/aws-lc/issues/1185
Similar issues here: https://github.com/aws/aws-lc/commit/305ec03e73c8c5858466ce775fbaa87ce461e805
Similar issues here: https://github.com/aws/aws-lc/commit/d0501c589165a70491f875551bc83096e3abddb9#diff-6fde57725bf74f073ccac9d404387d74a39824fbc2465a02cfe37e86e679bbe8R34
Causes CI fails
Resolves #P188618529
Zero variables before use.
The fail only occurs for gcc-12 with ubuntu2204 on x86_64.
Only variables `|ftmp2|` and `|fourbeta|` are caught as maybe uninitialized `error: 'var_name' may be used uninitialized [-Werror=maybe-uninitialized]`.
CI tests.

Init variable to avoid "may be used uninitialized" warning

---

tests/ci/cdk/util/iam_policies.py

Addresses P187446337
Grant permissions required for Scrutinice.

CDK: Add scrutinice permissions

---

crypto/evp_extra/p_pqdsa.c
crypto/pkcs8/pkcs8_x509.c

Addresses P188794065
* Cleanup a few issues identified through static anaylsis

Address Scrutinice findings

---

CMakeLists.txt
crypto/cipher_extra/tls_cbc.c
crypto/evp_extra/evp_extra_test.cc
crypto/fipsmodule/bn/bytes.c
crypto/fipsmodule/bn/div.c
crypto/fipsmodule/bn/div_extra.c
crypto/fipsmodule/bn/exponentiation.c
crypto/fipsmodule/bn/gcd_extra.c
crypto/fipsmodule/bn/montgomery_inv.c
crypto/fipsmodule/bn/mul.c
crypto/fipsmodule/bn/prime.c
crypto/fipsmodule/bn/random.c
crypto/fipsmodule/curve25519/curve25519_nohw.c
crypto/fipsmodule/evp/p_ec.c
crypto/fipsmodule/rsa/rsa_impl.c
crypto/internal.h
crypto/stack/stack_test.cc
crypto/x509/x509_trs.c
include/openssl/stack.h
include/openssl/x509.h

Merging from Upstream considering commits between
https://github.com/google/boringssl/commit/9b8b483276da2b3d36ea21e97743e310314a8de0 (Mar 20, 2024) and https://github.com/google/boringssl/commit/821fe3380cce646fa3557b882d91fba318981b9b (Mar 22, 2024).
See internal document as well as "AWS-LC" notes inserted in some of the commit messages for additions/deviations from the upstream commit.

Upstream merge 2025 01 02

---

PrivacyInfo.xcprivacy
crypto/bytestring/unicode.c
crypto/cipher_extra/e_des.c
crypto/cipher_extra/e_null.c
crypto/cipher_extra/e_rc2.c
crypto/cipher_extra/e_rc4.c
crypto/decrepit/blowfish/blowfish.c
crypto/decrepit/cast/cast.c
crypto/err/err.c
crypto/mem.c
include/openssl/base.h
include/openssl/bytestring.h
include/openssl/rand.h
include/openssl/stack.h
ssl/dtls_record.cc
ssl/internal.h
ssl/test/runner/runner.go

Merging from Upstream considering commits between
https://github.com/google/boringssl/commit/36e85b6a05fe185f6b3a1b7e609e8b775c9b5a81 (Mar 22, 2024) and https://github.com/google/boringssl/commit/89f097740e6376521926eb56a61b25f639c473ac (April 10, 2024).
See internal document as well as "AWS-LC" notes inserted in some of the commit messages for additions/deviations from the upstream commit.

Upstream merge 2025 01 17

---

ssl/test/runner/runner.go

The [GitHub Mac runners occasionally fail](https://github.com/aws/aws-lc/actions/runs/12839452846/job/35806842991?pr=2127) the Channel ID tests with an error like:
```
bad error (wanted ':CHANNEL_ID_SIGNATURE_INVALID:' / ''): local error 'channel ID unexpectedly negotiated', child error 'exit status 1', stdout:
```
This change tries to log more things to get more info to make progress debugging these failures. 
I wasn't able to test this code path locally because I can't get these failures to reproduce locally.

Add more debug logging to channelID test failures

---

crypto/fipsmodule/evp/digestsign.c
include/openssl/digest.h
include/openssl/x509.h

Ruby's made a couple larger refactors to require versions later than OpenSSL 1.1.1.
* https://github.com/ruby/ruby/commit/441862dc9f11d83e9e35c3b965fe84e42e178a35
* https://github.com/ruby/ruby/commit/43c48e3030c513c17bfcf4c37bbe533097fa1a22
These changes require us to make a few tweaks to the patch in https://github.com/aws/aws-lc/pull/2071 and have exposed a couple minor symbols that we don't support. Adding support for the ones that aren't complicated in this PR. 
N/A
N/A

Minor symbols to work with Ruby's mainline

---

crypto/fipsmodule/aes/asm/aesni-xts-avx512.pl
generated-src/linux-x86_64/crypto/fipsmodule/aesni-xts-avx512.S
generated-src/mac-x86_64/crypto/fipsmodule/aesni-xts-avx512.S
generated-src/win-x86_64/crypto/fipsmodule/aesni-xts-avx512.asm

P192842055
Define the set `S = [i*128+80,i*128+80+15], i=1,2,3,...,` . The set of inputs with lengths from `S`, on the XTS encrypt path using the AVX512 implementation, a bimodal performance occurred. We have observed more than 80% drop in performance.
The graph depicts AWS-LC (blue) and AWS-LC-FIPS-2024 (orange), showing the pattern.
This is caused by mixing SSE and AVX instructions in the AVX512 implementation. In particular, for lengths in `S`, the path `L_remaining_num_blocks_is_5_` is taken. This path contains a single move `movdqa`, an SSE instruction:
```
.L_remaining_num_blocks_is_5_${rndsuffix}:
vmovdqu8 	 ($input),%zmm1
vmovdqu 	 0x40($input),%xmm2
[...]
vmovdqu8 	 %zmm1,($output)
vmovdqu 	 %xmm2,0x40($output)
add 	 \$0x50,$output
movdqa 	 %xmm2,%xmm8
vextracti32x4 …
```

Avoid mixing SSE and AVX in XTS-mode AVX512 implementation

---

crypto/evp_extra/p_pqdsa_test.cc
crypto/ml_dsa/ml_dsa.c
crypto/ml_dsa/ml_dsa.h
crypto/ml_dsa/ml_dsa_ref/packing.c
crypto/ml_dsa/ml_dsa_ref/packing.h

Resolves #CryptoAlg-2868
It is often useful when serializing asymmetric key pairs to populate both the public and private elements, given only the private element. For this to be possible, an algorithm utility function is often provided to derive key material. ML-DSA does not support this in the reference implementation.
An ML-DSA private key is constructed of the following elements: (ref https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.204.pdf)
```
sk = (
rho, // public random seed (32-bytes)
tr,  // public key hash (64-bytes)
key, // private random seed (32-bytes) (utilized during sign)
t0,  // polynomial vector: encodes the least significant bits of public-key polynomial t, facilitating certain computational efficiencies.
s1,  // secret polynomial vectors. These vectors contain …
```

Support for ML-DSA public key generation from private key

---

include/openssl/target.h

Addresses: 
* aws/aws-lc-rs#522
Setup macros for big-endian MIPS in "target.h"
A contributor informs us that the build for `mips-unknown-linux-musl` succeeds with this change: https://github.com/aws/aws-lc-rs/issues/522#issuecomment-2618841038
No CI testing for it. 

Check for MIPSEB in target.h

---

crypto/fipsmodule/md5/asm/md5-armv8.pl
crypto/fipsmodule/md5/asm/md5-x86_64.pl
generated-src/ios-aarch64/crypto/fipsmodule/md5-armv8.S
generated-src/linux-aarch64/crypto/fipsmodule/md5-armv8.S
generated-src/linux-x86_64/crypto/fipsmodule/md5-x86_64.S
generated-src/mac-x86_64/crypto/fipsmodule/md5-x86_64.S
generated-src/win-aarch64/crypto/fipsmodule/md5-armv8.S
generated-src/win-x86_64/crypto/fipsmodule/md5-x86_64.asm

(Equivalent to https://github.com/openssl/openssl/commit/ebe34f9a62630b45a825bc07a2e9cf52731e836e)
As suggested in https://github.com/animetosho/md5-optimisation?tab=readme-ov-file#dependency-shortcut-in-g-function, we can delay the dependency on 'x' by recognizing that ((x & z) | (y & ~z)) is equivalent to ((x & z) + (y + ~z)) in this scenario, and we can perform those additions independently, leaving our dependency on x to the final addition. This speeds it up around 5% on both platforms.
I applied the x86 patch manually, it's trivial, and the aarch64 patch applied cleanly after fixing the file name/path.
`ninja-build run_tests` on x86. `bssl speed -filter MD5` on x86 shows the expected speedup:
```
Before
Did 7169250 MD5 (16 bytes) operations in 1000024us (7169077.9 ops/sec): 114.7 …
```

Optimize x86/aarch64 MD5 implementation

---

crypto/pkcs7/pkcs7.c
crypto/pkcs7/pkcs7_test.cc
include/openssl/pkcs7.h

We’re still missing two PKCS7 symbols: https://github.com/aws/aws-lc/actions/runs/12898691659/job/35966230534#step:4:4012 This also applies to past releases.
* `PKCS7_get_detached` is basically an alias to `PKCS7_is_detached`, so I've done that accordingly.
* `PKCS7_set_detached` is used to "detach" data contents from the internal `PKCS7` structure. [The OpenSSL code](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/crypto/pkcs7/pk7_lib.c#L26-L48) uses a detached field in the PKCS7 structure that’s missing in AWS-LC. This field isn't necessarily needed though, we can just detect the functionality accordingly.
N/A
New tests

Add support for PKCS7_set/get_detached

---

crypto/evp_extra/p_pqdsa.c
crypto/evp_extra/p_pqdsa_asn1.c
crypto/evp_extra/p_pqdsa_test.cc
crypto/pqdsa/internal.h
crypto/pqdsa/pqdsa.c

Resolves `P195558735`
This fixes a memory read misalignment in the ML-DSA public and private key parsing. I've also added new tests to verify that the test works. This should also fix the intermittent errors we've been having in our fuzz tests. The plan is to cut a release as soon as this is merged.
N/A
New tests

Fix issue with ML-DSA key parsing

---

crypto/CMakeLists.txt
crypto/fipsmodule/rand/getrandom_fillin.h
crypto/fipsmodule/rand/internal.h
crypto/fipsmodule/rand/urandom.c
crypto/fipsmodule/rand/urandom_test.cc
crypto/rand_extra/getentropy.c
include/openssl/base.h
include/openssl/target.h

Use `getentropy` for some operating systems. Namely, Apple MacOS, OpenBSD, and FreeBSD. `getentropy` is closer to the noise sources.
See also q/3t08AyoE0m4q.
Even though we didn't use `getentropy` prior to this PR, we had a unit test. Just re-use that.

Use getentropy for OpenBSD, FreeBSD, and MacOS

---

crypto/pkcs8/pkcs12_test.cc
crypto/pkcs8/pkcs8_x509.c
include/openssl/pkcs8.h

Addresses `CryptoAlg-2821`
Ruby has added a binding for an additional function called `PKCS12_set_mac` in it's master branch: https://github.com/ruby/ruby/commit/c79b4354074742ca1cbbb25a4f04bbffeb58407d This was discovered prior to the PR for Ruby's CI integration with the master branch being merged: https://github.com/aws/aws-lc/pull/2071
OpenSSL's implementation of the function directly sets a designated mac field within the `PKCS12` structure. Our `PKCS12` structure is folded into a string of bytes along with its length and there aren't any available fields for us to directly set. This means that AWS-LC's implementation of `PKCS12_set_mac` has to parse the proper contents from `PKCS12` and rerun the key and mac generation with the new parameters provided. 
1. The parsing logic is …

Add support for PKCS12_set_mac

---

crypto/fipsmodule/cpucap/cpu_arm_linux.h

Addresses: aws/aws-lc-rs#681
On some platforms ARM's `HWCAP2_XXX` macros might be defined in system header files, causing compilation failure due to their being redefined here.
```
.../aws-lc/crypto/fipsmodule/cpucap/cpu_arm_linux.h:35:9: error: 'HWCAP2_AES' redefined [-Werror]
35 | #define HWCAP2_AES (1 << 0)
|         ^~~~~~~~~~
In file included from .../armv7ve-libreelec-linux-gnueabihf/sysroot/usr/include/bits/hwcap.h:53:9: note: this is the location of the previous definition
53 | #define HWCAP2_AES              1
|         ^~~~~~~~~~
```

Validate or define ARM HWCAP2_XXX macros

---

crypto/curve25519_extra/curve25519_extra.c
crypto/fipsmodule/curve25519/curve25519.c
crypto/fipsmodule/rsa/rsa_impl.c
include/openssl/service_indicator.h

Resolves P186477736
Currently the service indicator checks that `before != after` and multiple approved APIs might call each other. If a lock is missed a lower approved algorithm will increment the count which incorrectly marks the higher level API as approved. This is happening in three spots:
1. Approved API's self tests run and increment the service indicator on first use
2. In Ed25519 sign/verify the calls to SHA were incrementing the indicator
3. In the Ec25519 and RSA keygen the PCT sign/verify was incrementing the count
This change updates the service indicator to enforce `before + 1 == after` with a debug assert.
This doesn't change the external behavior of the service indicator, what algorithms are approved, or what APIs are approved. The service indicator tests are unchanged. …

Ensure service indicator is incremented only once, update RSA and ED25519 to ensure the state is locked

---

tests/ci/run_fips_tests.sh

The original intention of https://github.com/aws/aws-lc/pull/1005 was to ensure break-kat.go always worked with the library. https://github.com/aws/aws-lc/pull/1252 then used a side effect to get the module hash but didn't actually fail the build if the hash was different.
Turn on `pipefail` so the script exits unsuccessfully if any command fails even in a pipe. Previously if test-break-kat.sh failed the script didn't exit, instead it would continue to the grep which would also fail to find any matching string, and then the `|| true` ensured the script always continued on.

Ensure enabling local symbols doesn't change the module hash

---

tests/ci/run_benchmark_build_tests.sh
tool/speed.cc

AES XTS requires at least 16 bytes of input, all other algorithms support 1 or more bytes. This change also updates the remaining algorithm benchmarks to support any sized chunks.
Updated run_benchmark_build_tests.sh to test every libcrypto benchmark with 1 to 20,000 bytes.

Update benchmark to skip chunk sizes that doesn't work with the algorithm

---

crypto/CMakeLists.txt

Instead of silently ignoring the parameter CMake now prints a warning and lets the command continue to work:
```
CMake Warning (dev) at crypto/CMakeLists.txt:654 (add_custom_command):
The following keywords are not supported when using
add_custom_command(TARGET): DEPENDS.
Policy CMP0175 is not set: add_custom_command() rejects invalid arguments.
Run "cmake --help-policy CMP0175" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
```
https://cmake.org/cmake/help/latest/policy/CMP0175.html
Built locally after deleting the option and didn't see the error message.

Remove DEPENDS from add_custom_command as CMake made the behavior clear

---

tests/ci/run_install_shared_and_static.sh

`P198393553`
Making the test more robust to prevent flaky behavior: 
1. Add more logging
2. Use sync to force file state after delete operations
3. use --fresh with CMAKE to prevent using any cache 
4. Turn off parallel CMAKE build

Make install_shared_and_static test more robust

---

crypto/fipsmodule/ec/ec_key.c
crypto/fipsmodule/evp/p_pqdsa.c
crypto/fipsmodule/ml_dsa/ml_dsa_ref/sign.c
crypto/fipsmodule/pqdsa/pqdsa.c
crypto/fipsmodule/rsa/rsa.c

`P197895641`, `P197898490`
Scrutinice alerts for a null check and potential memory leak 

SCRUTINICE fixes

---

crypto/fipsmodule/FIPS.md
crypto/fipsmodule/curve25519/curve25519.c
crypto/fipsmodule/ml_dsa/ml_dsa_ref/sign.c
crypto/fipsmodule/ml_kem/ml_kem_ref/kem.c
tests/ci/run_fips_tests.sh
util/fipstools/test-runtime-pwct.sh
util/fipstools/test_fips.c

To easily demonstrate the pairwise consistency tests function this change adds support to the existing BORINGSSL_FIPS_BREAK_TEST environment variable.
This adds a new test file for all the runtime tests and runs them from the run_fips_test.sh script on the break-able build.

Add runtime options to break the pairwise consistency test for Ed, ML-KEM, and ML-DSA

---

crypto/fipsmodule/ml_kem/ml_kem.c
crypto/fipsmodule/ml_kem/ml_kem_ref/kem.c

Discussed with: @andrewhop 
-----
If AWSLC_FIPS is set, ML-KEM includes a PCT check after key generation, in compliance with the FIPS-203 IG
https://csrc.nist.gov/csrc/media/Projects/cryptographic-module-validation-program/documents/fips%20140-3/FIPS%20140-3%20IG.pdf If the PCT fails, AWS_LC_FIPS_failure is called to abort operation.
This PR hoists the call to AWS_LC_FIPS_failure one level up, into the toplevel ML-KEM API of crypto/fipsmodule/ml_kem/ml_kem.h: When the PCT fails, the lower-level key generation API that invokes the PCT returns -1, which is caught by the top-level ML-KEM API and converted into a call to AWS_LC_FIPS_failure. There is no other …

ML-KEM: Move FIPS-abort upon PCT failure to top-level ML-KEM API

---

include/openssl/target.h

Allow to build rustup on Solaris SPARC.

Add SPARCV9 target

---

tool-openssl/crl.cc
tool-openssl/rsa.cc
tool-openssl/s_client.cc
tool-openssl/verify.cc
tool-openssl/verify_test.cc
tool-openssl/version.cc
tool-openssl/x509.cc
tool/args.cc
tool/ciphers.cc
tool/client.cc
tool/generate_ech.cc
tool/generate_ed25519.cc
tool/genrsa.cc
tool/internal.h
tool/pkcs12.cc
tool/rand.cc
tool/server.cc
tool/sign.cc
tool/speed.cc

* OpenSSL supports passing lower-case `pem` or `der` when using the `-inform` argument to the `x509` sub-command.
* Add support for the `-untrusted` flag to the `verify` sub-command which allows for passing in a set of one or more chain certificates which may be used in the certificate chain building and validation.

Improve tool-openssl compatability for x509 and verify subcommands

---

crypto/fipsmodule/bcm.c
crypto/fipsmodule/self_check/self_check.c
crypto/internal.h

This change does two things:
1. Update bcm.c to always build a AWS_LC_FIPS_failure function that either prints the message and aborts or just prints the message
2. Update the remaining spots in self_check.c to always use that function and not print directly to stderr
This does not change any of the expected output from AWS-LC.
The existing tests that check the FIPS failure messages ensure there is no change in behavior with this change

Refactor AWS_LC_FIPS_failure to always exist

---

tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml
tests/ci/integration/run_pq_tls_integration.sh

Adding cross library PQ TLS interop test with BoringSSL

Add pq-tls interop test with BoringSSL

---

include/openssl/aead.h
include/openssl/bn.h
include/openssl/crypto.h
include/openssl/curve25519.h
include/openssl/ec.h
include/openssl/service_indicator.h
include/openssl/ssl.h
tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
tests/ci/codebuild/linux-x86/pre-push.yml
tests/ci/run_posix_tests.sh
tests/coding_guidelines/c99_cplusplus98_test.sh
tests/coding_guidelines/coding_guidelines_test.sh

Addresses `CryptoAlg-2693`
We encountered this when trying to compile Xtrabackup on gcc versions lower than 10. Apparently scoped enums are a C++11 feature, which the compiler can't understand without additional linker flags. 
```
/home/ubuntu/workplace/percona-xtrabackup/aws-lc/test_build_dir/include/openssl/ssl.h:174:30: warning: scoped enums only available with ‘-std=c++11’ or ‘-std=gnu++11’
174 | #define BORINGSSL_ENUM_INT : int
|                              ^~~
...
|                              ^~~
/home/ubuntu/workplace/percona-xtrabackup/aws-lc/test_build_dir/include/openssl/ssl.h:4783:31: note: in expansion of macro ‘BORINGSSL_ENUM_INT’
4783 | enum ssl_select_cert_result_t BORINGSSL_ENUM_INT {
|                               ^~~~~~~~~~~~~~~~~~
make[2]: *** …
```

Fix C++98 compatibility in our header files

---

tool/speed.cc

The current filter logic in the speed tool is a bit weird. It's not possible to run all the benchmarks because RSA key gen was off by default. If you pass in the filter "RSAKeyGen" you get the keygen benchmarks and all the other RSA benchmarks. This change updates it to be treated the same as all the other benchmarks. 
The RSA key gen benchmarks are still a little weird because they override the timeout which is why they are slower and take more time. For now the canary use case is fine.
The CI will run this benchmark with all the libcryptos we expect to support.

Enable RSA keygen becnhmarks by default

---

crypto/fipsmodule/ec/ec_key.c
crypto/fipsmodule/ml_dsa/ml_dsa_ref/sign.c
crypto/fipsmodule/ml_kem/ml_kem_ref/kem.c

Currently AWS_LC_FIPS_failure always aborts the process and it is impossible to continue after calling that function. In a future change this will be optional and AWS-LC will not abort and the overall API call should return a failure. This change updates the current pairwise consistency test spots to theoretically return a failure.
This PR does not change the behavior, if there is a PWCT failure the process still aborts.
With the current AWS_LC_FIPS_failure implementation it is impossible to test this change.

Update pairwise consistency test failures to support gracefully continiung

---

tool/args.cc

Resolves P194739376
There was some logically dead code that was unnecessary and would never be reached.

Simplify IsFlag check logic

---

crypto/fipsmodule/rand/snapsafe_detect.c

This change uses stat() instead of access() to check for the existence of the Sysgenid device. This is more accurate to ascertain whether the device exists on a machine. access() could fail for various other reasons such as missing permissions. 

Remove access() call from Snapsafe detection

---

ssl/ssl_lib.cc
ssl/ssl_test.cc

This is a follow up to https://github.com/aws/aws-lc/commit/154f9986bc18f8f0e6126157a3abc84230456f77. 
These changes initialize the SSL object with configured ciphersuites from the parent SSL_CTX object at initialization. Now both SSL and SSL_CTX objects will have their own copy of ciphersuites. 
We inherited the behavior of defaulting to SSL_CTX ciphersuites when none are set on SSL from BoringSSL. OpenSSL does things differently and copies the ciphersuites to SSL at init. This behavioral difference is aligned in this PR. 
A test to ensure changes to SSL_CTX don't impact SSL configurations and we correctly inherit ciphersuites. 

Modify SSL to inherit ciphersuites from SSL_CTX at initialization

---

.github/workflows/integrations.yml
tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml
tests/ci/codebuild/common/run_ipv6_target.yml
tests/ci/integration/run_bind9_integration.sh

This PR migrates jobs that require `ipv6` enabled in CodeBuild to run properly (with `nmap` being a special add-on to balance out the size of the next batch of jobs). 
The jobs to be migrated in this PR are:
- `grpc`
- `bind9`
- `strongswan`
- `openvpn2.6`
- `openvpnMaster`
- `nmap`
In this PR, I changed the build directory of `bind9` to resolve a character limit issue in CodeBuild.
In one of its tests, `bind9` will try to create a socket with a path deep within the build directory. Since CodeBuild's build directory is already very long, the combined socket path length will exceed the Linux limit of 108 characters. Therefore, I had to reduce the length of the build directory to mitigate this issue. …

Migrate 3rd batch of CI jobs

---

PORTING.md

Addresses V1612276057
Add clear documentation around AWS-LC's default behavior of disabling certificate auto-chaining and it's impact TLS client and server certificates present over the wire.

Add guidance around certificate auto-chaining in TLS

---

util/fipstools/compare_hash/main.go

Ran the utility locally and verified the output.

Add utility for querying and comparing the BORINGSSL_bcm_text_hash

---

util/fipstools/compare_hash/main.go

Cherry-pick https://github.com/aws/aws-lc/pull/2217 to the FIPS 2024 branch.
This changes does not modify the FIPS module hash.

Cherry-pick BORINGSSL_bcm_text_hash Go utility

---

.github/workflows/abidiff.yml

Update ABI Diff Action to work correctly on push events

---

ssl/dtls_method.cc

After f94f3ed3965ea033001fb9ae006084eee408b861, there's a std::bitset in it, so memset is not guaranteed to do what we want.
There are still other problems here, and we may decide not to keep the reset at all, but fix the memset for now. See these discussions for more details:
https://boringssl-review.googlesource.com/c/boringssl/+/68027/comment/7ff3d697_a6808cee/ https://boringssl-review.googlesource.com/c/boringssl/+/68027/comment/74cabada_eadf5394/
Change-Id: I79c62d71d74a58be4ac822e0cc5a41586472a26a Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/68067
Reviewed-by: Nick Harper <nharper@chromium.org>
Reviewed-by: Bob Beck <bbe@google.com>
(cherry picked from commit …

Reset DTLS1_BITMAP without resorting to memset

---

crypto/fipsmodule/aes/asm/aesni-xts-avx512.pl
crypto/fipsmodule/modes/xts_test.cc
generated-src/linux-x86_64/crypto/fipsmodule/aesni-xts-avx512.S
generated-src/mac-x86_64/crypto/fipsmodule/aesni-xts-avx512.S
generated-src/win-x86_64/crypto/fipsmodule/aesni-xts-avx512.asm

Original PR: #2227 
Cherry-pick https://github.com/aws/aws-lc/commit/eb0c0c0d8e4e94183a608b0403d899beb9d4b949
- Fix instruction that caused out-of-bound read in the input reading of the 16x loop (which processes a batch of 16 blocks of AES, 1 block = 16 bytes). This was triggered on lengths that are in the range  [16*k * (16 bytes), (16*k +3)* (16 bytes)-1], k = 1, 2, ...  The instruction was reading up to 3*16 bytes beyond the input length bound.
- The fix was inspired by the 8x loop in https://github.com/aws/aws-lc/blob/becf5785c131012bb5a64f3da6cdb117ddc0f431/crypto/fipsmodule/aes/asm/aesni-xts-avx512.pl#L2544
- The existing unit tests cover those cases but there were no explicit memory protections and ASAN doesn't instrument assembly code to check for out-of-bound reads even when the …

Cherry-pick: Fix out-of-bound (OOB) input read in AES-XTS Decrypt in AVX-512 implementation

---

.github/docker_images/gcc-4.8/Dockerfile
.github/workflows/cmake.yml
CMakeLists.txt

[CMake 4.0](https://cmake.org/cmake/help/latest/release/4.0.html) is coming out soon and requires cmake_minimum_required to be at least 3.5:
> Compatibility with versions of CMake older than 3.5 has been removed. Calls to [cmake_minimum_required()](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#command:cmake_minimum_required) or [cmake_policy()](https://cmake.org/cmake/help/latest/command/cmake_policy.html#command:cmake_policy) that set the policy version to an older value now issue an error
The [common runtime](https://github.com/awslabs/aws-c-common/pull/1178) and [s2n-tls](https://github.com/aws/s2n-tls/issues/4899) upgraded to 3.9 last year.  
This will break any customer using CMake version less than 3.9 which was [released in November …

Increase required CMake version to 3.5

---

crypto/fipsmodule/modes/xts_test.cc

Addresses #P206132928
Coverity signaled that pagesize is passed to `mprotect()` without ensuring it's non-negative.

Check pagesize is non-negative in AES-XTS test

---

include/openssl/base.h

Addresses aws/aws-lc-rs#715 
On Windows, avoid marking exported symbols with `__declspec(dllexport)` when performing a static build.
* This is a partial revert of this PR: https://github.com/aws/aws-lc/pull/466

Don't 'dllexport' Windows symbols on static build

---

.github/workflows/windows-alt.yml

Addresses CI failure: https://github.com/aws/aws-lc/actions/runs/13661696749/job/38194107977?pr=2239#step:6:65
```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\include\yvals_core.h:927:1: error: static assertion failed: error STL1000: Unexpected compiler version, expected Clang 18.0.0 or newer.
927 | _EMIT_STL_ERROR(STL1000, "Unexpected compiler version, expected Clang 18.0.0 or newer.");
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
* Use Clang v18 for `windows-latest` (i.e `windows-2025`).

Update to using Clang 18 on Windows

---

CMakeLists.txt
crypto/fips_callback_test.cc
crypto/fipsmodule/ec/ec_test.cc
tests/ci/run_fips_tests.sh
tool/tool.cc

Due to how shared libraries and applications load it's not possible for an application to dynamically link with AWS-LC and define it's own custom callback before AWS-LC's constructor runs which expects the callback to be defined. This change requires anyone expecting to build with the callback to statically build and link AWS-LC so their callback is defined before AWS-LC's constructor runs. 
This change also enables the call_back_test to run all the time, this test can run on any platform, platforms that don't support the callback will get the default (abort) behavior. 
This change also disables one death test if the callback is defined. Because the callback doesn't call abort the test fails. 
Update a test dimension to enable the callback and just run the tests like normal to ensure …

Enforce FIPS callback is only enabled for static builds

---

crypto/fipsmodule/rand/rand.c
util/all_tests.json

Use lower-case for internal function  names and set env variables to the env variable field.

Lower-case internal function names and correct env variable

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

https://github.com/aws/aws-lc/releases/edit/untagged-aef9ee5aee62c3242f30
* Remove BORINGSSL_FIPS_BREAK_FFC_DH by @andrewhop in https://github.com/aws/aws-lc/pull/2216
* Increase required CMake version to 3.5 by @andrewhop in https://github.com/aws/aws-lc/pull/2219
* Coverity Fix by @smittals2 in https://github.com/aws/aws-lc/pull/2236
* Check pagesize is non-negative in AES-XTS test by @nebeid in https://github.com/aws/aws-lc/pull/2237
* Don't 'dllexport' Windows symbols on static build by @justsmth in https://github.com/aws/aws-lc/pull/2238
* Update to using Clang 18 on Windows by @justsmth in https://github.com/aws/aws-lc/pull/2240
* Enforce FIPS callback is only enabled for static builds by @andrewhop in https://github.com/aws/aws-lc/pull/2241
By submitting this pull request, I …

Prepare for release v.1.48.0

---

crypto/bio/bio_mem.c
include/openssl/bio.h

Can't track it down the historical reason why, but we have `BIO_get_mem_data` defined as a preprocessor macro, but BoringSSL does not. This creates an annoying compatibility issue for rust-openssl, and has forced us to implement the function properly in our aws-lc-sys crates in Rust. This redefines the function to have a concrete definition.
As a side-note, the macro was technically wrong as it was casting contents to a `char *` when it was actually `char **`, but this wasn't problematic per-se since it was being passed into a `void *` argument. If you look at the ctrl function definition you can see that it is indeed treated as a `char **` pointer.

Make BIO_get_mem_data a function again

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

* Move OCSP ASN1 type functions to public header by @skmcgrail in https://github.com/aws/aws-lc/pull/2239
* Make BIO_get_mem_data a function again by @skmcgrail in https://github.com/aws/aws-lc/pull/2246

Prepare v1.48.1

---

crypto/fipsmodule/bn/bn.c
include/openssl/bn.h

This PR adds a public wrapper for an existing internal function bn_minimal_width. OpenSSL stores the minimal number of words needed in a field called top within the bignum struct. AWS-LC does not do this, instead we have a field called width which is a loose upper bound on this value. The new function, BN_get_minimal_width will provide us with the value of "top" for a given Bignum. 

Add public wrapper to internal bn_minimal_width function

---

CMakeLists.txt
crypto/fipsmodule/FIPS.md

Setting the CMake option FIPS_BREAK_TEST to something like FFC_DH would result in defining `BORINGSSL_FIPS_BREAK_FFC_DH=1` which used to be how the break tests were broken. break-kat.go replaced all of that and all the code using the definitions were removed. https://github.com/aws/aws-lc/commit/913af96d029e0c80e8d573af6ddbbfd798ed98c5 removed the last legacy usage of it.
The correct way to test breaking AWS-LC is outlined in FIPS.md:
1. Compile with `BORINGSSL_FIPS_BREAK_TESTS` defined
2. Run break-kat.go to break a certain CAST
This also removes the note about fips_break_tests.h since that file doesn't exist anymore.

Remove unused CMake options for break tests

---

crypto/fips_callback_test.cc
crypto/fipsmodule/curve25519/curve25519.c
crypto/fipsmodule/curve25519/internal.h
crypto/fipsmodule/evp/p_ed25519.c
tests/ci/run_fips_tests.sh

`ED25519_keypair` has always been void, this used to be okay because it was infallible. Now it can fail due to the PWCT failing. Usually if that happened the process would abort which is the default (and only approved) behavior of `AWS_LC_FIPS_failure`. However, if AWS-LC is built with the callback and that callback doesn't abort it is possible for `EVP_PKEY_keygen` to continue. Changes:
* `EVP_PKEY_keygen` now detects this failure and return the error to the caller
* `ED25519_keypair` doesn't increment the service indicator if the PWCT fails
I updated the fips_callback_test to use the EVP API for ED and check the return value

Update EVP_PKEY ED keygen to use an internal function that can return the result of the PWCT

---

tool/ossl_bm.h
tool/speed.cc

Adds a benchmark for CMAC, OpenSSL 1.0.2 does not support CMAC. 

Add CMAC benchmark for AWS-LC

---

tests/ci/integration/postgres_patch/aws-lc-postgres.patch

Addresses `CryptoAlg-2917`
The original patch I had for Postgres wasn't the best, as it just simply commented out the single test we didn't support. It's not a patch worthy of submitting upstream.
This new patch simply adds a function check specific to AWS-LC and leverages existing logic to skip the test. I've kept the error string replacements out of the script to minimize churn with our Postgres CI and left a comment regarding that.
N/A
CI

Update patch for Postgres

---

crypto/bio/bio_mem.c
crypto/bio/bio_test.cc
crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h
include/openssl/bio.h

* Reverts https://github.com/aws/aws-lc/commit/5826a075e6186ff85c4383b8f0e051d50783cc2c
* New release v1.48.2
* Added a test for this going-forward.

Revert BIO_get_mem_data back to macro

---

crypto/fipsmodule/bn/bn.c
crypto/fipsmodule/bn/bn_test.cc
include/openssl/bn.h

Return type of `BN_get_minimal_width()` should probably be `unsigned` as the rest of the size return functions. Take the opportunity to improve testing.

Use unsigned return type for BN_get_minimal_width and word size tests

---

crypto/chacha/asm/chacha-x86_64.pl
generated-src/linux-x86_64/crypto/chacha/chacha-x86_64.S
generated-src/mac-x86_64/crypto/chacha/chacha-x86_64.S
generated-src/win-x86_64/crypto/chacha/chacha-x86_64.asm

r11 does not have anything in it yet, and r10 is never read. This is a remnant of the ia32cap dispatch that we missed in
f5e0c8f92a22679b0cd8d24d0d670769c1cc07f3.
Bug: 673
Change-Id: I5cc179401418aee6479b4a38ae1c09f68ec40238 Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/68291
Reviewed-by: Bob Beck <bbe@google.com>
(cherry picked from commit [03d1b7c544851d9f44df1e9ff21839742e08c819](https://github.com/google/boringssl/commit/03d1b7c544851d9f44df1e9ff21839742e08c819))

Remove no-op register move from ChaCha20_ctr32_ssse3_4x

---

.github/workflows/aws-lc-rs.yml

* CI tests are failing when symbol are migrated to being macros due to the symbols still being listed in the symbol files.
* This change ensures that the symbol files and headers are deleted prior to their regeneration.

Fix aws-lc-rs CI test when symbols removed

---

crypto/fipsmodule/rand/new_rand_test.cc
crypto/fipsmodule/rand/rand.c
include/openssl/rand.h

In the non-UBE support runtime, a fresh lazy init will spawn a seed of the CTR-DRBG state. But then in `rand_bytes_core()`, there will be an immediate spawn of a reseed of the CTR-DRBG state to ensure uniqueness for non-UBE support.
Fix this by telling `rand_bytes_core` whether the CTR-DRBG state is fresh or not.
This requires a few changes in the tests to account for a reseed that might not happen. Now I'm there, refactor a bit.

Avoid double seed for non-UBE support runtimes

---

.github/workflows/aws-lc-rs.yml

* Consolidate the aws-lc-rs CI tests.
* Perform a "cargo clean" prior generating bindings. (Fixes Windows attempting to link to the "no-prefix" build of the library.)

Fix aws-lc-rs CI test (again)

---

crypto/fips_callback_test.cc
tests/ci/gtest_util.sh

Resolves q/2qabAwnLeC09
Previously shard_gtest left GTEST_SHARD_INDEX and GTEST_TOTAL_SHARDS defined. Any future gtest executable that ran after shard_gtest would re-use those values and potentially skip tests in other shards besides the last one.
Identified in https://github.com/aws/aws-lc/pull/2266/files#r1993474700.
Previously fips_callback_test should have failed but was incorrectly skipping tests. Now the tests are running and this change fixes one issue. EVP_PKEY_keygen for ED might fail if EDDSA_PWCT is set, so keygen should only be called inside the if block to check for the correct result.

Update shard_gtest to unset environment variables once all the tests are done

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

* Use unsigned return type for BN_get_minimal_width and word size tests by @torben-hansen in https://github.com/aws/aws-lc/pull/2260
* Revert removal of "PEM_X509_INFO_write_bio" by @smittals2 in https://github.com/aws/aws-lc/pull/2226
* Remove no-op register move from ChaCha20_ctr32_ssse3_4x by @nebeid in https://github.com/aws/aws-lc/pull/2234
* Fix aws-lc-rs CI test when symbols removed by @justsmth in https://github.com/aws/aws-lc/pull/2262
* Add x4 batched SHAKE128 and SHAKE256 APIs by @manastasova in https://github.com/aws/aws-lc/pull/2247
* Fix aws-lc-rs CI test (again) by @justsmth in https://github.com/aws/aws-lc/pull/2268
* Minor build fixes for CMake and libssl on x86 by @skmcgrail in https://github.com/aws/aws-lc/pull/2267
By submitting this pull request, I confirm that my …

Prepare v1.48.3

---

crypto/fipsmodule/bcm.c
crypto/internal.h
tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
tests/ci/run_fips_callback_tests.sh
tests/ci/run_fips_tests.sh
tool/tool.cc

This makes the FIPS callback optional when AWS-LC is built with AWSLC_FIPS_FAILURE_CALLBACK which turns it on. Previously if AWS-LC was built with AWSLC_FIPS_FAILURE_CALLBACK then any application that might link with AWS-LC would need to define the callback or AWS-LC would abort. Turns out that's hard to ensure, this change goes back to the old behavior:
* Regular FIPS build of AWS-LC doesn't require a callback and always aborts
* FIPS build with AWSLC_FIPS_FAILURE_CALLBACK allows a callback to be defined and AWS-LC will call that and not abort
* FIPS build with AWSLC_FIPS_FAILURE_CALLBACK and no callback defined fallback to the first bullet point behavior
I had to remove `EXPECT_TRUE(EVP_PKEY_keygen(ed_ctx.get(), &ed_key));` because that keygen call should only happen after the check for …

Make AWS_LC_fips_failure_callback optional in builds with AWSLC_FIPS_FAILURE_CALLBACK

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

https://github.com/aws/aws-lc/releases/edit/untagged-64078f9fa7b969a1a3e7
* Make AWS_LC_fips_failure_callback optional in builds with AWSLC_FIPS_FAILURE_CALLBACK by @andrewhop in https://github.com/aws/aws-lc/pull/2266
**Full Changelog**: https://github.com/aws/aws-lc/compare/v1.48.3...v1.48.4

Prepare for release v.1.48.4

---

.github/workflows/misc-tests.yaml
util/git-tag-check/git-tag-check.py
util/git-tag-check/tag-branch.json

* Verify that tags matching specific patterns appear on the expected branches.
N/A
* Script succeeds locally (if I change `REMOTE_NAME` to "upstream").
* Successful CI run here: https://github.com/aws/aws-lc/actions/runs/13159309149/job/36723792502?pr=2170#step:4:12

GitHub CI job to verify tags are on expected branches

---

crypto/fipsmodule/CMakeLists.txt

* https://github.com/aws/aws-lc-rs/pull/729
MacOS assembly required the use of `boringssl_prefix_symbols_asm.h`
* For other platforms this is [equivalent to `boringssl_prefix_symbols.h`](https://github.com/aws/aws-lc-rs/blob/main/aws-lc-sys/generated-include/openssl/boringssl_prefix_symbols_asm.h#L15-L17)

s2n-bignum build should use boringssl_prefix_symbols_asm.h

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

Prepare AWS-LC v1.48.5.
* GitHub CI job to verify tags are on expected branches by @justsmth in https://github.com/aws/aws-lc/pull/2170
* ci: Nix flake and devShell by @dougch in https://github.com/aws/aws-lc/pull/2189
* s2n-bignum build should use boringssl_prefix_symbols_asm.h by @justsmth in https://github.com/aws/aws-lc/pull/2265

Prepare AWS-LC v1.48.5

---

.github/workflows/cmake.yml
CMakeLists.txt

This code does not modify the FIPS boundary.
Cherry-picks:
* https://github.com/aws/aws-lc/commit/2c1b35b8feeebb4038688d5c04dc0a48421ce06b (#2219)

Cherry-pick support for CMake 4.0 to fips-2024-09-27

---

crypto/asn1/tasn_dec.c
crypto/x509/x509_test.cc

This reverts commit 2a722260329a62e0682410060f84cf144960afe4.
Addresses `CryptoAlg-3037`
We've ran into issues with parsing indefinite BER with PKCS7 and it turns out our support for parsing is not as complete. Instead of parsing BER to an invalid unusable state that's confusing, we should outright disallow parsing of constructed strings in BER until we fix the issue.
N/A
Original tests.
Ruby CI is expected to fail. I'll update the patches in another PR.

Revert "Allow constructed strings in BER parsing (#2015)"

---

crypto/fipsmodule/FIPS.md
include/openssl/service_indicator.h

Documentation for the FIPS service indicator.
Preview here: https://github.com/justsmth/aws-lc/blob/doc-service-indicator/crypto/fipsmodule/FIPS.md#service-indicator

Documentation on service indicator

---

include/openssl/bio.h
include/openssl/ssl.h
ssl/bio_ssl.cc
ssl/ssl_test.cc

Resolves `CryptoAlg-2926`
Xtrabackup happens to take a dependency on some of OpenSSL's BIO_ssl methods. These are essentially helper BIOs that maintain an `SSL` within them. We have the necessary functionality available, this is just wrapping these BIOs around them.
N/A
Ideally we would test against the "connect" BIO created within `BIO_new_ssl_connect` with `BIO_do_connect`, but this isn't quite easy since we do not have any BIO methods that set up sockets on the server end (`BIO_s_accept`). We have other mechanisms of doing so in our `bssl` tool and `ocsp_integration_tests`, but pulling the functionality over just to test these `BIO`s seemed a bit overkill for my liking. I've given my reasoning in the test comments, if we ever do support `BIO_s_accept` we can look to update the test.
By …

Add support for more SSL BIO functions

---

.github/workflows/integrations.yml
tests/ci/integration/run_bind9_integration.sh
tests/ci/integration/run_rust_openssl_integration.sh
tests/ci/integration/run_strongswan_integration.sh

Adds validation that AWS-LC will build with rust-openssl when using the bindgen feature or bindgen-cli if pointed at an AWS-LC installation directory. We will add coverage on the aws-lc-rs side specifically for handling coverage of the crate specific feature flag that toggles on `aws-lc-sys`.
Not putting this into CodeBuild right now as it would require building new docker images with Rust, and the current process is influx. Will wait for the new deployment process to be completed so we can guarantee more frequently updated rust compiler releases without having to automate that with each invocation.

Wire-up rust-openssl into GitHub CI (for the time being)

---

crypto/fipsmodule/modes/xts_test.cc

Addresses #V1681992550
This change hardens the tests introduced in #2227 Fix out-of-bound (OOB) input read in AES-XTS Decrypt in AVX-512 implementation.
It adds a memory page preceding the input and output buffer that is protected against read and write in order to detect any under-read, in which case a segfault occurs.
The suspected code that can potentially cause a "pre-bound" OOB is the cipher-stealing section in Encrypt
[crypto/fipsmodule/aes/asm/aesni-xts-avx512.pl#L1809-L1810](https://github.com/aws/aws-lc/blob/v1.48.5/crypto/fipsmodule/aes/asm/aesni-xts-avx512.pl#L1809-L1810)
and decrypt
[crypto/fipsmodule/aes/asm/aesni-xts-avx512.pl#2572-L2573](https://github.com/aws/aws-lc/blob/v1.48.5/crypto/fipsmodule/aes/asm/aesni-xts-avx512.pl#L2572-L2573).
The efficacy of the added test was …

Adding detection of out-of-bound pre-bound memory read to AES-XTS tests.

---

crypto/fipsmodule/aes/mode_wrappers.c

--------
On AArch64, the delocator can patch up the computation of function pointers only if the pointers can be computed with a PC-relative offset in the range (-1MB, 1MB).
For the function pointer computations in aes/mode_wrappers.c, this bounds condition is about to be violated by further code additions to AWS-LC, as witnessed in AES-unrelated PRs (specifically #2176).
This commit preventatively fixes the issue by adding function pointer trampolines to crypto/fipsmodule/aes/mode_wrappers.c: These are stub functions immediately branching into the desired assembly routines, but close enough to the C code computing their address to ensure that their …

AES: Add function pointer trampoline to avoid delocator issue

---

crypto/dsa/dsa.c
crypto/dsa/dsa_asn1.c
crypto/dsa/dsa_test.cc
crypto/dsa/internal.h

`P211191334`
This PR cherrypicks 68c29a24ee6c9c70ecce56766ca70b115aad768f from BoringSSL. 
This change adds size checks to DSA_generate_parameters_ex and DSA_generate_key operations, completing our bounds checks for DSA operations. While this was prompted by CVE-2024-4603, BoringSSL and AWS-LC are not affected by that vulnerability. These additional checks likely have no security impact since attackers typically can't control inputs to these functions, but we're adding them for consistency with our other DSA operations.  …

Cherrypick hardening DSA param checks from BoringSSL 

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

* Revert "Allow constructed strings in BER parsing (#2015)" by @samuel40791765 in https://github.com/aws/aws-lc/pull/2278
* Add the rehash utility to the openssl CLI tool by @smittals2 in https://github.com/aws/aws-lc/pull/2258
* Documentation on service indicator by @justsmth in https://github.com/aws/aws-lc/pull/2281
* Update patches in Ruby CI by @samuel40791765 in https://github.com/aws/aws-lc/pull/2233
* Reject DSA trailing garbage in EVP layer, add test cases by @skmcgrail in https://github.com/aws/aws-lc/pull/2289
* Add support for verifying PKCS7 signed attributes by @samuel40791765 in https://github.com/aws/aws-lc/pull/2264
* Add support for more SSL BIO functions by @samuel40791765 in https://github.com/aws/aws-lc/pull/2273
* Wire-up rust-openssl into GitHub CI (for the time …

Prepare for v1.49.0

---

crypto/fipsmodule/self_check/self_check.c
include/openssl/base.h
tests/ci/run_fips_callback_tests.sh

CryptoAlg-2437
Mirror more of the build options to make sure we catch any build issues early in GitHub. Adding the release with debug issue raised an issue with break-kat.go failing with: `Test input value was still found after erasing it. Second copy?`. This happens because the function which contains the test vectors are inlined into two functions which results in two copies of the data. This only appears to happen with GCC 7.3.1. This change fixes that by marking all of the tests as no inline. 

Add more build options to match callback build

---

tests/ci/benchmark_framework/install_docker.sh
tests/ci/cdk/cdk/ssm/general_test_run_ssm_document.yaml
tests/ci/run_ec2_test_framework.sh

Currently Cloudwatch logs only captures the output of commands run, not which command ran so it's hard to figure out what is causing an issue. This turns on logging for all commands, combines the standard error and out logs, and turns on exit on any failure.
Before:
```
DEPENDENCIES_DIR=/home/dependencies
OLDPWD=/var/snap/amazon-ssm-agent/7984/aws-lc-pr
_=/usr/bin/env
Building AWS-LC in Release mode with address sanitizer, and running only non ssl test.
Using Ninja build system (ninja).
-- Go compiler 1.20.1 found
-- The C compiler identification is Clang 15.0.7
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
```
After:
```
+ echo 'Using Ninja build system (ninja).'
+ …
```

Turn on better logging for EC2 test framework

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

* FIPS Integrity Hash Tooling by @skmcgrail in https://github.com/aws/aws-lc/pull/2296
* Add more build options to match callback build by @andrewhop in https://github.com/aws/aws-lc/pull/2279
* Add req to OpenSSL CLI tool by @smittals2 in https://github.com/aws/aws-lc/pull/2284
* Turn on better logging for EC2 test framework by @andrewhop in https://github.com/aws/aws-lc/pull/2298

Prepare for v1.49.1

---

tests/ci/integration/python_patch/3.12/aws-lc-cpython.patch
tests/ci/integration/python_patch/3.13/aws-lc-cpython.patch
tests/ci/integration/python_patch/main/aws-lc-cpython.patch

Two recent upstream CPython PRs removed the need for patching around our lack of support for [FFDHE TLS ciphersuites](https://github.com/python/cpython/pull/131051) and [non-0 `SECLEVEL` values](https://github.com/python/cpython/pull/131739).
n/a
- local
- CI
---

Remove FFDHE and SECLEVEL python test patches

---

CMakeLists.txt
tests/ci/run_benchmark_build_tests.sh
tests/ci/run_posix_sanitizers.sh
tests/ci/run_posix_tests.sh

Dilithium (really ML-DSA) is always enabled in AWS-LC now. No C or C++ files used the ENABLE_DILITHIUM define.
Any customers or automated builds of AWS-LC that define the CMake option will not be broken by this. They will get a small message and the build will continue:
```
CMake Warning:
Manually-specified variables were not used by the project:
ENABLE_DILITHIUM
-- Build files have been written to: ~/aws-lc/build
```
This will also save some CI time by reducing the total number of builds in the posix tests by 1. 

Remove unused ENABLE_DILITHIUM CMake option

---

include/openssl/ssl.h
ssl/ssl_lib.cc

Provide functions `SSL_in_connect_init` and `SSL_in_accept_init`.
Function definitions match OpenSSL macros: https://github.com/openssl/openssl/blob/a3fc812c0c78e2f5db8b9d45bddaff62dfc958ae/include/openssl/ssl.h#L1071-L1073

SSL_in_*_init macros

---

crypto/fipsmodule/FIPS.md

The link to `bcm.c` in the [Linux Shared Build section](https://github.com/aws/aws-lc/blob/main/crypto/fipsmodule/FIPS.md#linux-shared-build) of FIPS.md wass formatted incorrectly.
* Update can be seen [here](https://github.com/justsmth/aws-lc/blob/fix-bcm.c-in-FIPS.md/crypto/fipsmodule/FIPS.md#linux-shared-build).

Fix link to bcm.c in FIPS.md

---

crypto/CMakeLists.txt
crypto/test/x509_util.cc
crypto/test/x509_util.h
crypto/x509/x509_compat_test.cc
crypto/x509/x509_test.cc

This is mostly a re-organization PR so that the new comparability related tests are in a separate unit file for easier grokking in the future as more are added.  I also re-generated the current certificates added in the previous PR for the trust-store change to define a better distinguished namespace hierarchy. Mainly to have better binding and name-spacing of the root certificate to any intermediate, and end-entity certificates generated for testing.
Additionally added a text representation of the certificates as well. Note the certificate start dates are back date to 2015 through 2100. This is mainly for consistency with the other certificates BoringSSL had generated in various places in the library.
Otherwise this also adds a test case for RFC 5280 4.2.1.1 which states with regards to …

Reorganizing compatability tests, rework certificates for better groking

---

README.md

This PR updates the formal verification section in README with P-256 curve.
The update could be confirmed by checking:
The `third_party/s2n-bignum` directory (https://github.com/aws/aws-lc/tree/main/third_party/s2n-bignum) against the places the functions are actually used (https://github.com/aws/aws-lc/blob/main/crypto/fipsmodule/ec/p384.c for P384, https://github.com/aws/aws-lc/blob/main/crypto/fipsmodule/ec/p521.c for P512, https://github.com/aws/aws-lc/blob/main/crypto/fipsmodule/ec/p256-nistz.c for P256, https://github.com/aws/aws-lc/blob/main/crypto/fipsmodule/curve25519/curve25519_s2n_bignum_asm.c for X25519 and ED25519, and PR https://github.com/aws/aws-lc/pull/1135 for RSA).
Point out areas that need special attention or support during the review process. Discuss architecture or …

Update formal verification section in README.md

---

tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml
tests/ci/docker_images/linux-x86/ubuntu-22.04_gcc-12x_integration/Dockerfile
tests/ci/integration/run_xtrabackup_integration.sh

Addresses `CryptoAlg-2926`
We've added support for Xtrabackup in https://github.com/aws/aws-lc/pull/2273, this ensures that the build doesn't break.
N/A
CI

Add CI for Xtrabackup

---

crypto/bio/bio.c
crypto/bio/bio_test.cc
include/openssl/bio.h

Addresses #CRYPTOALG-3030
Adds legacy callback to BIO meeting previous application compatibility.
Router function implemented to prefer enhanced callback but provide legacy callback if needed and available.
We now check if callback is NULL after checking if we have a callback.
Rather than calling enhanced callback directly we check with router function get_callback
Updated parameters for BIOPairTest to include boolean pairs enabling current enhanced callback testing to test for legacy callback.
Changed multiple tests from BIOTest to BIOPairTest for parameterized testing.
Will be adding test for get_callback in future PR

Implement legacy callback with BIO_set_callback

---

.clang-tidy
.github/workflows/clang-tidy-post.yml
.github/workflows/clang-tidy-review.yml
CMakeLists.txt

* Created a .clang-tidy configuration file.
* Added an `ENABLE_CLANG_TIDY` option for out CMake build.
* Added CI workflows for clang-tidy.
* `clang-tidy-review` performs reviews and uploads the artifacts.
* `clang-tidy-post` posts comments to the PR.
* These two workflow must be separate due to limited permissions on PRs originating from forks.

Run clang tidy

---

crypto/mem.c
docs/porting/functionality-differences.md
include/openssl/crypto.h

Addresses #CryptoAlg-2905
Applications requiring CRYPTO_mem_ctrl can now build successfully. However, we define `OPENSSL_NO_CRYPTO_MDEBUG` in AWS-LC, which disables this functionality. As a result, the implemented function intentionally does nothing.
We've added a defensive compilation error that will trigger if `OPENSSL_NO_CRYPTO_MDEBUG` is removed in the future. This will allow us to fully implement the function if needed.
No testing is required for this intentional no-operation function. This approach is consistent with OpenSSL 1.1.1's handling of `OPENSSL_NO_CRYPTO_MDEBUG`.

Implemented no-op CRYPTO_mem_ctrl

---

crypto/rand_extra/windows.c
crypto/test/test_util.cc
third_party/jitterentropy/import.sh

Follow-up to https://github.com/aws/aws-lc/pull/2335, fixing various build errors.
Also sneaked in a documentation change to the jitter entropy import script.

Fix various build errors

---

crypto/test/x509_util.cc
crypto/test/x509_util.h
crypto/x509/v3_purp.c
crypto/x509/x509_compat_test.cc

* CRL Distribution Points extension per RFC 5280 should be marked non-critical, but OpenSSL 1.1.1 does allow for it to be marked critical by a CA issuing a certificate. Thus we modify to allow for this condition and add an associated test-case.
* Adds a test for a Root CA missing the basic constraints extension and a corresponding end-entity certificate signed by such a root.
* Adds a test for a certificate containing a negative serial number. While this does not conform to RFC 5280, it is supported by OpenSSL 1.1.1 and many other implementations. This adds a test-case for this behavior which was not previously covered.

Additional X.509 Behavior Compatability Tests

---

tool-openssl/CMakeLists.txt

* Use `file` instead of `configure_file` for copying scripts.
* Fixes warning output when using older CMake versions.
* The `FILE_PERMISSIONS` option for [`configure_file` is only available after v3.20](https://cmake.org/cmake/help/latest/command/configure_file.html#id2). Older CMake versions produce the following warning:
```
CMake Warning (dev) at tool-openssl/CMakeLists.txt:50 (configure_file):
configure_file called with unknown argument(s):
FILE_PERMISSIONS
OWNER_READ
OWNER_WRITE
OWNER_EXECUTE
GROUP_READ
GROUP_EXECUTE
WORLD_READ
WORLD_EXECUTE
This warning is for project developers.  Use -Wno-dev to suppress it.
```

Fix CMake (< v3.20) warning

---

crypto/obj/obj_xref.c

resolves https://github.com/aws/aws-lc/issues/2347
Add the missing nids so that OBJ_find_sigid_algs succeeds.
Just manual testing. When I build s2n-tls against this fix, my ML-DSA certificate parsing tests pass without any hacky workarounds.

Add MLDSA44 and MLDSA87 to OBJ_find_sigid_algs

---

crypto/fipsmodule/aes/asm/aesni-xts-avx512.pl
crypto/fipsmodule/modes/xts_test.cc
generated-src/linux-x86_64/crypto/fipsmodule/aesni-xts-avx512.S
generated-src/mac-x86_64/crypto/fipsmodule/aesni-xts-avx512.S
generated-src/win-x86_64/crypto/fipsmodule/aesni-xts-avx512.asm
tests/ci/run_benchmark_build_tests.sh

Original PRs: https://github.com/aws/aws-lc/pull/2286 and https://github.com/aws/aws-lc/pull/2140
Original commits: https://github.com/aws/aws-lc/commit/a39439bca37714c3d4090dc90f99ae876cc919b2 and https://github.com/aws/aws-lc/commit/37c2b5e8cf5a325beb6ab2abd5b2946bcfe01bde
This is a follow-up to https://github.com/aws/aws-lc/pull/2228 where an out-of-bound (OOB) read was fixed in the AVX512 implementation of AES-XTS and more tests were added.
This cherry-picks:
- further hardening tests on checking pre-bound reads #2286 
- a fix to a performance glitch on a code path that had an SSE instruction instead of an AVX512 one which was triggered by certain input lengths. #2140 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and …

Cherry-pick: Harden bound checking tests of AES-XTS and replace SSE instructions that degraded performance for certain input lengths

---

include/openssl/base.h

related to https://github.com/aws/aws-lc/issues/2347
Bump the API version so that customers like s2n-tls can ensure they have a working version of OBJ_find_sigid_algs + ML-DSA after https://github.com/aws/aws-lc/commit/d285977905d40f9240702ce62003f0ae3479ec20
I just let the CI test it :)

Bump AWSLC_API_VERSION to account for OBJ_find_sigid_algs bug

---

tests/ci/cdk/cdk/codebuild/ec2_test_framework_omnibus.yaml
tests/ci/cdk/cdk/ssm/general_test_run_ssm_document.yaml

* Update to latest Ubuntu AMI so there are fewer things to update as well
* Check the lock and wait for it to be released before installing our dependencies
* Kill more background update processes, from the debian docs:
* Used for downloads: /lib/systemd/system/apt-daily.timer 
* Used for upgrades: /lib/systemd/system/apt-daily-upgrade.timer 
* The purpose of [unattended-upgrades](https://packages.debian.org/unattended-upgrades) is to keep the computer current with the latest security (and other) updates automatically
These instance are short lived (under an hour) and don't need any updates. But these background process cause issues when our test script attempts to install the AWS CLI:
```
+ apt-get -y remove needrestart
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by …
```

Stop more background process that might be holding any apt locks in the EC2 test framework

---

crypto/x509/x509_vpm.c
include/openssl/x509.h

t/V1752105287
A recent CPython [change](https://github.com/python/cpython/commit/9752c840229fa6329d12e4a271698027363fd5ef) uses an OpenSSL symbol that we don't provide, causing relevant CI to [fail](https://us-west-2.codebuild.aws.amazon.com/project/eyJlbmNyeXB0ZWREYXRhIjoicEtxdUl5RTdsWW95MmtnM0pSWjJmQU92T2RhQUJPN2VzRFdXZTdHOG1FWU1NQ2VwcGtucE92ZlA1Q3pSRHFCWW1VRTFLa3VTN1RWVC96dmsraFl5WXZwSmFha2tOTFZBOEdiWittVlRGKzlBVkRqVk5Gaz0iLCJpdlBhcmFtZXRlclNwZWMiOiJxS01SNWtSdUR0d2NvSUMvIiwibWF0ZXJpYWxTZXRTZXJpYWwiOjF9/build/488c86c9-2549-42ef-beeb-551bb8c3a261). This PR copies [that function](https://github.com/openssl/openssl/blob/8f99bcdbb80103b7cbdc4269c607142549e2d678/crypto/x509/x509_vpm.c#L408) over.
n/a
CI
---
By submitting this pull request, I confirm that my contribution is made under the …

Add X509_VERIFY_PARAM_get_hostflags

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

Bump version to 1.50.0
* Remove FFDHE and SECLEVEL python test patches by @WillChilds-Klein in https://github.com/aws/aws-lc/pull/2307
* Remove unused ENABLE_DILITHIUM CMake option by @andrewhop in https://github.com/aws/aws-lc/pull/2304
* SSL_in_*_init macros by @justsmth in https://github.com/aws/aws-lc/pull/2302
* Fix link to bcm.c in FIPS.md by @justsmth in https://github.com/aws/aws-lc/pull/2309
* Test build with CMake v4.0 by @justsmth in https://github.com/aws/aws-lc/pull/2251
* Update formal verification section in README.md by @pennyannn in https://github.com/aws/aws-lc/pull/2301
* Add CI for Xtrabackup by @samuel40791765 in https://github.com/aws/aws-lc/pull/2275
* Add Libwebsockets to our CI by @smittals2 in https://github.com/aws/aws-lc/pull/2290
* Implement legacy callback …

Bump to v1.50.0

---

.clang-tidy

* Expand the number of checks done by clang-tidy.
<details>
<summary>CLICK HERE for a dump of clang-tidy configuration: <pre>$ clang-tidy --dump-config
...
</pre></summary>
```
---
Checks:          'clang-diagnostic-*,clang-analyzer-*, -*, bugprone-*, cert-*, clang-analyzer, concurrency-*, cppcoreguidelines-*, hicpp-*, misc-*, modernize-*, performance-*, portability-*, readability-* '
WarningsAsErrors: ''
HeaderFileExtensions:
- ''
- h
- hh
- hpp
- hxx
ImplementationFileExtensions:
- c
- cc
- cpp
- cxx
HeaderFilterRegex: ''
ExcludeHeaderFilterRegex: ''
FormatStyle:     none
User:            justsmth
CheckOptions:
bugprone-argument-comment.CommentBoolLiterals: '0'
bugprone-argument-comment.CommentCharacterLiterals: '0'
bugprone-argument-comment.CommentFloatLiterals: '0' …
```

Expand .clang-tidy configuration

---

tests/ci/integration/nginx_patch/aws-lc-nginx.patch

Updated integrations aws-lc-nginx.patch against nginx 1.28.0
Successful build of nginx 1.28.0 against AWS-LC 1.50.0

nginx-1.28.0 aws-lc-nginx.patch

---

crypto/bio/printf.c

Found by code inspection. If vsnprintf wanted to write INT_MAX characters, allocating a INT_MAX + 1 scratch buffer will overflow. Since we always have INT_MAX < SIZE_MAX, just casting to size_t earlier avoids this.
(If the malloc implementation is unwilling to allocate INT_MAX + 1, e.g. it is forbidden to on 32-bit, that's malloc's responsibility to detect.)
Change-Id: I3c2a740ebc7ecd58464a9f63858ffcefe67f648f
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/74247
Commit-Queue: Adam Langley <agl@google.com>
Reviewed-by: Adam Langley <agl@google.com> …

Fix a theoretical overflow in BIO_printf

---

crypto/x509/x509_vfy.c
include/openssl/x509.h
tests/ci/integration/tpm2_tools_patch/aws-lc-tpm2-tools.patch
tests/ci/integration/tpm2_tss_patch/aws-lc-tpm2-tss.patch

Resolves V1753330919
* Add support for [OpenSSL's X509_STORE_CTX_set0_untrusted](https://github.com/openssl/openssl/blob/1c1c9dc11b574c7e034c553aef2c9472ecafca80/crypto/x509/x509_vfy.c#L2711-L2714)
* Update tpm2-tss patch.

Fix tpm2-tss integration test

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

Bump version to 1.50.1. (Needed so that `aws-lc-sys` can to pick up latest s2n-bignum changes.)
* Fix GCC 4.8 docker img; Also w/ GCC 7.5 by @justsmth in https://github.com/aws/aws-lc/pull/2344
* Fix LibRdKafka CI by @smittals2 in https://github.com/aws/aws-lc/pull/2372
* Expand .clang-tidy configuration by @justsmth in https://github.com/aws/aws-lc/pull/2356
* nginx-1.28.0 aws-lc-nginx.patch by @robvanoostenrijk in https://github.com/aws/aws-lc/pull/2373
* s2n bignum import method change by @torben-hansen in https://github.com/aws/aws-lc/pull/2324
* Fix a theoretical overflow in BIO_printf by @justsmth in https://github.com/aws/aws-lc/pull/2369
* Fix tpm2-tss integration test by @justsmth in https://github.com/aws/aws-lc/pull/2370
By submitting this pull request, I confirm that my …

Bump to v1.50.1

---

.github/workflows/actions-ci.yml
.github/workflows/aws-lc-rs.yml

We don't need to use the large/xlarge instances for MacOS.
The following runner information can be found [here](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories).
| Virtual Machine | Processor (CPU) | Memory (RAM) | Storage (SSD) | Architecture | Workflow label |
|-----------------|----------------|--------------|--------------|--------------|----------------|
| macOS | 4 | 14 GB | 14 GB | Intel | macos-13 |
| macOS | 3 (M1) | 7 GB | 14 GB | arm64 | macos-latest, macos-14, macos-15 |

No need for MacOS large/xlarge

---

tests/ci/integration/postgres_patch/aws-lc-postgres.patch

This reverts commit db723116a144386007295521987feed4a6daab2f.
The original patch was much more stable. Instead of changing the postgres configure script to check against AWS-LC functions, we comment out the relevant test instead. I've added comments in the patch to reference back to the commit if we ever decide to upstream support to postgres.
The Postgres ARM CI dimension is failing, but the failure doesn't seem relevant to this patch.

Revert "Update patch for Postgres (#2232)"

---

.github/workflows/integrations.yml
tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml
tests/ci/integration/run_socat_integration.sh

Addresses V1753367409
* Move socat integration test out of CodeBuild
* The tests that were failing that involve to signals and child processes. We've had similar trouble with the libssh2 test running in CodeBuild.
* Update integration test script so it fails with script modifications are not applied.

Fix socat test

---

crypto/fipsmodule/CMakeLists.txt
include/openssl/asm_base.h
util/fipstools/delocate/delocate.go

Because of https://github.com/awslabs/s2n-bignum/pull/213, we can now simplify part of the build that handles s2n-bignum integration. This PR removes the special pre-processing of s2n-bignum source code e.g. removal of `;` as new-line delimiter. Instead, handle any special s2n-bignum build logic in the existing build logic e.g. specify header file location and compile-time definitions.
This also means we no longer need to copy the s2n-bignum source code anywhere. 
I manually tested a few things to ensure s2n-bignum source was correctly used in the build. First, measuring performance before and after. This was the same. Second, dis-assembling some binaries (for different build configs) to check s2n-bignum was there. They were.
By submitting this pull request, I confirm that my contribution …

Remove special s2n-bignum source code processing at buid-time

---

ssl/test/runner/runner.go
util/all_tests.go

I don't think this is currently used for anything. While the malloc-test machinery is working atm, some errors won't be caught due to the typo. https://man7.org/linux/man-pages/man3/mallopt.3.html says it should be `MALLOC_CHECK_`.
The malloc test is sorta in a weird state. Upstream has migrated `malloc` hijack functions to `mem.c`. But not in this repo. However, the build support exists in the shape of
```
if(MALLOC_FAILURE_TESTING)
add_definitions(-DBORINGSSL_MALLOC_FAILURE_TESTING)
endif()
```
which does nothing...
Anyway, this could be useful for something, one day, so I left all the code there. For further features, some honorary mentions one could research are `MALLOC_PERTURB_` and `mcheck()`. …

Correct typo in malloc debug environment variable

---

crypto/x509/internal.h
crypto/x509/x509_test.cc
crypto/x509/x509_vfy.c
include/openssl/x509.h

Resolves `V1726629971`
As of today, AWS-LC returns an error as part of verification if there are any critical extensions present in the certificate being validated. There have been asks to set a custom OID on the issued certificates to ensure that additional validation is performed by customers after or during the handshake. The intention is to prevent accidental mis-use of these certificates without that extra validation.
To support this, we've decided to add two new APIs for this use case. 
1. `X509_STORE_CTX_add_custom_crit_oid` adds  an oid as an `ASN1_OBJECT` to the list of "known" critical extension OIDs in `ctx`. Typical OpenSSL/AWS-LC behavior returns an error if there are any unknown critical extensions present within the certificates being validated. This function lets users …

Support allowing specific unknown critical extensions

---

include/openssl/opensslconf.h
tests/ci/integration/python_patch/main/aws-lc-cpython.patch

Due to [security concerns](https://www.rfc-editor.org/rfc/rfc9258.html#section-1), neither AWS-LC [nor BoringSSL](https://issues.chromium.org/issues/369963041) support external (i.e. non-session-resumption, established out of band) PSKs in TLS 1.3. This PR proposes a "configuration" flag to indicate this limitation to consumers, much as we did with `OPENSSL_NO_TLS_PHA` in 0aebf17.
Other cryptography libraries do not set this macro; it's unique to us.
- CI w/ new patch set
---

Set OPENSSL_NO_EXTERNAL_PSK_TLS13 to indicate lack of TLS 1.3 PSK

---

crypto/CMakeLists.txt
crypto/bio/bio.c
crypto/bio/bio_mem.c
crypto/bio/bio_socket_test.cc
crypto/bio/connect.c
crypto/bio/dgram.c
crypto/bio/internal.h
crypto/bio/socket.c
crypto/bio/socket_helper.c
include/openssl/bio.h

Resolves CryptoAlg-3032
Adds support for datagram (UDP) sockets to BIO. The implementation includes:
- New BIO_s_datagram() method for creating datagram BIOs
- Support for both connected and unconnected datagram sockets
- IPv4, IPv6 and Unix domain socket support (where available)
- Adds support for `BIO_get_close`
N/A
* Added tests to cover new functionality.

BIO datagram functions

---

ssl/test/runner/runner.go
ssl/tls13_client.cc

In TLS 1.2, the ticket field could be empty to indicate the server changed its mind on sending a ticket, having previously committed to sending a NewSessionTicket message a round-trip ago.
In TLS 1.3, the server does not commit to sending NewSessionTicket. It can always just not send it. So the ticket field is required to be non-empty.
It's important we enforce this on the client because otherwise we produce a mixed up SSL_SESSION object that looks like an ID session (thanks to the placeholder ID field that was added for a still unfixed Envoy bug, see b/200292207). That, in turn, confuses some code in assembling the next ClientHello.
The subsequent CL will tighten that up.
Update-Note: BoringSSL TLS 1.3 clients will now correctly reject zero-length tickets, rather than letting servers get …

Reject NewSessionTicket messages with empty tickets in TLS 1.3

---

crypto/fipsmodule/cpucap/cpu_intel.c

Change-Id: I8aa11f6c64d973ca33324687e8e61d35790cd331
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/74127
Reviewed-by: David Benjamin <davidben@google.com>
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and the …

Ensure that AVX512 is not used on macOS

---

tests/ci/integration/python_patch/main/aws-lc-cpython.patch

As of [PR 133624](https://github.com/python/cpython/pull/133624), CPython's mainline is now fully source- and test-compatible with AWS-LC. This means that we can reduce our CI patch file to a static build configuration.
n/a
- CI

Remove python CI patch for main

---

ssl/handoff.cc

It's evidently too easy to ignore the return values of these operations. After all, ignoring allocation failures is the normal pattern in most C++ code.
Thus this change marks these functions as `nodiscard`. This does require a few CHECKs in test code, but it also catches one real instance of a problem.
Change-Id: I24432506283145fc2f459336fe1035cbca27bd4f
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/75187
Commit-Queue: Adam Langley <agl@google.com>
Auto-Submit: Adam Langley <agl@google.com>
Reviewed-by: David Benjamin <davidben@google.com>
Point out areas that …

Mark fallible container operations as `nodiscard`

---

ssl/ssl_lib.cc

This function doesn't make sense for non-QUIC SSLs.
Change-Id: I3fc08a01f45d8c4e36e449675aecc98ce296abe1
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/73127
Reviewed-by: Nick Harper <nharper@chromium.org> …

Check for QUIC in SSL_process_quic_post_handshake

---

.clang-tidy
.github/workflows/clang-tidy-review.yml

clang-tidy is way too noisy.
* Forces the clang-tidy-review to use the configuration that we provide
* The `readibility-*` checks are not enabled.
* Silences a few other noisy checks. (Feel free to recommend others to silence.)

Squelch clang-tidy

---

.clang-tidy

Clang-tidy is still way too noisy. This makes a more aggressive cut.

Clang-tidy is still noisy

---

crypto/asn1/asn1_lib.c
crypto/asn1/internal.h

https://github.com/aws/aws-lc/commit/eafd9404887d5982dd647bd4f914664281130060 made all calls to ASN1 parsers able to parse indefinite length BER. This work to do this was easier thanks to https://github.com/aws/aws-lc/commit/cfe86a3830d5212099b2284a964be066c653dcbc, but this also removes the need for the divergent logic in `asn1_get_object_maybe_indefinite`. 
N/A
N/A

Make ASN1_get_object a direct call

---

.github/workflows/integrations.yml
tests/ci/integration/python_patch/3.9/aws-lc-cpython.patch

This PR provides a source patch and CI integration test for building + testing CPython 3.9 with AWS-LC. The patch file draws heavily on [our 3.10 patch](https://github.com/aws/aws-lc/blob/771c13d73295a32ae55954220d4b83be7ce73f01/tests/ci/integration/python_patch/3.10/aws-lc-cpython.patch#L4) for behavioral tweaks, namely:
- Detect AWS-LC's lack of TLSv1.3 PHA support
- In tests, account for differences in error message formatting/casing between AWS-LC and OpenSSL
- Don't look for `tls-unique` channel binding in TLS 1.3, where [channel bindings are not defined](https://datatracker.ietf.org/doc/html/rfc8446#appendix-C.5)
- In tests, account for AWS-LC's lack of non-EC Diffie-Hellman cipher suites
We also draw on a [prior exploration of testing against Python …

Add Python 3.9 CI patch

---

crypto/evp_extra/p_pqdsa_asn1.c
crypto/evp_extra/p_pqdsa_test.cc
crypto/fipsmodule/pqdsa/internal.h
crypto/fipsmodule/pqdsa/pqdsa.c

Resolves https://github.com/aws/aws-lc/issues/2413
ISSUE #CryptoAlg-3149
This PR implements support for importing ML-DSA private keys in the "both" format, as specified in https://datatracker.ietf.org/doc/draft-ietf-lamps-dilithium-certificates/ Section 6. Previously, AWS-LC only supported import of ML-DSA private keys as seed or expanded format. 
The changes include:
1. Adding a third mode to the `PQDSA` ASN.1 private key decoding function `pqdsa_priv_decode` to parse ML-DSA private keys of the form `both SEQUENCE`:
```
ML-DSA-XX-PrivateKey ::= CHOICE {
seed [0] OCTET STRING (SIZE (32)),
expandedKey OCTET STRING,
both SEQUENCE {
seed OCTET STRING (SIZE (32)),
expandedKey OCTET STRING
}
}
```
2. Implementing a new function `PQDSA_KEY_set_raw_keypair_from_both` that handles the "both" …

ML-DSA: ASN.1 Module - add parsing of BOTH private key format

---

crypto/fipsmodule/rand/entropy/tree_drbg_jitter_entropy.c
crypto/rand_extra/getrandom_fillin.h
crypto/rand_extra/urandom_test.cc

The PRNG model has been disabled for a while in the RAGDOLL branch. This PR fixes the PRNG model test for the new implementation. It only captures system calls, so it was pretty straightforward to model the correct flow. Some changes were required to capture the real trace due to Jitter Entropy and other stuff... This should all be explained in inline comments in the source code. Few details below.
The following assumption is no longer true
> It's assumed that any arguments to open(2) are constants in read-only memory
because of system calls originating from Jitter Entropy. This requires a bit more care when parsing the filename argument to `open/openat`. Take the opportunity to simplify the string handling a bit by changing to c++ native std strings.
When reading registers through …

Fix PRNG model test

---

include/openssl/base.h

`V1726629971`
Bump the API version so that customers like s2n-tls can know that the feature for specific unknown X509 critical extensions are supported.
CI

Bump AWSLC_API_VERSION for X509_STORE_CTX_set_verify_crit_oids

---

crypto/test/x509_util.h
crypto/x509/internal.h
crypto/x509/v3_utl.c
crypto/x509/x509_compat_test.cc
crypto/x509/x509_test.cc
include/openssl/x509.h
ssl/ssl_test.cc

Support client-side hostname checks with leading .

---

ssl/internal.h
ssl/ssl_cert.cc
ssl/ssl_privkey.cc
ssl/ssl_test.cc
ssl/ssl_x509.cc

There was an issue with trying to use `SSL_PRIVATE_KEY_METHOD` functionality that was working for the most part, but had some edge scenarios that had stopped working. For example setting the `privkey_method` argument when calling `SSL_CTX_set_chain_and_key` or `SSL_set_chain_and_key`. Originally I thought this feature had been in a complete broken state, but upon further investigation realized that the bssl runner framework was using this functionality for testing async and hints functionality. The caveat was the framework was using alternative functions to directly set the certificate and private key method without using this entrypoint. In theory this entrypoint should work as it is for the most part coded correctly, but had a bug in that is tried to use the private key to determine the …

Resolve SSL_PRIVATE_METHOD and certificate slots functionality

---

crypto/bio/bio_mem.c
crypto/bio/bio_test.cc

Resolves #CryptoAlg-3111
Same as #2380. 
Fixed the state bug that was causing Ruby failures. The failures came from `BIO_reset`, which tries to "rewind" the R/O buffer to its original state. The old implementation only works when the buffer pointer and read pointer are aligned. But in the new memory BIO, this is not always the case. The buffer pointer (`b->data`) does not need to align with the read pointer (since we can have a positive `bbm->read_off`). Our tests didn't cover this because the buffer pointer was synced with read pointer after every test case. 
Added tests for `BIO_reset` and `BIO_seek` functions that attempt to rewind the buffer internally. The tests cover both cases -- when buffer pointer and read pointer are synced and when they are not. …

Rework memory BIOs and implement BIO_seek (2nd try)

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

* Fix prefix build when path has spaces by @justsmth in https://github.com/aws/aws-lc/pull/2400
* Prepare v1.51.2 by @justsmth in https://github.com/aws/aws-lc/pull/2401
* Set OPENSSL_NO_EXTERNAL_PSK_TLS13 to indicate lack of TLS 1.3 PSK by @WillChilds-Klein in https://github.com/aws/aws-lc/pull/2399
* BIO datagram functions by @justsmth in https://github.com/aws/aws-lc/pull/2321
* Reject NewSessionTicket messages with empty tickets in TLS 1.3 by @justsmth in https://github.com/aws/aws-lc/pull/2367
* Ensure that AVX512 is not used on macOS by @justsmth in https://github.com/aws/aws-lc/pull/2363
* Fix socket test issues by @torben-hansen in https://github.com/aws/aws-lc/pull/2404
* Remove python CI patch for main by @WillChilds-Klein in https://github.com/aws/aws-lc/pull/2407
* Remove …

Prepare v1.52.0 release

---

crypto/pkcs8/internal.h
crypto/pkcs8/pkcs8.c
crypto/pkcs8/pkcs8_x509.c
include/openssl/evp.h

Currently PKCS8_marshal_encrypted_private_key function uses salt
length of 8 bytes / 64 bits when no salt length is specified. Increase
this fallback default to 16 bytes / 128 bits, as recommended by NIST
SP 800-132.
Note this is for interoperability purposes. Some FIPS implementations
enforce minimum salt length of 16 bytes. Examples of such FIPS
implementations are Bouncycastle FIPS Java API and Chainguard FIPS
Provider for OpenSSL. Also future v3.6 release of OpenSSL will also
increase the default salt length to 16 bytes. A similar change has
also been submitted to BoringSSL and LibreSSL.
Keep legacy EVP_BytesToKey and PKCS5_SALT_LEN defines at 8 bytes. Add
a new internal only define PKCS12_SALT_LEN set to 16 bytes. Use
PKCS12_SALT_LEN as the fallback salt length in PKCS#8 and PKCS#12 …

Increase default salt from 8 to 16 bytes for PKCS#8 & PKCS#12

---

crypto/rand_extra/ccrandomgeneratebytes.c
crypto/rand_extra/deterministic.c
crypto/rand_extra/getentropy.c
crypto/rand_extra/internal.h
crypto/rand_extra/urandom.c
crypto/rand_extra/windows.c
tool/speed.cc

`CRYPTO_init_sysrand` is not necessary as a standalone function. `CRYPTO_pre_sandbox_init` were the only real consumer and that no longer uses it. That pre-sandbox configuration is now just handled by calling the high-level interface instead, that doesn't require remembering to add now features that have kernel touch points.
`CRYPTO_sysrand_for_seed` is always just a wrapper around `CRYPTO_sysrand` and, therefore, is redundant. `CRYPTO_sysrand_for_seed` was inherited from upstream that had other requirements. Mainly some FIPS stuff.

Simplify operating system randomnness inteface 

---

tool-openssl/x509.cc
tool-openssl/x509_test.cc

The X509 tool should output the has subject-hash before the fingerprint.
Previous output comparison:
```
❯ openssl x509 -subject_hash -fingerprint -noout -in test.pem
b7d05793
SHA1 Fingerprint=EC:B8:70:11:AA:0C:7F:45:0A:86:EE:A4:AA:CA:8A:81:84:9B:72:00
❯ ~/lib/AWS-LC-DEBUG-INSTALL/bin/openssl x509 -subject_hash -fingerprint -noout -in test.pem
SHA1 Fingerprint=EC:B8:70:11:AA:0C:7F:45:0A:86:EE:A4:AA:CA:8A:81:84:9B:72:00
b7d05793
```
With this change comparison:
```
❯ openssl x509 -subject_hash -fingerprint -noout -in test.pem
b7d05793
SHA1 Fingerprint=EC:B8:70:11:AA:0C:7F:45:0A:86:EE:A4:AA:CA:8A:81:84:9B:72:00
❯ ~/lib/AWS-LC-DEBUG-INSTALL/bin/openssl x509 -subject_hash -fingerprint -noout -in test.pem
b7d05793
SHA1 Fingerprint=EC:B8:70:11:AA:0C:7F:45:0A:86:EE:A4:AA:CA:8A:81:84:9B:72:00
``` …

Display X509 fingerprint after hash

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

* Increase default salt from 8 to 16 bytes for PKCS#8 & PKCS#12 by @xnox in https://github.com/aws/aws-lc/pull/2409
* fix(nix): Make sure bssl is in the PATH; workaround nix build failure… by @dougch in https://github.com/aws/aws-lc/pull/2431
* Fix path-has-spaces test by @justsmth in https://github.com/aws/aws-lc/pull/2436
* Create pre-production stage for CI pipeline by @nhatnghiho in https://github.com/aws/aws-lc/pull/2282
* Fix CI cross-mingw by @justsmth in https://github.com/aws/aws-lc/pull/2437
* Display X509 fingerprint after hash by @justsmth in https://github.com/aws/aws-lc/pull/2444

Prepare v1.52.1

---

tool-openssl/x509_test.cc

Quick fix for failing Openssl tool output comparison test.
* The Openssl cli tool orders its output by the order that the parameters were specified.
Verified locally on macos.

Openssl tool output ordered by options provided

---

crypto/fipsmodule/rand/ctrdrbg.c
crypto/fipsmodule/rand/ctrdrbg_test.cc
crypto/fipsmodule/rand/internal.h
include/openssl/ctrdrbg.h

In e.g. `CTR_DRBG_init` arguments `entropy` and `personalization` are effectively xor'd `entropy XOR personalization`. If the two arguments were to ever alias, the resulting XOR would be `0` and therefore predictable (if the aliasing would turn out to be predictable, of course).
This is theoretical, but prevent it explicitly anyway.

Explicitly don't allow buffers aliasing in ctr-drbg implementation

---

crypto/bio/bio_socket_test.cc
crypto/bio/dgram.c

Addresses P247622553
On Windows `AF_UNIX` is not used, so `#include <afunix.h>` is not needed.

Remove unused Windows afunix.h

---

crypto/x509/x509_test.cc
crypto/x509/x509_txt.c
crypto/x509/x509_vfy.c
include/openssl/x509.h
ssl/ssl_x509.cc

OpenSSL's behavior when performing X509 certificate validation is to build the up certificate chain, verify the extensions of the constructed chain, etc, finally proceeding with handling the subjectPublicKeyInfo algorithm and parameters inheritance as appropriate through the chain when applicable per [rfc5280](https://www.rfc-editor.org/rfc/inline-errata/rfc5280.html). This process will cause OpenSSL to reject certificates when encountering public keys that it doesn't understand, for example unknown / unsupported EC curve names, invalid curve points etc. This includes intermediate and root certificates with such public keys (which would need to be usable to validate the issuer signatures on subjects in the chain etc), but also includes the leaf certificate as it's public key is parsed to …

Verify leaf certificate public key rather then leaving it to the caller

---

ssl/handshake.cc

Certificate chains are transfered to the respective peer during the TLS handshake in the ServerHello, and sometimes the ClientHello, messages. These certificate chains can be of arbitrary size due to the number of intermediary issuers, and due to the extensions within the certificates.
To avoid resource exhaustion, BoringSSL limits the size of handshake messages, and rejects handshakes beyond a certain size. By default, the max message size is 16 KiB, but it can be increased with the SSL_CTX_set_cert_max_list setting.
This setting allows handshakes to complete with large certificate chains. However, a new problem surfaces for TLSv1.3 sessions. In TLSv1.3, session tickets (for supporting session resumption) are sent after the handshake in NewSessionTicket messages. BoringSSL currently …

Use max_cert_list for TLSv1.3 NewSessionTicket

---

.github/workflows/actions-ci.yml
crypto/fipsmodule/CMakeLists.txt
tests/docker_images/gcc/15.1.0/Dockerfile
tests/docker_images/gcc/build_images.sh
third_party/googletest/include/gtest/gtest-printers.h
util/fipstools/test_fips.c

* Simplify CI for testing various compilers by using prepared Docker images for each.
* Fix build failures affecting GCC 15/16 and Clang 21.
* The FIPS build appears to be failing with Clang 20/21.
* Clang 20/21 warn when both `-S` and `-c` are used together as options to the compiler.  This is potentially related to the FIPS built failure. (?)
* GCC 16 and Clang 21 are not yet released, but thought it would be useful to proactively build against them in our CI.

Simplify Compiler CI jobs

---

tests/ci/run_bsd_tests.sh
tests/ci/run_cross_mingw_tests.sh
tests/ci/run_cross_tests.sh
tests/ci/run_ios_sim_tests.sh

I forgot to add `tree_drbg_jitter_entropy_isolated_test` to the `shard_gtest` tests in some of the test runner scripts. While I'm here, add the new RNG text executables to the iOS test case using shard_gtest.

Add RNG isolated test executables to shard_gtest sections in some test runner scripts

---

crypto/ocsp/ocsp_integration_test.cc

Fix flakiness of OCSP integration test. Created `CryptoAlg-3363` to follow up on splitting the integration test into another CMake alias and CI dimension.

Fix OCSP integration test failures

---

crypto/fipsmodule/bn/asm/x86_64-gcc.c

Searched for other cases using `grep -rl "_asm_" ./`. My analysis:
./crypto/internal.h: Not multi-instruction inline asm
./crypto/mem.c: Not multi-instruction inline asm
./crypto/fipsmodule/ml_kem/mlkem/verify.h: Not multi-instruction inline asm
./crypto/fipsmodule/bn/asm/x86_64-gcc.c: This commit
./crypto/fipsmodule/bn/div.c: Not multi-instruction inline asm
./crypto/fipsmodule/cpucap/cpu_aarch64_linux.c: Not multi-instruction inline asm
./crypto/fipsmodule/cpucap/cpu_intel.c: Explicitly registers
./crypto/fipsmodule/cpucap/cpu_aarch64_sysreg.c: Not multi-instruction inline asm
./crypto/fipsmodule/cpucap/cpu_aarch64.c: Not multi-instruction inline asm
./third_party/jitterentropy/jitterentropy-base-user.h: Not multi-instruction inline asm
./third_party/jitterentropy/README.md: Text file …

Fix some theoretical missing earlyclobber markers in inline assembly

---

crypto/bio/bio_test.cc
crypto/bio/pair.c

See upstream commits:
* BoringSSL: https://github.com/google/boringssl/commit/37373b9ddf06b4818abd92b94868e3909278dc73
* OpenSSL: https://github.com/openssl/openssl/commit/3105d695358d86c0f2a404b2b74a1870b941ce5e
-----
See uptream's 3105d695358d86c0f2a404b2b74a1870b941ce5e. Fleshed out BIO pair tests to cover all these cases.
Change-Id: I5fd7f9c08c50b1462459c19a34230212b81cb674
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/78829
Reviewed-by: Adam Langley <agl@google.com>
Commit-Queue: Adam Langley <agl@google.com>
-----

[UPSTREAM] Fix BIO_eof for BIO pairs

---

crypto/fipsmodule/service_indicator/service_indicator_test.cc
include/openssl/base.h

* Add build with hardened flag by @m271828 in https://github.com/aws/aws-lc/pull/2396
* Openssl tool output ordered by options provided by @justsmth in https://github.com/aws/aws-lc/pull/2452
* [SCRUTINICE] Remove redundant condition check by @nhatnghiho in https://github.com/aws/aws-lc/pull/2450
* Support relro in delocator by @torben-hansen in https://github.com/aws/aws-lc/pull/2455
* Explicitly don't allow buffers aliasing in ctr-drbg implementation by @torben-hansen in https://github.com/aws/aws-lc/pull/2458
* Remove unused Windows afunix.h by @justsmth in https://github.com/aws/aws-lc/pull/2461
* Revert "Rework memory BIOs and implement BIO_seek (2nd try) (#2433)" by @justsmth in https://github.com/aws/aws-lc/pull/2466
* Use max_cert_list for TLSv1.3 NewSessionTicket by @skmcgrail in …

Prepare v1.53.0

---

tests/ci/integration/run_pq_tls_integration.sh

V1795657921
Some TLS CLI tools listen on stdin for data to send over a TLS connection, other TLS CLI tools immediately close the TLS connection. To ensure that PQ TLS integration tests are not broken if TLS command line tools are updated to await input from stdin instead of immediately closing the TLS connection, run the CLI tools in the background (so that stdin is closed and they should not wait forever for input), and add a timeout (so that even if they do wait, they will be closed, and test progress is ensured).
None
Ran locally and confirmed passing in CI. 

Add timeouts to PQ TLS Integ Tests

---

crypto/fipsmodule/ml_kem/META.yml
crypto/fipsmodule/ml_kem/importer.sh
crypto/fipsmodule/ml_kem/ml_kem.c
crypto/fipsmodule/ml_kem/mlkem/common.h
crypto/fipsmodule/ml_kem/mlkem/mlkem_native.h
crypto/fipsmodule/ml_kem/mlkem/mlkem_native_bcm.c
crypto/fipsmodule/ml_kem/mlkem/poly.c
crypto/fipsmodule/ml_kem/mlkem/poly.h
crypto/fipsmodule/ml_kem/mlkem/poly_k.c
crypto/fipsmodule/ml_kem/mlkem/sampling.c
crypto/fipsmodule/ml_kem/mlkem/sys.h
crypto/fipsmodule/ml_kem/mlkem_native_config.h

---------
This PR updates mlkem-native to v1.0.0.
The main change upstream was a file restructuring which moved `mlkem/*` to `mlkem/src/*`, and moved to `mlkem/*`  the SCU files `mlkem_native.[cS]` and the header `mlkem_native.h`. This necessitates minor changes in the importer, which were captured as an [AWS-LC patch](https://github.com/pq-code-package/mlkem-native/blob/321c30f/integration/awslc/awslc.patch) so that mlkem-native CI could continue to do AWS-LC integration tests. We don't forward the upstream layering here, but keep the original file structure. Also, we don't need the assembly SCU file yet.
Other than that, a new typo-checker upstream found …

Update mlkem-native to v1

---

tool-openssl/CMakeLists.txt
tool-openssl/internal.h
tool-openssl/ordered_args.cc
tool-openssl/x509.cc
tool-openssl/x509_test.cc

* The OpenSSL CLI tool orders its output based on the order of the options passed to it.
* Our tool was using a static order that was unaffected by the order of the options.
* This change adds an alternative suite of functions to parse options in a way that preserves their order.
* The new argument parser was integrated into the "X509" subcommand logic for the tool.
* The new parser still needs to be integrated with the other subcommands as well.
Added new tests that vary the order of the parameters provided.

Order tool output by options provided - x509

---

crypto/console/console.c
crypto/console/console_test.cc

PemPasswdTest suite of tests hang when running them locally on a terminal. Currently the code directly tries to connect to /dev/tty and if not available falls back to stdin and stdout. In the CI env, there is no /dev/tty so the redirection in the test suite works. But when running locally, the code bypasses this since a /dev/tty is available. 
This PR introduces an env var to force using stdin/stdout when running the test suite. This ensures in both CI and local environments, the stdin/stdout redirection works as intended with PemPasswdTest. 

Fix Console Test Suite Execution Locally

---

include/openssl/evp.h

See upstream commit: https://github.com/google/boringssl/commit/860c27038fcd9c2c27242e9874c18408dec1f84c
------
Change-Id: I66fa0b3ebc0cc79c29dafa74509ff6f06ad94ecf
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/79747
Reviewed-by: Adam Langley <agl@google.com>
Commit-Queue: Adam Langley <agl@google.com>

Document that EVP_PKEY_CTX_set_rsa_keygen_pubexp takes ownership

---

crypto/bio/bio_addr.c
crypto/bio/dgram.c
crypto/bio/internal.h
include/openssl/bio.h

Addresses `CryptoAlg-3316`, `CryptoAlg-3292`, `CryptoAlg-3310`, `CryptoAlg-3284`, and `CryptoAlg-3346`.
Some internal builds are failing due to the duplicate header file references that `bio.h` has.
```
/usr/include/bits/types/struct_iovec.h:26:8: error: redefinition of 'struct iovec'
struct iovec
^~~~~
In file included from src/core/tsi/alts/crypt/aes_gcm.cc:23:0:
./src/core/tsi/alts/crypt/gsec.h:30:8: note: previous definition of 'struct iovec'
struct iovec {
```
The `sockaddr` references requires the `<sys/socket.h>` header to exist, but it turns out we never actually implemented `BIO_dgram_get_mtu_overhead`. Removing `BIO_dgram_get_mtu_overhead` for now allows us to get around the "redefinition failure".
OpenSSL gets around the `sockaddr` by containing `BIO_dgram_get_mtu_overhead` in …

Remove sys headers from bio.h

---

tests/ci/run_bsd_tests.sh
tests/ci/run_cross_mingw_tests.sh
tests/ci/run_cross_tests.sh
tests/ci/run_ios_sim_tests.sh

`shard_gtest()` spaws multiple child processes to shard test GoogleTest fixtures. But `rwlock_static_init` is not a GoogleTest executable. So, this is redundant.

rwlock race tests is not a GoogleTest executable

---

crypto/bio/bio_test.cc
ssl/bio_ssl.cc

Resolves `CryptoAlg-3316`, `CryptoAlg-3292`, `CryptoAlg-3310`, `CryptoAlg-3284`, and `CryptoAlg-3346`.
An extension off of https://github.com/aws/aws-lc/commit/9db959e270a02de5d2460f934830538711996f1b, this commit adds "CI" for the change. Instead of adding a new integration CI dimension that's likely going to be ignored, the best (and noisier) way to enforce this was introducing a similar concept in one of the files that referenced `bio.h`. The test files that include `bio.h` have too many header file references to introduce this to, so `bio_ssl.cc` seemed like the more suitable choice.
Rolled back https://github.com/aws/aws-lc/commit/9db959e270a02de5d2460f934830538711996f1b and ran the build, the build does fail without the necessary change.
By submitting this pull request, I confirm …

Intentionally redefine iovec in headers as CI

---

crypto/fipsmodule/rand/entropy/internal.h
crypto/fipsmodule/rand/entropy/tree_drbg_jitter_entropy.c
crypto/fipsmodule/rand/entropy/tree_drbg_jitter_entropy_isolated_test.cc
crypto/thread_pthread.c
tests/ci/run_bsd_tests.sh
tests/ci/run_cross_mingw_tests.sh
tests/ci/run_cross_tests.sh
tests/ci/run_ios_sim_tests.sh

V1827078279
Fixes a logical bug in the tree-DRBG `tree_jitter_check_drbg_must_reseed()` that would prevent a reseed under UBE.
Adds test coverage for tree-DRBG under UBE's. 
Must amend the retry logic for mingw due to the bug https://sourceforge.net/p/mingw-w64/bugs/883/. The existing mitigation for that issue wasn't sufficient anymore (for unknown reasons). I counted up to thousands of retries required.
Instead of relying on tight retries, we implement time-based backoff. This added another complication that `nanosleep()` might not be available on Arm64. To get around that on Arm64, use `Sleep`. Buuut, this function has millisecond resolution, so we don't apply exponential backoff, instead we backoff with 1 ms at a time, to avoid it exploding. x86 still use nanosleep. …

Fix logical bug and add test for tree-DRBG fork

---

include/openssl/ssl.h

Resolves `CryptoAlg-3349`
There's usage of the ssl structure in Openresty where it's trying to pull from SSL as if it's non-opaque.
Looking more closely, the failure is around this code block: https://github.com/openresty/lua-nginx-module/blob/9688812a4eba47c1f43892c998e50b988d740f5d/src/ngx_http_lua_ssl_ocsp.c#L514-L518
```
#ifdef SSL_CTRL_GET_TLSEXT_STATUS_REQ_TYPE
if (SSL_get_tlsext_status_type(ssl_conn) == -1) {
#else
if (ssl_conn->tlsext_status_type == -1) {
#endif
```
`SSL_CTRL_GET_TLSEXT_STATUS_REQ_TYPE` [is used](https://github.com/openssl/openssl/blob/b6ff5598539bf91608246ed81b4b534cbea6539d/include/openssl/tls1.h#L304-L305) by `SSL_get_tlsext_status_type` in Openssl, so it's fair to assume that the functionality exists if the definition is defined. …

Add SSL_CTRL defines for SSL_*_tlsext_status_type

---

crypto/asn1/a_strex.c

https://github.com/aws/aws-lc/issues/2516
GCC 15 started warning about uninitialized variable. Correct/silence that by just initializing it to 0.
Code execution won't/shouldn't reach `utflen = UTF8_putc(utfbuf, sizeof utfbuf, c);` if `c` has not been initialized by prior operations. So, this is a false-positive. However, it probably ain't trivial static analysis given the `UTF8_getc` function call is one code-path that must be inspected for assurance that `c` has been initialized. 

Silence GCC 15 warning for uninitialized variable

---

crypto/fipsmodule/CMakeLists.txt
third_party/s2n-bignum/import.sh
third_party/s2n-bignum/s2n-bignum-imported/include/_internal_s2n_bignum.h

------------
AWS-LC's prefix build works by providing a 'prefix header' which prefixes global symbols through a series of `#define ...` directives. This header needs to be included ahead of the source files it applies to.
1. For C files, the prefix header is pulled in through openssl/base.h.
2. For perl-generated ASM files, it comes from openssl/asm_base.h which is `#include`d through `xxx-xlate.pl`.
3. In contrast to 1. and 2., for s2n-bignum assembly, the prefix header is indirectly included through an `--include` directive in the CMakeLists.txt. Similarly, the cc_builder in aws-lc-rs is patched to use such `--include` clause when building s2n-bignum …

s2n-bignum: Add prefix header to _s2n_bignum_internal.h

---

tests/ci/integration/python_patch/main/aws-lc-cpython.patch

n/a
This PR updates our CPython `main` patch to account for CPython PR [135572](https://github.com/python/cpython/pull/135572). We'll need to update the patch file one more time to remove the the `configure` script change if/when [CPython PR 135402](https://github.com/python/cpython/pull/135402) is merged.
n/a
- CI
---

Remove obsolete python main patch

---

crypto/decrepit/blowfish/blowfish.c
include/openssl/blowfish.h

Resolves `CryptoAlg-3304`
`BF_cfb64_encrypt` was historically a public symbol in OpenSSL until BoringSSL made it internal. This exports the symbol for applications still dependent on it from OpenSSL.
N/A
Only exports the symbol, our existing test coverage should already have this covered.

Export BF_cfb64_encrypt

---

include/openssl/pem.h
include/openssl/ssl.h
include/openssl/ui.h
ssl/ssl_lib.cc

A few small changes to improve OpenSSL compatibility:
* Provide an (empty) "openssl/ui.h" file to prevent compiler from loading OpenSSL's "openssl/ui.h" from system headers.
* Define `PEMerr` as alias for `OPENSSL_PUT_ERROR`
```
// For compatibility with OpenSSL. First argument ignored.
#define PEMerr(f, r) OPENSSL_PUT_ERROR(PEM, (r))
```
* Define `SSL_verify_client_post_handshake` as a no-op function:
```
int SSL_verify_client_post_handshake(SSL *ssl) {
return 0;
}
```

Improve OpenSSL compatibility

---

crypto/pkcs8/pkcs8_x509.c
include/openssl/pkcs8.h

`CryptoAlg-3347`
Serf forces a failure and checks for the PKCS12 error library and  PKCS12_R_MAC_VERIFY_FAILURE  error code in a specific test. This change aligns our PKCS12_Parse implementation to align with OpenSSL for this test case. 

Fix PKCS12 Error Code

---

crypto/fips_callback_test.cc
crypto/fipsmodule/FIPS.md
crypto/fipsmodule/ec/ec_key.c
tests/ci/run_fips_callback_tests.sh
util/fipstools/break-tests.sh
util/fipstools/test-runtime-pwct.sh

The FIPS build type is currently employing an "ECDSA PCT" on the EC key generation code-path and EC key check code-path. This has explosive performance impact.
Our key generation is agnostic (and totally unaware) to which algorithm type a key is being generated for. Hence switch method to "SP 800-56Arev3 Section 5.6.2.1.4.b PCT" (the "New PCT"). For key generation primitives, this will increase performance by up 4-5x. For an ECDH workflow, performance could increase by 2-3x.
Funnily, the current implementation performs the ECDSA PCT but also does the New PCT in `EC_KEY_check_key()` irrespective of FIPS build type or not. Basic impl is to just delete the ECDSA PCT.
Hence, if things were easy, the only thing we must do is to remove the existing ECDSA PCT. But, the `ECDSA_PWCT` test is …

Use SP 800-56Arev3 Section 5.6.2.1.4.b instead of ECDSA PCT method

---

tool-openssl/rehash_test.cc

Caught when working on writing an RPM specfile and the `-Werror=stringop-overread` was used.
```
In function 'createTempDirPath',
inlined from 'SetUp' at /home/mcgrails/rpmbuild/BUILD/aws-lc-1.55.0/tool-openssl/rehash_test.cc:22:5:
/home/mcgrails/rpmbuild/BUILD/aws-lc-1.55.0/crypto/test/test_util.cc:228:17: error: 'strnlen' specified bound 4096 exceeds source size 128 [-Werror=stringop-overread]
228 |   return strnlen(buffer, PATH_MAX);
|                 ^
/home/mcgrails/rpmbuild/BUILD/aws-lc-1.55.0/crypto/test/test_util.cc: In member function 'SetUp':
/home/mcgrails/rpmbuild/BUILD/aws-lc-1.55.0/tool-openssl/rehash_test.cc:82:8: note: source object declared here
82 |   char test_dir[128];
|        ^
lto1: all warnings being treated as errors
make[3]: *** [/tmp/cckPSIxl.mk:2: …
```

tool-openssl: Fix warning 'strnlen' specified bound 4096 exceeds source size 128

---

include/openssl/ssl.h
ssl/internal.h
ssl/ssl_handshake_test.cc
ssl/ssl_key_share.cc
ssl/ssl_lib.cc

Addresses `CryptoAlg-1969`
We're preparing to see if nginx is willing to accept our changes. I found these email threads regarding past attempts to integrate AWS-LC:
* https://mailman.nginx.org/pipermail/nginx-devel/2024-March/2JRAR2JEHWUTVQIAQJZEHHILR6JNXQ6S.html
* https://mailman.nginx.org/pipermail/nginx-devel/2024-March/RAS6R7UE3ZK6K6EQQVA4AHVV4WYNYX3P.html
The second change requested us to pull in the two commits from BoringSSL to support `SSL_get_negotiated_group` and `TLSEXT_nid_unknown `.
* https://github.com/google/boringssl/commit/6cf98208371e5c2c8b9d34ce3b8c452ea90e2963
* https://github.com/google/boringssl/commit/28c24092e39bfd70852afa2923a3d12d2e9be2f5
The first commit has additional complexities with new BoringSSL specific APIs that we probably aren't going to support …

Pull in SSL_get_negotiated_group and TLSEXT_nid_unknown from upstream

---

include/openssl/ssl.h
ssl/handshake.cc
ssl/handshake_server.cc
ssl/internal.h
ssl/ssl_lib.cc
ssl/ssl_session.cc
ssl/ssl_test.cc
ssl/ssl_x509.cc

This reverts commit 127633fc77e752b12e12d8e05304e52b3230b65f.
This PR was accidentally merged in by auto-merge

Revert "Implement SSL_set_verify_result (#2526)"

---

crypto/x509/x509spki.c

Addresses [aws-lc issue 2578](https://github.com/aws/aws-lc/issues/2578)
Return NULL when a NULL or empty string is passed to NETSCAPE_SPKI_b64_decode.
Was causing a segmentation fault in Deno, see https://github.com/denoland/deno/issues/30180. 
Was fixed there as well in https://github.com/denoland/deno/pull/30207.

Return NULL when a NULL or empty string is passed to NETSCAPE_SPKI_b64_decode.

---

include/openssl/ssl.h
ssl/ssl_lib.cc
ssl/test/bssl_shim.cc

Addresses `CryptoAlg-3252` & `CryptoAlg-3341`
Some older internal software happens to depend on `SSL_clear_num_renegotiations`. This was taken out in https://github.com/aws/aws-lc/commit/7cde0dee7cfc508835bf47200004960a58353631, but too much has changed since then and it's not directly revertable.
N/A
SSL runner tests

Reimplement SSL_clear_num_renegotiations

---

.github/actions/latest-semver-tag/README.md
.github/actions/latest-semver-tag/action.yml
.github/actions/latest-semver-tag/get-latest-tag.sh
.github/workflows/abidiff.yml

Improve the ABI diff monitoring workflow to also compute whether the current pull request or push event to a branch breaks (or has broken) ABI compatibility when compared to the latest tagged release.
Previously the workflow jobs (now called incremental diffs) compared the current pull request or push event to the target branch / previous commit. This is problematic in the push event scenario when trying to track whether the current main branch has broken ABI comparability with the previous tagged release. For example:
`A -> B -> C -> C_1 -> C_2` where each is a commit on the main branch.
Assume `B` is the latest tagged release commit. Commit C does not break ABI compatibility, `C_1` is then merged from a pull request commit that breaks ABI compatibility (shows on the branch checks). If …

ABI monitoring GitHub workflow improvements

---

tool-openssl/crl.cc
tool-openssl/crl_test.cc
tool-openssl/pkcs8.cc
tool-openssl/rehash.cc
tool-openssl/req.cc
tool-openssl/rsa.cc
tool-openssl/rsa_test.cc
tool-openssl/s_client.cc
tool-openssl/verify.cc
tool-openssl/version.cc

Follow-up from previous PR: https://github.com/aws/aws-lc/pull/2454
* Migrates the remainder of the subcommands to using `ordered_args` for parameter processing.
* Updates tests for rsa and crl to use reordered arguments.

Migrate Openssl-tool parameter parsing

---

include/openssl/base.h
tool/speed.cc

Follow up to https://github.com/aws/aws-lc/commit/80f986b9430c520462973dcc3aa1b31da1f74b5e. 
On an M1 mac:
```
./tool/bssl speed -filter HMAC -chunks 16,16384
Did 5260000 HMAC-MD5 init operations in 1000094us (5259505.6 ops/sec)
Did 5034750 HMAC-MD5 (16 bytes) operations in 1000048us (5034508.3 ops/sec): 80.6 MB/s
Did 41000 HMAC-MD5 (16384 bytes) operations in 1009616us (40609.5 ops/sec): 665.3 MB/s
Did 13546000 HMAC-SHA1 init operations in 1000004us (13545945.8 ops/sec)
Did 10967750 HMAC-SHA1 (16 bytes) operations in 1000016us (10967574.5 ops/sec): 175.5 MB/s
Did 145000 HMAC-SHA1 (16384 bytes) operations in 1002971us (144570.5 ops/sec): 2368.6 MB/s
Did 14913750 HMAC-SHA256 init operations in 1000013us (14913556.1 ops/sec)
Did 12340000 HMAC-SHA256 (16 bytes) operations in 1000018us …
```

Add HMAC SHA3 benchmarks

---

crypto/fipsmodule/sha/internal.h
crypto/fipsmodule/sha/keccak1600.c
crypto/fipsmodule/sha/sha3.c
tool/speed.cc

-----------
Previously, the 4-fold batched SHAKE APIs
- SHAKE256_Init_x4
- SHAKE256_Squeezeblocks_x4
- SHAKE256_Absorb_once_x4
- SHAKE256_x4
were implemented as four sequential calls to the toplevel 1-fold SHAKE_Init, SHAKE_Squeeze, SHAKE_Absorb, and SHAKE256, respectively.
As such, the implementations can not readily make use of the optimized and verified 4-fold Keccak-F1600 implementations that s2n-bignum provides.
To pave the way for this, this commit rewrites the implementations of the above functions by effectively inlining the definitions of the underlying SHAKE_xxx functions and interleaving them at the function level, exposing KeccakF1600_x4 as the …

Rewrite 4-fold batched SHAKE to be amenable to batched Keccak-F1600 assembly

---

include/openssl/target.h

Currently clang builds on ppc64 (big-endian) fail because little-endian code path is attempted. This patch uses the canonical way of checking endianness.
Fixes build on ppc64 (big-endian)
Build testing.

target.h: more clearly check for ppc64 endianness

---

crypto/fipsmodule/ml_dsa/ml_dsa_ref/poly.c
crypto/fipsmodule/ml_dsa/ml_dsa_ref/reduce.c
crypto/fipsmodule/ml_dsa/ml_dsa_ref/rounding.c

N/A
ML-DSA constant-time hardening for caddq, poly_chknorm, decompose
Based on https://github.com/pq-code-package/mldsa-native/pull/371.

ML-DSA constant-time hardening for caddq, poly_chknorm, decompose

---

crypto/evp_extra/evp_asn1.c
crypto/evp_extra/evp_extra_test.cc
crypto/fipsmodule/evp/evp_ctx_test.cc
include/openssl/evp.h

Resolves https://github.com/ruby/openssl/issues/933
Ironically, this was a discrepancy introduced due to our recent endeavors for more OpenSSL compatibility. We introduced support for `EVP_PKEY_check` and `EVP_PKEY_public_check` with https://github.com/aws/aws-lc/commit/bbf9ff6176b056bfbeab9d46f719fc724fc5edb8 and this was pulled into the latest release.
Unfortunately, ruby/openssl uses `EVP_PKEY_check` as a function support check for `EVP_PKEY_param_check` and we happened to only implement `EVP_PKEY_check` without `EVP_PKEY_param_check`. This PR implements support for such to resolve the OpenSSL discrepency.
N/A
Tests inserted within code.

Add support for EVP_PKEY_param_check

---

crypto/fipsmodule/ml_kem/META.yml
crypto/fipsmodule/ml_kem/mlkem/cbmc.h
crypto/fipsmodule/ml_kem/mlkem/common.h
crypto/fipsmodule/ml_kem/mlkem/compress.c
crypto/fipsmodule/ml_kem/mlkem/indcpa.c
crypto/fipsmodule/ml_kem/mlkem/kem.c
crypto/fipsmodule/ml_kem/mlkem/kem.h
crypto/fipsmodule/ml_kem/mlkem/mlkem_native_bcm.c
crypto/fipsmodule/ml_kem/mlkem/native/aarch64/meta.h
crypto/fipsmodule/ml_kem/mlkem/native/aarch64/src/arith_native_aarch64.h
crypto/fipsmodule/ml_kem/mlkem/native/aarch64/src/intt.S
crypto/fipsmodule/ml_kem/mlkem/native/aarch64/src/ntt.S
crypto/fipsmodule/ml_kem/mlkem/native/aarch64/src/poly_mulcache_compute_asm.S
crypto/fipsmodule/ml_kem/mlkem/native/aarch64/src/poly_reduce_asm.S
crypto/fipsmodule/ml_kem/mlkem/native/aarch64/src/poly_tobytes_asm.S
crypto/fipsmodule/ml_kem/mlkem/native/aarch64/src/poly_tomont_asm.S
crypto/fipsmodule/ml_kem/mlkem/native/aarch64/src/polyvec_basemul_acc_montgomery_cached_asm_k2.S
crypto/fipsmodule/ml_kem/mlkem/native/aarch64/src/polyvec_basemul_acc_montgomery_cached_asm_k3.S
crypto/fipsmodule/ml_kem/mlkem/native/aarch64/src/polyvec_basemul_acc_montgomery_cached_asm_k4.S
crypto/fipsmodule/ml_kem/mlkem/native/aarch64/src/rej_uniform_asm.S
crypto/fipsmodule/ml_kem/mlkem/native/api.h
crypto/fipsmodule/ml_kem/mlkem/poly.c
crypto/fipsmodule/ml_kem/mlkem/poly_k.c
crypto/fipsmodule/ml_kem/mlkem/sampling.c
crypto/fipsmodule/ml_kem/mlkem/sampling.h
crypto/fipsmodule/ml_kem/mlkem/sys.h
crypto/fipsmodule/ml_kem/mlkem/verify.h
crypto/fipsmodule/ml_kem/mlkem/zetas.inc
crypto/fipsmodule/ml_kem/mlkem_native_config.h

-----------
This PR updates crypto/fipsmodule/ml_kem by re-importing the latest mlkem-native `main` ([ed62d312](https://github.com/pq-code-package/mlkem-native/commit/ed62d31297bca103cbbf02e125646af098253872)). It also leverages recently added configuration options to use `OPENSSL_memset` and `OPENSSL_memcpy` where previously `memset/memcpy` were used.
This update is a prerequisite to @dkostic's integration of the x86_64 backend from mlkem-native.

ML-KEM: Re-import mlkem-native

---

tests/ci/integration/run_bind9_integration.sh

Resolves #P289577271
Bind9 made an upstream change to append project version to the library name, leading to failure in our CI. This PR fixes that.

Fix Bind9 CI test

---

.github/workflows/test-cpp-capture-hash.yml
.github/workflows/test-cpp-inject-hash.yml
crypto/CMakeLists.txt
tests/ci/run_capture_hash_cpp.bat
util/fipstools/inject_hash_cpp/CMakeLists.txt
util/fipstools/inject_hash_cpp/capture_hash.cpp

This pull request implements a C++ version of capture_hash for AWS-LC's FIPS module integrity verification. The implementation now has a complete solution for handling FIPS integrity across all supported platforms (Linux, MacOS, and Windows) for a shared build. It also maintains compatibility with existing FIPS integrity verification workflow
Windows-specific implementation for capturing correct hash values
Integration with MSVC build process
Error handling and output parsing
tests/ci/run_capture_hash_cpp.bat: Test script for Windows
util/fipstools/inject_hash_cpp/capture_hash.cpp: Windows implementation
util/fipstools/inject_hash_cpp/CMakeLists.txt: Build configuration
crypto/CMakeLists.txt: Integration with AWS-LC build system
Command-line argument handling
Output parsing
Hash …

capture hash functionality

---

crypto/fipsmodule/sha/keccak1600.c

Bit Interleave is used for performance optimizations on 32-bit platforms. Bit Interleave adds unnecessary complexity.
Some Windows compiler, e.g., old versions of Microsoft Visual C++ (MSVC), do not support some preprocessor directives and expressions, e.g., of the type:
```
// Double-check that bit-interleaving is not used on AArch64
#if BIT_INTERLEAVE != 0
#error Bit-interleaving of Keccak1600 states should be disabled for AArch64
#endif
```
in https://github.com/aws/aws-lc/blob/d781046a99638d1466ec912cf0191d0564de2084/crypto/fipsmodule/sha/keccak1600.c#L422
A solution could be:
```
#if defined(BIT_INTERLEAVE) && BIT_INTERLEAVE
#error Bit-interleaving of Keccak1600 states should be disabled for AArch64
#endif
```
However, BIT_INTERLEAVE is intended for only optimizing 32-bit platforms, …

Remove BIT_INTERLEAVE support

---

tests/ci/cdk/cdk/aws_lc_android_ci_stack.py
tests/ci/cdk/cdk/aws_lc_base_ci_stack.py
tests/ci/cdk/cdk/aws_lc_ec2_test_framework_ci_stack.py
tests/ci/cdk/cdk/aws_lc_github_ci_stack.py
tests/ci/cdk/cdk/aws_lc_github_ci_x509_stack.py
tests/ci/cdk/cdk/aws_lc_github_fuzz_ci_stack.py

Addresses P292389560
Instead of managing an opaque list of GitHub account IDs this migrates the CI to he new [CodeBuild pull request comment approval](https://docs.aws.amazon.com/codebuild/latest/userguide/pull-request-build-policy.html). Any user that has admin, write, triage, or maintainer permission to the repository will have the CI run automatically when they open a PR. If any other user opens a pull request the CodeBuild jobs will not run until someone in the above permission list comments on the PR with `codebuild_run(<SHA_OF_THE_LATEST_COMMIT>)` e.g. `codebuild_run(0faf56fee7b72f842408930bfbdab9e90e4d174d)`.
As far as I can tell this isn't modeled in the CDK yet which requires manually configuring the CFN property on each job. This also isn't a property of …

Migrate from CodeBuild account actor filter to pull request comment filter based on GitHub permissions

---

.github/workflows/actions-ci.yml
.gitignore
crypto/fipsmodule/CMakeLists.txt
util/fipstools/inject_hash/macho_parser/tests/macho_tests.h

Fix MacOS FIPS build when using Clang-20
MacOS FIPS build w/ clang-20 was failing with the following error:
```
...
FAILED: [code=1] crypto/fipsmodule/fips_apple_end.o /var/folders/bd/5rrlftjx2098f44h7jbj3n400000gr/T/tmp.iTYkPA1vWf/AWS-LC-BUILD/crypto/fipsmodule/fips_apple_end.o
cd /var/folders/bd/5rrlftjx2098f44h7jbj3n400000gr/T/tmp.iTYkPA1vWf/AWS-LC-BUILD/crypto/fipsmodule && /usr/bin/cc -arch arm64 -isysroot -c /Users/justsmth/repos/aws-lc/crypto/fipsmodule/fips_shared_library_marker.c -DAWSLC_FIPS_SHARED_END -o fips_apple_end.o
clang: warning: no such sysroot directory: '-c' [-Wmissing-sysroot]
/Users/justsmth/repos/aws-lc/crypto/fipsmodule/fips_shared_library_marker.c:17:10: fatal error: 'stdio.h' file not found
17 | #include <stdio.h>
|          ^~~~~~~~~
1 error generated.
```
By …

Fix macOS FIPS build w/ clang-20

---

CMakeLists.txt
include/openssl/base.h

Draft release notes https://github.com/aws/aws-lc/releases/edit/untagged-8f8fd2e32f499f673910, bumping the minor release number for the new encoding support added in https://github.com/aws/aws-lc/pull/2624

Prepare for v1.60.0 release

---

tests/ci/cdk/cdk/codebuild/github_ci_linux_arm_omnibus.yaml
tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
tests/ci/run_benchmark_build_tests.sh
tool/speed.cc

Resolves `P296550391`
Turns out we never run against FIPS with main in our own benchmarking CI tests. It took breaking the benchmarking canary for us to notice this. This PR fixes the issue and adds the CI code path to ensure that this doesn't break in the future. Also made some minor adjustments to fix naming misalignments and a bug where we weren't running the right benchmarking binary for the FIPS 2024 branch.
Original error:
```
o-omit-frame-pointer -O2 -g -DNDEBUG -fPIE -Wno-deprecated-declarations -std=gnu++17 -MD -MT tool/CMakeFiles/aws-lc-fips-main.dir/speed.cc.o -MF tool/CMakeFiles/aws-lc-fips-main.dir/speed.cc.o.d -o tool/CMakeFiles/aws-lc-fips-main.dir/speed.cc.o -c /home/ubuntu/workplace/aws-lc/tool/speed.cc
/home/ubuntu/workplace/aws-lc/tool/speed.cc:2509:65: error: use of …
```

Fix benchmarking issues with FIPS main

---

crypto/fipsmodule/rand/entropy/tree_drbg_jitter_entropy.c
crypto/fipsmodule/rand/internal.h
crypto/fipsmodule/rand/rand.c

2^48 is generally an upper bound on number of CTR-DRBG invocations without reseed. Statically assert type is large enough and for other counters document that 2^64 is the assumed strict upper bound.

Document and statically assert counters can't overflow

---

.github/workflows/actions-ci.yml

The constructed ternary: `A && B || C` equivalent to `A ? B : C`. In Github action `B` must evaluate to True for this to work. See https://github.com/actions/runner/issues/409#issuecomment-752775072

Fix ternary operator in github workflow

---

CMakeLists.txt

* aws/aws-lc-rs#512
Zig compiler looks like both MINGW and CLANG. When building with zig, it fails due to the definition being set here:
```
...
<command line>:9:9: error: '_WIN32_WINNT' macro redefined [-Werror,-Wmacro-redefined]
9 | #define _WIN32_WINNT _WIN32_WINNT_WIN7
|         ^
<command line>:2:9: note: previous definition is here
2 | #define _WIN32_WINNT 0x0a00
|         ^
In file included from <built-in>:416:
<command line>:9:9: error: '_WIN32_WINNT' macro redefined [-Werror,-Wmacro-redefined]
9 | #define _WIN32_WINNT _WIN32_WINNT_WIN7
|         ^
<command line>:2:9: note: previous definition is here
2 | #define _WIN32_WINNT 0x0a00
|         ^
1 error generated.
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license …

Fix for zig build

---

crypto/fipsmodule/sha/internal.h
crypto/fipsmodule/sha/keccak1600.c

Resolves #P299110829
Update `KECCAK1600_ASM` for x86_64 platforms to only be defined when `!MY_ASSEMBLER_IS_TOO_OLD_FOR_512AVX`.
./crypto/crypto_test --gtest_filter=SHA3Test.*
./crypto/crypto_test --gtest_filter=All/PerKEMTest.KAT/*

Fix Keccak MY_ASSEMBLER_IS_TOO_OLD_FOR_512AVX flag

---

third_party/jitterentropy/CMakeLists.txt

For MSVC, the `/FI` option should be used for force-includes: https://learn.microsoft.com/en-us/cpp/build/reference/fi-name-forced-include-file?view=msvc-170

Use /FI for MSVC forced-includes

---

tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml

Modified the name of the duplicate ACCP tests to fix CI failures

Fix duplicate test names in CodeBuild integration tests

---

.github/actions/codebuild-docker-run/action.yml
.github/actions/codebuild-docker-run/codebuild-docker-run.sh
.github/workflows/actions-ci.yml
tests/ci/cdk/cdk/aws_lc_github_actions_stack.py
tests/ci/cdk/cdk/codebuild/github_ci_linux_arm_omnibus.yaml
tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
tests/ci/cdk/pipeline/ci_stage.py
tests/ci/cdk/pipeline/ci_util.py
tests/ci/common_posix_setup.sh
tests/ci/run_fips_tests.sh
tests/ci/setup.py

Sets up a CodeBuild project to be able to leverage self-hosted GitHub Action Runners in AWS CodeBuild.
Follow-up PRs will migrate various omnibus jobs and demonstrate this working. For now this just stages the CDK code needed to get it setup so we can phase roll it out.
A demonstration of this code in action can be found here: https://github.com/skmcgrail/aws-lc/actions/runs/17870473934

CodeBuild GitHub Actions Runner Project

---

ssl/extensions.cc
ssl/internal.h
ssl/ssl_encoding_test.cc
ssl/ssl_version_test.cc
ssl/test/runner/runner.go

Fixes tests that assume X25519 will be negotiated and will break when the default TLS supported group is changed to X25519MLKEM768. 
Related to https://github.com/aws/aws-lc/pull/2531/files
None
Unit tests

Fix tests that assume X25519 will be negotiated

---

CMakeLists.txt

Don't ignore `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS` when building w/ MSVC.
This issue was first identified upstream: https://github.com/google/boringssl/commit/61780c6123af0cc8b85e20ea200f17f1604394b1

Don't ignore CMAKE_C_FLAGS w/ MSVC

---

crypto/fipsmodule/ml_dsa/ml_dsa_ref/poly.c

Change types `uint32_t t0, t1;` to` int32_t t0, t1;` due to potential overflow in `if (t0 < 9){a[ctr++] = 4 - t0;}` causing cbmc proofs to fail.
From https://github.com/pq-code-package/mldsa-native/pull/86.
The output array is of type `int32_t* a`, thus, `uint32_t` aux values `t0, t1` cause cbmc proofs to fail due to potential overflow.
`./crypto/crypto_test `

Type fix in mldsa

---

crypto/pem/pem_lib.c

Resolves #2719 
The code previously used:
`if (strncmp(buf, "-----END ", 9) == 0) { ... }`
If buf is a string with length < 9, or even just one character, GCC knows at compile time that this comparison can never return 0 (i.e. never match). So, GCC is giving out a warning here.. But because of `-Werror=string-compare` this warning is getting converted to an error which causing build failures in some platforms like s390x and riscv64
Build Logs:
```
[root@b314lp50 build]# make -j$(nproc)
[  1%] Generating crypto_test_data.cc
[  1%] Building CXX object CMakeFiles/boringssl_gtest.dir/third_party/googletest/src/gtest-all.cc.o
[  1%] Built target boringssl_prefix_symbols
[  1%] Generating err_data.c
[  1%] Building C object third_party/jitterentropy/CMakeFiles/jitterentropy.dir/jitterentropy-lib …
```

crypto/pem: replace strncmp with CRYPTO_memcmp to fix -Wstring-compare error

---

third_party/s2n-bignum/s2n-bignum-to-be-imported/arm/aes/aes-xts-enc.S

Addresses CryptoAlg-2941
- We don't need to do `len DIV 0x50` until before the loop that processes 5 blocks at a time.
- We don't need the computation of the second block's tweak (iv) until we know we will use it.
Note: that iv was not needed in the case of 1 block + k bytes, k < 16, i.e. cipher-stealing case of tail1x, because that iv is anyway computed before cipher-stealing, so it was actually computed twice before this move.

Move udiv and sencond tweak calculations to when needed

---

crypto/fipsmodule/rsa/rsa.c

Was running into segfaults with this with some internal builds switching over to AWS-LC.

Add null check on RSA key checks

---

tool-openssl/CMakeLists.txt
tool-openssl/ec.cc
tool-openssl/ec_test.cc
tool-openssl/internal.h
tool-openssl/tool.cc

Addresses #CryptoAlg-3382
This PR implements a minimal EC CLI tool for AWS-LC to provide EC key processing capabilities similar to OpenSSL's `openssl ec` command. The tool supports essential EC key operations including format conversion between PEM/DER for both private and public keys, using AWS-LC's native EC APIs for proper key handling.
- **Unit tests:** 13 comprehensive test cases in `ec_test.cc` covering:
- Format conversion (PEM ↔ DER) for both private and public keys
- Round-trip validation ensuring data integrity
- Error handling for invalid inputs and file operations
- Cross-compatibility with OpenSSL when environment variables are set
- **Manual verification:** Tested format conversion and OpenSSL interoperability during development
By submitting this pull request, I confirm …

Add minimal EC CLI tool implementation
