aws/aws-lc

README.md
Resolves CryptoAlg-733
Update the Readme to accurately reflect the state of the project and include useful links to more information.
It is easier to review a rendered version of the readme on my repository https://github.com/andrewhop/aws-lc/tree/readme_updates#readme
=> Update top level readme with links to more information

README.md
Follow up from the previous readme changes with updated Windows server version we test with and remove specific C/C++ standard until remaining issues are addressed. 
https://github.com/andrewhop/aws-lc/tree/readme_updates#readme
=> Minor readme updates with correct versions

README.md
Just a trivial spelling fix on this one. 😉
=> Trivial typo fix: there ↪ their

CMakeLists.txt
Addresses V378887705
This PR converted the message type from error to warning.
It also added additional reference to the message.
Next PR, I will use `check_compiler` in CMakeLists.txt to check if the compiler has the issue.
=> Add additional reference to the message.

tool/bssl_bm.h, tool/ossl_bm.h
None
Adding copyright statements to some files that were missing them in the last PR. Copyright statements are important.
None
None
=> add copyright statements to header files that are missing them

crypto/rsa_extra/rsassa_pss_asn1.c
Resolves V415616132
This PR is to add some missing error code.
TBD
=> Add specific error code.

tests/ci/run_formal_verification.sh
Addresses CryptoAlg-858?selectedConversation=c8d2e015-22b8-4832-8db2-a2d1f861c56a
This PR disabled ECDSA and ECDH formal checks.
* This PR will be reverted when related formal checks get fixed.
* CI of this PR.
* CI of https://github.com/awslabs/aws-lc/pull/269
=> Disable ECDSA, ECDH and RSA formal checks.

crypto/fipsmodule/service_indicator/service_indicator_test.cc
Addresses #CryptoAlg-835
Adding MD4 in the service indicator tests. MD4 should be a non-approved service.
N/A
new testing dimensions in `crypto/fipsmodule/service_indicator/service_indicator_test.cc`
=> Add md4 to service indicator tests

crypto/fipsmodule/service_indicator/service_indicator.c, crypto/fipsmodule/service_indicator/service_indicator_test.cc
N/A
Addresses FIPS feedback on PR#342
The description is in the comment in the change.
This PR is based on top of PR#342; only the last commit is the contributed change.
=> Init Service Indicator counter in `FIPS_service_indicator_update_state`

crypto/crypto.c, crypto/fipsmodule/cpucap/cpucap.c, crypto/fipsmodule/evp/p_ec.c, crypto/fipsmodule/evp/p_rsa.c, crypto/fipsmodule/rsa/rsa_impl.c, crypto/fipsmodule/service_indicator/internal.h, crypto/fipsmodule/service_indicator/service_indicator.c, crypto/fipsmodule/service_indicator/service_indicator_test.cc
Merge in the latest changes from:
* https://github.com/awslabs/aws-lc/pull/342
* https://github.com/awslabs/aws-lc/pull/344
This is the minimal changes from today and does not include all other changes from main.
Only in CI.
=> Cherry pick additional FIPS fixes

tests/ci/run_fips_tests.sh
Cherry-pick https://github.com/awslabs/aws-lc/commit/995524e30167e19b71bbe6a2b430e73c789df525
=> Use DCMAKE_BUILD_TYPE=Release as FIPS build type.

crypto/ecdh_extra/ecdh_test.cc, crypto/fipsmodule/ec/ec_key.c, crypto/fipsmodule/ec/ec_test.cc, crypto/fipsmodule/ecdh/ecdh.c, crypto/fipsmodule/service_indicator/service_indicator_test.cc
Addresses CryptoAlg-905, CryptoAlg-835
See description in 
- PR https://github.com/awslabs/aws-lc/pull/358
- PR https://github.com/awslabs/aws-lc/pull/360
=> Cherry pick to fips-2021-10-20 public key validation in ECDH

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
Prepare new release by bumping release version number string to `1.0.1`.
=> Bump release version to v1.0.1

crypto/ocsp/ocsp_test.cc
Resolves CryptoAlg-914
Previously the OCSP test would remove the `\n` before calling `EVP_DecodeBase64` which does not handle any new line characters. This then fails on Windows which has a `\r\n` in the test data files which `EVP_DecodeBase64` can't handle. This change updates the test to use `EVP_DecodeUpdate` which can handle all newline characters. `EVP_DecodeUpdate` also is used by the PEM parser which is why the rest of the tests with test data in files works for Windows.
The previous code passed locally and in CodeBuild thanks to everything using the same linux line endings. I tested this locally on a Windows machine.
=> Update ocsp tests to use EVP_DecodeUpdate which handles all newlines correctly

third_party/s2n-bignum/arm/p521/bignum_montmul_p521.S, third_party/s2n-bignum/arm/p521/bignum_montmul_p521_alt.S, third_party/s2n-bignum/arm/p521/bignum_mul_p521.S, third_party/s2n-bignum/arm/p521/bignum_mul_p521_alt.S, third_party/s2n-bignum/x86_att/p521/bignum_montmul_p521.S, third_party/s2n-bignum/x86_att/p521/bignum_montmul_p521_alt.S, third_party/s2n-bignum/x86_att/p521/bignum_montsqr_p521.S, third_party/s2n-bignum/x86_att/p521/bignum_montsqr_p521_alt.S, third_party/s2n-bignum/x86_att/p521/bignum_mul_p521.S, third_party/s2n-bignum/x86_att/p521/bignum_mul_p521_alt.S, third_party/s2n-bignum/x86_att/p521/bignum_sqr_p521.S, third_party/s2n-bignum/x86_att/p521/bignum_sqr_p521_alt.S
N/A
Pull in the latest changes from s2n-bignum (2022-03-03)
The commands used:
```
TODAY=$(date +%Y-%m-%d)
git fetch upstream main
git checkout -b aws-lc-s2n-bignum-update-${TODAY} upstream/main
git fetch s2n-bignum
git checkout -b s2n-bignum-${TODAY} s2n-bignum/main
PATHS_TO_KEEP="./arm/p384 ./x86_att/p384 ./arm/p521 ./x86_att/p521"
git filter-branch -f --index-filter "git rm --ignore-unmatch --cached -qr -- . && git reset -q \$GIT_COMMIT -- $PATHS_TO_KEEP" --msg-filter 'cat; echo; echo "s2n-bignum original commit: https://github.com/awslabs/s2n-bignum/commit/$GIT_COMMIT"' --prune-empty -- HEAD
git checkout aws-lc-s2n-bignum-update-${TODAY}
git merge -s subtree -Xsubtree="third_party/s2n-bignum" s2n-bignum-${TODAY} --allow-unrelated-histories
```
Point out areas that need special …
=> Pull in the latest changes from s2n-bignum (2022-03-03)

tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml, util/whitespace.txt
Addresses CryptoAlg-1043
This PR removed HMAC select check but still keeps the HMAC quick check.
=> Remove HMAC select check.

tests/ci/benchmark_framework/compare_results.py
The benchmarking framework would fail due to issues with Pandas.
Changes the ways type conversion and assignment is done to be in line with what Pandas expects.
The commits will be replaced with a more cohesive title/message when I merge.
Tested in my personal account.
=> New bm fix

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
N/A
Update the version of AWS-LC to v1.0.2.
=> Update AWS-LC version to 1.0.2

tests/ci/run_cryptofuzz.sh
Addresses CryptoAlg-1175
This PR disabled botan. Details are included in the comment. Without this change, PR merges are blocked.
=> Disable botan.

README.md
=> Fix README.md replacing cmake with cmake3

README.md, tests/ci/README.md
Specify what is meant by "support".
No code was harmed in this PR.
=> Specify what is meant by support

tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml, tests/ci/docker_images/linux-x86/ubuntu-20.04_clang-8x/Dockerfile
In order to merge pr#583 we need to first update our docker images.
=> Update images for pr#583

crypto/CMakeLists.txt, third_party/jitterentropy/CMakeLists.txt
Resolves A SIM mentioned by @andrewhop in Slack
Brings PR#511 into the FIPS branch to ease linking issues.
n/a
n/a
=> Add PR511 to fips-2021-10-20

crypto/kyber/README.md
=> Add readme file for Kyber

bindings/rust/aws-lc-sys-template/build.rs
Updates the Rust `aws-lc-sys` crate generator to use the `generated_name_override` callback added in bindgen `0.61.0` to simplify the crate generation logic.
Standard bindgen test cases for each supported platform (macOS & Linux (386, x86-64, arm64)).
=> Migrate to ParseCallbacks for Rust bindgen modifications

crypto/bytestring/asn1_compat.c, crypto/bytestring/bytestring_test.cc, crypto/bytestring/cbb.c, crypto/fipsmodule/bcm.c, crypto/fipsmodule/cpucap/cpu_aarch64_freebsd.c, crypto/fipsmodule/cpucap/cpu_arm_freebsd.c, crypto/fipsmodule/ecdsa/ecdsa.c, crypto/hpke/hpke.c, crypto/trust_token/trust_token.c, crypto/x509/x509_test.cc, crypto/x509/x_all.c, include/openssl/bytestring.h, include/openssl/ssl.h, ssl/t1_enc.cc
Upstream Merge. See internal docs for details.
A number of cherry-picked upstream BSSL commits.
CI
=> Upstream merge 2022-10-31

bindings/rust/README.md, bindings/rust/publish/publish.sh
N/A
Clarify requirements for crate publishing at crates.io
N/A
N/A
=> Add crate publishing readme

tests/ci/run_posix_sanitizers.sh, tool/README.md
Print the full stack trace if the UndefinedBehaviorSanitizer detects an issue. Update the benchmark readme to clarify usecases and build options
Ran locally with a bug in AWS-LC and verified UBSAN printed the stack trace.
=> Update UBSAN run config and benchmark readme

crypto/bio/bio.c, crypto/bio/bio_mem.c, crypto/bio/connect.c, crypto/bio/fd.c, crypto/bio/file.c, crypto/bio/pair.c, crypto/ec_extra/ec_asn1.c, crypto/ex_data.c, include/openssl/ec_key.h, include/openssl/ex_data.h, include/openssl/ssl.h, ssl/handshake_client.cc, ssl/internal.h, ssl/s3_lib.cc, ssl/ssl_lib.cc, ssl/ssl_test.cc, ssl/test/async_bio.cc, ssl/test/bssl_shim.cc, ssl/test/packeted_bio.cc, ssl/test/runner/runner.go, ssl/test/test_config.cc, ssl/test/test_config.h, util/BUILD.toplevel, util/fipstools/delocate/delocate.peg, util/fipstools/delocate/delocate.peg.go, util/fipstools/delocate/testdata/aarch64-Basic/in.s, util/fipstools/delocate/testdata/aarch64-Basic/out.s
Regular upstream merge. See internal doc for details.
Might be worth looking at "acvptool: KDA replaces KAS-KDF for HKDF." a bit extra.
Tested locally. Relying on CI for additional tests.
=> Upstream merge 12 20

CMakeLists.txt, crypto/fipsmodule/FIPS.md, crypto/fipsmodule/modes/gcm.c, crypto/fipsmodule/modes/internal.h, crypto/x509/asn1_gen.c, crypto/x509v3/internal.h, crypto/x509v3/v3_alt.c, crypto/x509v3/v3_bcons.c, crypto/x509v3/v3_conf.c, crypto/x509v3/v3_cpols.c, crypto/x509v3/v3_crld.c, crypto/x509v3/v3_extku.c, crypto/x509v3/v3_pci.c, crypto/x509v3/v3_pcons.c, crypto/x509v3/v3_pmaps.c, crypto/x509v3/v3_utl.c, include/openssl/x509v3.h, util/BUILD.toplevel
Merging from Upstream from https://github.com/google/boringssl/commit/5f6d57a48b364544fbfbbbef66e5613b1c17fe96 to https://github.com/google/boringssl/commit/096d095151f7b6e3ea2cb6c9f212386648902e5e
See internal document as well as "AWS-LC" notes inserted in some of the commit messages for deviations from the commit changes.
=> Upstream merge 2023-01-23

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
V819878264
Prepare new release by bumping release version number string to `1.4.0`.
=> Bump release version to v1.4.0

crypto/ocsp/ocsp_test.cc
N/A
OCSP tests on Windows for the FIPS 1MU branch currently fail because this commit is missing. This PR cherrypicks the commit and brings it from main to the `fips-2021-10-20-1MU` branch.
N/A
Tested by running `ninja run_tests` and ensuring that all tests succeed after bringing in the changes.
=> Update ocsp tests to use EVP_DecodeUpdate which handles all newline charecters correctly (#378)

tests/ci/cdk/cdk/aws_lc_mac_arm_ci_stack.py, tests/ci/cdk/cdk/ssm/m1_tests_ssm_document.yaml, tests/ci/run_m1_ec2_instance.sh
Addresses `CryptoAlg-1423`
We need our Codebuild dimension to be able to handle source code from S3. This lets us easily test internal fixes.
N/A
Tested by following the internal runbook and running against the source code from s3. 
=> Update ssm document to handle s3 files

CMakeLists.txt, crypto/CMakeLists.txt, ssl/CMakeLists.txt, tests/ci/run_windows_tests.bat, tool/CMakeLists.txt
Move Windows FIPS RelWithDebInfo fix into fips-2022-11-02 branch
=> Move Windows FIPS RelWithDebInfo fix into fips-2022-11-02 branch

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
Prepare a new release of AWS-LC by bumping the version to `1.5.0`.
=> Release v1.5.0

.github/workflows/stale_issue.yml
=> Fix typo in stale_issue.yml

util/fipstools/cavp/test_fips.c
Bring https://github.com/aws/aws-lc/pull/853 into the FIPS 1MU branch.
=> Bring added test_fips tool functions to the FIPS 1MU branch

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
N/A
Bump release version to v1.5.1
=> Bump release version to v1.5.1

tests/ci/README.md
N/A
Update the CI docker images documentation about building the images locally.
=> Update the CI docker images documentation

crypto/fipsmodule/bcm.c, crypto/fipsmodule/fips_shared_library_marker.c
Please see PR https://github.com/aws/aws-lc/pull/880 for details.
=> Bring Windows FIPS Segment Changes into FIPS 2022 Branch (#880)

crypto/cipher_extra/e_aesctrhmac.c, crypto/cipher_extra/e_aesgcmsiv.c, crypto/cipher_extra/e_chacha20poly1305.c, crypto/cipher_extra/e_tls.c, crypto/fipsmodule/cipher/aead.c, crypto/fipsmodule/cipher/e_aes.c, crypto/fipsmodule/cipher/internal.h, include/openssl/aead.h, include/openssl/ssl.h, ssl/internal.h, ssl/ssl_aead_ctx.cc, ssl/ssl_lib.cc, ssl/ssl_test.cc, ssl/ssl_transfer_asn1.cc, ssl/test/bssl_shim.cc, ssl/test/runner/mock_quic_transport.go, ssl/test/runner/runner.go
=> clang-format a subset of files

crypto/CMakeLists.txt, crypto/ocsp/internal.h, crypto/ocsp/ocsp_server.c, crypto/ocsp/ocsp_test.cc, include/openssl/ocsp.h
Addresses `CryptoAlg-1564`
Additional supporting functions for OCSP.
N/A
New small unit tests
=> Implement more OCSP functions for better compatibility 

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
P84189141
Prepare new release by bumping release version number string to `v1.6.0`.
=> Bump release version to v1.6.0

CMakeLists.txt, tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml, tests/ci/common_posix_setup.sh, util/all_tests.json
=> Enable Valgrind testing for libssl

crypto/fipsmodule/bn/generic.c
Addresses P81044924
This is a follow up to cc3e7ce6c02ec0b0536af9fe82cff3422e207018 which skipped some of these changes. I verified with this change bn/generic.c matches the upstream file before their latest commit.
Existing tests pass, tested locally with OPENSSL_NO_ASM flag enabled.
=> Remove remaining branches in bn/generic.c

crypto/fipsmodule/digest/internal.h, crypto/fipsmodule/ecdsa/ecdsa.c, crypto/fipsmodule/hmac/hmac.c
Please refer to PR https://github.com/aws/aws-lc/pull/911 for details.
=> Zeroize data immediately after use for FIPS to FIPS 2022 branch 

crypto/asn1/asn1_lib.c
=> Add back ASN1_STRING_clear_free that was accidentally removed

crypto/evp_extra/internal.h
N/A
Delete leftover code from previous Kyber implementation.
=> Delete leftover code from previous Kyber implementation

README.md
=> Remove Gitter from README.md

crypto/fipsmodule/modes/asm/aesni-gcm-avx512.pl
N/A
Compatible with old PERL@5.8.8
Suggested by @dkostic 
Tests can be found from https://github.com/awslabs/aws-c-cal/pull/144 CI actions on `manylinux1-x64`
=> compatible with old perl

crypto/fipsmodule/ecdh/ecdh.c
N/A
Zeroize shared_point in ECDH immediately after use. This is for FIPS.
N/A
N/A
=> Zeroize shared_point in ECDH

.gitignore, CMakeLists.txt, crypto/asn1/a_int.c, util/bot/DEPS, util/bot/UPDATING, util/bot/perl-win32.zip.sha1, util/bot/vs_toolchain.py, util/go_fips_tests.txt, util/go_tests.txt
Merge (some) changes from uptream
CI
=> Upstream merge 2023-05-01

tests/ci/devicefarm_job.py, tests/ci/setup.py
=> Fix device farm CI build with boto3

crypto/fipsmodule/rand/rand.c
This reverts commit fada3c6466a034c87af27a0c8f8c6ab4a9f450fa.
Rebase on https://github.com/aws/aws-lc/pull/991.
=> Revert "Framework to support multiple entropy sources (#928)"

crypto/err/err.c, ssl/ssl_test.cc
Minor fixes pointed out by static analysis
=> Minor fixes pointed out by static analysis

tests/ci/cdk/cdk.context.json, tests/ci/cdk/cdk/components.py
=> Fix incorrect lambda CodeBuild policy permission

crypto/asn1/a_bool.c, crypto/asn1/a_object.c, crypto/asn1/a_type.c, crypto/asn1/asn1_test.cc, crypto/asn1/internal.h, crypto/asn1/tasn_fre.c, crypto/bytestring/bytestring_test.cc, crypto/bytestring/cbs.c, include/openssl/asn1.h, include/openssl/bytestring.h, include/openssl/obj.h, include/openssl/x509.h
=> Upstream merge 2023-05-12

crypto/ocsp/internal.h, crypto/ocsp/ocsp_lib.c, crypto/ocsp/ocsp_test.cc, include/openssl/ocsp.h
Resolves `V918074826`
Small fixes requested internally
N/A
N/A
=> Clean up parts of OCSP_parse_url and additional documentation

crypto/CMakeLists.txt, ssl/CMakeLists.txt
Cherry-pick https://github.com/aws/aws-lc/pull/1081
=> (fips-2022-11-02) Mark include as PUBLIC not SYSTEM PUBLIC (#1081)

tests/ci/docker_images/linux-x86/ubuntu-20.04_clang-10x_formal-verification/create_image.sh, tests/ci/run_formal_verification.sh
Resolve Formal Verification CI issues introduced by https://github.com/awslabs/aws-lc-verification/commit/e504944f94b6379eaf95f1146a168feb72ce844f
=> Fix formal verification CI

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
N/A
Prepare release with the following changes:
* [FIPS-2021-10-20] Detect GCM-SIV alignment change by @justsmth in https://github.com/aws/aws-lc/pull/1147
N/A
N/A
=> [FIPS-2021-10-20] Release v1.1.2

SANDBOXING.md, crypto/CMakeLists.txt, crypto/fipsmodule/cpucap/cpu_aarch64_apple.c, crypto/fipsmodule/hkdf/hkdf.c, crypto/fipsmodule/rand/rand.c, crypto/internal.h, crypto/rand_extra/rand_test.cc, crypto/refcount_lock.c, crypto/refcount_win.c, crypto/stack/stack.c, include/openssl/stack.h, include/openssl/x509.h, ssl/ssl_test.cc, util/fipstools/acvp/acvptool/acvp.go, util/fipstools/acvp/acvptool/subprocess/subprocess.go, util/fipstools/acvp/acvptool/subprocess/tls13.go
Recreation of #1152
N/A
Recreation of upstream merge PR: #1152
N/A
N/A
=> Recreating: Upstream merge 2023 08 09

crypto/cipher_extra/aead_test.cc
Addresses V987750306
Make sure allocation succeeded before using a pointer.
=> Minor fix in aead test

crypto/bio/bio_test.cc, ssl/test/settings_writer.cc, ssl/test/ssl_transfer.cc
=> Fix Compiler Error on GCC 13

CMakeLists.txt, crypto/CMakeLists.txt
Validated compilation of artifacts is successful on Windows 2022 using Visual Studio 2017 Build Tools
=> Add prefix symbols for Windows FIPS Shared Build

third_party/s2n-bignum/arm/generic/bignum_copy_row_from_table.S, third_party/s2n-bignum/arm/generic/bignum_copy_row_from_table_16_neon.S, third_party/s2n-bignum/arm/generic/bignum_copy_row_from_table_32_neon.S, third_party/s2n-bignum/arm/generic/bignum_copy_row_from_table_8n_neon.S
N/A
This PR is splitted from https://github.com/aws/aws-lc/pull/1189.
This PR pulls in the verified constant-time table lookup codes:
- ./arm/generic/bignum_copy_row_from_table.S
- ./arm/generic/bignum_copy_row_from_table_16_neon.S
- ./arm/generic/bignum_copy_row_from_table_32_neon.S
- ./arm/generic/bignum_copy_row_from_table_8n_neon.S
The commands I used are:
(The commands in the internal Quip document was used, with PATHS_TO_KEEP added to include the new 4 files)
```
TODAY=$(date +%Y-%m-%d)
git fetch upstream main  # Fetch the tip of main of AWS-LC 
git checkout -b aws-lc-s2n-bignum-update-${TODAY} upstream/main
git fetch s2n-bignum     # Fetch the tip of main of s2n-bignum
git checkout -b s2n-bignum-${TODAY} s2n-bignum/main
PATHS_TO_KEEP="./arm/p384 ./x86_att/p384 ./arm/p521 …
```
=> Pull in the latest changes from s2n-bignum (2023-09-17)

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
P99720717
Prepare new release by bumping release version number string to 1.16.0.
=> Bump release version to v1.16.0

crypto/fipsmodule/rand/internal.h
Comment had "TBD". But we consider it determined by now.
No code harmed in this PR.
=> Elaborate on whiten factor for passive entropy

crypto/fipsmodule/rand/internal.h
Backports the following PRs from main to fips-2022-11-02:
* https://github.com/aws/aws-lc/pull/1209 | https://github.com/aws/aws-lc/commit/15b2d6c18515bfa30d46d427195823aaa4aacea3
=> Backport: Elaborate on whiten factor for passive entropy

tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml, tests/ci/docker_images/linux-aarch/amazonlinux-2023_base/Dockerfile, tests/ci/docker_images/linux-aarch/ubuntu-22.04_base/Dockerfile
Resolves `CryptoAlg-2096`
We want to increase our OE testing coverage for the integration build.
N/A
New CI dimensions
=> Add ARM dimensions for integration test CI 

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
(cherry picked from commit 8772d197620f8aefd264b9f312716ee77e4ca5b4)
=> Bump version to 2.0 for FIPS

crypto/fipsmodule/sha/sha3_test.cc
Resolves `V1064313897`
Resolving some minor complaints from the static analysis tool. Ran clang format on the file while I was at it.
N/A
N/A
=> Use scoped version of EVP_MD_CTX in test

.github/workflows/aws-lc-rs.yml
=> Resolve aws-lc-rs CI build issues

crypto/bio/bio_test.cc
N/A
* Recent change breaks compilation on GCC 13.x.
```
/tmp/tmp.eF9hAnUZHy/crypto/bio/bio_test.cc: In member function 'virtual void BIOTest_CloseFlags_Test::TestBody()':
/tmp/tmp.eF9hAnUZHy/crypto/bio/bio_test.cc:167:59: error: ignoring attributes on template argument 'int (*)(FILE*)' [-Werror=ignored-attributes]
167 |   using TempFILE = std::unique_ptr<FILE, decltype(&fclose)>;
|       
```
* Fixed in a way similar to previous PR #1184 
N/A
Builds succeeds for me with GCC 13.2.0.
=> Fix GCC 13.x compiler error

tests/ci/integration/README.md, tests/ci/integration/nginx_patch/aws-lc-nginx.patch
Integration CI was failing due to some updates in the nginx code. This resolves that.
nginx commit: https://github.com/nginx/nginx/commit/52d50714eb0ffd46796b52526da273db7b4a3883
=> Update patch for nginx integration CI

crypto/bio/bio_test.cc, ssl/ssl_test.cc
Addresses V1073362943, V1075629722
Added checks on a value and a pointer to ensure they're positive and non-null, respectively.
=> Test fixes

crypto/fipsmodule/rand/rand.c
Backport https://github.com/aws/aws-lc/pull/1288.
=> Backport rand_thread_state zero patch to 2021-10-20-1MU

util/fipstools/acvp/modulewrapper/main.cc
Everything isn't working fully, but to at least compile the module wrapper we need this.
Cross compiled.
=> Add PPC64BE to module wrapper

crypto/fipsmodule/rand/rand.c, crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
Backport https://github.com/aws/aws-lc/pull/1294
=> [fips-2021-10-20] Only update thread_states_list if freed state is head when prev is NULL

crypto/fipsmodule/rand/rand.c, crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
Backport https://github.com/aws/aws-lc/pull/1294
=> [fips-2022-11-02] Only update thread_states_list if freed state is head when prev is NULL

crypto/fipsmodule/rand/rand.c, crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
Backport https://github.com/aws/aws-lc/pull/1294
=> [fips-2021-10-20-1MU] Only update thread_states_list if freed state is head when prev is NULL

crypto/x509/x509_vfy.c
Resolves `V1102304651`
Adds an additional check on where we were calling `sk_X509_push`.
=> Add check for sk_X509_push

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
N/A
Prepare new release by bumping release version number string to 1.17.4.
=> Bump release version number string to 1.17.4

.github/workflows/cross-ppc64.yml, .gitignore, crypto/fipsmodule/bn/bytes.c, tests/ci/common_posix_setup.sh, tests/ci/gtest_util.sh, tests/ci/run_cross_ppc64_tests.sh
N/A
* Add CI for build and testing of ppc64 (big-endian).
N/A
N/A
=> CI for Build/Testing on PPC64BE

crypto/curve25519/curve25519.c
Follow-up to https://github.com/aws/aws-lc/pull/1309. Simplifies the decision logic for which s2n-bignum implementation that should be used at run-time. Basically, before the overall ISA type decision logic was repeated twice.
Suggested by @dkostic.
The aborts before calling s2n-bignum is actually not important, so removed it. The reason is that we already assume that the fallback s2n-bignum implementation works on all available cpu (for the specific type).
Manually inspected the same implementation is chosen as before. Also ran a couple of speed experiments to see that the same speed was reported.
=> Improve decision logic for s2n-bignum implementation

crypto/ocsp/ocsp_integration_test.cc
The non-Amazon unauthorized OCSP responder endpoint decided to start returning a different value (`OCSP_RESPONSE_STATUS_INTERNALERROR`) at times, which resulted in a large amount of test failures for us.
This relaxes the assumption to just verify that the OCSP response isn't successful.
=> Relax test pinging unauthorized OCSP responder

crypto/ec_extra/hash_to_curve.c, crypto/err/err.c, crypto/fipsmodule/ec/ec.c, crypto/fipsmodule/ec/ec_key.c, crypto/fipsmodule/ec/felem.c, crypto/fipsmodule/ec/internal.h, crypto/fipsmodule/ec/simple.c, crypto/fipsmodule/ec/simple_mul.c, crypto/fipsmodule/ec/wnaf.c, crypto/fipsmodule/ecdsa/ecdsa_test.cc, crypto/fipsmodule/pbkdf/pbkdf.c, crypto/pkcs8/internal.h, crypto/pkcs8/p5_pbev2.c, crypto/pkcs8/pkcs8.c, crypto/pkcs8/pkcs8_x509.c, crypto/trust_token/pmbtoken.c, crypto/x509/x509_vfy.c, include/openssl/evp.h, include/openssl/x509.h
=> Upstream merge 2023-11-30

tool/speed.cc
Extension of PR #1311
EVP_chacha20_poly1305 is an alternative interface for ChaCha20-Poly1305.
Notably, it uses an implementation of the algorithm that is distinct
from the preferred AEAD interfaced. This implementation, while still
assembly optimized, is older and slower.
The new interface is 5x slower because of the slower poly1305 implementation.
Initial results when run on a Macbook rocking an Intel Core i7.
```
/Users/gcr/git-workplace/aws-lc/build/clion/tool/bssl speed -filter ChaCha20-Poly1305
Did 3067000 EVP-ChaCha20-Poly1305 encrypt init …
```
=> Add EVP_chacha20_poly1305() to speed.cc

.github/workflows/integrations.yml, tests/ci/integration/run_trousers_integration.sh
N/A
* Integration build with [TrouSerS](http://trousers.sf.net/)
N/A
N/A
=> TrouSerS integration

tool/speed.cc
Add a benchmark that measures the time of HMAC init. This is similar to the other init benchmarks for ciphers.
Update AEAD init benchmark to reuse the same stack allocated AEAD context for each iteration. This removes the time for `EVP_AEAD_CTX_zero` and `EVP_AEAD_CTX_cleanup` from the benchmark loop. This was called automatically for the ScopedEVP_AEAD_CTX when the [stack object goes out of scope](https://github.com/aws/aws-lc/blob/main/include/openssl/aead.h#L487-L489).
The only other init benchmark for XTS [already reuses the same context for all iterations](https://github.com/aws/aws-lc/blob/main/tool/speed.cc#L1005-L1017). 
```
Did 1466000 HMAC-SHA256 init operations in 1000568us (1465167.8 ops/sec)
Did 1425000 HMAC-SHA256 (16 bytes) operations in 1000255us (1424636.7 ops/sec): 22.8 …
```
=> Add HMAC init benchmark

.github/docker_images/cmake_build_versions/Dockerfile, .github/docker_images/cmake_build_versions/awslc_build.sh, .github/docker_images/cmake_build_versions/cmake_build.sh, .github/docker_images/cmake_build_versions/entry.sh, .github/workflows/cmake.yml
=> Add CMake GitHub Actions CI

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
[Version number bump for 1.20.0](https://github.com/aws/aws-lc/releases/edit/untagged-c0513cad353746e2623c).
I [checked the changes](https://github.com/aws/aws-lc/releases/edit/untagged-c0513cad353746e2623c) and verified none are a breaking change.
=> Staging v1.20.0 release

tests/ci/cdk/cdk/codebuild/ec2_test_framework_omnibus.yaml
Turn off Graviton 3 test, pending P113131493.
This PR.
=> Turn off Graviton 3 test

tests/ci/integration/run_grpc_integration.sh
Currently the grpc CI takes ~100 minutes to complete. 90 minutes of that is spent building grpc, this is 8,328 tasks for ninja which includes compiling each c file, and linking all libraries and tests. We then run only a subset of the tests that mention tls, ssl, or certs in the name.
This change finds the tests we're going to run, and then only builds those targets. This drops the number of tasks for ninja down to 1,877 and the overall job only takes 19 minutes.
[Here is an example of the test config](https://github.com/grpc/grpc/blob/master/CMakeLists.txt#L29959) the grep is attempting to find. Previously we built all tests and only ran matching `[[ -x "$file" && ( "$file" == *ssl* || "$file" == *tls* || "$file" == *cert* ) ]]`, now we only build test targets matching …
=> Only build the grpc tests that we're going to run to save time

tests/ci/cdk/README.md, tests/ci/cdk/cdk/aws_lc_ec2_test_framework_ci_stack.py, tests/ci/cdk/cdk/windows_docker_image_build_stack.py, tests/ci/cdk/run-cdk.sh, tests/ci/docker_images/dependencies/build_cryptofuzz_modules.sh, tests/ci/setup.py
N/A
* Minor updates to CDK docs and dependency versions.
N/A
Successfully running CDK deployments on my account.
=> Update CDK docs/dependencies

README.md
Resolves #1404 
The Formal Verification section in README is updated to match latest status
None
None
=> Update Formal Verification section in README to match latest status

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
Bump version number for next release
No breaking changes.
=> Staging v1.21.0 release

tests/ci/cdk/cdk/aws_lc_github_ci_stack.py, tests/ci/cdk/util/iam_policies.py
CryptoAlg-1446
Enables public access to logs for the following CodeBuild projects:
* aws-lc-ci-linux-x86
* aws-lc-ci-linux-arm
* aws-lc-ci-integration
* aws-lc-ci-windows-x86
This will create new CloudWatch LogGroups for logs to be written to.
CodeBuild public log enabled on my test account:
* [aws-lc-ci-linux-x86](https://us-west-2.codebuild.aws.amazon.com/project/eyJlbmNyeXB0ZWREYXRhIjoic1piZ3QxVEJUZDhCT2M5eFBLTnV2QVNxSTkvRnR2dVlmcjU1MUkzM0dMaEhua3o0ODNSOVZ5SStCb3Vpck1zN0xwc1h3TVloRk9Ka25uUGdDRkI2U3JnNW5MVVdaM1pWMHVVaFRlU2tTSUJ2aktDNSIsIml2UGFyYW1ldGVyU3BlYyI6IitKMnZRZFZlYm03YTFjWE8iLCJtYXRlcmlhbFNldFNlcmlhbCI6MX0%3D)
* [aws-lc-ci-linux-arm](https://us-west-2.codebuild.aws.amazon.com/project/eyJlbmNyeXB0ZWREYXRhIjoiK01DTkN6dHhJZEpPU240c0xTM2IyTTg4R1dwTHRKRFRMb05DOGtHZTJ0NkpHNWI5TE1mUTV5U …
=> CodeBuild project public artifacts

README.md, tests/ci/README.md
* Add section on platform support to our README
* Cleanup spacing in tables in CI README
=> Add platform support section to README

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
Preparing release of AWS-LC-FIPS-2.0.8.
* (Pending a rebase onto) #1461
=> FIPS 2.0.8 release version number update

tests/ci/integration/run_sslproxy_integration.sh
We updated our SSL Proxy patching strategy with https://github.com/aws/aws-lc/commit/1196b6cb1d55502b313642ef7f89eaad98ff02ac, so the reminders aren't needed anymore.
If our session format is ever updated, the SSL Proxy integration CI will fail and we can update correspondingly.
Relying on SSL_Session formats across different versions is not expected behavior, this is only to satisfy SSL Proxy integration tests.
=> Remove SSL Proxy API version update reminders

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
Preparing release of AWS-LC-FIPS-2.0.9.
* #1489 
* #1485
=> FIPS 2.0.9 release version number update

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
N/A
Bump the release version number string to 1.23.0
=> Bump the release version number string to 1.23.0

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
=> Bump to v1.24.0

tests/ci/integration/python_patch/3.12/aws-lc-cpython.patch, tests/ci/integration/python_patch/main/aws-lc-cpython.patch
This is in light of upstream [PR 117234#][1] being merged.
[1]: https://github.com/python/cpython/pull/117234
We'll need to adjust the 3.12 patch as well if/when the cpython change is backported.
- CI tests
=> Fix python CI patches

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
=> Bump to v1.24.1

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
Bump version to AWS-LC v1.25.0
=> AWS-LC v1.25.0

.github/workflows/actions-ci.yml
* Expend CI coverage to all supported GH MacOS runner types.
=> CI for other MacOS versions

tests/ci/integration/run_ntp_integration.sh, tests/ci/integration/tpm2_tss_patch/aws-lc-tpm2-tss.patch
=> Fix CI - tpm2-tss and ntp

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
=> Prepare for release v1.27.0

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
=> Prepare for release v1.28.0

fuzz/CMakeLists.txt
* Add build target for compiling all fuzz tests
=> Add `all_fuzz_tests` build target

.github/workflows/aws-lc-rs.yml
* Pin to a working Rust nightly toolchain.
=> Pin aws-lc-rs integ to nightly-2024-05-22

.github/workflows/windows-alt.yml, crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
* Prepare for v1.29.0 release.
=> Prepare for release 1.29.0

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
=> Prepare for release v1.30.0

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
AWS-LC-FIPS-2.0.13 release preparation
=> AWS-LC-FIPS-2.0.13 release preparation

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
=> Prepare for release v1.30.1

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
[Draft release](https://github.com/aws/aws-lc/releases/edit/untagged-11ac3412a1f5ec7633c3)
=> Prepare for release v1.31.0

tests/ci/integration/tpm2_tss_patch/aws-lc-tpm2-tss.patch
Resolves V1447930622
* Update patch for tpm2-tss 
=> Update patch for tpm2-tss

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
AWS-LC-FIPS-2.0.14 release preparation
=> AWS-LC-FIPS-2.0.14 release preparation

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
Preparing for AWS-LC v1.32.0 release.
=> Prepare release v1.32.0

crypto/kyber/pqcrystals_kyber_ref_common/verify.c, crypto/ml_kem/ml_kem_ipd_ref_common/verify.c
N/A
Fix cmov implementation in ML-KEM/Kyber to use our built-in constant-time functions.
=> Fix cmov implementation in ML-KEM/Kyber

.github/workflows/actions-ci.yml, .github/workflows/aws-lc-rs.yml, .github/workflows/codecov-ci.yml, .github/workflows/cross-test.yml, .github/workflows/go.yml, .github/workflows/integrations.yml, .github/workflows/opensslcomparison.yml, .github/workflows/windows-alt.yml
no issue is filed
cosmetic CI speedup. 1-2 sec for each job
=> CI: speed up GHA package manipulation by skipping some feeds

crypto/hmac_extra/hmac_test.cc
=> Resolve useless_type_qualifier_on_return_type in hmac_test.cc

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
https://github.com/aws/aws-lc/releases/tag/untagged-568f71655be03bb3d9e7
=> Prepare for the 1.34.0 release

crypto/ml_kem/ml_kem_ipd_ref_common/indcpa.c
CryptoAlg-2619
In this PR we made a small change that transitions the ML-KEM
implementation from the Initial Public Draft (IPD) to the final ML-KEM
as defined in FIPS 203: https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.203.pdf.
The only change needed was the domain separation in key generation.
This required updated KATs as well. The new KATs were obtained from:
https://github.com/post-quantum-cryptography/KAT/pull/15,
and converted to the form AWS-LC expects.
In as subsequent PR we'll rename all functions/folders/identifiers
to drop the "ipd" suffix.
*python script used for KATs conversion:
```
import sys
if len(sys.argv) != 2:
print("Usage: python convert.py <filename>")
sys.exit(1)
filename = sys.argv[1]
all_groups = []
try:
with open(filename, 'r') as file:
group = {}
for line in …
```
=> ML-KEM-IPD to ML-KEM as defined in FIPS 203

.gitignore, tests/ci/lambda/Cargo.lock, tests/ci/lambda/src/bin/purge-stale-builds.rs
Resolves P149524833
* Fix our CodeBuild Purge Lambda
=> Fix GitHub/CodeBuild Purge Lambda

crypto/fipsmodule/service_indicator/service_indicator_test.cc
Addresses CryptoAlg-2622
@nebeid noticed we were missing some coverage here.
- n/a
- CI
- 
---
=> Add EVP_Digest one-shot test XOFs

tests/ci/run_analytics.sh
We stopped shipping debug symbols with the release build, but we know some customers use the debug build and also care about the size. 
We never used the per object file data and it takes a lot of time to generate all of those metrics and cost to store them so just remove them.
Ran script locally with put_metric updated to be a no-op.
=> Begin tracking RelWithDebInfo library statistics

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
* Prepare for release v1.36.0.
=> Prepare release v1.36.0

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
* Set version to AWS-LC-FIPS v3.0.0
=> AWS-LC-FIPS v3.0.0

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
* Prepare release AWS-LC v1.36.1.
=> Prepare release 1.36.1

crypto/fipsmodule/ec/ec_test.cc
=> P159598331 coverity cleanup

crypto/evp_extra/evp_extra_test.cc, crypto/fipsmodule/evp/evp_ctx_test.cc
=> P161732527 coverity cleanup

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
=> Prepare v2.0.17 release

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
Bump version number to prepare 1.37.0
=> Prepare 1.37.0 release

crypto/dh_extra/dh_test.cc
P162820196
Could theoretically be null I suppose.
=> Add null check in dh testing

crypto/evp_extra/evp_extra_test.cc, crypto/evp_extra/p_dh.c
Resolves CryptoAlg-2696
* Add support for callbacks in DH paramgen
* EVP_PKEY_paramgen uses the same setup for callbacks as EVP_PKEY_keygen: https://docs.openssl.org/3.0/man3/EVP_PKEY_keygen/
=> DH paramgen callback

util/all_tests.go
* Add back "p4p" testing.
* Increase timeout for test.
* Clarify error message.
=> Add p4p, bump up time

crypto/fipsmodule/FIPS.md
=> Fix FIPS.md typo

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
Prepare release AWS-LC v1.39.0
=> Prepare release AWS-LC v1.39.0

crypto/evp_extra/evp_extra_test.cc, crypto/evp_extra/p_dsa_asn1.c
Addresses: P169046023
* Improve error handling of some DSA (ASN1) functions.
* Improve handling of null returns in tests. 
=> Minor improvement to DSA (ASN1) + DSA Tests

PORTING.md
=> Document TLS Server Renegotiation Behavior

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
Changing version number
Draft Release link: https://github.com/aws/aws-lc/releases/edit/untagged-ae5cc4568c4ae25df7a3
=> Prepare for v1.40.0 release

crypto/fipsmodule/FIPS.md
Link FIPS.md to the security policies on the NIST website.
=> Link to NIST website

.github/workflows/aws-lc-rs.yml
* Update the aws-lc-rs bindings generation CI check.
* Depends on: aws/aws-lc-rs#640
=> Fix CI for aws-lc-rs

.github/workflows/integrations.yml, tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml
Migrate the following jobs from `integrations.yml` to CodeBuild:
- `haproxy`
- `trousers`
- `ntp`
=> Migrate 1st batch of jobs

.github/workflows/integrations.yml
=> Fix tpm2-tss CI job

util/fipstools/acvp/acvptool/testmodulewrapper/testmodulewrapper.go
The testmodulewrapper is used to test ACVP things that the real modulewrapper doesn't support due to lack of support in libcrypto. We have added [XTS](https://github.com/aws/aws-lc/blob/main/util/fipstools/acvp/modulewrapper/modulewrapper.cc#L314-L322) and [KDF](https://github.com/aws/aws-lc/blob/main/util/fipstools/acvp/modulewrapper/modulewrapper.cc#L1152-L1195) to the modulewrapper and no longer need to test them here. 
Removed code, existing tests pass.
=> Remove algorithms from testmodulewrapper that are now used in the real modulewrapper

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
=> Prepare release v1.42.0

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
=> Prepare AWS-LC v1.43.0

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
=> Prepare AWS-LC v1.44.0

tests/ci/cdk/cdk/ecr_stack.py, tests/ci/cdk/util/iam_policies.py
Validated the YAML output with `cdk synth`.
=> Fix policy grant on ECR resource policy

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
=> Prepare AWS-LC v1.45.0

tests/ci/integration/nginx_patch/aws-lc-nginx.patch
Updating patch for nginx build 
=> Fix Nginx build

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
=> Prepare release v1.46.0

.github/workflows/integrations.yml, tests/ci/integration/run_libssh2_integration.sh
* Integration test for Libssh2.
* I tried to setup the tests to run in CodeBuild, but they fail due to the docker commands not being available.
=> Integration test for libssh2

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
=> Bump version, preparing for release v1.47.0

.github/workflows/cmake.yml
* Test our build with CMake v4.0.
=> Test build with CMake v4.0

.clang-tidy, .github/workflows/clang-tidy-post.yml, .github/workflows/clang-tidy-review.yml
* No more "Looks good to me!" comments.
* Update to latest action version.
* Add a few more lints.
=> Tweaking clang-tidy config

crypto/fipsmodule/rand/rand_isolated_test.cc
Extend test cases for randomness generation under process forks. Added two:
- Double fork process without intermediate randomness generation.
- Double fork process with intermediate randomness generation.
=> Extend fork test cases for randomness generation

.github/workflows/actions-ci.yml
=> Migrate jobs from ubuntu-20.04 to ubuntu-22.04

.github/workflows/actions-ci.yml
=> Test on 13.5 and 14.2 FreeBSD which are non-EOL, Fix Workflow

.github/workflows/misc-tests.yaml
=> Checkout full depth of repo for tag ci check to work on push events

.github/workflows/actions-ci.yml
=> GCC-10 & Clang-10 testing for Ubuntu-20.04 via container

tests/ci/integration/run_mysql_integration.sh
Resolves P226181810
Update MySQL integration test.
=> Fix CI - MySQL 2025-04

tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml
=> Enable IPv6 for curl integ

crypto/impl_dispatch_test.cc
ImplDispatchTest for 32-bit x86 architectures for SHA256 and AES-GCM
was not correct. The issue started manifesting itself when the CI
underlying hardware upgraded to a newer x86 CPU generation.
The fix is that the test shouldn't expect SHA and AES HW instructions
to be used for 32-bit x86 build.
=> Fix ImplDispatchTest for 32-bit x86 build

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
Bump version to 1.51.0. Needed for new APIs by https://github.com/aws/aws-lc/commit/995e1231539e3e1cd0c7d8f34c6fc0ac49b8755c
=> Bump to v1.51.0

.github/workflows/misc-tests.yml, crypto/fipsmodule/CMakeLists.txt
Fix prefix build when path has space.
* See CI results: https://github.com/aws/aws-lc-rs/pull/805
=> Fix prefix build when path has spaces

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
=> Prepare v1.51.2

crypto/bio/bio_socket_test.cc
P235969624
Just a few smaller fixes to the socket test:
* `sizeof(p)` returns the size of the operand type, which is a pointer.
* `type()` class function is unused.
* Explicit null-terminator for `buff` array
* `return OwnedSocket();` appeared twice.
=> Fix socket test issues

.clang-tidy
2 rules added back that are still valuable. 
=> Add back two rules for clang-tidy

crypto/bio/bio_socket_test.cc, tests/ci/gtest_util.sh
=> Fix CI for mingw

crypto/bio/bio_mem.c, crypto/bio/bio_test.cc
This reverts commit 5a748352b9a2a8685e959e2505e74ef053542201.
Our Ruby CI checks with 3.4-3.2 started failing with this commit. This reverts the commit until we know what's up.
* Working run in mainline: https://us-west-2.codebuild.aws.amazon.com/project/eyJlbmNyeXB0ZWREYXRhIjoicEtxdUl5RTdsWW95MmtnM0pSWjJmQU92T2RhQUJPN2VzRFdXZTdHOG1FWU1NQ2VwcGtucE92ZlA1Q3pSRHFCWW1VRTFLa3VTN1RWVC96dmsraFl5WXZwSmFha2tOTFZBOEdiWittVlRGKzlBVkRqVk5Gaz0iLCJpdlBhcmFtZXRlclNwZWMiOiJxS01SNWtSdUR0d2NvSUMvIiwibWF0ZXJpYWxTZXRTZXJpYWwiOjF9/batch/d9df5a0d-661f-4dd1-b99e-20c81db833d7
* Failing run: https://us-west-2.codebuild.aws.amazon.com/project/eyJlbmNyeXB0ZWREYXRhIjoicEtxdUl5RTdsWW95MmtnM0pSWjJmQU92T2RhQUJPN2VzRFdXZTdHOG1FWU1NQ2VwcGtucE92ZlA1Q3pSRHFCWW1VRTFLa3VTN1RWVC96dmsraFl5WXZwSmFha2tOTFZBOEdiWittVlRGKzlBVkRqVk5 …
=> Revert "Rework memory BIOs and implement BIO_seek (#2380)"

tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
Occasionally times out. So, bump the timeout a bit.
=> Increase Go timeout for the sanitizer dimension

crypto/bio/bio_mem.c
Remove a redundant check in memory BIO that Scrutinice caught.
=> [SCRUTINICE] Remove redundant condition check

crypto/fipsmodule/FIPS.md
Updates `FIPS.md` RNG section with new design.
No code was harmed in the making of this PR.
=> Update RNG FIPS documentation

.github/workflows/actions-ci.yml, crypto/bio/bio_mem.c, crypto/bio/bio_socket_test.cc, crypto/bio/bio_test.cc, crypto/bio/dgram.c, crypto/fipsmodule/rand/ctrdrbg.c, crypto/fipsmodule/rand/ctrdrbg_test.cc, crypto/fipsmodule/rand/internal.h, crypto/fipsmodule/service_indicator/service_indicator_test.cc, crypto/pkcs7/pkcs7_test.cc, crypto/test/test_util.cc, include/openssl/base.h, include/openssl/ctrdrbg.h, ssl/handshake.cc, tests/ci/run_posix_tests.sh, tool-openssl/x509.cc, tool-openssl/x509_test.cc, util/fipstools/delocate/delocate.go, util/fipstools/delocate/delocate_test.go, util/fipstools/delocate/testdata/x86_64-Relro/in.s, util/fipstools/delocate/testdata/x86_64-Relro/out.s
Feature branch update onto main e71557c73eff484df4063711228756c69b61dc23.
=> Update feature branch onto main e71557c73eff484df4063711228756c69b61dc23

.github/workflows/actions-ci.yml
Hardened build accidentally removed from CI.
=> Add hardened build back in

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
=> Prepare v1.53.1

crypto/bio/bio_addr.c
Re-apply removal: https://github.com/aws/aws-lc/pull/2461
=> Re-remove afunix.h

tests/ci/cdk/cdk/aws_lc_base_ci_stack.py
N/A
Temporarily allowlist the webhook actors to AWS-LC.
=> Temporarily allowlist the webhook actors to AWS-LC

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
Addresses [CPython PR 135402](https://github.com/python/cpython/pull/135402)
---
=> Prepare AWS-LC v1.55.0

crypto/bio/bio_mem.c, crypto/pem/pem_lib.c
P264515118
Axe redundant conditions that are always false.
=> Remove redundant conditions

tests/ci/cdk/cdk/aws_lc_base_ci_stack.py
Resolves P272674309
Add members of the aws-lc-contributor group to our CodeBuild allowlist
=> Add LC contributors to allowlist

crypto/fipsmodule/service_indicator/service_indicator_test.cc, include/openssl/base.h
=> Prepare AWS-LC v1.56.0

nix/devshell.nix
=> Fix nixfmt CI failure

CMakeLists.txt, include/openssl/base.h
=> Prepare release v1.58.1

.github/workflows/integrations.yml, tests/ci/integration/httpd_patch/2.4.65/0001-Support-AWS-LC.patch, tests/ci/integration/run_httpd_integration.sh
Add Apache httpd integration test to our CI.
=> Apache httpd integration test

crypto/fipsmodule/md5/asm/md5-armv8.pl, generated-src/ios-aarch64/crypto/fipsmodule/md5-armv8.S, generated-src/linux-aarch64/crypto/fipsmodule/md5-armv8.S, generated-src/win-aarch64/crypto/fipsmodule/md5-armv8.S
Addresses https://github.com/aws/aws-lc/issues/2459
Continuation of the changes from https://github.com/aws/aws-lc/pull/2584. 
Before:
After:
=> Add CFI directives in md5-armv8.pl

CMakeLists.txt, include/openssl/base.h
=> Prepare release v1.59.0

.github/workflows/misc-tests.yml, third_party/jitterentropy/CMakeLists.txt
=> Fix build when path has spaces
