- README.md
You shouldn't need `sudo` to run `wget`.
> docs: no sudo wget

- cmake/apply-quilt-patches.cmake
- tests/check_licenses.go
N/A
This re-enables a step in `check_licenses.go` that fails if a copyright header is missing.
This change also adds a missing copyright header to `apply-quilt-patches.cmake`
This was tested locally by removing a copyright header from a file (cmake/awslc-config.cmake) and running `check_licenses.go`:
```
go run ./tests/check_licenses.go
```
This resulted in:
```
cmake/awslc-config.cmake is missing a copyright header
panic: FAILED Copyright Check
```
> Have check fail if copyright header is missing

- tests/ci/cdk/cdk/github_codebuild_stack.py
Resolves CryptoAlg-533
This PR updates CDK CodeBuild timeout to provide enough time for ARM sanitizer test. 
N/A
* `cdk synth`
* `cdk deploy aws-lc-test-ubuntu-19-10--clang-9x--sanitizer`
* Timeout of the CodeBuild is changed to 2 hours now. Before this deployment, the timeout was set to 5 hours manually.
> Increase ARM CodeBuild timeout.

- patches/0012-replace-boringssl-api-version-macro.patch
- patches/series
Resolves CryptoAlg-413
This PR replaces BORINGSSL_API_VERSION with AWSLC_API_VERSION to avoid users interpreting AWSLC as BoringSSL.
N/A.
See CIs.
> Replace BORINGSSL_API_VERSION with AWSLC_API_VERSION.

- docs/Coverage.md
N/A
This adds instructions to generate a user friendly HTML report using existing CMake config and tools.
None
Ran the steps locally on an Ubuntu 18.04 host and verified it worked.
> Add documentation explaining how to generate a code coverage report.

- patches/0007-extend_evp_pkey_tls_encoding_functions.patch
N/A
The patch file 007 does not have new line ending. When `patch push -av` command is executed, some warnings are print out.
Fix or not does not affect functionality but current code generates unnecessary warnings.
See CI.
> Fix patch warning.

- tests/ci/run_posix_sanitizers.sh
Addresses CryptoAlg-558
[BoringSSL provides two sets tests: the C/C++ tests and the blackbox tests.](https://github.com/google/boringssl/blob/master/BUILDING.md) The blackbox tests (run `go test` under `ssl/test/runner`) takes at least 30 minutes to complete on ARM when ASAN clang flag enabled. This does not happen on X86 ASAN and ARM (when ASAN disabled).
This PR is to disable the blackbox tests when ARM ASAN clang flag is enabled.
With this change, the whole CI will be able to complete with 15 minutes (decreased from 45 minutes).
AWS-LC currently only aims to provide crypto related functionality. The blackbox tests are ssl specific. So I think this disabling is ok because it dramatically reduces the time waiting for CI complete.
TBD.
See CI.
> Disable ARM ASAN blackbox tests.

- patches/0013-p256-armv8-optimizations
- patches/series
CryptoAlg-573
Continuing on top of [PR#52](https://github.com/awslabs/aws-lc/pull/52), this is the second assembly function needed to support the optimized implementation of P-256, nistz256, to be used on ARMv8 as it is currently used only with x86_64.
* This PR would be merged on top of [PR#52](https://github.com/awslabs/aws-lc/pull/52/).
* C code duplication continued in this change. This is only transient so that the assembly functions are added and tested gradually. The code duplication will be removed in subsequent PR(s).
* The test for that function was enabled in `p256-x86_64_test.cc` by this change.
* Tested on M6g (ARMv8) and M5a (x86_64) instances, as well as on a MacBook (x86_64).
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> Implement ARMv8 PerlAsm of ecp_nistz256_select_w7

- patches/0013-p256-armv8-optimizations
CryptoAlg-591
Remove C code duplication in p256.c for ARMv8 nistz256
Instead the C code in `p256-x86_64.[h,c]` is now used with bothx86_64 and AArch64 (ARMv8).
The code duplication was done in order to support gradual experimentation and development of ARMv8 P-256 optimization as in PRs 52, 56 and 57. In those PRs, the C functions that called Assembly functions were copied, few at a time, to `p256.c` to test the ARM assembly functions, one or more at a time.
In subsequent PRs, the files names will be changed, preferably after merging to main, so we have commits with the original name for ease of reference.
Tested on x86_64 (Macos) and ARMv8 (Graviton2).
> CryptoAlg-591: Remove C code duplication in p256.c for ARMv8 nistz256

- patches/0013-p256-armv8-optimizations
CryptoAlg-587
- Makes P-256 optimizations (nistz256) disabled by default.
- They can be enabled by running (under a newly-created build directory):
```
$ cmake -DOPENSSL_AARCH64_P256=1 -DCMAKE_BUILD_TYPE=Release -GNinja ..
```
- Added a CI test with -DOPENSSL_AARCH64_P256=1
Tested `cmake` with and without the new macro on ARMv8 instance
and ran the speed tests, which showed the expected difference.
> CryptoAlg-587: OPENSSL_AARCH64_P256 enables P-256 ARM optimisations

- tests/ci/cdk/app.py
env info is not passed to stack. This prevents CDK from creating resources in target AWS region. This was missed when migrating to batch build spec.
This PR passed env info to each stack so resources can be created in target AWS region (passed by `CDK_DEPLOY_REGION` env variable).
N/A
Resources are created after running below command.
```
./run-cdk.sh xxxxxx eu-west-3 bryce-shang aws-lc DEPLOY
```
> Pass env to stack.

- ssl/ssl_test.cc
Addresses CryptoAlg-534
This change disables the parameterized test DefaultTicketKeyInitialization which has been failing in our CI. The fix is being investigated in CryptoAlg-534 and in the mean time to reduce interruptions we're turning it off. This is safe for two reasons:
1. The libssl portion of AWS-LC should not be used, it is only kept for testing
2. It only fails in Docker which leads us to believe it is an issue with our CI setup and not AWS-LC
Before:
```
./ssl/ssl_test --gtest_filter='*DefaultTicketKeyInitialization*'
Note: Google Test filter = *DefaultTicketKeyInitialization*
[==========] Running 6 tests from 1 test suite.
[----------] 6 tests from WithVersion/SSLVersionTest
[ RUN      ] …
```
> Temporarily turn off DefaultTicketKeyInitialization

- tests/ci/cdk/app.py
- tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
- util/all_tests.go
CryptoAlg-578
This PR is to re-enable `urandom_test`.
* `Running CodeBuild with least privilege -- seccomp` seems not supported. A feature request ticket (see CryptoAlg-578) has been cut to AWS CodeBuild.
* CI set up in my personal account has priviledged mode enabled and ran on branch `urandom_test`. Test links are available in CryptoAlg-578.
> Enable urandom_test and CodeBuild priviledge mode.

- CMakeLists.txt
- crypto/cipher_extra/aead_test.cc
- tests/ci/README.md
- tests/ci/cdk/cdk/codebuild/github_ci_linux_arm_omnibus.yaml
- tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
- tests/ci/codebuild/linux-aarch/amazonlinux-2_gcc-7x_valgrind.yml
- tests/ci/codebuild/linux-x86/amazonlinux-2_gcc-7x_valgrind.yml
- tests/ci/common_posix_setup.sh
- tests/ci/docker_images/linux-aarch/amazonlinux-2_gcc-7x/Dockerfile
- tests/ci/docker_images/linux-x86/amazonlinux-2_gcc-7x/Dockerfile
- tests/ci/run_valgrind_tests.sh
- tests/ci/valgrind_suppressions_crypto_test.supp
- util/all_tests.go
- util/all_tests.json
- util/testconfig/testconfig.go
- util/whitespace.txt
CryptoAlg-597
This PR adds a Valgrind test target to the CI.
The target is implemented for AL2 x86 and Arm. Only x86 is currently enabled in the CI due to the Arm tests hitting the 2 hour time out limit in Codebuild (track resolution in CryptoAlg-597).
The only unit test suite that is run is `crypto_test`. The reason is that it takes +1 hour for only this test suite.
Valgrind picked up an uninitialised memory usage that is also fixed as part of this PR. See change in `aead_test.cc`.
Tested on a replica of the CI in my personal account.
It also running now in the CI.
>  Add Valgrind target to CI

- crypto/fipsmodule/ec/p256-nistz_test.cc
Addresses CryptoAlg-560
Below errors are reported when compiled with MSVC. This PR fixed the compile errors by replacing `__attribute__((aligned(64)))` with [`alignas`](https://en.cppreference.com/w/cpp/language/alignas). The ARM platform using gcc (6 - 7) will continue with `__attribute__((aligned(64)))` due to [gcc bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57271).
```
0 -wd4820 -wd5026 -wd5027 -wd5045  -w44265 /MD /O2 /Ob2 /DNDEBUG /showIncludes /Focrypto\CMakeFiles\crypto_test.dir\fipsmodule\ec\p256-nistz_test.cc.obj /Fdcrypto\CMakeFiles\crypto_test.dir\ /FS -c ..\crypto\fipsmodule\ec\p256-nistz_test.cc
..\crypto\fipsmodule\ec\p256-nistz_test.cc(44): error C3861: 'aligned': identifier not found
..\crypto\fipsmodule\ec\p256-nistz_test.cc(44): error C3861: '__attribute__': …
```
> Fix MSVC compile error - C3861.

- CMakeLists.txt
- crypto/fipsmodule/sha/asm/sha512-x86_64.pl
- crypto/impl_dispatch_test.cc
- include/openssl/cpu.h
- tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
- tests/ci/cdk/run-cdk.sh
- tests/ci/codebuild/linux-x86/amazonlinux-2_gcc-7x_intel-sde.yml
- tests/ci/common_posix_setup.sh
- tests/ci/docker_images/linux-x86/amazonlinux-2_gcc-7x-intel-sde/Dockerfile
- tests/ci/docker_images/linux-x86/build_images.sh
- tests/ci/docker_images/linux-x86/push_images.sh
- tests/ci/run_tests_with_sde.sh
This change enables the implementation of SHA-256/512 with
SHA extension instruction set on x86 platforms.
Signed-off-by: Kostic <dkostic@amazon.com>
Addresses CryptoAlg-599.
This change enables the implementation of SHA-256/512 with
SHA extension instruction set on x86 platforms.
The change should not be merged before it is ensured that the CI is running
code tests for all the possible CPU platforms. See CryptoAlg-622.
See call-outs.
> Enable the SHA extension implementation of SHA-256/512 on x86

- BUILDING.md
- CMakeLists.txt
- crypto/fipsmodule/ec/asm/p256-armv8-asm.pl
- tests/ci/run_posix_tests.sh
- util/asm_dev/armv8/p256/Makefile
- util/asm_dev/armv8/p256/src/beeu.S
- util/asm_dev/armv8/p256/src/main.c
- util/asm_dev/armv8/p256/src/select.S
Resolves CryptoAlg-629
This PR addresses the [comments](https://github.com/awslabs/aws-lc/pull/67#pullrequestreview-555043259) from @sebpop on the assembly functions developed to support ARMv8-optimized P-256 implementation.
- Removed the prefetch instruction from select_w7 to
> let the processor figure out the memory access pattern: in this case it is linear access which is very easy to predict.
This will reduce code size for the loop and it will reduce execution time by not having to decode the instruction.
There was a noticeable small improvement in the performance of ECDSA sign (0.6%) and ECDH (0.2%) where multiplying by the base point is employed. It's more noticeable in ECDSA sign than ECDH since multiplication by the base point dominates ECDSA sign operation, but is only the first …
> CryptoAlg-629: Remove prefetch from select_w7

- tests/ci/docker_images/linux-x86/amazonlinux-2_gcc-7x/Dockerfile
Scrutinice has some analysis script using `which` command. The command is not installed by default in AL2.
This PR installs 'which' in AL2.
I will build this image when working on gcc10 build task. This image change is not needed by external CI.
Internal scrutinice build.
> Install 'which' in AL2.

- crypto/fipsmodule/rsa/padding.c
- include/openssl/rsa.h
Addresses CryptoAlg-614
This PR imports `RSA_PSS_SALTLEN_DIGEST` from [OpenSSL 1.1.1](https://github.com/openssl/openssl/commit/137096a7ead3738a0035b9e760b7c3f74b7555a3) to support s2n usage.
The macro means the salt length must equal the length of hash function output. This macro is the most common usage mentioned in standards. 
* Other RSA_PSS_SALTLEN macros (`RSA_PSS_SALTLEN_AUTO` and `RSA_PSS_SALTLEN_MAX`) are not imported currently because these may need additional investigation on this [OpenSSL commit](https://github.com/openssl/openssl/commit/137096a7ead3738a0035b9e760b7c3f74b7555a3) . Besides, BoringSSL has one [TODO](https://github.com/awslabs/aws-lc/blob/main/crypto/x509/rsa_pss.c#L201-L203) to forbid the auto mode.
* I will keep all CryptoAlg-614 code in  `rsa-pss` branch and …
> Define RSA_PSS_SALTLEN_DIGEST macro.

- crypto/x509/x509_cmp.c
CryptoAlg-657
This is a fix for CVE-2021-23841
More details in: https://www.openssl.org/news/secadv/20210216.txt
> Improvement for CVE-2021-23841

- crypto/fipsmodule/cipher/cipher.c
- include/openssl/cipher.h
CVE-2021-23840
(Imported from upstream's 6a51b9e1d0cf0bf8515f7201b68fb0a3482b3dc1.)
This differs slightly from upstream's version:
- EVP_R_OUTPUT_WOULD_OVERFLOW didn't seem necessary when ERR_R_OVERFLOW
already exists. (Also since we use CIPHER_R_*, it wouldn't have helped
with compatibility anyway. Though there's probably something to be
said for us folding CIPHER_R_* back into EVP_R_*.)
- For simplicity, just check in_len + bl at the top, rather than trying
to predict the exact number of bytes written.
Update-Note: Passing extremely large input lengths into EVP_CipherUpdate
will now fail. Use EVP_AEAD instead, which is size_t-based and has more
explicit output bounds.
Change-Id: I31835c89dcdecb6b112828f57deb798dc7187db5
Reviewed-on: …
> Don't overflow the output length in EVP_CipherUpdate calls.

- tests/ci/run_s2n_integration.sh
N/A
This PR changes s2n repo from https://github.com/awslabs/s2n.git to https://github.com/aws/s2n-tls
N/A
Tested in personal account. See CI
> Change s2n GitHub repo.

- crypto/bytestring/cbs.c
- crypto/cpu-intel.c
- crypto/err/err.c
- crypto/fipsmodule/rand/fork_detect_test.cc
- crypto/obj/obj.c
- crypto/x509/a_strex.c
- include/openssl/bn.h
- ssl/test/bssl_shim.cc
- util/asm_dev/armv8/p256/src/beeu_scratch.c
- util/asm_dev/armv8/p256/src/main.c
Resolves: CryptoAlg-672
On older systems supported by aws-c-cal, gcc 4.8.2, we run into compilation errors when building our test code.  It turns out that some of the defines in inttypes are only defined if you specify __STDC_FORMAT_MACROS before including inttypes.h.  
The change is very simple, add the __STDC_FORMAT_MACROS to each include to ensure it's always defined.  
```
/root/aws-c-cal/build/deps/aws-lc/ssl/test/bssl_shim.cc: In function bool CheckHandshakeProperties(SSL*, bool, const TestConfig*):
/root/aws-c-cal/build/deps/aws-lc/ssl/test/bssl_shim.cc:659:45: error: expected ) before PRId32
fprintf(stderr, "Ticket age skew was %" PRId32 ", wanted %d\n",
^
/root/aws-c-cal/build/deps/aws-lc/ssl/test/bssl_shim.cc:660:73: error: spurious trailing % in format [-Werror=format=] …
```
> Wrapping all <inttypes.h> includes with __STDC_FORMAT_MACROS

- CMakeLists.txt
Resolves: CryptoAlg-671
When integrating with [aws-c-cal](https://github.com/awslabs/aws-c-cal) in this [PR](https://github.com/awslabs/aws-c-cal/pull/65), `aws-lc` fails to build in a 32-bit container running on a 64-bit host. This is because `CMAKE_SYSTEM_PROCESSOR` returns the architecture of the host and, as a result, assembly files meant for 64-bit were being included. This expands to check `CMAKE_SIZEOF_VOID_P` for either `x86` or `x86_64` and update `ARCH` accordingly.
We do not currently have a dimension in our CI that tests this behavior, but this will be added in the work for CryptoAlg-663.
> Expand ARCH check to use CMAKE_SIZEOF_VOID_P for x86 and x86_64

- tests/ci/docker_images/linux-x86/README.md
- tests/ci/docker_images/linux-x86/aws-crt/aws-crt-common.sh
- tests/ci/docker_images/linux-x86/common.sh
- tests/ci/docker_images/linux-x86/pull_github_pkg.sh
- tests/ci/docker_images/linux-x86/push_images.sh
Addresses CryptoAlg-663
This PR adds scripts to pull aws crt Docker images from `docker.pkg.github.com`.
Next PR https://github.com/awslabs/aws-lc/pull/103 will integrate the scripts with CI setup code.
```sh
GITHUB_READ_PKG_ACCESS_TOKEN=xxx
./pull_github_pkg.sh
ECS_REPO="654358955777.dkr.ecr.us-west-2.amazonaws.com/aws-lc-docker-images-linux-x86"
$(aws ecr get-login --no-include-email)
source ./aws-crt/aws-crt-common.sh
push_aws_crt_docker_img
```
> Pre-pull aws crt Docker images.

- CMakeLists.txt
- crypto/CMakeLists.txt
- crypto/bio/socket.c
- ssl/test/CMakeLists.txt
- ssl/test/bssl_shim.cc
- tool/transport_common.cc
Previously, MSVC specific pragma comment are used to link with ws2_32 library.
But those does not work with MinGW gcc and clang. Hence, use CMake's own
target_link_libraries() to link with ws2_32 for Win32 platform conditionally.
> CMake: Fix linking with compiler other than MSVC.

- tests/ci/cdk/app.py
- tests/ci/cdk/cdk/aws_lc_github_ci_stack.py
- tests/ci/cdk/cdk/codebuild/github_ci_linux_arm_omnibus.yaml
- tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
- tests/ci/cdk/cdk/codebuild/github_ci_windows_x86_omnibus.yaml
- tests/ci/cdk/cdk/linux_docker_image_batch_build_stack.py
- tests/ci/cdk/cdk/windows_docker_image_build_stack.py
- tests/ci/cdk/util/iam_policies.py
Resolves CryptoAlg-674
This PR scopes down permissions of IAM role used by AWS CodeBuild. The major change is to replace [AmazonEC2ContainerRegistryReadOnly](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr_managed_policies.html#AmazonEC2ContainerRegistryReadOnly) with below iam permission (more restricted).
```json
{
"Version": "2012-10-17",
"Statement": [
{
"Action": [
"ecr:BatchCheckLayerAvailability",
"ecr:GetDownloadUrlForLayer",
"ecr:BatchGetImage"
],
"Resource": "arn:aws:ecr:us-west-2:xxxxxx:repository/aws-lc-docker-images-linux-x86",
"Effect": "Allow"
}
]
}
```
* No other changes (including FILE_PATH) planned. FILE_PATH may stop CI running when files under tests dir get changed.
* CryptoAlg-674?selectedConversation=3af70d1d-3676-4ca7-ac2a-b0a7f41773ff …
> Scope down IAM role permissions.

- CMakeLists.txt
- crypto/CMakeLists.txt
- decrepit/CMakeLists.txt
- ssl/CMakeLists.txt
- util/all_tests.go
N/A
With this change AWS-LC will no longer build test targets or libssl if `-DBUILD_TESTING=OFF` and `-DBUILD_LIBSSL=OFF` are specified. By default, all tests and libssl will still be built.
Setting both of these options to `OFF` also disables the CXX language when building.
Build succeeds when `BUILD_TESTING=OFF` is specified, and all tests pass when this flag is not provided. When `BUILD_LIBSSL=OFF` and `BUILD_TESTING` is not specified, all tests pass and `ssl_test` is excluded.
> Add support for BUILD_TESTING and BUILD_LIBSSL

- tests/ci/cdk/README.md
- tests/ci/cdk/cdk/linux_docker_image_batch_build_stack.py
- tests/ci/cdk/run-cdk.sh
- tests/ci/cdk/util/iam_policies.py
- tests/ci/cdk/util/metadata.py
- tests/ci/codebuild/linux-x86/docker-img-build.yml
- tests/ci/docker_images/linux-x86/README.md
- tests/ci/docker_images/linux-x86/aws-crt/aws-crt-common.sh
- tests/ci/docker_images/linux-x86/common.sh
- tests/ci/docker_images/linux-x86/pull_github_pkg.sh
- tests/ci/docker_images/linux-x86/push_images.sh
Addresses CryptoAlg-663
This PR integrated the script created in https://github.com/awslabs/aws-lc/pull/102 with CDK code.
* The new change assumes CodeBuild and SSM runCommand result success status can indicate all images are pushed to ECR instead of checking images with `aws ecr`.
* To provide the script with GitHub access token, the major change of this PR is to store the token in SecretsManager.
* To pass the token to `run-cdk.sh` script, arguments parser are refactored.
* Pre-requisite: https://github.com/awslabs/aws-lc/pull/102
* The tests have disabled Ubuntu 19.10 Docker Image Build, which cannot be pulled due to `No support`. 
See log in `CryptoAlg-663?selectedConversation=33d3e3af-a5b5-4e5d-b78f-b4f49b8e250a`
By submitting this pull request, I confirm that my contribution is …
> Integrate pull script with CDK.

- tests/ci/README.md
- tests/ci/cdk/README.md
- tests/ci/cdk/app.py
- tests/ci/cdk/cdk/aws_lc_github_ci_stack.py
- tests/ci/cdk/cdk/aws_lc_github_fuzz_ci_stack.py
- tests/ci/cdk/cdk/codebuild/github_ci_fuzzing_omnibus.yaml
- tests/ci/cdk/run-cdk.sh
- tests/ci/cdk/util/ecr_util.py
- tests/ci/cdk/util/iam_policies.py
- tests/ci/codebuild/linux-x86/run_fuzz_tests.yml
- tests/ci/common_fuzz.sh
- tests/ci/common_posix_setup.sh
- tests/ci/docker_images/linux-aarch/ubuntu-20.04_base/Dockerfile
- tests/ci/docker_images/linux-x86/ubuntu-20.04_base/Dockerfile
- tests/ci/run_fuzz_tests.sh
- tests/ci/run_posix_sanitizers.sh
- tests/ci/run_posix_tests.sh
Resolves CryptoAlg-651
This adds 2 new CI targets: running the existing fuzz tests on ARM and x86. This uses EFS to store the shared and minimized corpus. 
Other changes:
* Cleanup common test directories and set common bash flags
* Add -u to check for unset variables, also update existing checks for variables to handle this
* Remove the pull image permission from the CodeBuild roles, we grant permission to the CodeBuild service principal already
I have not deployed this change to the CI account. I can walk you through the changes in my account.
> Add configuration to build and run existing Fuzz tests in our CI

- tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
- tests/ci/cdk/run-cdk.sh
- tests/ci/common_posix_setup.sh
- tests/ci/run_fips_tests.sh
Addresses CryptoAlg-723
This PR added FIPS shared builds on x86 platform.
Some minor changes of this PR include
* Add comment for AL2 Clang FIPS build.
* Validate GitHub access token when building Docker image.
* Check FIPS mode by running `tool/bssl isfips`.
* FIPS Shared release build on x86 Gcc-7x is disabled. I will make additional investigation on the build error.
* CI
> Add FIPS shared builds on x86 platform.

- tests/ci/README.md
- tests/ci/cdk/cdk/codebuild/github_ci_fuzzing_omnibus.yaml
- tests/ci/cdk/cdk/codebuild/github_ci_windows_x86_omnibus.yaml
- tests/ci/docker_images/build_cryptofuzz_modules.sh
Resolves Cryptofuzz ARM failures due to this issue and latest Windows Docker container issue.
Cryptofuzz previously required changes from BoringSSL not yet merged into AWS-LC. With the recent merge we can use the latest version again.
This change also uses the older tag of our Windows Docker image while we investigate why the latest built one is failing.
Built image into my personal account for testing and the main AWS-LC one.
> Fuzzing and Windows CI updates

- crypto/fipsmodule/ec/p384.c
- crypto/fipsmodule/ec/simple_mul.c
- crypto/fipsmodule/ec/wnaf.c
CryptoAlg-740
- This change appends the analysis of non-trivial doubling case when using the Joye_Tunstall recoding (AFRICACRYPT `09).
- Also Removed the commented lines with TBD in wnaf.c and simple_mul.c
so they continue to call the underlying algorithms from EC_METHOD and not from ec_montgomery.c
- Fixed few typos.
- This analysis can be moved to util.c if the recoding is used
with other curves than P-384 and is made generic in the size of w.
The attached python script tests the values mentioned in this analysis.
[JTrecoding.py.txt](https://github.com/awslabs/aws-lc/files/6352488/JTrecoding.py.txt)
> CryptoAlg-740: Adding the doubling case analysis in p384.c

- crypto/fipsmodule/ec/asm/p256-armv8-asm.pl
- generated-src/ios-aarch64/crypto/fipsmodule/p256-armv8-asm.S
- generated-src/linux-aarch64/crypto/fipsmodule/p256-armv8-asm.S
- generated-src/win-aarch64/crypto/fipsmodule/p256-armv8-asm.S
- tests/ci/cdk/cdk/codebuild/github_ci_linux_arm_omnibus.yaml
- util/fipstools/delocate/README.md
- util/fipstools/delocate/delocate.go
- util/fipstools/delocate/delocate.peg
- util/fipstools/delocate/delocate.peg.go
Resolves CryptoAlg-725
This PR added FIPS aarch build dimensions to awslc CI.
* Unlike x86 FIPS build, gcc7x is not planned to be in FIPS POC scope.
* Related reference -- `CryptoAlg-723?selectedConversation=e0c5b7c9-60f5-4d30-a496-f5f8dbc711cd` 
* The first two code commits were reviewed.
* CI set up in personal account
* ~~CodeBuild request - `aws-lc-ci-linux-arm:db6724d9-5b22-4f6f-a429-c0b552eec1f9`~~
* This build failed because the test used default `go test` timeout, which is 10m.
* CodeBuild request - `aws-lc-ci-linux-arm:8f624494-6ea8-46e2-b337-1f924dc40d03`
> Add FIPS aarch POC build to CI.

- crypto/fipsmodule/rand/fork_detect.c
- crypto/fipsmodule/rand/fork_detect.h
- crypto/fipsmodule/rand/fork_detect_test.cc
- crypto/fipsmodule/rand/urandom_test.cc
- crypto/rand_extra/rand_test.cc
- util/all_tests.json
- util/whitespace.txt
CryptoAlg-727
AWS-LC currently has one fork detection mechanisms: `WIPEONFORK`. This PR implements an additional fork detection mechanism using the pthread library function `pthread_atfork`. Using this function, we can register a handler that is executed in the child after a fork call `fork()` that is used to flip a sentinel fork detection value. This change is intended to add defense-in-depth to the fork detection.
The code flow is roughly as follows:
* The fork detection is lazily initialised
* On first call: `init_fork_detect` is only called by the first thread entering it
* mmap a page that is acting as the sentinel informing whether a fork has occurred or not
* Initialise the two fork detection mechanisms
* If initialisation is successful, set the sentinel value to 1 (indicating no …
> Implements an additional fork detection mechanism: pthread_atfork

- CMakeLists.txt
- crypto/fipsmodule/ec/p256.c
- crypto/fipsmodule/ec/simple_mul.c
- crypto/fipsmodule/rand/rand.c
- crypto/fipsmodule/rsa/rsa_impl.c
- crypto/hrss/hrss.c
- crypto/poly1305/poly1305.c
- crypto/poly1305/poly1305_arm.c
- crypto/poly1305/poly1305_vec.c
- third_party/fiat/curve25519_64.h
- third_party/fiat/p256_64.h
Resolves CryptoAlg-626
This PR added a broader set of compile flags in `./CMakeLists.txt`.
Some compiler warnings are fixed in this PR:
* ISO C does not support ‘__int128’ types [-Werror=pedantic].
* The error was in the header file of the third-party lib `fiat`. The warning is suppressed by `__extension__`.
* Previous discussion: https://github.com/awslabs/aws-lc/pull/152#discussion_r633829479
* ISO C99 doesn’t support unnamed structs/unions [-Werror=pedantic].
* Added a name to the union.
* `-Wpedantic` is not enabled to avoid c99 warnings.
* One warning is `CryptoAlg-626?selectedConversation=763115b6-a861-42f9-9fa5-acea8cbcb825`. 
* CryptoAlg-759 is created to clarify if all code need to follow c99 spec.
* `-Wno-unused-parameter` is added instead of using `OPENSSL_UNUSED` because
* …
> Add a broader set of compile flags.

- third_party/fiat/curve25519_64.h
- third_party/fiat/p256_64.h
Addresses CryptoAlg-762
This fixes an issue with GCC 4.1.2 which has __int128_t and not __int128 which function the same. 
Manually tested with GCC 4.1.2 waiting to fix all issues before adding a build to our CI.
> Fix Fiat crypto 128 bit int type definitions to support older compilers

- crypto/asn1/asn1_lib.c
- include/openssl/asn1.h
Addresses CryptoAlg-760
This PR added `ASN1_STRING_clear_free`, which is [used by `aws-encryption-sdk-c` to free ASN1_INTEGERS](https://github.com/aws/aws-encryption-sdk-c/blame/f98243bd364fcea3e17dc07644275c7f22a0f433/source/cipher_openssl.c#L621-L622). 
* [OpenSSL 1.1.1 ASN1_STRING_clear_free has special treatment based on the macros(`ASN1_STRING_FLAG_NDEF` and `ASN1_STRING_FLAG_EMBED`)](https://github.com/openssl/openssl/blame/7fc0b9376135e9e5db76c713122a6e319c0b9768/crypto/asn1/asn1_lib.c#L336-L360). These macros are only set in `PKCS7_stream` and `asn1_primitive_new1`. These macro related features are not used by `aws-encryption-sdk-c` and not supported by awslc. Accordingly, https://github.com/awslabs/aws-lc/commit/9bdec296adba5e3891151ab4bcb8f7ebfcd1fc37 is not reverted.
* awslc …
> Add ASN1_STRING_clear_free.

- CMakeLists.txt
Addresses CryptoAlg-762
GCC 4.1.2 does not support all of these flags and causes builds to fail. Some flags are supported but create false positives that got fixed in later versions of GCC. This change keeps the current set of flags when building with reasonably modern compilers.
Manually tested with GCC 4.1.2 waiting to fix all issues before adding a build to our CI.
> Update CMakeLists.txt to correctly handle GCC 4.1.2 and set the flags it supports

- crypto/hrss/hrss.c
This helps resolves build issues for older versions of GCC.
For older versions of GCC like 4.1.2, there are errors when trying to access values of an `__m128i` type as well as errors related to unnamed union/struct.
This was manually tested on GCC 4.1.2
> Hrss fixes

- crypto/rand_extra/rand_test.cc
This test suite doesn't pass through any of the fork detection stuff. Removing that redundant call.
> Remove redundant call

- CMakeLists.txt
- crypto/compiler_test.cc
- tests/compiler_features_tests/memcmp_invalid_stripped_check.c
Addresses V378887705
This PR added `memcmp invalid strip check` to CMakeLists.txt.
TBD
> Add memcmp invalid strip check to CMakeLists.txt.

- crypto/fipsmodule/CMakeLists.txt
- crypto/fipsmodule/gcc_fips_shared.lds
- tests/ci/run_fips_tests.sh
Addresses CryptoAlg-723?selectedConversation=5bbdd8be-635b-434f-934f-ea9dfa6ac67a
This PR fixed FIPS gcc shared release build on x86.
* Next PR will include related CI change.
* `crypto/fipsmodule/gcc_fips_shared.lds` is copy from `crypto/fipsmodule/fips_shared.lds` because the gcc specific change is not needed by clang generated code.
```sh
./tests/ci/run_fips_tests.sh
```
> Fix FIPS gcc shared release build on x86.

- tests/ci/run_fips_tests.sh
Addresses CryptoAlg-806
This PR added new build flag 'RelWithDebInfo', which may be used as final FIPS option.
* ASAN build is time consuming. Accordingly, RelWithDebInfo with ASAN is not enabled.
> Add FIPS RelWithDebInfo build.

- tests/ci/common_fuzz.sh
Resolves P50460092
Previously the `cov` output of libfuzzer was sorted as a string which puts `999` ahead of `8000` which creates confusing reports. This will fix the dashboard for future data only. Past reports can be cleaned up manually if needed.
Tested locally sorting things.
> Sort the output of libfuzzer's cov as a number

- crypto/cipher_extra/asm/chacha20_poly1305_armv8.pl
Signed-off-by: Dusan Kostic <dkostic@amazon.com>
Old versions of Perl don't know how to evaluate a substitute regex with /r modifier. The commit fixes this issue.
> Workaround in ChaCha20 armv8 Perlasm for old Perl versions

- CMakeLists.txt
- util/all_tests.go
In #105 we added support for the `BUILD_TESTING` and `BUILD_LIBSSL` options. For `BUILD_LIBSSL`, it was missed that we link the `ssl` target when building `libdecrepit` and we should not be doing this when we disable building libssl.
> Do not build libdecrepit if we are not buildling libssl

- crypto/fipsmodule/rand/asm/rdrand-x86_64.pl
- generated-src/linux-x86_64/crypto/fipsmodule/rdrand-x86_64.S
- generated-src/mac-x86_64/crypto/fipsmodule/rdrand-x86_64.S
- generated-src/win-x86_64/crypto/fipsmodule/rdrand-x86_64.asm
Port s2n's `rdrand` defense-in-depth https://github.com/aws/s2n-tls/blob/main/utils/s2n_random.c#L520 but do it at the asm level.
**All 0s as error code:** `test` performs a bit-wise `and` and discards the result. `ZF` is set if the result is 0. Hence, `ZF = 1` iff `tmp1` contains all 0s.
**AMD CPU "sticky on 1" bug:** The immediate `-1` is 2-compliment interpreted and sign-extended to 64 bits with no cleared bits. `ZF` is set if the two operands for the `cmp` instruction are equal. Hence, `ZF = 1` iff `tmp1` has all bits set.
Flipping branches to `jnz`/`jne`, produces errors when calling `CRYPTO_rdrand` or `CRYPTO_rdrand_multiple8_buf` as expected.
Some standalone perfs - nothing egregious observed.
w/ changes
```
Platform: Linux x86_64
CPU model name: Intel(R) Xeon(R) Platinum 8124M CPU …
```
> Defend against RDRAND triggery

- crypto/fipsmodule/rand/internal.h
- crypto/fipsmodule/rand/rand.c
- crypto/fipsmodule/rand/urandom.c
- crypto/fipsmodule/rand/urandom_test.cc
CryptoAlg-812
Implement recommended retries for entropy read functions: `rdrand`, `/dev/[u]random`, and `getrandom`.
`rdrand`: Retry 10 times in case of failure in the accumulator function.
`/dev/[u]random`/`getrandom`: Exponential backoff in case of certain failures based on observed behaviour in practice.
Sneaked in removing two redundant `break`s.
Replaced `usleep` with `nanosleep` to avoid having to cater for any potential aliasing of the former.
Modified testing in the following way:
* Capture system calls: `__NR_nanosleep` and `__NR_clock_nanosleep` (the latter is an alias for `nanosleep()` in at least Ubuntu 20.04.
* Modified the PRNG model to account for the extra system calls resulting from exponential backoff.
By submitting this pull request, I confirm that my contribution is …
> Entropy read retries

- crypto/x509/t_x509a.c
Resolves AWS-LC-1
This fix is picked from https://github.com/openssl/openssl/commit/ccb0a11145ee72b042d10593a64eaf9e8a55ec12 to address [CVE-2021-3712](https://cve.report/CVE-2021-3712).
N/A
CI
> Fix a read buffer overrun in X509_CERT_AUX_print()

- crypto/crypto_test.cc
- include/openssl/base.h
Define downstream consumable directive that can be used during pre-compilation to branch depending on whether AWS-LC is build in FIPS mode or not.
Simple unit test.
> Downstream fips pre-compilation flag

- util/fipstools/acvp/modulewrapper/modulewrapper.cc
Resolves CryptoAlg-823
This PR is to update config of `modulewrapper.cc`. This change is to keep the config update to date. The config sometimes is used as reference to request ACVP data.
TBD
CryptoAlg-823 has one quip doc and test report shows this role is supported.
> Add 'responder' role of KAS-FFC-SSC in ACVP config.

- CMakeLists.txt
- crypto/fipsmodule/rand/urandom.c
- tests/compiler_features_tests/linux_u32.c
Addresses CryptoAlg-829?selectedConversation=71347c06-0be3-4d5f-ade8-274ddeee05af
This PR is to fix compiler error: unknown type name '__u32'.
Background:
crypto/fipsmodule/rand/urandom.c includes below Linux header file for FIPS.
Some old Linux OS does not define '__u32', and then reports below error.
```
/usr/include/linux/random.h:38:2: error: unknown type name '__u32'
__u32 buf[0];
^
```
Currently, I assume the compiler error is caused by '__u32' is not defined. If not, the redefine the same type will trigger compiler error.
* A quip doc has more details and is included in `CryptoAlg-829?selectedConversation=71347c06-0be3-4d5f-ade8-274ddeee05af`.
* `/usr/include/asm-x86_64/types.h` uses the same code to define `__u32`. The header file is not included because I plan to keep the change …
> Fix compiler error: unknown type name '__u32'.

- pq-crypto/CMakeLists.txt
- pq-crypto/EVP_kem.h
- pq-crypto/README.md
- pq-crypto/sike_r3/LICENSE
- pq-crypto/sike_r3/sike_internal.h
- pq-crypto/sike_r3/sikep434r3.c
- pq-crypto/sike_r3/sikep434r3.h
- pq-crypto/sike_r3/sikep434r3_api.h
- pq-crypto/sike_r3/sikep434r3_ec_isogeny.c
- pq-crypto/sike_r3/sikep434r3_ec_isogeny.h
- pq-crypto/sike_r3/sikep434r3_fips202.c
- pq-crypto/sike_r3/sikep434r3_fips202.h
- pq-crypto/sike_r3/sikep434r3_fp.c
- pq-crypto/sike_r3/sikep434r3_fp.h
- pq-crypto/sike_r3/sikep434r3_fpx.c
- pq-crypto/sike_r3/sikep434r3_fpx.h
- pq-crypto/sike_r3/sikep434r3_kem.c
- pq-crypto/sike_r3/sikep434r3_sidh.c
Updated with clear and necessary comments.
>  AWS license removal for SIKE

- tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
Addresses CryptoAlg-847
https://github.com/awslabs/aws-lc-verification/pull/54 added a pair of env var to make the the parameter range configurable. This PR used the env variable to reduce the total time of AES-GCM select check.
* CryptoAlg-847?selectedConversation=a20c9db4-403b-4184-b0d1-1acf7c663e34
> Split AES-GCM formal verification with smaller parameter range.

- crypto/fipsmodule/rand/rand.c
N/A
In FIPS mode we have to completely zeroize all the DRBG states. However, the `last_block` field in the state was not being zeroized even though it contains part of the entropy being used for the DRBG. This commit adds the zeroization of the `last_block` field.
N/A
> Zeroize the last_block field in DRBG state

- crypto/fipsmodule/rand/rand.c
N/A
Documentation for Jitter read_entropy functions states that the functions return either a negative integer which signifies an error, or the number of generated bytes of entropy. The implementation of the functions however checks if it the requested and the generated number of bytes is the same and returns an error if it's not. Nevertheless, to be on the safe side we now check that Jitter function returns the expected value.
N/A
> Correctly check Jitter read_entropy return value

- crypto/fipsmodule/rand/urandom_test.cc
N/A
Remove unused macro check in urandom_test (leftover from when `JITTER_ENTROPY` flag was defined).
N/A
> Remove unused macro check in urandom_test

- LICENSE
Resolves CryptoAlg-863 
Update our top level license with information from Jitter's license file.
Approval was granted in V438103860.
N/A
> Add third_party/jitterentropy license to the top level LICENSE file

- crypto/hrss/hrss.c
**Intel-specific intrinsic**
~~`OPENSSL_AARCH64` is used at compile-time to branch away from non-arm supported code. However, this is only enabled for Arm 64-bit platforms:
https://github.com/awslabs/aws-lc/blob/main/include/openssl/base.h#L96~~
~~The 32-bit Arm platform we are looking at makes the compiler define `__ARMEL__`, making us defining `OPENSSL_ARM`:
https://github.com/awslabs/aws-lc/blob/main/include/openssl/base.h#L99.~~
~~Fixed two instances of this.~~
https://github.com/awslabs/aws-lc/pull/165 introduced a breaking change. The CI didn't exercise this code path because it doesn't have an Arm 32-bit w/ Neon dimension. So it didn't pick up that it now uses Intel specific intrinsics.
Revert back to the original implementation for the Arm code path but use the fix in the PR for …
> Don't use Intel-specific intrinsic on the Arm path and force alignment of Arm vector type

- tests/ci/cdk/cdk/aws_lc_github_fuzz_ci_stack.py
- tests/ci/common_fuzz.sh
Previously all shared corpus operations required reading from EFS including each thread of libfuzzer. This results in a lot of EFS capacity utilization and possible some slow downs. This change copies the shared corpus to each CodeBuild job host one time, uses the local copy and then merges back to the shared EFS corpus.
This is a draft PR and I want to collect data on average build runtime before and after this change. The question is how does the extra copy time compare to the advantage of local file reads, and how does that impact EFS utilization? 
I tested the change by running the script in local mode and checking the contents of `mock_efs` and `fuzz_run_root`.
Copying the Cryptofuzz corpus (the largest one) to CodeBuild takes 28 seconds, but it saves 10 seconds to count the files …
> Create a local copy of the shared fuzzing corpus for each fuzz test

- util/fipstools/acvp/modulewrapper/modulewrapper.cc
Resolves CryptoAlg-902
This PR replaced `EVP_aead_aes_128/256_gcm` with `EVP_aead_aes_128/256_gcm_tls12` in ACVP test based on the FIPS validation lab request. 
* `EVP_aead_aes_192_gcm` is not used in s2n/TLS RFC. awslc does not have related tls API.
* https://datatracker.ietf.org/doc/html/rfc5288
* https://datatracker.ietf.org/doc/html/rfc8446#section-9.1
CI. `./util/fipstools/acvp/acvptool/test/vectors/ACVP-AES-GCM.bz2` includes the external IV test data.
> Replace EVP_aead_aes_128/256_gcm with EVP_aead_aes_128/256_gcm_tls12 in ACVP test.

- crypto/fipsmodule/ec/ec_key.c
- crypto/fipsmodule/rsa/rsa_impl.c
- crypto/internal.h
- crypto/rsa_extra/rsa_test.cc
Resolves #CryptoAlg-908
It's required that the FIPS module aborts when PCT tests fail in `EC_KEY_generate_key_fips()` and `RSA_check_fips()`.
This change inserts the abort on failure after a certain number of attempts in the case of a FIPS build.
- In RSA, there existed a number of attempts already in the key generation.
There were also tests for the failure cases.
These tests are here repeated as part of the RSADeathTest suite when
built with -DFIPS=1 using ASSERT_DEATH.
- In EC, a number of attempts is introduced around the key generation and check.
There are currently no tests for the failure cases in EC.
> Abort when RSA or EC key generation fail

- crypto/fipsmodule/bn/bn_test.cc
- crypto/fipsmodule/bn/div.c
- crypto/fipsmodule/bn/gcd_extra.c
- crypto/fipsmodule/bn/internal.h
- crypto/fipsmodule/rsa/rsa.c
- crypto/fipsmodule/rsa/rsa_impl.c
The bulk of RSA_check_key is spent in bn_div_consttime, which is a naive
but constant-time long-division algorithm for the few places that divide
by a secret even divisor: RSA keygen and RSA import. RSA import is
somewhat performance-sensitive, so pick some low-hanging fruit:
The main observation is that, in all but one call site, the bit width of
the divisor is public. That means, for an N-bit divisor, we can skip the
first N-1 iterations of long division because an N-1-bit remainder
cannot exceed the N-bit divisor.
One minor nuisance is bn_lcm_consttime, used in RSA keygen has a case
that does *not* have a public bit width. Apply the optimization there
would leak information. I've implemented this as an optional public
lower bound on num_bits(divisor), which all but that call fills in. …
> Make RSA_check_key more than 2x as fast.

- crypto/fipsmodule/ec/ec_test.cc
- crypto/rsa_extra/rsa_test.cc
Addresses #CryptoAlg-908
This commits continues 6bdd4c340 (Abort when RSA or EC key generation fail (#324)) by adding to ECTest a failure case for `EC_KEY_generate_key_fips` which fails in non-FIPS builds and aborts in FIPS builds.
Attempting to make this test simpler by setting the group order directly in `key` causes other tests because it actually changes the group order of the P-224 curve. See this [TODO in ec.c about making the built-in groups actually static](https://github.com/awslabs/aws-lc/blob/6bdd4c3403a17f85cf8cee0a245f220c5c0c28e5/crypto/fipsmodule/ec/ec.c#L499-L500).
> Test EC_KEY_generate_key_fips failure case in FIPS and non-FIPS builds

- crypto/fipsmodule/ec/ec_test.cc
Addresses CryptoAlg-908
As in the title. This name is more indicative of what the test does.
> Rename the negative tests of EC key generation

- crypto/cpu-aarch64-linux.c
N/A
Add Arm CPU capabilities environment variable override.
The effect of the change can be checked for example by comparing the speed of SHA-256 when run with `bssl speed SHA-256` and `export OPENSSL_armcap_P=0 && bssl speed SHA-256`.
> Add Arm CPU capabilities environment variable override

- crypto/fipsmodule/ec/ec_key.c
- crypto/fipsmodule/ec/ec_test.cc
- crypto/fipsmodule/rsa/rsa_impl.c
- crypto/internal.h
- crypto/rsa_extra/rsa_test.cc
Resolves CryptoAlg-908
It's required that the FIPS module aborts when PCT tests fail in `EC_KEY_generate_key_fips()` and `RSA_check_fips()`.
This change inserts the abort on failure after a certain number of attempts in the case of a FIPS build.
- In RSA, there existed a number of attempts already in the key generation.
There were also tests for the failure cases.
These tests are here repeated as part of the RSADeathTest suite when
built with -DFIPS=1 using ASSERT_DEATH.
- In EC, a number of attempts is introduced around the key generation and check.
And a failure test case for EC_KEY_generate_key_fips was added which fails in non-FIPS builds and aborts in FIPS builds.
> cherry-pick to fips-2021-10-20: Abort when RSA and EC keygen fail

- crypto/fipsmodule/ec/ec_key.c
- crypto/fipsmodule/rsa/rsa_impl.c
- crypto/internal.h
Continues CryptoAlg-908
Based on feedback about the FIPS RSA PCT, it was only done once and not included in the number of attempts of key generation. This change moves it inside the `do-while` loop.
> Include the RSA PCT check in the number of keygen attempts.

- crypto/fipsmodule/ec/ec_key.c
- crypto/fipsmodule/rsa/rsa_impl.c
- crypto/internal.h
- crypto/rsa_extra/rsa_test.cc
Addresses CryptoAlg-908
In the FIPS feedback of the previous commit, it was pointed out a flaw in the logic:
Failing for other reasons than TOO_MANY_ITERATIONS would not allow more retries.
So the original loop in `RSA_generate_key_ex_maybe_fips()` in rsa_impl.c as in 6bdd4c3 is brought back to focus on only retrying keygen when TOO_MANY_ITERATIONS is the reason for failure.
An outer loop is added to test for PCT and have its own number of attempts which covers both keygen and PCT failures. This behaviour now matches that of `EC_KEY_generate_key_fips()`.
> Reverted the inner loop of RSA keygen to retry when TOO_MANY_ITERATIONS

- crypto/fipsmodule/ec/ec_key.c
- crypto/fipsmodule/rsa/rsa_impl.c
- crypto/internal.h
- crypto/rsa_extra/rsa_test.cc
Addresses CryptoAlg-908
In the FIPS feedback of the previous commit, it was pointed out a flaw in the logic:
Failing for other reasons than TOO_MANY_ITERATIONS would not allow more retries.
So the original loop in `RSA_generate_key_ex_maybe_fips()` in rsa_impl.c as in 6bdd4c3 is brought back to focus on only retrying keygen when TOO_MANY_ITERATIONS is the reason for failure.
This inner loop can be thought of as one call for RSA key generation.
An outer loop is added to test for PCT and have its own number of attempts which covers both keygen and PCT failures. This behaviour now matches that of `EC_KEY_generate_key_fips()`.
Reverted the inner loop of RSA keygen to retry when TOO_MANY_ITERATIONS #334  …
> cherry-pick to fips-2021-10-20: Reverted the inner loop of RSA keygen

- util/fipstools/acvp/modulewrapper/modulewrapper.cc
By default, the auto mode is used in some crypto lib impl (e.g. [Golang VerifyPSS](https://pkg.go.dev/crypto/rsa#VerifyPSS) and awslc code) when generating PSS signature. In FIPS validation, the data we request expects the `saltlen == hashlen`. Accordingly, `RSA_PSS_SALTLEN_DIGEST` should be set.
* Will merge this PR when the ACVP lab confirms this fix works for the non sample data.
The generated signature was tested with Golang https://pkg.go.dev/crypto/rsa#VerifyPSS
> Set RSA_PSS_SALTLEN_DIGEST(-1) in acvp tool.

- tests/ci/run_fips_tests.sh
This PR used `DCMAKE_BUILD_TYPE=Release` as FIPS build type based on the ACVP lab request.
TBD
CI
> Use DCMAKE_BUILD_TYPE=Release as FIPS build type.

- CMakeLists.txt
- tests/ci/docker_images/windows/README.md
* The Windows CI readme was out of date and would not be able to build or use our Docker containers.
* Add a safety check to our FIPS build to reduce confusion. Without the check the build fails with a delocate parse error.
We already don't support a FIPS static build, this check just helps users understand the issue.
Not passing in the required flag fails with:
```
CMake Error at CMakeLists.txt:501 (message):
Building AWS-LC for FIPS only supports the shared build, you must pass in
'-DBUILD_SHARED_LIBS=TRUE'
```
> Documentation updates for Windows and building FIPS

- crypto/ecdh_extra/ecdh_test.cc
- crypto/fipsmodule/ec/ec_test.cc
- crypto/fipsmodule/ecdh/ecdh.c
Addresses CryptoAlg-905
Continuing on the requirements of public key validation in SP 800-56Ar3, this change satisfies Sec. 5.6.2.3.4, where a peer public key should undergo a partial key validation.
This change:
- satisfies performing the check in `EVP_PKEY_derive` and `ECDH_compute_key_fips`.
- ~also performs the check in `ECDH_compute_key` (non-FIPS-Approved), since the check is not expensive.~
> Partial public-key validation for peer key in ECDH

- crypto/fipsmodule/ec/ec_key.c
- crypto/fipsmodule/ecdh/ecdh.c
- crypto/fipsmodule/service_indicator/service_indicator_test.cc
Addresses CryptoAlg-835 (FIPS follow-up)
The previous service indicator check in `EC_KEY_check_fips` missed out on `EC_KEY`s that only had `pub_key` available. This was not the correct behavior and this PR fixes that.
New test in `crypto/fipsmodule/service_indicator/service_indicator_test.cc` where only `pub_key` is copied over from a generated `EC_KEY`.
> Fix service indicator check for `EC_KEY_check_fips` 

- CMakeLists.txt
- ssl/test/runner/runner.go
- tests/ci/cdk/cdk/codebuild/github_ci_linux_arm_omnibus.yaml
- tests/ci/codebuild/linux-aarch/run_ssl_asan_tests.yml
- tests/ci/run_posix_sanitizers.sh
- tests/ci/run_ssl_asan_tests.sh
Cherry pick ee356753851b1682ac90c86fd0b755bfe2278f2b from main onto the FIPS branch to fix the CI. Without this change the CI fails due to:
```
[Container] 2021/12/22 02:50:53 Phase context status code: YAML_FILE_ERROR Message: stat /codebuild/output/src352659667/src/github.com/awslabs/aws-lc/tests/ci/codebuild/linux-aarch/run_ssl_asan_tests.yml: no such file or directory
```
> Enable SSL runner tests with ASAN on arm

- CMakeLists.txt
- crypto/CMakeLists.txt
- crypto/fipsmodule/CMakeLists.txt
- decrepit/CMakeLists.txt
- ssl/CMakeLists.txt
- tests/ci/run_windows_tests.bat
Addresses CryptoAlg-907
* Turn on most windows build flavors:
* Debug build
* Only for MSVC 2017
* Release small
* Release no assembly
* Release shared build
* Regular Release is still on
* Update Window's PATH variable to search for our DLLs in the build directory
* Update CI script to support testing on local paths
* Update CI script to skip printing useless CMake logs
* Enable `GTEST_CREATE_SHARED_LIBRARY` so Windows can get the `dllexport`s it needs
* Only specify `BORINGSSL_IMPLEMENTATION` when building our code so Windows picks correctly between `__declspec(dllexport)` and `__declspec(dllimport)` in base.h
Without the changes to `BORINGSSL_IMPLEMENTATION` Windows tests would fail because in the unit tests `BORINGSSL_IMPLEMENTATION` would be set and all the `OPENSSL_EXPORT`s would …
> Enable more Windows builds

- crypto/CMakeLists.txt
- crypto/fipsmodule/CMakeLists.txt
- crypto/fipsmodule/fips_macos_support.c
- crypto/thread_test.cc
- util/fipstools/inject_hash/inject_hash.go
CryptoAlg-906
This change enables the FIPS build of the shared library on macOS.
We don't have macOS testing in the CI yet, so this change is tested only on my macbook. The reviewers should download the code and try to build the library to at least verify that it works on their macbook.
See call-outs
> Enabling the FIPS build on macOS

- crypto/fipsmodule/rand/fork_detect.c
The memory mapping during fork detection initialisation is currently deleted twice:
1. https://github.com/awslabs/aws-lc/blob/main/crypto/fipsmodule/rand/fork_detect.c#L56
2. https://github.com/awslabs/aws-lc/blob/main/crypto/fipsmodule/rand/fork_detect.c#L145
in the error-path.
Only do this once. We choose to do this in (2) because this captures all error-paths encountered from entry into `init_fork_detect()`.
It is not an "error" to unmap twice per https://man7.org/linux/man-pages/man3/munmap.3p.html:
> If there are no mappings in the specifie address range, then munmap() has no effect. 
But it saves work to not do it twice in the error-path.
We invalidate the pointer after unmapping for defense-in-depth, because:
> Further references to these [unmapped] pages shall result in the …
> Don't double delete mapping

- crypto/fipsmodule/ec/p384.c
- crypto/fipsmodule/ec/p384_table.h
- third_party/fiat/p384_32.h
- third_party/fiat/p384_64.h
N/A
Refactoring P-384 implementation for consistency (removing `fiat` prefix from functions, enforcing 80 characters per line, etc.)
N/A
> Refactoring P-384 implementation for consistency

- include/openssl/ssl.h
CryptoAlg-954
Add some reason codes from OpenSSL to ease compilation and integration against AWS-LC. Do this under its own "namespace"  for clarity and protect against any upstream merge conflict annoyance.
These will have a different reason code value compared to OpenSSL. But it all works fine if compilation happens against AWS-LC headers, of course!
None of these reason codes are actually returned by AWS-LC. Code paths that condition on these codes might break. Grep for `ERR_GET_REASON` and `ERR_GET_FUNC` to inspect.
> Add reason codes for backwards compilation compatibility

- .github/workflows/osx.yml
- tests/ci/README.md
- tests/ci/common_posix_setup.sh
Resolves CryptoAlg-605
This PR added macOS CI, which uses [GitHub workflow](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore) to run `./tests/ci/run_posix_tests.sh` on macOS 11.
* Billing related questions are still being investigated.
* This PR does not cover macOS FIPS build.
https://github.com/bryce-shang/aws-lc/runs/5061261641?check_suite_focus=true
> Add macOS CI.

- .github/workflows/osx.yml
- tests/ci/run_fips_tests.sh
- tests/ci/run_posix_tests.sh
Resolves CryptoAlg-605
This PR added macOS FIPS build to CI. The build runs `./tests/ci/run_fips_tests.sh` on macOS 11.
* https://github.com/awslabs/aws-lc/pull/381
TBD
CI
> Add macOS FIPS build to CI.

- crypto/CMakeLists.txt
- third_party/jitterentropy/CMakeLists.txt
Addresses `CryptoAlg-895`
Previously the FIPS shared build would work if the source code was built directly with the AWS-LC's root CMake file. This change helps support building from other CMake projects that build AWS-LC with `add_subdirectory`. 
Using `CMAKE_SOURCE_DIR` will refer to the folder where the top-level `CMakeLists.txt ` is defined, which in some cases will be the external CMake file which calls `add_subdirectory`.  This lets parts of the current build point to the incorrect places. Replacing `CMAKE_SOURCE_DIR` with `PROJECT_SOURCE_DIR` fixes this, as `PROJECT_SOURCE_DIR` points to the project source directory. 
Resource: https://stackoverflow.com/questions/32028667/are-cmake-source-dir-and-project-source-dir-the-same-in-cmake 
This was found when trying to build the AWS-LC …
> CMake Target Changes

- tests/ci/codebuild/linux-x86/docker-img-build.yml
Fixes CI docker image build
Previous PR https://github.com/awslabs/aws-lc/pull/374 removed the script `pull_github_pkg.sh` since it was no longer needed. Running the `build-linux-img` command with the `run-cdk.sh` will fail because the script can't be found with the 
`tests/ci/codebuild/linux-x86/docker-img-build.yml` build spec. 
N/A
Ran `build-linux-img` with the cdk script in my personal Isengard account. Docker images got updated as intended.
> Remove reference to removed script in docker build spec

- .github/workflows/osx.yml
Run OSx CI dimension for all target branches.
Reason: We don't want to carry OSx regressions on branches. In particular, we would carry these on upstream staging branches.
CI
> Run OSx CI dimension for all target branches

- crypto/fipsmodule/CMakeLists.txt
- crypto/fipsmodule/ec/make_tables.go
- crypto/fipsmodule/ec/p384.c
- crypto/fipsmodule/ec/p384_table.h
- third_party/fiat/p384_32.h
- third_party/fiat/p384_64.h
- third_party/s2n-bignum/include/s2n-bignum_aws-lc.h
CryptoAlg-946
On x86_64 platforms s2n-bignum uses bmi2 and adx instruction sets
for some of the P-384 functions. These instructions are not supported
by every x86 CPU. Previously, we checked in runtime if bmi2 and adx
are supported and if not we fallback to Fiat's implementation. This
solution had a drawbacks that we had to always compile both
s2n-bignum and Fiat code.
s2n-bignum implemented "alternative" implementations of functions
that don't require any special instructions. In this commit we integrate
those changes and instead of falling-back to Fiat's code we fall back
to s2n-bignum alternative implementations. The change has two
benefits:
- s2n-bignum and Fiat are decoupled so we compile only one.
- Performance improvement on x86 CPUs that don't support bmi2
and adx instructions is …
> Integrate s2n-bignum alternative functions for P-384

- crypto/fipsmodule/rand/rand.c
Make condition less strict, to make sure we also catch some weird situation where `tries` jumps past `RDRAND_MAX_RETRIES - 1`.
> Improve rdrand retries

- tests/ci/cdk/README.md
This PR is to update the CI README by specifying `GITHUB_REPO_OWNER`, which is to specify the GitHub repo targeted by this CI setup.
* https://github.com/${GITHUB_REPO_OWNER}/aws-lc.git
* Without `--github-repo-owner=${GITHUB_REPO_OWNER}`, the default value `awslabs` is used for convenience.
CI.
> Update CI README.

- crypto/fipsmodule/service_indicator/service_indicator.c
- crypto/fipsmodule/service_indicator/service_indicator_test.cc
Addresses CryptoAlg-907
Add lazy initialization logic to all service indicator functions. This is *not* an issue for the current Linux FIPS branch. This issue only happens on Windows FIPS builds. The Windows issue is nothing was calling `FIPS_service_indicator_update_state` which created the state before calling `FIPS_service_indicator_lock_state`. When lock was called with a null state nothing happens and AWS-LC continues and eventually hits a call to update state which creates the state, then something calls unlock and underflows. My hypothesis is MSVC changes the order of self tests in the `BORINGSSL_bcm_power_on_self_test` to hit this unlock issue while Clang/GCC does not.
The CI does not test FIPS on Windows yet due to other issues. I have tested this part on a Windows machine …
> Improve service indicator initialization and add tests for under/overflow

- crypto/fipsmodule/bn/bn_tests.txt
- crypto/fipsmodule/bn/sqrt.c
This commit fixes the issue released as OpenSSL CVE-2022-0778 that
affects AWS-LC as well. A bug in BN_mod_sqrt() can cause the function
to enter an infinite loop. The issue is now fixed and two test
cases are added to verify that the function returns a failure instead
of hanging.
By submitting this pull request, I confirm that my contribution is …
> OpenSSL CVE-2022-0778 Fix possible infinite loop in BN_mod_sqrt()

- README.md
CryptoAlg-861
Modifying our readme to add instructions on how to register for pre-notifications of AWS-LC.  
Ensured the e-mail list allowed access from both internal and external e-mail addresses. 
> Adding pre-notification instructions to AWS-LC

- crypto/bio/bio.c
- include/openssl/bio.h
Resolves CryptoAlg-1041
This PR added some BIO getter/setter functions to avoid some compilation errors(due to missing functions) in some code packages of customers.
TBD
No test. These are setter and getter functions.
> Add BIO setter/getter functions.

- tests/ci/cdk/cdk/aws_lc_analytics_stack.py
- tests/ci/cdk/cdk/codebuild/github_ci_analytics_omnibus.yaml
Add a filter to the analytics webhook so it only runs on pushes to main. This is useful because not all branches have the analytics config yet and would create failing builds. 
I deployed this change to my local CI and made several pushes to branches and verified it only ran when I pushed to my main.
> Update the analytics to only run on the main branch

- tests/ci/docker_images/linux-aarch/amazonlinux-2_base/Dockerfile
The ARM AmazonLinux2 base image is out of sync with the [X86 image which includes the AWS CLI](https://github.com/awslabs/aws-lc/blob/main/tests/ci/docker_images/linux-x86/amazonlinux-2_base/Dockerfile#L29-L33). This change adds it to get them both in sync.
Built this image on an ARM instance and verified the `aws` command is found.
> Add AWS CLI to ARM AmazonLinux2 base image

- crypto/fipsmodule/hmac/hmac.c
This PR fixed compiler warning(treated as error) reported by gcc-4.1 in the build `5907986753`.
```
cc1: warnings being treated as errors
...
crypto/fipsmodule/hmac/hmac.c: In function 'HMAC':
crypto/fipsmodule/hmac/hmac.c:188: warning: missing initializer
crypto/fipsmodule/hmac/hmac.c:188: warning: (near initialization for 'ctx.methods')
```
TBD
* This fix is verified by build `5908005917`.
> Fix compiler warn(treated as error) reported by gcc-4.1.

- crypto/crypto.c
- include/openssl/base.h
- include/openssl/crypto.h
- include/openssl/is_awslc.h
`OpenSSL_version()` can be a convenient method to distinguish AWS-LC from other projects at run-time. But it can't be used as a distinguisher from BSSL without changing the name to AWS-LC. Make this change since AWS-LC is a dependency in projects that can also depend on BSSL.
At the same time, modify the name of the project-specific header file (`is_boringssl.h`) to an AWS-LC-specific name.
It is better to make these changes early on.
> Make it possible to distinguish BSSL and AWS-LC

- tests/ci/cdk/cdk/aws_lc_android_ci_stack.py
- tests/ci/cdk/util/iam_policies.py
Resolves Android failure in https://github.com/awslabs/aws-lc/pull/460
The new https://github.com/awslabs/aws-lc/pull/460 Android CI functionality requires device farm IAM permissions to start up the new tests.
N/A
IAM Policy used and tested in https://github.com/samuel40791765/aws-lc/pull/14. 
> Add Device Farm permissions for android codebuild dimension

- tests/ci/cdk/cdk/codebuild/github_ci_android_omnibus.yaml
Addresses `CryptoAlg-895`
Upgrading the Android CI compute type, reason described in `CryptoAlg-1063`.
N/A
N/A
> Upgrade Android CI to use larger instance

- crypto/fipsmodule/rsa/internal.h
- crypto/fipsmodule/rsa/rsa.c
- crypto/fipsmodule/rsa/rsa_impl.c
- crypto/rsa_extra/rsa_asn1.c
- crypto/rsa_extra/rsa_test.cc
Prior to this change, all RSA private keys were also validated as public
keys during ASN.1 decoding. That was all well and good for CRT-enabled
private keys, as they contained the public exponent `e`, but was not
suitable for stripped private keys (i.e. keys defined only by `n` and
`d`) as required by the JCA and ACCP.
The refactor is based directly on @htorben's sketch [here][1], and does
not change AWS-LC's external API at all. We intentionally attempt to
minimize behavior and validation changes in order to minimize risk of
accidentally impacting RSA key generation and validation. To that end,
we only perform ACCP-aware validation when parsing from DER, and not
when doing key generation or general validation. The relevant RFC
([RFC-8107][2]) does not seem to explicitly permit omitted …
> Detect ACCP keys when parsing RSA private keys from ASN.1/DER

- include/openssl/base.h
#458 is not backwards compatible. Bump API version to allow downstream detection in the preprocessor. 
> Bump AWS-LC API version

- tests/ci/cdk/cdk/codebuild/github_ci_fuzzing_omnibus.yaml
Tracked in `CryptoAlg-1066`
Fixating the CI to use the same cryptofuzz docker image.
N/A
The tag points to the same docker image that we currently use.
> Set cryptofuzz docker image to use an older tag

- crypto/CMakeLists.txt
- crypto/fipsmodule/aes/internal.h
- crypto/fipsmodule/aes/mode_wrappers.c
- crypto/internal.h
- crypto/xts/xts.c
- crypto/xts/xts_test.cc
- decrepit/CMakeLists.txt
- tool/CMakeLists.txt
Addresses CryptoAlg-929
AES-XTS C implementation and tests were part of `libdecrepit` before this PR. Here, they are moved into `libcrypto`.
Note: the assembly implementation already co-exists with the rest of AES assembly functions in the respective Perl-Assembly code for AArch64 and x86_64 in `crypto/fipsmodule/aes/asm`.
> Move XTS from libdecrepit to libcrypto

- include/openssl/base.h
Partially Resolves https://github.com/aws/s2n-tls/issues/3262
While trying to internalize aws-lc into libs2n.so, we have observed that while symbols aren't hidden in static builds, once objcopy copies libcrypto, the fact that symbols are marked hidden is still honored in the shared lib.  This means libcrypto symbols aren't available (see the issue).
This change makes symbols visible for the aws-lc static.
Test summery run using this branch and the other changes in #3262
```
S2N_LIBCRYPTO=awslc ./codebuild/bin/test_libcrypto_interning.sh
...
Total Test time (real) =  57.71 sec
make: Leaving directory '/home/dougch/gitrepos/s2n-tls/build/static'
testing static linking with /home/dougch/gitrepos/s2n-tls/build/openssl_1_0
testing static linking with /home/dougch/gitrepos/s2n-tls/build/awslc …
```
> Symbol visibility to default for static build

- CMakeLists.txt
- tests/ci/run_minimal_tests.sh
- tests/ci/run_posix_tests.sh
#412 introduced a build regression when using the `MY_ASSEMBLER_IS_TOO_OLD_FOR_AVX` build option. Regression was fixed in #426 
This PR improves the CI ability to verify that changes doesn't regress the `MY_ASSEMBLER_IS_TOO_OLD_FOR_AVX` build option using the light weight tests.
Also, makes it clear in the cmake output that `MY_ASSEMBLER_IS_TOO_OLD_FOR_AVX` is active.
> Improve MY_ASSEMBLER_IS_TOO_OLD_FOR_AVX build option test

- tests/ci/run_posix_tests.sh
This PR enables tests for shared build and removes duplicate Fuzz build.
* Enabling tests for shared build was missed during the CI migration from old repo.
* Fuzz build logics were moved to `run_fuzz_tests.sh`.
> Enable tests for shared build and remove duplicate Fuzz build.

- tests/ci/benchmark_framework/compare_results.py
- tests/ci/build_run_benchmarks.sh
The Benchmarking framework was missing several variables that was
previously defined by an orchestrator, since we now run the framework
directly these variables needed to be adjusted so that the data would
not overwrite old data. Additionally 5% was too stringent a requirement
so we've relaxed it to 10%
> Fix minor Benchmarking issues

- tests/ci/run_analytics.sh
Track the size of bssl as an indicator for the size implications to our customers picking between linking with the static or shared libraries for libcrypto and libssl. This isn't a perfect indicator as the size impact with a static library will depend on the customer's usecase.
Ran locally and verified new metrics are emitted with expected values:
```
aws cloudwatch put-metric-data --timestamp 1651012758 --namespace AWS-LC --metric-name ToolSize --value 3117944 --unit Bytes --dimensions Branch=analytics,Optimization=Release,BuildSize=Small,Assembly=NoAsm,CPU=x86_64,Linking=Shared,FIPS=NotFIPS
```
> Track size of bssl overtime

- crypto/CMakeLists.txt
Clang-7's assembler doesn't support the generation of debug symbols. Our current cmake logic depends on the value of `CMAKE_ASM_COMPILER_ID` to indicate whether Clang's assembler is being used. However, this variable is not always set. When not set, `-Wa,-g` gets added to `CMAKE_ASM_FLAGS` causing the build to fail.
If it's unable to determine which assembler is being used, the logic assumes that debug symbols are supported by the assembler.
Successfully completed a debug build using clang-7:
```
cmake . -DBUILD_SHARED_LIBS=TRUE "-DCMAKE_C_COMPILER=clang-7" "-DCMAKE_CXX_COMPILER=clang++-7" "-DCMAKE_ASM_COMPILER=clang-7" "-DFIPS=1" "-DCMAKE_INSTALL_PREFIX=/tmp/fips-build"
```
```
cmake --build . --target ssl --config Debug
```
By submitting this pull request, I confirm that my contribution …
> CMAKE_ASM_COMPILER_ID not always set

- crypto/fipsmodule/hmac/hmac.c
https://github.com/awslabs/aws-lc/pull/368 broke the prefix build. For example, the symbol list will contain the public symbol `MD5`. But then the object type [expanded here](https://github.com/awslabs/aws-lc/blob/e14e153cda6c0921a10209c78762de37707d48c4/crypto/fipsmodule/hmac/hmac.c#L90) will be
`<prefix>_MD5_CTX`. But the prefixing tool will only match exact, so the [corresponding declaration](https://github.com/awslabs/aws-lc/blob/e14e153cda6c0921a10209c78762de37707d48c4/include/openssl/base.h#L441) is not prefixed. 
The result are undefined identifiers.
Need to be more specific and avoid general tokens e.g. `MD5` to avoided them being prefixed. Unfortunately, this involves moving away from the more general `MD_TRAMPOLINES` to using only the explicit version and making it even more …
> Fix prefix build

- crypto/fipsmodule/sha/sha256.c
- crypto/x509v3/v3_utl.c
- tests/ci/docker_images/linux-x86/build_images.sh
- tests/ci/docker_images/linux-x86/push_images.sh
- tests/ci/docker_images/linux-x86/ubuntu-22.04_base/Dockerfile
- tests/ci/docker_images/linux-x86/ubuntu-22.04_gcc-12x/Dockerfile
https://github.com/awslabs/aws-lc/issues/487
This PR fixed below warnings reported by gcc-12 on x86-64. Both warnings are false-positive.
```
In function 'memset',
inlined from 'OPENSSL_memset' at /home/ubuntu/aws-lc/crypto/x509v3/../internal.h:845:10,
inlined from 'ipv6_from_asc' at /home/ubuntu/aws-lc/crypto/x509v3/v3_utl.c:1285:9,
inlined from 'x509v3_a2i_ipadd' at /home/ubuntu/aws-lc/crypto/x509v3/v3_utl.c:1194:14,
inlined from 'X509_check_ip_asc' at /home/ubuntu/aws-lc/crypto/x509v3/v3_utl.c:1114:21:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:59:10: error: '__builtin_memset' forming offset 16 is out of the bounds [0, 16] of object 'ipout' with type 'unsigned char[16]' [-Werror=array-bounds]
59 |   return __builtin___memset_chk (__dest, __ch, __len,
| …
```
> Avoid gcc-12 compile warnings.

- tests/ci/common_posix_setup.sh
- tests/ci/run_posix_tests.sh
Needed to know the cmake version, but it is not printed anywhere in the codebuild logs - at least I can't find it.
A first try to print some more information to the log that might be useful.
Not sure what to name the function `print_system_and_dependency_information`(?).
Should we add more information?
> Print information directly in CI

- CMakeLists.txt
* `BORINGSSL_PREFIX` was being set for `CMAKE_ASM_NASM_FLAGS`, but not `CMAKE_ASM_FLAGS`.
* When the path `BORINGSSL_PREFIX_SYMBOLS` was absolute, the build would fail due to an assumption that this path is always relative to `${CMAKE_BINARY_DIR}`
* I successfully performed a prefix build on both Mac and Linux.
> Fix prefix build - allow absoolute path to symbol file

- include/openssl/digest.h
Addresses `P64861145`
Some of the comments in `EVP_MD_CTX_set_pkey_ctx` may have been unclear on who's responsibility it is to free the `pctx` pointer. This tries to clarify that the caller is responsible.  
N/A
Tests already exist. When doing the incorrect behavior, the test will fail against address sanitizer tests due to a leaked pointer.
> Update `EVP_MD_CTX_set_pkey_ctx` comments about responsibility

- crypto/cmake/crypto-config.cmake
- tests/ci/run_s2n_integration.sh
CryptoAlg-1088
This PR accomplishes two things:
Firstly, interned `s2n-tls+aws-lc` is a thing now https://github.com/aws/s2n-tls/issues/3262. `s2n-tls` has a complete and comprehensive set of tests. But we ought to have minimal assurance we don't regress making the feedback loop for trivial errors shorter. Hence, we add a few trivial intern tests to the CI.
Secondly, generally re-factors the `s2n-tls` integrations tests to remove code re-use. Also, run `s2n-tls` unit tests for all build flavors, not only the shared flavor.
This PR will affect the running time of the `s2n-tls` integration tests. In the existing test only one execution of the `s2n-tls` unit tests is performed. This PR will execute the unit tests a total of four times and add two extra `s2n-tls` builds.  …
> Add interned s2n-tls+aws-lc test and re-factor script

- ssl/test/runner/runner.go
Addresses CryptoAlg-1040
[InvalidChannelIDSignature-TLS13-TLS-Sync-SplitHandshakeRecords](https://github.com/awslabs/aws-lc/blob/59eccdf959c93a4543b8cb4ae7af01e7be265d3e/ssl/test/runner/runner.go#L5859-L5872) expects `CHANNEL_ID_SIGNATURE_INVALID` is put in [the error stacks of the `bssl_shim`](https://github.com/awslabs/aws-lc/blame/59eccdf959c93a4543b8cb4ae7af01e7be265d3e/ssl/test/bssl_shim.cc#L1337-L1341), which has [SSL_R_CHANNEL_ID_SIGNATURE_INVALID](https://github.com/awslabs/aws-lc/blame/6c57dafb2498e138f983415fb7654557f04760f2/ssl/extensions.cc#L4169) added.
However, the test fails sometimes with below error message on GitHub MacOS CI.
```
FAILED (InvalidChannelIDSignature-TLS13-TLS-Sync-SplitHandshakeRecords)
bad error (wanted ':CHANNEL_ID_SIGNATURE_INVALID:' / ''): local error …
```
> Retry InvalidChannelIDSignature-TLS13-TLS-Sync-SplitHandshakeRecords.

- tests/ci/docker_images/linux-x86/amazonlinux-2_base/Dockerfile
Addresses CryptoAlg-1067
[`valgrind/memcheck.h`](https://github.com/awslabs/aws-lc/blob/e14e153cda6c0921a10209c78762de37707d48c4/crypto/internal.h#L121-L123) is provided by the `valgrind-devel` package on AL2. see `P63119011`.
* Valgrind is not enabled on arm because [the Arm tests hitting the 2 hour time out limit in Codebuild (track resolution in CryptoAlg-597)]( https://github.com/awslabs/aws-lc/pull/71).
* Next PR will be published to enable the build flag `CONSTANT_TIME_VALIDATION`.
* `CryptoAlg-1067?selectedConversation=6fd74357-b5ea-45d8-bff7-a411d24255e7`
> Install valgrind-devel.

- .gitignore
- CMakeLists.txt
- tests/ci/cdk/README.md
- tests/ci/cdk/cdk/codebuild/github_ci_linux_arm_omnibus.yaml
- tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
- tests/ci/codebuild/linux-aarch/run_prefix_tests.yml
- tests/ci/codebuild/linux-x86/run_prefix_tests.yml
- tests/ci/common_posix_setup.sh
- tests/ci/docker_images/linux-x86/ubuntu-7.10_gcc-4.1x/Dockerfile
- tests/ci/run_prefix_tests.sh
- util/read_symbols.go
Add prefix builds to our CI.
Also fixed a few related issues:
* CDK Readme showed commands that were incomplete, and wouldn't even work.
* Move Ubuntu's gcc-11x build to Ubuntu 22.04 to avoid Ubuntu glibc/kernel install issue: https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1962225.
* Patched Ubuntu-7.10/gcc-4.1x docker image to avoid same glibc/kernel install issue.
* Explicitly invokes the `boringssl_prefix_symbols` target prior to prefix build.  AL2/CMake2 hosts seemed to ignore this target dependency when building target `ssl`
* With certain build flags (like `OPENSSL_NO_ASM=1`) some object files would be w/o a "Symbols" section causing the `read_symbols.go` script to fail. Updated script to ignore object files not containing symbols.
* I synthesized the docker images and CDK …
> Ci prefix build

- crypto/cipher_extra/internal.h
Currently, it's unknown how to validate stitch APIs and if some customers use these ciphers in FIPS mode. `CryptoAlg-1155` is created to provide next steps.
* No test needed.
> Disable stitch code when AWSLC_FIPS is defined.

- include/openssl/base.h
- include/openssl/ssl.h
AWS-LC's libcrypto library is standard C99, but there are a few
`#ifdef`'d forward-declared enums in `base.h`, which are exclusively
C++11 features. Further, they're C++11 features that are not supported
by GCC 4.1.2, which is the GCC installation on RHEL5. Since ACCP's
native library is C++, its CMake also tries to compile AWS-LC as C++,
triggering the `#if defined(__cplusplus)` macro and trying to compile
the forward-declared enums as C++. This fails on RHEL5 due to
aforementioned GCC version.
So, @htorben's solution is to simply move these forward declarations to
`ssl.h`, which is outside the object boundary of libcrypto. Both he and
I have confirmed that the resulting object compiles correctly with ACCP
under RHEL5 (RDE) environments. …
> Move C++11 fwd-declared enum to ssl.h

- tests/ci/run_cryptofuzz.sh
Addresses CryptoAlg-1136
This PR enabled XTS fuzz by passing `CRYPTOFUZZ_AWSLC`. The macro functionality is is similar to `CRYPTOFUZZ_BORINGSSL`, which tells if the target library provides some cipher APIs(e.g. `EVP_aes_256_xts`). When the target API is provided, `cryptofuzz` tool can start fuzzing the code.
* `CRYPTOFUZZ_AWSLC` will be available in upstream after the approval of `V610453347`. In testing, a forked cryptofuzz repo is used.
* Some `cryptofuzz development` related commands are needed by runbook.
```sh
docker run -it -v `pwd`:`pwd` -w `pwd` ubuntu-20.04:cryptofuzz
rm -rf nohup.out && bash -c "nohup sh -c './tests/ci/run_cryptofuzz.sh' &"
cat nohup.out | grep 'code_block' | sort | uniq
```
By submitting this pull request, I confirm that my contribution is made under the terms …
> Enable XTS fuzz.

- tests/ci/run_cryptofuzz.sh
Disable differential fuzzing in local development.
* Without this change, the build fails when `CUSTOM_CRYPTOFUZZ_REPO_DIR` is defined.
```sh
docker run -it -v `pwd`:`pwd` -w `pwd` ubuntu-20.04-aarch:cryptofuzz
rm -rf nohup.out && bash -c "nohup sh -c './tests/ci/run_cryptofuzz.sh' &"
```
> Disable differential fuzzing in local development.

- CMakeLists.txt
Currently, the prefix build requires a list of symbols be provided. These symbols are only used to generate the header files containing preprocessor macros.
This change allows for the header files to be prepared prior to the build and their location passed in as a parameter.
I tested on both a Mac (x64) and AmazonLinux (ARM). 
1) Ran the standard build.
2) Generated the symbol files:
```
$ go run read_symbols.go -out ../../symbols1.txt ../../AWS-LC-BUILD/crypto/libcrypto.a
$ go run read_symbols.go -out ../../symbols2.txt ../../AWS-LC-BUILD/ssl/libssl.a
$ cat symbols1.txt symbols2.txt |sort | uniq > symbols-combined.txt
```
3) Generated the header files:
```
$ mkdir -p symbol_prefix_include
$ go run ../aws-lc/util/make_prefix_headers.go -out symbol_prefix_include ../symbols-combined.txt …
```
> Allow prefix headers to be parameter for build

- tests/ci/benchmark_framework/compare_results.py
The benchmarking CI has been giving spurious failures frequently because
the sensitivity was set too high. We expected to have to make
adjustments to this, and it seems like 10% was too low a cutoff for
detecting regressions. Adjusting that number to 15% so we will see fewer
spurious failures.
> Adjusted the sensativity of the benchmarking CI

- tests/ci/cdk/run-cdk.sh
AWS CLI uses default region configured in `.aws/config`. The default region  in `.aws/config` can be different from the one set in our script and cause the `ResourceNotFoundException`. The change of this PR avoids the difference by exporting [AWS_DEFAULT_REGION](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-region)
TBD
```sh
$ aws codebuild update-webhook --project-name aws-lc-ci-linux-x86 --build-type BUILD_BATCH
An error occurred (ResourceNotFoundException) when calling the UpdateWebhook operation: Project does not exist
```
```sh
$ export AWS_DEFAULT_REGION=us-west-2
$ aws codebuild update-webhook --project-name aws-lc-ci-linux-x86 --build-type BUILD_BATCH
{
"webhook": { ...}
}
```
By submitting this pull request, I confirm that …
> Specify the AWS region used by CLI.

- tests/ci/common_posix_setup.sh
- tests/ci/docker_images/linux-aarch/amazonlinux-2_base/Dockerfile
- tests/ci/docker_images/linux-x86/amazonlinux-2_base/Dockerfile
CryptoAlg-1137
Prepare for bumping cmake dependency requirement to `3.0`.
Next step: deploying to CI infrastructure.
Verified docker image builds and that cmake3 can be executed during build
https://github.com/torben-hansen/aws-lc/pull/6
> Bump docker image cmake dependency to at least 3 0

- tests/ci/cdk/cdk/codebuild/github_ci_linux_arm_omnibus.yaml
https://github.com/awslabs/aws-lc/commit/dc5ad88a1f131aa39c2b19fb3134bd2c49f41629 rebuilt the gcc-11 Docker image. Accordingly, the related ECR tag should get changed.
> Use new gcc-11 Docker image.

- tests/ci/build_run_benchmarks.sh
https://github.com/awslabs/aws-lc/pull/538 uncovered a bug in the benchmark CI script: the path used to source the script `common_posix_setup.sh` is wrong because of a prior `cd ..` before sourcing.
```
+ source tests/ci/common_posix_setup.sh
./tests/ci/build_run_benchmarks.sh: line 21: tests/ci/common_posix_setup.sh: No such file or directory
+ git clone https://github.com/awslabs/aws-lc.git aws-lc-prod
```
This has been silently failing since the refactor in https://github.com/awslabs/aws-lc/pull/435.
Remedy this by utilising the already defined `AWSLC_PR_ROOT`.
Could maybe have moved up the sourcing. But for sake of keeping the order the same, used `AWSLC_PR_ROOT` instead.
A third solution would be to remove it, because clearly it has no use. But I need the definitions in the sourced …
> Correct source script path

- tests/ci/docker_images/linux-x86/centos-7_gcc-4x/Dockerfile
CryptoAlg-1137
Same as https://github.com/awslabs/aws-lc/pull/534 but the Centos 7 image was missed.
Tested Docker image build works locally.
> Install cmake3 in centos 7 docker image

- crypto/bytestring/cbs.c
When gcc-11 was first released, there was a false positive warning that we had to suppress: https://github.com/awslabs/aws-lc/commit/0c52a41d3210bb50188e16da5d280fb047364f0b. GCC-11 has been around for a while now and the bug seems to be fixed, so we're reverting that change. 
N/A
tested on local with our gcc11 docker image.
> Revert suppressed warning in gcc-11

- CMakeLists.txt
- tests/ci/build_run_benchmarks.sh
- tests/ci/common_posix_setup.sh
- tests/ci/run_cryptofuzz.sh
- tests/ci/run_s2n_integration.sh
CryptoAlg-1137
Bump minimal cmake version to 3.0.
To cater for non-unique executable names. First check whether `cmake3` is present. If not, pick `cmake` as executable name. This assumes that `cmake3` is actually at least version 3.0, but I don't know of any OS where this is not the case (covering all the OS's we claim to support).
There are a bunch of inconsistencies in our scripts. I tried using `CMAKE_COMMAND` everywhere. But the same is not true for e.g. `ninja` vs `ninja-build`. Maybe we can fix this in a future PR.
Tried grepping for additional occurrences of using `cmake`:
```
$ pwd
[...]/aws-lc/tests
$ grep -r "cmake " ./ 
.//ci/common_posix_setup.sh:  if command -v cmake &> /dev/null
.//ci/common_posix_setup.sh:    cmake --version
.//ci/run_windows_tests.bat:@echo  LOG: …
```
> Bump minimal cmake version to 3.0

- BUILDING.md
https://github.com/awslabs/aws-lc/pull/538 bumped minimal CMake version to 3.0 at least. https://github.com/awslabs/aws-lc/pull/549 pointed out that some documentation does not reflect this change.
Modify existing documentation to cater for the CMake version bump. Also call out CMake executable name differences
I could not identify other places that needs to cater for `cmake`/`cmake3` differences (through grepping) or the CMake version requirement bump.
> Bump cmake version requirement in BUILDING doc

- tool/CMakeLists.txt
`bssl` tool is not installed. Hence, we don't distribute it.
This change adds an install target to install `bssl` on (e.g.) `ninja-build install`, in turn, making it easier to distribute.
Right now, just installed in root of install directory. That is:
```
% pwd
[...]/aws-lc/awslc-install/lib64
% ls
bssl  /crypto  libcrypto.a  libssl.a  /ssl
```
Ran `ninja-build install` on AL2 instance. Got the output you see in "Call-outs".
> Install bssl as well

- include/openssl/ssl.h
- ssl/ssl_lib.cc
Addresses CryptoAlg-1073
This change unblocks [MySQL 8.0 tls-ciphersuites related build issue](https://github.com/mysql/mysql-server/blame/8d8c986e5716e38cb776b627a8eee9e92241b4ce/vio/viosslfactories.cc#L650-L666).
* `tls-ciphersuites`: https://dev.mysql.com/doc/refman/8.0/en/connection-options.html#option_general_tls-ciphersuites
* [OpenSSL added `|SSL_CTX_set_ciphersuites|` to configure TLS 1.3 specific ciphersuites](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_ciphersuites.html). But the API is added in AWS-LC as no-op due to https://github.com/awslabs/aws-lc/commit/abbbee10ad4739648bcbf36a5ac52f23263a67dd. We can add related code in future if needed(e.g. compatible with OpenSSL). This is just 1st step to unblock the build.
No test is needed because the added impl does …
> Add no-op |SSL_CTX_set_ciphersuites|.

- third_party/jitterentropy/LICENSE
- third_party/jitterentropy/arch/jitterentropy-base-windows.h
- third_party/jitterentropy/arch/jitterentropy-base-x86.h
- third_party/jitterentropy/jitterentropy-base-user.h
- third_party/jitterentropy/jitterentropy-base.c
- third_party/jitterentropy/jitterentropy-base.h
- third_party/jitterentropy/jitterentropy-gcd.c
- third_party/jitterentropy/jitterentropy-gcd.h
- third_party/jitterentropy/jitterentropy-health.c
- third_party/jitterentropy/jitterentropy-health.h
- third_party/jitterentropy/jitterentropy-noise.c
- third_party/jitterentropy/jitterentropy-noise.h
- third_party/jitterentropy/jitterentropy-sha3.c
- third_party/jitterentropy/jitterentropy-sha3.h
- third_party/jitterentropy/jitterentropy-timer.c
- third_party/jitterentropy/jitterentropy-timer.h
- third_party/jitterentropy/jitterentropy.h
CryptoAlg-1195
Import [jitterentropy version 3.4.0](https://github.com/smuellerDD/jitterentropy-library/releases/tag/v3.4.0). The import contains all the special changes and omission we originally did. In particular, the only commit imported is a copyright change:
* https://github.com/smuellerDD/jitterentropy-library/commit/2e5019cfe63038faaa405ce53715effe4ea580e4
See SIM for reasoning.
See SIM for testing and validation performed.
> import Jitter@3.4.0

- util/fipstools/delocate/delocate.peg
- util/fipstools/delocate/delocate.peg.go
Resolves parsing issues for ARMv8 assembly with clang7 on ubuntu 20.04 (Note: found through PR https://github.com/awslabs/aws-lc/pull/566 CI test fails).
- Fix parsing issue in `delocate.peg` for ARM assembly.
- Edit rule `RegisterOrConstant` to allow shifting a register/constant by two digit value (e.g., the case of ARMv8 mask for  SHA3 hardware support) instead of just one digit.
- Add a new rule for allowing addition, subtraction and multiplication in the offset. (Note: useful for looping address accesses, e.g., `#8*($i+2)`). Add a set of `OffsetOperator` to define the operations allowed in the offset. Add a new set of `Offset` rule operations interpreted depending on parenthesis location, if added. 
The parenthesis in the `Offset` rule should be included both or should not be included …
> Fix parse issue in delocate.peg

- crypto/x509/x509_test.cc
To cater for gcc version 4.8.5 (Ubuntu 4.8.5-4ubuntu8).
Note that gcc version 4.8.5 20150623 (Red Hat 4.8.5-44)
doesn't complain.
A problem was reported with the usage of gcc version 4.8.5 (Ubuntu 4.8.5-4ubuntu8):
```
crypto/x509/x509_test.cc:4364:20: error: unterminated raw string
EXPECT_EQ(print, R"(Certificate:
^
```
The string literal was put in a constant in order to avoid having it in a macro causing a problem like the following:
https://godbolt.org/z/Wc8TYaqbf
The version used in our CI in Centos-7 Docker image is gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) which does not incur this error.
It's not tested with our CI so pending customer testing for now.
> Removing the string literal from within the macro.

- tests/ci/run_benchmark_build_tests.sh
- tool/CMakeLists.txt
- tool/speed.cc
Addresses `CryptoAlg-1093`
Fix some of the broken benchmark framework behavior so it can properly work in our CI. The tip of the OpenSSL3.0 branch currently fails so I've chosen to lock down a commit.
N/A
Running `./tests/ci/run_benchmark_build_tests.sh` passes the build.
> Fix benchmarking behavior with other libcryptos

- include/openssl/evp.h
The documentation for EVP_PKEY_new_raw_private_key and EVP_PKEY_new_raw_public_key states that it returns 1 on success and 0 on error. It in fact returns the |EVP_PKEY| on success and NULL on error.
Fix description of EVP_PKEY_new_raw_private_key and EVP_PKEY_new_raw_public_key
> Fix incorrect return type description in evp.h

- tests/ci/cdk/cdk/codebuild/github_ci_linux_arm_omnibus.yaml
- tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
A typo in https://github.com/awslabs/aws-lc/pull/577 caused the CI to fail, this fixes that
This is a simple typo, and the images generated by the CI are present in my personal account. Their names match the name I changed these tests to point to.
> Fixed typo that was causing CI to fail

- tests/ci/cdk/run-cdk.sh
This PR added more validation on CI deployment script.
* Team account can still create CodeBuild to other GitHub repo. That means the creation will use GitHub access token instead of OAuth. Maybe we are also interested in disabling this path.
```sh
./run-cdk.sh --aws-account 12345678 --github-repo-owner awslabs --github-source-version main --action build-linux-img
./run-cdk.sh --aws-account 620771051181 --github-repo-owner awslabs --github-source-version main --action build-linux-img
./run-cdk.sh --github-repo-owner awslabs --github-source-version main --action build-linux-img
```
> Add more validation on CI deployment script.

- crypto/fipsmodule/ec/p384.c
- crypto/fipsmodule/ec/p521.c
N/A
Enable `_alt` s2n-bignum functions in P-384 and P-521 implementation
on iOS. The speedups we get when using the "alternative" s2n-bignum
is shown in the table below. The measurements were done on an iPhone X
with A11 Bionic Arm chip.
```
| Operation           | Before(ops/sec) | After(ops/sec) | Improvement |
| ECDH P-384          |       3122      |      3345      |     1.07x   |
| ECDSA P-384 signing |       8715      |      9124      |     1.05x   |
| ECDSA P-384 verify  |       3431      |      3649      |     1.06x   |
------------------------------------------------------------------------
| ECDH P-521          |       1727      |      2453      |     1.42x   |
| ECDSA P-521 signing |       4363      |      5249      |     1.20x   |
| ECDSA P-521 verify  |       1725      | …
```
> Enable _alt s2n-bignum functions on iOS

- tests/ci/run_analytics.sh
Resolves issue from dashboard review.
Previously the analytics build defined these flags as 0 or 1. However, our C code uses `if defined(SMALL/FIPS/NO_ASM)` which is true as they are defined when the preprocessor runs. This change now only defines the macros when we expect to test that build flavor. I checked `run_posix_tests.sh` and that script does not have this issue.
This wont fix historical data and we will see a sudden drop in these metrics.
Run the script locally with logging, CodeBuild defines the branch for us automatically and my desktop doesn't have that:
```
cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_SMALL=1 -DOPENSSL_NO_ASM=1 -DBUILD_SHARED_LIBS=ON -GNinja /home/ANT.AMAZON.COM/andhop/workplace/oss/aws-lc
aws cloudwatch put-metric-data --timestamp 1661874519 --namespace AWS-LC …
```
> Fix analytic build sizes by not defining CMake build flags (FIPS, SMALL, NO_ASM) when they should be off

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
Prepare new release by bumping release version number string to `1.2.0`. Also bump API version to 19 because of (e.g.) additions of new ciphers.
CI
> Bump version number to 1.2.0 and api version number to 19

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
Resolves P71418080
Prepare new release by bumping release version number string to 1.3.0.
Not raising the API version. 
> Bump version to 1.3.0

- crypto/CMakeLists.txt
Resolves PR620 breaking s2n-tls's CI.
PR620 depended on some additional build changes; this PR makes those changes.
n/a
Compiled non-FIPS and FIPS mode on: macOS (FIPS mode fails as expected there), x86 AL2, ARM AL2.
> Fix jitterentropy linking

- ssl/internal.h
- ssl/ssl_lib.cc
- ssl/test/runner/runner.go
- ssl/tls13_both.cc
Resolves V728984594 and D52012438
AWS-LC currently only allows 32 consecutive key updates before closing the connection. This is a reasonable behavior because a client and server should be sending application data and not just doing key updates for fun. However, OpenSSL and s2n-tls do not restrict consecutive key updates and this breaks some clients when migrating to AWS-LC. 
Reviewed internally in V728984594. I decided not to remove `SSL_R_TOO_MANY_KEY_UPDATES` from ssl.h because some customers might be using the define and we may continue to tweak this restriction in the future.
Updated the lots of key updates tests to expect it to pass and not fail.
> Remove the 32 consecutive KeyUpdate limit for TLS 1.3

- crypto/fipsmodule/rand/urandom.c
This reverts commit 35301400bfaf635057d5840267e45cadfa1f75f4.
We need to revert this to support the 2.6.18 kernel. It might be worth putting this back in with preprocessor directives in the future
Resolves AWS-LC-93
Drops O_CLOEXEC since it doesn't work on very old linux kernels
`ninja-build run tests`
> Revert "Use O_CLOEXEC instead of fcntl(FD_CLOEXEC)"

- tool/speed.cc
PrintWithBytes has two options: text output and JSON output. In JSON output mode it emits a field "numberOfBytes" and also put the number of bytes in the "description" field. This made it hard to aggregate the algorithms without lots of partial matching and was redundant. 
Before:
```
➜  build git:(main) ✗ ./tool/bssl speed -filter EVP-AES-128-GCM
Did 4468000 EVP-AES-128-GCM Encrypt (16 bytes) operations in 1000106us (4467526.4 ops/sec): 71.5 MB/s
Did 4060000 EVP-AES-128-GCM Decrypt (16 bytes) operations in 1000156us (4059366.7 ops/sec): 64.9 MB/s
....
➜  build git:(main) ✗ ./tool/bssl speed -filter EVP-AES-128-GCM -json
[
{"description": "EVP-AES-128-GCM Encrypt (16 bytes)", "numCalls": 4496000, "microseconds": 1000038, "bytesPerCall": 16},
{"description": "EVP-AES-128-GCM Decrypt (16 …
```
> Update speed.cc PrintWithBytes with nicer names

- crypto/kyber/pqcrystals-kyber_kyber512_ref/symmetric.h
- include/openssl/base.h
N/A
- Remove two macros that were added to the Kyber source code without any need (I don't know the reason for this addition).
- Remove the `ossl_params` struct that was part of the initial design of KEM support which was later changed to a new design that doesn't need `ossl_params`.
> Remove macros unnecessarily added in Kyber

- tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
None
Use 2XLARGE compute type for quickcheck SAW proofs. There is an upcoming [change](https://github.com/awslabs/aws-lc-verification/pull/70) in aws-lc-verification that parallels the proof scripts. This change requires more memory than the current compute type can support.
None
This change needs to pass the CI.
> Use 2XLARGE compute type for quickcheck SAW proofs

- tests/ci/run_analytics.sh
- tests/ci/run_fips_tests.sh
Fix an issue where the analytics build fails on the last build for ARM. Supporting the Static FIPS GCC ARM build is tracked in CryptoAlg-1399.
This will also address the false positive in https://github.com/awslabs/aws-lc/pull/677.
Existing CI tests skip the Static FIPS GCC ARM build, the Clang build is still tested.
> Update run_analytics.sh to skip ARM FIPS Static builds with GCC

- crypto/decrepit/rsa/rsa_decrepit.c
- crypto/fipsmodule/rsa/internal.h
- crypto/fipsmodule/rsa/rsa.c
- include/openssl/rsa.h
This reverts commit da59eeb9ea33c24abab7af35c1fb2b75d7462d3a.
Down-stream customer's code requires the previous function signatures.
Reverts changes to RSA function signatures.
Ran local tests in FIPS and non-FIPS modes.
> Revert "Switch RSA_sign to size_t."

- bindings/rust/aws-lc-sys-template/Cargo.toml
- bindings/rust/aws-lc-sys-template/build.rs
- bindings/rust/generate/generate.sh
- bindings/rust/publish/publish.sh
N/A
* Added `generated-src` to the crate, removing need for Perl and Golang.
* Removed `ssl` and other unnecessary files. Verified crate size is now ~5MB.
* Removed dependence on `cmake-rs` so that build options can be passed prior to build path.
* Updated `aws-lc-sys` crate version to `0.2.0`
* Added verification of backwards compatible public api to the `publish.sh` script.
* Set minimum supported rust version to 1.57.0.
* Ran the generate/publish scripts (but didn't publish).  Verified crate size if ~4.8MB:
```
➜ du -h tmp/aws-lc-sys/target/package/aws-lc-sys-0.2.0.crate 
4.8M	tmp/aws-lc-sys/target/package/aws-lc-sys-0.2.0.crate
``` …
> Rust - include generated-src in crate

- include/openssl/base.h
This increments `AWSLC_API_VERSION` so that S2N's build can determine whether or not AWS-LC has a usable Kyber implementation. Long-term we aim to remove S2N's private Kyber implementation and standardize on the one provided by AWS-LC.
[Related PR in S2N](https://github.com/aws/s2n-tls/pull/3634)
- Checked that `AWSLC_API_VERSION` 19 predates the requisite change, so we needed to increment this version number to affect the S2N build
How is this change tested (unit tests, fuzz tests, etc.)? Are there any testing …
> Increment API Version

- crypto/CMakeLists.txt
CryptoAlg-1426
On macOS 11 and higher on Apple Silicon, codesigning is mandatory for
binaries to run. This applies to both executables and dylibs. An ad-hoc
signature is sufficient, and the linker will automatically apply one when
a binary is created (see https://github.com/Homebrew/brew/issues/9082).
When we build libcrypto.dylib the linker automatically signs it. But then
we inject the FIPS integrity hash into libcrypto.dylib which changes the
binary so the signature applied by the linker is obviously not valid
anymore. So when an application, like crypto_test, tries to load
libcrypto.dylib it crashes because the signature is not valid. To work
round this we add an ad-hoc signature to `libcrypto.dylib` after the
FIPS integrity hash is injected.
Point out areas that need special …
> Fix the code signing issue on M1 Macs

- crypto/CMakeLists.txt
On macOS 11 and higher on Apple Silicon, codesigning is mandatory for binaries to run. This applies to both executables and dylibs. An ad-hoc signature is sufficient, and the linker will automatically apply one when a binary is created (see https://github.com/Homebrew/brew/issues/9082).
When we build libcrypto.dylib the linker automatically signs it. But then we inject the FIPS integrity hash into libcrypto.dylib which changes the binary so the signature applied by the linker is obviously not valid anymore. So when an application, like crypto_test, tries to load libcrypto.dylib it crashes because the signature is not valid. To work round this we add an ad-hoc signature to `libcrypto.dylib` after the FIPS integrity hash is injected.
Adds an extra code signing step to the macOS build.
> Fix the code signing issue on M1 Macs (#693)

- tests/ci/run_benchmark_build_tests.sh
- tool/CMakeLists.txt
- tool/bssl_bm.h
- tool/ossl_bm.h
- tool/speed.cc
This fixes an issue when building the benchmark with libcrypto that happens to be AWS-LC. This is useful to test AWS-LC FIPS when new benchmarks are added to mainline that we want to run against an existing FIPS branch. Previously when building the `awslc_bm` we passed in just `crypto` which results in CMake using the `crypto` defined in crypto/CMakeLists.txt, not the libcrypto in `AWSLC_INSTALL_DIR`. This change uses the same pattern as OpenSSL which uses find_library to only search in `AWSLC_INSTALL_DIR`.
Two of the existing benchmarks (trust token and hash to curve) require internal header files. These were already disabled when building with OpenSSL. Currently we don't care a ton about these two functions so I disabled them for external AWS-LC benchmark builds.
Also update …
> Update benchmark to support externally built aws-lc

- tests/ci/build_run_benchmarks.sh
- tool/CMakeLists.txt
In https://github.com/awslabs/aws-lc/pull/686 we changed the tool CMakeList to find the libcrypto library as a part of the build_benchmark function. However, by default CMake caches the result of the find library call and if multiple libcryptos are passed in only the first is used. To get around that create a new variable per libcrypto so CMake doesn't cache the result, CMake 3.21 add a [NO_CACHE](https://cmake.org/cmake/help/latest/command/find_library.html) option to avoid this behavior that we can use in the future.
Also specify the [message as status so it gets printed to stdout](https://cmake.org/cmake/help/latest/command/message.html) and captured by the logs.
Fix build_run_benchmarks.sh so it uses the "locally" built `bssl` executable that gets built as a part of the overall AWS-LC …
> Create a variable per benchmark built to avoid CMake caching the result of find_library

- crypto/CMakeLists.txt
PR #693 added a `codesign` post-build command to be executed when building the FIPS module on an M1 mac. The command was done only if `ARCH` is "aarch64". However, when `NO_ASM` build flag is defined the `ARCH` variable is set to "generic" instead and the `codesign` command is not called. This commit fixes the issue.
> Fix the code signing issue on M1 Macs when NO_ASM=1 (#697)

- tool/speed.cc
Enable the existing AES-256-XTS benchmark that works with OpenSSL 1.0.2. Thanks to Craig for noticing we were missing this data and that OpenSSL already supports it.  
```
ossl_1_0_bm -filter XTS
Did 7435000 AES-256-XTS init and encrypt (16 bytes) operations in 1000062us (7434539.1 ops/sec): 119.0 MB/s
Did 5887000 AES-256-XTS init and encrypt (256 bytes) operations in 1000142us (5886164.2 ops/sec): 1506.9 MB/s
Did 2648000 AES-256-XTS init and encrypt (1350 bytes) operations in 1000018us (2647952.3 ops/sec): 3574.7 MB/s
Did 608000 AES-256-XTS init and encrypt (8192 bytes) operations in 1001113us (607324.0 ops/sec): 4975.2 MB/s
Did 319000 AES-256-XTS init and encrypt (16384 bytes) operations in 1001200us (318617.7 ops/sec): 5220.2 MB/s
Did 7394000 AES-256-XTS init and decrypt (16 bytes) …
```
> Enable AES-256-XTS benchmark for OpenSSL 1.0.* which does support it

- tool/speed.cc
Before the total time would include the time take to run |func| one additional time over the number of times reported by |done|, depending on the function number of calls can be millions or just a few thousand which can skew the results. 
The bigger issue is for FIPS builds this could run a self check the first time which is very slow and skews the results. This is a particular problem if you attempt to filter and only run a subset of the benchmarks. This self check will only be run once per algorithm so the order of tests  (or what tests are run) run can change the results.
Before our FIPS RSA sign look like:
```
./tool/bssl speed -filter RSA
Did 2298 RSA 2048 signing operations in 1000330us (2297.2 ops/sec)
Did 2301 RSA 2048 signing operations in 1001189us (2298.3 ops/sec)
Did 2268 RSA …
```
> Update TimeFunction to avoid FIPS self check time affecting results

- bindings/rust/generate/generate.sh
Resolves `CryptoAlg-1422`
Bumping version number for a new public crate version
N/A
generation script
> Bump aws-lc-sys version number

- ssl/ssl_test.cc
Bug: b:261632678, chromium:1396479
Change-Id: I82f7ce05ece8b5c145d4394dc0d4173e357ce176
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/55585
Reviewed-by: David Benjamin <davidben@google.com>
Commit-Queue: Bob Beck <bbe@google.com>
This fixes the current failing SSLTest.HostMatching test.
> Fix timebomb by disabling time check in this test

- bindings/rust/aws-lc-sys-template/Cargo.toml
- bindings/rust/generate/generate.sh
N/A
The `build_bindgen` file wasn't being published properly along with the crate. This fixes that.
N/A
Tested by running `cargo package --no-verify` on the generated directory. Then ran `cargo test --features generate_bindings` on the produced package.
> fix bindgen feature for aws-lc-sys

- ssl/handshake_client.cc
- ssl/ssl_session.cc
- ssl/ssl_test.cc
Addresses `CryptoAlg-1462` and `V804867912`
Scrutinize found that the client-side's session reuse counter was unreachable. This moves the counter to a more suitable place and adds tests to verify that.
N/A
Added the counter at the bottom of tests where client sessions have been reused
> Move client-side session reuse counter

- third_party/jitterentropy/jitterentropy-base.c
N/A
Jitter: re-establish time_backwards
The check for time_backwards was accidentally lost in the code update
for 3.1.0 version of Jitter. This was fixed in upstream in:
https://github.com/smuellerDD/jitterentropy-library/commit/4ca4173b74afe5d99d852317c21666b2a7e6eca1
> Jitter: re-establish time_backwards

- crypto/x509v3/v3_utl.c
GCC 12 triggers a -Warray-bounds false positive in crypto/x509v3's IPv6 parser. Although v6stat.total cannot exceed 16 because of the callback, GCC doesn't know this and seems to get confused. Checking >= 16 seems to silence it.
The change copied from aws-lc main branch, commit:
26c4d4d3244345d3f513e53dd1af71ec5663f502
By submitting this pull …
> Silence a GCC 12 -Warray-bounds false positive warning.

- tests/ci/cdk/cdk/codebuild/github_ci_linux_arm_omnibus.yaml
- tests/ci/docker_images/linux-aarch/amazonlinux-2022_base/Dockerfile
- tests/ci/docker_images/linux-aarch/amazonlinux-2022_clang-14x/Dockerfile
- tests/ci/docker_images/linux-aarch/amazonlinux-2022_gcc-11x/Dockerfile
- tests/ci/docker_images/linux-aarch/build_images.sh
- tests/ci/docker_images/linux-aarch/push_images.sh
This is a follow up of https://github.com/awslabs/aws-lc/pull/745 which adds ARM CI coverage. The ARM static gcc FIPS build is still skipped because run_fips_tests.sh always skips the static build on ARM and will be addressed in https://github.com/awslabs/aws-lc/pull/744.
* Static FIPS build with GCC 11 is not tested
Built images locally and ran test
> Add ARM AL2022 CI

- crypto/fipsmodule/self_check/self_check.c
- tests/ci/run_fips_tests.sh
- util/fipstools/delocate/delocate.go
- util/fipstools/delocate/delocate.peg
- util/fipstools/delocate/delocate.peg.go
Resolves `CryptoAlg-1399`
This PR fixes the gcc release build for static FIPS on ARM. This had been working on other compiler combinations for ARM, like gcc debug or clang release/debug.
The following steps were done to fix this:
1. Fix three `delocate.peg` parsing issues.
2. An offset exists at the end of `:lo12:.LC9+8`, which `delocate.go` was choking on. Removing the check gets
around this.
3. The gcc release build does not use `.comm` to define common symbols. This creates a gap in the bss accessor functions, so we use `bl` to catch these accessor function symbols instead.
4. Older versions of the gcc assembler maps variables of the same value to each other, and skips label creation. `delocate.go` relies on these labels to determine if a symbol is "known"; if a label doesn't exist, …
> Fix FIPS static release build on ARM for gcc

- crypto/curve25519/curve25519.c
- crypto/curve25519/spake25519.c
- crypto/dsa/dsa.c
- crypto/fipsmodule/rand/rand.c
- include/openssl/curve25519.h
- ssl/ssl_key_share.cc
CryptoAlg-1524
Zeroise private random data immediately after use. This is just good secret value hygiene.
Most is stack-allocated. So, good changes it would be overwritten fairly quickly anyway. Looked in both `/crypto` and `/ssl`, grepping my way through.
CI
> Zeroise private random data on the stack before returning

- tests/ci/cdk/app.py
- tests/ci/cdk/cdk/aws_lc_mac_arm_ci_stack.py
- tests/ci/cdk/cdk/codebuild/github_ci_macos_m1_omnibus.yaml
- tests/ci/cdk/cdk/ssm/m1_tests_ssm_document.yaml
- tests/ci/cdk/run-cdk.sh
- tests/ci/cdk/util/iam_policies.py
- tests/ci/codebuild/macos-aarch/run_m1_tests.yml
- tests/ci/common_ssm_setup.sh
- tests/ci/run_bm_framework.sh
- tests/ci/run_m1_ec2_instance.sh
- tests/ci/setup.py
Resolves `CryptoAlg-1423`
The framework of this was taken from our original benchmarking framework. The CDK stack creates a Codebuild, Cloudwatch, and M1 ec2 instance resources, while we use the aws cli to spin up an M1 ec2.
When a Codebuild job is kicked off, we use SSM (Systems Manager) to send a command document to our M1 ec2. The results of this can be observed in a Cloudwatch URL printed on the Console.
* I envision this CI stack as something temporary we can to address our M1 CI gap. The end goal would be for us to migrate to GIthub Action's M1 Mac workflows when they make that available. This seems to be very near on the horizon (set for Q3 2023: https://github.com/github/roadmap/issues/528)
* I've put the non-FIPS and FIPS tests within the same SSM document, so we can get all …
> Add CI that uses M1 Mac ec2 Instance

- tests/ci/run_m1_ec2_instance.sh
Addresses `CryptoAlg-1423`
The m1 ec2 script wasn't failing correctly when the SSM command failed. This fixes that.
N/A
Tested in two PR runs on a local fork:
* https://github.com/crypto-alg/aws-lc/pull/7
* https://github.com/crypto-alg/aws-lc/pull/6
> Small fix for M1 ec2 CI script

- tests/ci/android/AWSLCAndroidTestRunner/app/build.gradle
- tests/ci/cdk/cdk/codebuild/github_ci_android_omnibus.yaml
- tests/ci/codebuild/android/run_android_fips_shared.yml
- tests/ci/codebuild/android/run_android_fips_static.yml
- tests/ci/kickoff_devicefarm_job.sh
N/A
The Android static FIPS build has confirmed to be working now.
N/A
Device Farm in Android CI 
> Turn on static FIPS build for Android CI

- crypto/x509/x509_test.cc
- crypto/x509v3/v3_genn.c
- include/openssl/x509v3.h
V819878264
Fixes a type confusion related to CVE-2023-0286.
CI
> Improve X.509 GeneralName parsing.

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
V819878264
Prepare new release by bumping release version number string to `1.0.3`.
> Bump release FIPS version to v1.0.3

- bindings/rust/aws-lc-fips-sys-template/Cargo.toml
- bindings/rust/aws-lc-fips-sys-template/build/bindgen.rs
- bindings/rust/aws-lc-sys-template/Cargo.toml
- bindings/rust/aws-lc-sys-template/build/bindgen.rs
- bindings/rust/generate/generate-fips.sh
- bindings/rust/generate/generate.sh
N/A
* Updated to bindgen 0.64 -- this fixes the problem of prefixes appearing on the bindings of external variables.
* Updated generation logic to ensure that the symbols file (used for prefixing) aligns with the AWS-LC source being used.
N/A
I generated both the `aws-lc-sys` (cfbc38bfbd72cfb1a680d0483381b2e93b9a3e73) and `aws-lc-fips-sys` (da2a8839affb1db4d9e3b361182c9bee16f48976) crates.
> Update Rust crate bindgen

- bindings/rust/aws-lc-fips-sys-template/build/main.rs
- bindings/rust/generate/generate-fips.sh
- bindings/rust/generate/generate.sh
- tests/ci/docker_images/rust/README.md
N/A
* Use distinct prefix in `aws-lc-fips-sys` to avoid potential symbol conflict in clients.
* Fix bug in script.
N/A
I generated the `aws-lc-fips-sys` crate and checked the resulting symbols:
```
❯ nm -g target/debug/build/aws-lc-fips-sys-e53936c72cf350ee/out/build/crypto/libaws_lc_fips_0_5_0crypto.a | head 
a_bitstr.c.o:
U __assert_fail
0000000000000000 T aws_lc_fips_0_5_0_ASN1_BIT_STRING_check
U aws_lc_fips_0_5_0_ASN1_BIT_STRING_free
0000000000000000 T aws_lc_fips_0_5_0_ASN1_BIT_STRING_get_bit
0000000000000000 T aws_lc_fips_0_5_0_asn1_bit_string_length
U aws_lc_fips_0_5_0_ASN1_BIT_STRING_new
0000000000000000 T aws_lc_fips_0_5_0_ASN1_BIT_STRING_num_bytes
0000000000000000 T aws_lc_fips_0_5_0_ASN1_BIT_STRING_set
```
By submitting this pull request, I confirm that my contribution is made …
> Different symbols prefix for FIPS crate

- crypto/curve25519/curve25519.c
- crypto/fipsmodule/bn/exponentiation.c
- crypto/fipsmodule/ec/p256.c
- crypto/fipsmodule/rsa/rsa.c
- crypto/internal.h
- crypto/rsa_extra/rsa_test.cc
- include/openssl/rsa.h
Cherry pick the RSA_set0_key change and value_barrier_w change from main.
We only need this pr or https://github.com/aws/aws-lc/pull/822 (which includes everything from main). This change has the minimal set of changes to pass the CI and include the e change.
CI
> Allow keys without e in RSA_set0_key

- tool/speed.cc
Related: CryptoAlg-1587
For e.g. TLS, the entire flow is really "public key" generation and computation of the shared secret. For X25519, the AWS-LC functions doing that are: `X25519_public_from_private()` and `X25519()`. Where the latter also includes the randomness generation work.
ATM, we only repot these individually. But to make comparison with e.g. `bssl speed -filter ECDH` easy, we should output the performance of the entire flow as well.
> Measure entire X25519 work for easy comparison with ECDH

- tests/ci/cdk/app.py
- tests/ci/cdk/cdk/aws_lc_mac_arm_ci_stack.py
- tests/ci/cdk/cdk/codebuild/github_ci_macos_m1_omnibus.yaml
- tests/ci/cdk/cdk/ssm/m1_tests_ssm_document.yaml
- tests/ci/cdk/util/iam_policies.py
- tests/ci/codebuild/macos-aarch/run_m1_tests.yml
- tests/ci/common_ssm_setup.sh
- tests/ci/run_bm_framework.sh
- tests/ci/run_m1_ec2_instance.sh
- tests/ci/setup.py
Cherry pick the two commits from main that added M1 CI:
* https://github.com/aws/aws-lc/commit/0ca969a07b66967b6de498deead603e70d559790
* https://github.com/aws/aws-lc/commit/1ccaebeb9a1c877d309337a93ff2c2c75d36f4e8
Without this change CI that runs against the fips-2022-11-02 branch fails with:
> [Container] 2023/02/20 00:05:46 Phase context status code: YAML_FILE_ERROR Message: stat /codebuild/output/src084154334/src/github.com/aws/aws-lc/tests/ci/cdk/cdk/codebuild/github_ci_macos_m1_omnibus.yaml: no such file or directory
> Add M1 CI to the fips-2021-10-20-1MU branch

- crypto/fipsmodule/bn/bn_test_to_fuzzer.go
- crypto/obj/objects.go
- crypto/x509/test/make_basic_constraints.go
- ssl/test/runner/hpke/hpke_test.go
- ssl/test/runner/runner.go
- ssl/test/runner/sharding.go
- ssl/test/runner/tls.go
- tests/check_licenses.go
- util/ar/ar_test.go
- util/compare_benchmarks.go
- util/convert_comments.go
- util/convert_wycheproof.go
- util/doc.go
- util/embed_test_data.go
- util/fetch_ech_config_list.go
- util/fipstools/acvp/acvptool/acvp.go
- util/fipstools/acvp/acvptool/acvp/acvp.go
- util/fipstools/acvp/acvptool/interactive.go
- util/fipstools/acvp/acvptool/test/check_expected.go
- util/fipstools/break-hash.go
- util/fipstools/break-kat.go
- util/fipstools/delocate/delocate.go
- util/fipstools/delocate/delocate_test.go
- util/fipstools/inject_hash/inject_hash.go
- util/run_android_tests.go
Resolves: CryptoAlg-1439
[This commit](https://github.com/google/boringssl/commit/5511fa833c96c8caa9b51c13367f057c74d850eb) was skipped due to out of date go version in our CI. They were all updated in https://github.com/aws/aws-lc/pull/811 and now we can take this change.
I fixed conflicts by keeping our existing logic and updating it to use `os` for everything.
Built locally, CI will check all the other versions.
> Migrate io/ioutil uses to new APIs.

- tests/ci/cdk/app.py
- tests/ci/cdk/cdk/aws_lc_mac_arm_ci_stack.py
- tests/ci/cdk/cdk/codebuild/github_ci_macos_m1_omnibus.yaml
- tests/ci/cdk/cdk/ssm/m1_tests_ssm_document.yaml
- tests/ci/cdk/util/iam_policies.py
- tests/ci/codebuild/macos-aarch/run_m1_tests.yml
- tests/ci/common_ssm_setup.sh
- tests/ci/run_bm_framework.sh
- tests/ci/run_m1_ec2_instance.sh
- tests/ci/setup.py
Cherry pick the two commits from main that added M1 CI:
* https://github.com/aws/aws-lc/commit/0ca969a07b66967b6de498deead603e70d559790
* https://github.com/aws/aws-lc/commit/1ccaebeb9a1c877d309337a93ff2c2c75d36f4e8
Without this change CI that runs against the fips-2022-11-02 branch fails with:
> [Container] 2023/02/20 00:05:46 Phase context status code: YAML_FILE_ERROR Message: stat /codebuild/output/src084154334/src/github.com/aws/aws-lc/tests/ci/cdk/cdk/codebuild/github_ci_macos_m1_omnibus.yaml: no such file or directory
> Add M1 CI to the fips-2022-11-02 branch

- third_party/jitterentropy/jitterentropy-base.c
- third_party/jitterentropy/jitterentropy-noise.c
- third_party/jitterentropy/jitterentropy-noise.h
- third_party/jitterentropy/jitterentropy-sha3.c
- third_party/jitterentropy/jitterentropy-sha3.h
- third_party/jitterentropy/jitterentropy.h
Resolves CryptoAlg-1535
Fix the M1 Jitter build by apply the hashstate patch from upstream Jitter to our copy of jitter. The fips-2021-10-20-1MU branch contains a copy of jitter is somewhere between v3.1.0 (which is on the fips-2021-10-20 branch) and v3.4.0 (which is what is currently on AWS-LC mainline). Those changes were made to take the Windows support from v3.4.0 and back port the changes to v3.1.0.
This PR diverges slightly from the upstream patch in one way: our version of jitter on this branch already had the SHA state change from https://github.com/smuellerDD/jitterentropy-library/commit/fee20a0010c25a7120d022b6a0c86f8491a6ac93. This causes the patch to not apply cleanly and needed to be tweaked to handle the difference.
Passes locally on my M1 mac, currently running 1 million …
> Apply hashstate patch to jitter

- crypto/ocsp/internal.h
- crypto/ocsp/ocsp_client.c
- crypto/ocsp/ocsp_http.c
- crypto/ocsp/ocsp_test.cc
- include/openssl/ocsp.h
Addresses `CryptoAlg-1536`
Add supporting functions and tests for `OCSPRequest`
Taken from: 
* https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/crypto/ocsp/ocsp_ht.c
* https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/crypto/ocsp/ocsp_cl.c
Code from OpenSSL was cleaned up to adhere to our code styling and library tools, but the actual logic stays the same.
Basic tests to test functions do what they should achieve
> Supporting functions for OCSP Request

- CMakeLists.txt
- crypto/CMakeLists.txt
- ssl/CMakeLists.txt
- tests/ci/run_windows_tests.bat
- tool/CMakeLists.txt
N/A
Currently AWS-LC's `RelWithDebInfo` build type fails when the library is being built in FIPS mode on Windows. This is unfortunate because ATSEC needs to be able to debug the library as a part of their process. This build fixes the `RelWithDebInfo` build on Windows and outputs `.pdb` files to facilitate debugging in Visual Studio.
This change replaces the `-g` flag with `/Zi` when running with MSVC in `RelWithDebugInfo` mode, which is used by Visual Studio to produce debug symbols.
Changes tested by ensuring the build now successfully produces debug files with the appropriate flags and that it is able to be used in the Visual Studio debugger. Also checked for any performance degradations (there were none) and ensured that no other flags were enabled that would make `RelWithDebInfo` not …
> Fix RelWithDebInfo with FIPS build on Windows

- CMakeLists.txt
- crypto/kyber/README.md
- crypto/kyber/pqcrystals_kyber_ref_common/verify.c
When Kyber's common reference code was imported, changes were made to the `verify` function to avoid a compiler warning that occurs on MSVC. However, the logic was inconsistent with the original reference code. This PR reverts the modification back to be consistent with [the original reference code](https://github.com/pq-crystals/kyber/blob/master/ref/verify.c#L24).
All existing unit tests have been run and are passing. This is expected to fail the MSVC CI test as written. The suppressed warnings list will be updated once I get the warning ID.
> Revert Kyber verify

- CMakeLists.txt
- crypto/CMakeLists.txt
- ssl/CMakeLists.txt
- tests/ci/run_windows_tests.bat
- tool/CMakeLists.txt
Move Windows FIPS RelWithDebInfo fix into fips-2021-10-20-1MU branch
> Move Windows FIPS RelWithDebInfo fix into fips-2021-10-20-1MU branch

- crypto/fipsmodule/rsa/rsa.c
- crypto/rsa_extra/rsa_test.cc
- include/openssl/rsa.h
CryptoAlg-1523/CryptoAlg-1626
This PR reverts the change from #756 and enables the "relaxed" RSA key import by default.
> Allow RSA keys with d > n to be imported

- crypto/fipsmodule/rsa/rsa.c
- crypto/rsa_extra/rsa_test.cc
- include/openssl/rsa.h
CryptoAlg-1626
Revert 80044b4ca and enable the "relaxed" RSA key import
by default. This will allow parsing RSA keys with d > n.
Previously, we ensured that |key->d| is bounded by |key->n|.
This ensures bounds on |RSA_bits| translate to bounds on
the running time of private key operations.
However, due to some users (V804729436) having to deal with private keys
that are valid but violate this condition we had to remove it.
The main concern for keys that violate the condition (the potential
DoS attack vector) is somewhat alleviated with the hard limit on
the size of RSA keys we allow.
How is this change tested (unit tests, fuzz tests, etc.)? Are there any testing steps …
> Allow RSA keys with d > n to be imported (#844)

- .github/workflows/stale_issue.yml
Adds the [aws-actions/stale-issue-cleanup](https://github.com/aws-actions/stale-issue-cleanup) GitHub Action to cleanup stale issues or pull requests.
It is currently configured to do the following:
* An issue or pull request is created to the repository.
* If the last comment on the issue/pr is over 4 days old then the issue/pr is marked as stale with the `closing-soon`/`no-pr-activity` labels.
* `response-request` can be applied to an issue/pr to indicate that a response is requested. If present the label application time is used for determining whether the issue is stale (labelTime + 4 days). If a comment is provided the label is removed automatically.
* `automation-exempt` can be applied to disable automatic closure of an issue or pull request.
* If an issue/pr has been marked with …
> Add Stale Issue GitHub Workflow

- util/fipstools/test_fips.c
Addresses CryptoAlg-1641
AWS-LC currently only tests a few AES functions as a part of its tooling in `test_fips.c`. However, as a part of ATSEC's process, they wish to be able to step into functions for AES-CCM, ECB, CTR, AND KW with a debugger and thus have requested that we add them to our testing script.
In the interest of not having to repeat this patch for future validations, these functions were added to the `test_fips` tool the intention to bring these changes into the main, FIPS 1MU, and FIPS 2022 branches. Additionally, it would likely be prudent to bring the self_checks for the main and FIPS 2022 branches in line with these changes in another PR.
N/A
Changes tested by ensuring that all tests still pass and that the output of the `test_fips` tool is as expected.
By submitting …
> Add AES-CCM/ECB/CTR/KW to 'test_fips' tool

- crypto/asn1/a_gentm.c
- crypto/asn1/a_time.c
- crypto/asn1/a_utctm.c
- crypto/asn1/asn1_test.cc
- crypto/x509/internal.h
- crypto/x509/x509_test.cc
- crypto/x509/x509_time_test.cc
- crypto/x509/x509_vfy.c
- crypto/x509/x509_vpm.c
- include/openssl/asn1.h
- include/openssl/x509.h
Addresses `CryptoAlg-1562`
BoringSSL commit: https://github.com/google/boringssl/commit/6e20b77e6b79069e2468686bdc69169d3fa2252e
The new OCSP function for `OCSP_check_validity` has some usage for `time_t` internally, so we decided to pull in this commit early. Pulling this in early lets us do the implementation right the first time.
N/A
CI
> Upstream Merge: Get rid of time_t usage internally, change to int64_t

- CMakeLists.txt
- crypto/evp_extra/evp_extra_test.cc
- crypto/evp_extra/p_kem.c
- crypto/evp_extra/p_kem_asn1.c
- crypto/fipsmodule/sha/asm/keccak1600-armv8.pl
- crypto/kem/internal.h
- crypto/kem/kem.c
- crypto/kyber/README.md
- crypto/kyber/pqcrystals_kyber_ref_common/verify.c
- generated-src/ios-aarch64/crypto/fipsmodule/keccak1600-armv8.S
- generated-src/linux-aarch64/crypto/fipsmodule/keccak1600-armv8.S
- generated-src/win-aarch64/crypto/fipsmodule/keccak1600-armv8.S
- include/openssl/evp.h
N/A
Cherry-picked three commits from the main branch:
- Revert Kyber verify (#841)
- KEM: fix key retrieval when public/secret key is missing (#855)
- Avoid potential for buffer overflow in SHA3 ARMv8 assembly (#863)
> Fix for bugs in the KEM implementation and SHA3

- crypto/fipsmodule/cpucap/cpu_intel.c
- crypto/fipsmodule/cpucap/internal.h
- crypto/fipsmodule/ec/p384.c
- crypto/fipsmodule/ec/p521.c
CryptoAlg-1577
The goal of this PR is to close a performance gap between FIPS static and FIPS shared build. The latter is more performant in some cases.
`OPENSSL_ia32cap_P` is a global, initialised, mutable variable. And hence, will typically go to `.bss`.  However, the location of the `.bss` segment is not known before program load-time. Hence, dereferences of `OPENSSL_ia32cap_P` in code must be filled in by the loader. This modifies `.text` before it's mapped into memory, in turn, would make any hash over (part of) `.text` unpredictable. This is bad for FIPS, which requires a deterministic hash over part of `.text` to implement the integrity check.
All of this is already known though and there already exist an implement solution! We are only concerned about the static FIPS build. The …
> Use function reference to get cpu capability vector at the C-level

- tests/ci/run_analytics.sh
We unintentionally broke our analytics CI with this change: https://github.com/aws/aws-lc/pull/865
This updates the CI to follow the symlink. Also updated the script to use the static FIPS build while I was at it.
N/A
CI
> Update analytics script to correspond to previous changes

- crypto/fipsmodule/bcm.c
- crypto/fipsmodule/fips_shared_library_marker.c
For it's Windows FIPS build, AWS-LC currently does not specify bss segment markers, and also sets the const segment to use the same markers as the data segment. This is a problem as that means that data that can change may end up in the constant section and vice versa. This PR fixes this by creating dedicated markers for the const and bss segments.
N/A
Built and tested on Windows platform to ensure that the changes work.
> Add Missing Windows FIPS Segment Markers

- crypto/fipsmodule/bcm.c
- util/all_tests.json
N/A
AWS-LC currently does not explicitly check that `OPENSSL_ia32cap`is not in the fips module during it's integrity check. Additionally, it only runs the urandom test - always returns success on x86 shared builds - with the environment variable set. This has proven to be a problem as outlined in the description for PR https://github.com/aws/aws-lc/pull/878.
As such, this PR adds checks to the integrity check and also tests `crypto_test` with the variable set in order to ensure that any change that accidentally adds OPENSSL_ia32cap back into the fips module is caught in the future.
N/A
Built locally on Windows x86 and MacOS arm to …
> Add checks to ensure that OPENSSL_ia32cap is not in the fips module

- util/fipstools/delocate/delocate.go
Executing `go test` (which executes `delocate.go` tests), results in:
```
$ go test
./delocate.go:1422:18: fmt.Errorf format %s has arg classification of wrong type boringssl.googlesource.com/boringssl/util/fipstools/delocate.instructionType
FAIL    boringssl.googlesource.com/boringssl/util/fipstools/delocate [build failed]
```
The enum type `instructionType` doesn't have an unwrap. I believe. In fact, not entirely sure how `Errorf` translates `%w` and it's argument. Instead, just stringify the enum type `instructionType` and pass that up the stack to pretty-print.
After these changes, we get:
```
$ go test
PASS
ok      boringssl.googlesource.com/boringssl/util/fipstools/delocate    0.011s
```
Modelled `delocate.go` call stack for the error as an attempt to verify changes work as …
> Stringify enum to pretty-print errors

- include/openssl/aead.h
- include/openssl/bio.h
- include/openssl/cipher.h
- include/openssl/crypto.h
- include/openssl/dh.h
- include/openssl/digest.h
- include/openssl/evp.h
- include/openssl/ocsp.h
- include/openssl/rc4.h
- include/openssl/rsa.h
- include/openssl/service_indicator.h
- include/openssl/sshkdf.h
- tests/ci/codebuild/linux-x86/pre-push.yml
- util/doc.config
- util/doc.go
Resolves CryptoAlg-1628
1. Update existing header files to match the expected format:
1. Comments for a symbol must start with the name of the symbol
2. Overall header file and per section preambles must be followed by two blank lines
3. C++ macro must be preceeded by two blank lines
2. Update pre-push.yml to build the documentation and ensure it all parses
The documentation is not pushed anywhere. To view it locally run `cd util && go run ./doc.go` and then open headers.html in a web browser.
Ran `go run ./doc.go` locally, the CI will also check it now. CodeBuild pre-push has:
```
[Container] 2023/03/21 22:04:03 Running command (cd util && go run ./doc.go)
[Container] 2023/03/21 22:04:05 Phase complete: BUILD State: SUCCEEDED
```
By submitting this pull request, I confirm that my …
> Fix existing documentation issues and build the docs in our CI

- tests/ci/run_analytics.sh
- tool/CMakeLists.txt
Resolves `P84022616`
Internal imports are finding broken symlinks. CMake doesn't seem to support relative path symlinks, so directly removing it and using `awslc` from now should resolve our issues. 
N/A
N/A
> Revert back to using bssl

- crypto/fipsmodule/bn/internal.h
- crypto/fipsmodule/bn/prime.c
- crypto/fipsmodule/dh/dh.c
- crypto/rsa_extra/rsa_test.cc
- include/openssl/bn.h
- include/openssl/crypto.h
- include/openssl/dh.h
* BN_GENCB_set_old sets old style callbacks on BN_GENCB
* DH_clear_flags which is a no op
* Define but don't support DH_FLAG_CACHE_MONT_P, AWS-LC always uses montgomery multiplication for DH
I considered using the existing [callback_wrapper](https://github.com/aws/aws-lc/blob/main/crypto/decrepit/dh/dh_decrepit.c#L57-L68) pattern used in DH_generate_parameters. However, that function can keep the `wrapped_callback` on the stack and not worry about memory management. For this use case users can call `BN_GENCB_set_old` directly. This would require allocating  `wrapped_callback` on the heap, but they don't expect to have to clean up any memory, and BN_GENCB_free wouldn't be able to tell what if anything it has to free. 
Therefore, using a union and `type` in bn_gencb_st seemed like the …
> Add missing APIs to better support Bind

- crypto/fipsmodule/sha/asm/keccak1600-armv8.pl
- crypto/fipsmodule/sha/keccak1600.c
- crypto/fipsmodule/sha/sha3_test.cc
- generated-src/ios-aarch64/crypto/fipsmodule/keccak1600-armv8.S
- generated-src/linux-aarch64/crypto/fipsmodule/keccak1600-armv8.S
- generated-src/win-aarch64/crypto/fipsmodule/keccak1600-armv8.S
Resolves CryptoAlg-1671
The idea behind this new test draws from [stack canaries](https://en.wikipedia.org/wiki/Buffer_overflow_protection#Canaries). Basically, we append a segment of memory with well-known contents to our output buffer, failing the test if that canary value changes after the call to SHA3_Squeeze. This methodology isn't perfect, as it won't detect cases where the function overwrites the canary segment with that same canary value (`0xff` in this case). If we wanted to improve this, we might fill the canary with random data, however the static value is enough to catch the motivating overflow in testing.
Interestingly, we [mark all ARM assembly `.globl`s as `.hidden`](https://github.com/aws/aws-lc/commit/3ab3e3db6e5e060612d9f2172aa0efa3ff8f55a3), making it impossible to …
> Add SHA3_Squeeze output buffer overflow test

- crypto/digest_extra/digest_test.cc
- crypto/fipsmodule/digest/digest.c
- crypto/fipsmodule/sha/sha3.c
- crypto/fipsmodule/sha/sha3_test.cc
- include/openssl/digest.h
- tool/speed.cc
- util/fipstools/acvp/modulewrapper/modulewrapper.cc
Partially addresses CryptoAlg-1665
For the deprecated opt-in functions, we modify the getter to always
return true and modify the setter to be a no-op as SHA3 is now always
enabled.
- CI checks
---
> Enable SHA3, deprecate its opt-in functions

- crypto/fipsmodule/digest/internal.h
- crypto/fipsmodule/ecdsa/ecdsa.c
- crypto/fipsmodule/hmac/hmac.c
Resolves `CryptoAlg-1720`
Zeroize HMAC padding and key block data immediately after use. Also add zeroization of k in ECDSA. This is for FIPS.
Benchmarking results are in the internal SIM. No noticeable regressions were found.
Original HMAC tests pass
> Zeroize data immediately after use for FIPS

- include/openssl/bn.h
N/A
* Added flag allowing library consumers to indicate that calls to `BN_set_flags` can be ignored.
* openssh still has logic that uses `BN_set_flags`.  A [recent change to openssh](https://github.com/openssh/openssh-portable/commit/3c527d55f906e6970d17c4cab6db90ae9e013235) similar to this one allows it to more easily compile against BoringSSL.
* With this change and the one for [PR 894](https://github.com/aws/aws-lc/pull/894), I built and tested OpenSSH-8.9p1 (with PKCS11 disabled) against AWS-LC.
> Build flag AWS_LC_INTERNAL_IGNORE_BN_SET_FLAGS

- CMakeLists.txt
- crypto/CMakeLists.txt
- crypto/fipsmodule/CMakeLists.txt
- crypto/test/CMakeLists.txt
- fuzz/CMakeLists.txt
- ssl/CMakeLists.txt
- ssl/test/CMakeLists.txt
- tool/CMakeLists.txt
- util/fipstools/CMakeLists.txt
- util/fipstools/acvp/modulewrapper/CMakeLists.txt
While working on this fix it became apparent that these 4 changes were required to be merged at one time. "Make boringssl_gtest_main a STATIC library" is needed to fix an issue with old CMake versions in "Clean up test_support_lib and GTest dependencies slightly" and the same for removing the global target.
I think this will fix the missing CMake dependency that is causing my issue in https://github.com/aws/aws-lc/pull/920.
> Cherry pick recent CMake changes

- util/fipstools/delocate/delocate.go
- util/fipstools/delocate/testdata/generic-FileDirectives/out.s
- util/fipstools/delocate/testdata/x86_64-BSS/out.s
- util/fipstools/delocate/testdata/x86_64-Basic/out.s
- util/fipstools/delocate/testdata/x86_64-GOTRewrite/out.s
- util/fipstools/delocate/testdata/x86_64-LabelRewrite/out.s
- util/fipstools/delocate/testdata/x86_64-LargeMemory/out.s
- util/fipstools/delocate/testdata/x86_64-Sections/out.s
- util/fipstools/delocate/testdata/x86_64-ThreeArg/out.s
CryptoAlg-1577
See [#856](https://github.com/aws/aws-lc/pull/856) for background and description of issue resolved in this PR.
This is the second PR out of two PRs that bridge the performance gap.
See ticket for performance comparisons.
The first PR took care of the C-level. But the machine-optimised algorithm implementation sometimes directly dereference `OPENSSL_ia32cap_P`. These also need to be fixed-up. As before, we can't just add a call instruction to `OPENSSL_ia32cap_get` because it would compromise soundness/correctness.
Recall, that the issue was the `add` instruction. Instead of injecting that instruction, we instead do the following for each occurrence of `OPENSSL_ia32cap_P` discovered in the textual assembly:
* Define a new unique symbol. Uniquness is ensured using both the …
> Reference OPENSSL_ia32cap_P at x86 machine code level through a unique symbol instead of a common offset symbol avoiding add instruction

- third_party/s2n-bignum/arm/curve25519/curve25519_x25519.S
- third_party/s2n-bignum/arm/curve25519/curve25519_x25519_alt.S
- third_party/s2n-bignum/arm/curve25519/curve25519_x25519base.S
- third_party/s2n-bignum/arm/curve25519/curve25519_x25519base_alt.S
- third_party/s2n-bignum/x86_att/curve25519/curve25519_x25519.S
- third_party/s2n-bignum/x86_att/curve25519/curve25519_x25519_alt.S
- third_party/s2n-bignum/x86_att/curve25519/curve25519_x25519base.S
- third_party/s2n-bignum/x86_att/curve25519/curve25519_x25519base_alt.S
CryptoAlg-1601
Follow-up to https://github.com/aws/aws-lc/pull/916.
Update s2n-bignum subtree with x25519 implementation. This is the initial import of curve25519 backends.
New copy of https://github.com/aws/aws-lc/pull/921 because of Git...
Importing:
- ./x86_att/curve25519/curve25519_x25519.S
- ./x86_att/curve25519/curve25519_x25519base.S
- ./x86_att/curve25519/curve25519_x25519_alt.S
- ./x86_att/curve25519/curve25519_x25519base_alt.S 
- ./arm/curve25519/curve25519_x25519.S
- ./arm/curve25519/curve25519_x25519base.S
- ./arm/curve25519/curve25519_x25519_alt.S
- ./arm/curve25519/curve25519_x25519base_alt.S
Next up is hooking up these as backend for x25519 in AWS-LC.
These implementation are verified upstream. No code in AWS-LC currently pass through this. …
> Import s2n-bignum x25519

- crypto/fipsmodule/rand/rand.c
CryptoAlg-1728
Introduces a static code configuration that uses rdrand as seed entropy source when the following conditions (at compile-time) are met:
* x86 isa
* assembly is allowed
* not in deterministic mode (we don't use this mode)
One could fall back to the default source when conditions above are not met. But it would introduce either a larger code delta (I would rip out the jitter code), or would leave dead code.
We can't just shift everything to rdrand either, since rdrand is strictly an x86 thing. That is, it would cause many of the CI dimensions to fail.
We continue to draw
* additional seeding material from OS source
* prediction resistance material from either rdrand or OS source. It still depends and no logic in this part has changed.
The seed entropy source has changed …
> Framework to support multiple entropy sources

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
* TLS 1.3 Transfer Support (https://github.com/aws/aws-lc/pull/891)
* SHA3 is always enabled now, and opt-in is no longer required. Deprecated opt-in functions. (https://github.com/aws/aws-lc/pull/898)
> Release v1.7.0

- crypto/fipsmodule/cpucap/cpucap.c
https://github.com/aws/aws-lc/pull/692 added aes_gcm_encrypt_avx512 to the flags and updated the external declaration in the [header file](https://github.com/aws/aws-lc/blame/main/crypto/internal.h#L1023-L1024), but the actual size of BORINGSSL_function_hit is still only 7. 
Working on an unrelated change locally with GCC 11.3.0 caught this:
```
workplace/oss/aws-lc/crypto/fipsmodule/cpucap/cpucap.c:76:16: error: conflicting types for ‘BORINGSSL_function_hit’; have ‘uint8_t[7]’ {aka ‘unsigned char[7]’}
76 | HIDDEN uint8_t BORINGSSL_function_hit[7] = {0};
|                ^~~~~~~~~~~~~~~~~~~~~~
In file included from workplace/oss/aws-lc/crypto/fipsmodule/cpucap/cpucap.c:13:
workplace/oss/aws-lc/crypto/fipsmodule/cpucap/../../internal.h:1044:16: note: previous declaration of …
```
> Update size of BORINGSSL_function_hit to account for new aes_gcm_encrypt_avx512

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
* Improves support for OpenSSH ([#894](https://github.com/aws/aws-lc/pull/894))
* **Bug fix**: Added back `ASN1_STRING_clear_free` which was incorrectly removed in `v1.7.0`. ([#936](https://github.com/aws/aws-lc/pull/936))
* **Bug fix**: `BORINGSSL_function_hit` array size did not match updated header definition ([#934](https://github.com/aws/aws-lc/pull/934))
> Release v1.8.0

- crypto/curve25519/curve25519.c
- crypto/curve25519/spake25519.c
- crypto/fips_callback_test.cc
- crypto/fipsmodule/bn/random.c
- crypto/fipsmodule/cipher/e_aes.c
- crypto/fipsmodule/rand/internal.h
- crypto/fipsmodule/rand/rand.c
- crypto/fipsmodule/rsa/padding.c
- crypto/hpke/hpke.c
- crypto/hrss/hrss.c
- crypto/pool/pool.c
- crypto/trust_token/pmbtoken.c
- crypto/trust_token/voprf.c
- tests/ci/run_fips_callback_tests.sh
Addresses CryptoAlg-1738
`RAND_bytes` has always returned an `int` but most callers assumed it would never fail. And there was no path that anything besides 1 could be returned, if any issue did happen it would `abort`. This PR adds a potential failure path that AWS-LC needs to handle, and updates all libcrypto callers. We could handle libssl in a separate PR. I believe this is okay for know because:
1. non-FIPS builds of AWS-LC will still abort, the only place that returns 0 is in the FIPS build
2. No one is currently using FIPS libcrypto with libssl
The most interesting logic/behavior changes are in:
* rand_nonzero
* ED25519_keypair/X25519_keypair
* HRSS_decap/HRSS_encap/HRSS_generate_key
All callers of RAND_bytes in libcrypto code now handle the return value. 
Existing unit tests and a …
> Update RAND_bytes to return return 0 on failure

- tool/bssl_bm.h
- tool/speed.cc
Add an AWS-LC FIPS specific benchmark for Jitter.
Sample output:
```
./tool/bssl speed -filter Jitter -chunks 10,20,40,80,160
Did 198 Jitter (10 bytes) operations in 1043768us (189.7 ops/sec): 0.0 MB/s
Did 209 Jitter (20 bytes) operations in 1094657us (190.9 ops/sec): 0.0 MB/s
Did 99 Jitter (40 bytes) operations in 1037250us (95.4 ops/sec): 0.0 MB/s
Did 66 Jitter (80 bytes) operations in 1036942us (63.6 ops/sec): 0.0 MB/s
Did 39 Jitter (160 bytes) operations in 1022004us (38.2 ops/sec): 0.0 MB/s
./tool/bssl speed -filter Jitter -chunks 10,20,40,80,160 -json
[
{"description": "Jitter", "numCalls": 195, "microseconds": 1036469, "bytesPerCall": 10},
{"description": "Jitter", "numCalls": 190, "microseconds": 1018698, "bytesPerCall": 20},
{"description": "Jitter", "numCalls": 99, …
```
> Add Jitter speed test for FIPS build

- tool/speed.cc
The canary currently fails to run the new benchmark code with the old 2022 branch which still has SHA3 off by default.
> Support older versions of AWS-LC that still need SHA3 turned on

- crypto/fipsmodule/modes/xts_test.cc
V874784593
XTS mode is sorta build to allow the tweak to change in a cheap way; requiring only one block cipher invocation on that tweak. The API supports this by setting the key argument to `NULL` but the "IV" argument (which is really the tweak when choosing the XTS implementation) to whatever tweak value desired.
Add unit tests to verify this and maintain the functionality in the future.
The tweak is typically the sector number and incremented for each 512 bytes. Using a non-NULL key input when changing the tweak is a lot of overhead: 2 AES key setup operations. For 512 bytes, the 2 key setup operations is almost equal to performing the actual encryption/decryption.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and …
> Ensure XTS mode API allows only re-initialising the tweak

- crypto/fips_callback_test.cc
- tests/ci/run_fips_callback_tests.sh
Addresses CryptoAlg-1737
Add two new tests to make sure the RSA and EC pairwise tests can be broken and call the new FIPS callback as expected.
This just worked when `BORINGSSL_FIPS_abort` was updated to the new logic in `AWS_LC_FIPS_error` in all of libcrypto including these two pairwise tests.
This passes locally. 
> Add RSA and EC FIPS pairwise failure tests with the new callback

- crypto/fipsmodule/aes/asm/aesv8-armx.pl
- crypto/fipsmodule/modes/xts_test.cc
- generated-src/ios-aarch64/crypto/fipsmodule/aesv8-armx.S
- generated-src/linux-aarch64/crypto/fipsmodule/aesv8-armx.S
- generated-src/win-aarch64/crypto/fipsmodule/aesv8-armx.S
- tests/ci/cdk/cdk/codebuild/github_ci_linux_arm_omnibus.yaml
Fixes: CVE-2023-1255
The buffer overread happens on decrypts of 4 mod 5 sizes. Unless the memory just after the buffer is unmapped this is harmless. This issue was reported on 27th February 2023 by Anton Romanov (Amazon). The fix was developed by Nevine Ebeid (Amazon).
See OpenSSL master branch commit
https://github.com/openssl/openssl/commit/72dfe46550ee1f1bbfacd49f071419365bc23304 The fix is also available in commit bc2f61ad (for 3.1) and commit 02ac9c94 (for 3.0).
> aesv8-armx.pl: Avoid buffer overread in AES-XTS decryption

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
N/A
* Provide a compile option to disable AVX512-specific optimizations ([#945](https://github.com/aws/aws-lc/pull/945))
* aesv8-armx.pl: Avoid buffer overread in AES-XTS decryption  ([#970](https://github.com/aws/aws-lc/pull/970))
> Release v1.9.0

- util/generate_build_files.py
Removes 50% of the code from `generate_build_files.py` which are never used. Probably a remnant from years ago when first changing this script to feed AWS-LC needs.
Consuming Perl-generated machine implementations and Go generated files are done by cmake scripts.
```
$ cp -r generated-src/ ../generated_source
$ rm -rf ./generated-src
$ python3 util/generate_build_files.py 
$ diff -rq generated-src/ ../generated_source/
<empty>
$ git diff
<empty>
```
```
$ cmake3 -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(pwd)/../awslc-install -DBUILD_SHARED_LIBS=OFF -DDISABLE_PERL=ON .. 
$ ninja-build run_tests
[...]
All tests passed!
```
```
$ cmake3 -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(pwd)/../awslc-install -DBUILD_SHARED_LIBS=OFF -DDISABLE_GO=ON .. 
$ ninja-build …
```
> Remove cruft from generate build script

- crypto/fipsmodule/ec/p384.c
- crypto/fipsmodule/ec/p521.c
Decide in runtime which s2n-bignum functions to call for P-384/521 field arithmetic. This gives us small improvement in the performance of P-384/521 operations on Graviton 3 (and any other non-Apple aarch64 processor). Performance (ops/s) measured on GV 3 c7g.4xlarge instance:
```
Operation           |  Before  |  After  | Speedup  |
----------------------------------------------------
P-384 ECDH          |   2975   |  3329   |  x1.12   |
P-384 ECDSA sign    |   8345   |  8871   |  x1.06   |
P-384 ECDSA verify  |   3306   |  3659   |  x1.11   |
P-521 ECDH          |   1603   |  2141   |  x1.33   |
P-521 ECDSA sign    |   3819   |  4466   |  x1.17   |
P-521 ECDSA verify  |   1599   |  2025   |  x1.27   |
```
While I'm here, replace calls to `OPENSSL_ia32cap_get()` with corresponding …
> P-384/521 runtime check for s2n-bignum on aarch64

- crypto/ocsp/ocsp_print.c
- crypto/ocsp/ocsp_test.cc
- include/openssl/ocsp.h
Resolves `CryptoAlg-1564`
Once https://github.com/aws/aws-lc/pull/901 is merged in, these should be the only OCSP functions left we'll need to support for the time being.
N/A
N/A
> Add support for OCSP_REQUEST_print and OCSP_RESPONSE_print

- tool/bssl_bm.h
- tool/ossl_bm.h
- tool/speed.cc
Makes it possible to measure performance of the function `DH_check()`.
Generating DH parameters for higher bit sizes gets pretty slow.
```
$ ./tool/bssl speed -filter dhcheck -timeout 10 -primes 2048,4096
DH check speed test is very slow. Speed test works best with higher timeouts.
Did 16 DH check(s) (2048 bits) operations in 10164348us (1.574 ops/sec)
Did 3 DH check(s) (4096 bits) operations in 15465898us (0.194 ops/sec)
$ ./tool/bssl speed -filter dhcheck -timeout 2 -primes 1024 -json
[
{"description": "DH check(s)", "numCalls": 20, "microseconds": 2045047, "primeSizePerCall": 1024}
]
```
**Checking new `-chuncks` and `-primes` parsing**
```
$ ./tool/bssl speed -filter EVP-AES-128-GCM -chunks 20,50,56
Did 5489000 EVP-AES-128-GCM encrypt init operations in 1000135us (5488259.1 ops/sec) …
```
> Add DH_check support to perf tool

- tool/speed.cc
While working on https://github.com/aws/aws-lc/pull/957, we noticed that we could use some benchmarks for `EC_KEY_generate_key(_fips)` as well.
N/A
N/A
> Add benchmarks for EC_KEY_generate_key(_fips)

- tests/ci/devicefarm_job.py
- tests/ci/run_formal_verification.sh
- tests/ci/setup.py
Fixes experimental fips refactoring branch CI.
Disables inline Formal Verification because it fails with some error unrelated to actual verification
```
[15:39:51.759] Loading file "/codebuild/output/src924307727/src/github.com/aws/aws-lc-verification-build/SAW/proof/AES/goal-rewrites.saw"
--
217 | [15:39:51.837] Loading file "/codebuild/output/src924307727/src/github.com/aws/aws-lc-verification-build/SAW/proof/AES/goal-rewrites-AES.saw"
218 | [15:49:13.840] Loading file "/codebuild/output/src924307727/src/github.com/aws/aws-lc-verification-build/SAW/proof/AES/AES.saw"
219 | [15:50:09.744] Loading file "/codebuild/output/src924307727/src/github.com/aws/aws-lc-verification-build/SAW/proof/AES/GHASH.saw"
220 | [15:50:10.088] Warning: function never returns
221 | Abort due to assertion …
```
> Fix ci experimental fips refactoring

- .github/PULL_REQUEST_TEMPLATE.md
After: https://raw.githubusercontent.com/torben-hansen/aws-lc/68c4238166ccea9844e7c9720651b3d493ede7f1/.github/PULL_REQUEST_TEMPLATE.md
before: https://raw.githubusercontent.com/aws/aws-lc/main/.github/PULL_REQUEST_TEMPLATE.md
One appeared as below:
> Describe AWS-LC’s current behavior and how your code changes that behavior. If there are no issues this pr is resolving, **trailing new-line**
Another one appeared in the license text as this:
>By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and **trailing new-line**
No code harmed
> Fix two trailing new-lines in PR template

- crypto/x509/internal.h
- crypto/x509/x509_cmp.c
- crypto/x509/x509_test.cc
- crypto/x509/x_pubkey.c
- include/openssl/x509.h
Resolves `CryptoAlg-1725`
mySQL consumes the `X509_get0_pubkey` API when building with OpenSSL1.1.1/AWS-LC, and uses the `X509_get_pubkey` when built with OpenSSL1.0.2. `X509_get0_pubkey` seems to have been added in OpenSSL1.1.1 and is very similar to `X509_get_pubkey` (which exists in AWS-LC).
`X509_get_pubkey` attempts to decode the public key for certificate x. If successful it returns the public key as an `EVP_PKEY pointer` with its reference count incremented: this means the returned key must be freed up after use. `X509_get0_pubkey` is similar except it does not increment the reference count of the returned `EVP_PKEY` so it must not be freed up after use.
N/A
N/A
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and the …
> Add support for X509_get0_pubkey

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
Update minor release number. [Looking at the 72 commits since the v1.9.0 release](https://github.com/aws/aws-lc/compare/v1.9.0...main) there are new APIs/Functioanlity (e.g. Dilithium, s2n-bignum runtime check) but the changes are all backward compatible. 
Test pass locally.
> Bump AWSLC_VERSION_NUMBER_STRING to 1.10.0

- crypto/conf/conf.c
- include/openssl/conf.h
- include/openssl/err.h
- include/openssl/ssl.h
- ssl/ssl_cert.cc
Resolves `CryptoAlg-1726`
mySQL consumes the `CONF_modules_unload` API when building with OpenSSL1.1.1/AWS-LC. `CONF_modules_unload` is used to finish and unload configuration modules in OpenSSL, but AWS-LC doesn't use the same configuration module logic. The `Conf_modules_*` family of functions in AWS-LC are all no-op functions, so we follow the same pattern here.
mySQL consumes the `SSL_CTX_get_security_level` API. The definition of security levels is defined here in OpenSSL's documentation: https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_security_level.html
We should only be using `SSL_CTX_get_security_level` to retrieve a security level number. Actually using `SSL_CTX_set_security_level` to configure security levels in AWS-LC is not supported. I've set the returned number to 3, …
> Add additional no-op symbols for support mySQL

- include/openssl/ssl.h
- ssl/ssl_lib.cc
- ssl/ssl_test.cc
Resolves `CryptoAlg-1852`
mySQL consumes the `SSL_(read/peek/write)_ex` family of APIs from OpenSSL1.1.1. These are similar to the existing `SSL_(read/peek/write)` APIs in AWS-LC, but have slightly different expected parameters and function signatures.
Since these have the same underlying operations, I just wrapped `SSL_*_ex` around it's respective `SSL_*` operation.
* More information can be found in OpenSSL's documentation here: https://www.openssl.org/docs/man1.1.1/man3/SSL_read_ex.html
N/A
I extended an existing test suite that was testing the `SSL_pending` and `SSL_(read/peek/write)`, and created one that used `SSL_(read/peek/write)_ex` instead.
> Add support for SSL_(read/peek/write)_ex

- CMakeLists.txt
- tests/ci/devicefarm_job.py
- tests/ci/run_fips_tests.sh
- tests/ci/setup.py
- util/fipstools/CMakeLists.txt
See PR for "main" branch: https://github.com/aws/aws-lc/pull/1012
N/A
* Previously when building for FIPS with both `-DBUILD_LIBSSL=OFF` and `-DBUILD_TESTING=OFF`, CMake produces an error, and the subsequent build attempt fails.
```
> cmake "-DFIPS=1" "-DBUILD_LIBSSL=OFF" "-DBUILD_TESTING=OFF" ../aws-lc
...
-- Configuring done
CMake Error: Cannot determine link language for target "modulewrapper".
CMake Error: CMake can not determine linker language for target: modulewrapper
-- Generating done
-- Build files have been written to: /home/justsmth/repos/AWS-LC-BUILD
```
* Added a build using these flags to the CI.
N/A
Successfully built using these flags:
```
> cmake "-DFIPS=1" "-DBUILD_LIBSSL=OFF" "-DBUILD_TESTING=OFF" ../aws-lc
...
-- Found Threads: TRUE  
-- Configuring done
-- Generating …
```
> Only build acvp/modulewrapper with BUILD_TESTING

- tool/speed.cc
Refactor our EVP AES GCM benchmark to support both GCM and CTR mode benchmarking. 
In the AES CTR mode benchmark I do not increment the counter. I think this is a more fair comparison with the AES GCM benchmark because it also reuses the IV. In theory we could add a separate benchmark that just increments the counter, or just generates new GCM IVs.
On an m1 mac:
```
./tool/bssl speed -filter EVP-AES-128-GCM
Did 7354000 EVP-AES-128-GCM encrypt init operations in 1000010us (7353926.5 ops/sec)
Did 20196500 EVP-AES-128-GCM encrypt (16 bytes) operations in 1000001us (20196479.8 ops/sec): 323.1 MB/s
Did 12446000 EVP-AES-128-GCM encrypt (256 bytes) operations in 1000045us (12445440.0 ops/sec): 3186.0 MB/s
Did 4585500 EVP-AES-128-GCM encrypt (1350 bytes) operations in 1000025us (4585385.4 …
```
> Add AES CTR benchmark

- include/openssl/ssl.h
- ssl/internal.h
- ssl/s3_lib.cc
- ssl/s3_pkt.cc
- ssl/ssl_lib.cc
- ssl/ssl_test.cc
- ssl/tls13_both.cc
Resolves `CryptoAlg-1851`
mySQL consumes `SSL_get_key_update_type` along with `SSL_KEY_UPDATE_NONE` when building with OpenSSL1.1.1.  OpenSSL indicates that: 
> SSL_get_key_update_type() can be used to determine whether a key update operation has been scheduled but not yet performed. The type of the pending key update operation will be returned if there is one, or SSL_KEY_UPDATE_NONE otherwise.
AWS-LC does have existing related symbols (`SSL_key_update` and `SSL_KEY_UPDATE_(NOT_)REQUESTED`) and a `key_update_pending` boolean in the underlying SSL3 structure which may seem to be reusable in this case.
However, in OpenSSL, `SSL_get_key_update_type` has 3 possible values (`SSL_KEY_UPDATE_REQUESTED`, `SSL_KEY_UPDATE_NOT_REQUESTED`, `SSL_KEY_UPDATE_NONE`). We could return `SSL_KEY_UPDATE_NONE` …
> add support for SSL_get_key_update_type and SSL_KEY_UPDATE_NONE

- crypto/dilithium/p_dilithium3.c
- crypto/dilithium/p_dilithium3_asn1.c
- crypto/dilithium/p_dilithium_test.cc
- crypto/evp_extra/internal.h
Dilithium `EVP_PKEY` structs can have:
1. both public and private keys (from key generation)
1. only public key (from deserialization)
1. only private key (from deserialization)
Dilithium keys are also very large, so it's preferable to allocate these
keys on the heap as needed to save potentially unused stack space.
Resolves V845897935
- CI checks
---
> Heap-allocate Dilithium keypair members

- crypto/fipsmodule/aes/asm/aesni-xts-avx512.pl
Fixes a build failure seen on the `quay.io/pypa/manylinux1_x86_64` container image as reported by the AWS Common Runtime team.
```
[  2%] Generating aesni-xts-avx512.S
Can't modify division (/) in division (/) at /root/aws-c-auth/build/deps/aws-lc/crypto/fipsmodule/aes/asm/aesni-xts-avx512.pl line 3061, near "0;"
(Might be a runaway multi-line // string starting on line 3060)
Execution of /root/aws-c-auth/build/deps/aws-lc/crypto/fipsmodule/aes/asm/aesni-xts-avx512.pl aborted due to compilation errors.
gmake[2]: *** [crypto/fipsmodule/aesni-xts-avx512.S] Error 255
gmake[1]: *** [crypto/fipsmodule/CMakeFiles/fipsmodule.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[  2%] Generating cipher_extra/chacha20_poly1305_x86_64.S
[  3%] Generating cipher_extra/aes128gcmsiv-x86_64.S …
```
> Fix aesni-xts-avx512 to support Perl v5.8.8

- crypto/fipsmodule/rand/cpu_jitter_test.cc
- crypto/fipsmodule/rand/internal.h
- crypto/fipsmodule/rand/rand.c
Previously, we were calling the |jent_entropy_read_safe| Jitter function to get entropy. This function has a built-in recover mechanism where if the source fails to produce entropy then the function changes some parameters and tries again. Due to FIPS rules, this is not possible any more. We change the call to |jent_entropy_read| instead and handle the potential failure in the AWS-LC part of the module by retrying three times (note that in this case the same entropy source parameters do not change).
Point out areas that need special attention or support during the review process. …
> Change the Jitter entropy recovery mechanism

- crypto/fipsmodule/rand/cpu_jitter_test.cc
- crypto/fipsmodule/rand/internal.h
- crypto/fipsmodule/rand/rand.c
Previously, we were calling |jent_entropy_read_safe| Jitter function to get entropy. This function has a built-in recover mechanism where if the source fails to produce entropy then the function changes some parameters and tries again. Due to FIPS rules, this is not possible any more. We change the call to |jent_entropy_read| instead and handle the potential failure in the AWS-LC part of the module by retrying three times (note that in this case the same entropy source parameters do not change).
(cherry picked from commit 64d8a6b4b1f518173d07edd25a22a09f5d7e6c3d)
> Change the Jitter entropy recovery mechanism (#1058)

- CMakeLists.txt
- crypto/ocsp/ocsp_test.cc
N/A
This broke the build during our internal import. I root caused it and discovered it was due to an ancient GCC bug.
I've documented it and we should add it to our build to prevent further import failures.
N/A
Turning on the warnings without the test tweak fails the build.
Change also tested in internal build.
> Add -Wmissing-braces to C++ build

- tests/ci/README.md
We have enabled Valgrind on AArch64 in PR#978. The README was missing to include it in the Valgrind section.
> Update CI README to include Valgrind on AArch64

- crypto/x509/name_print.c
- crypto/x509/x509_req.c
Resolves V935691760
Fix potential NULL pointer dereference in two places.
> Fix potential NULL pointer dereference

- tests/ci/cdk/cdk/aws_lc_github_ci_stack.py
- tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml
- tests/ci/codebuild/integration/mysql_integration.yml
- tests/ci/common_posix_setup.sh
- tests/ci/docker_images/linux-x86/ubuntu-22.04_base/Dockerfile
- tests/ci/docker_images/linux-x86/ubuntu-22.04_gcc-12x/Dockerfile
- tests/ci/integration/run_mysql_integration.sh
- tests/ci/integration/run_openssh_integration.sh
- tests/ci/integration/run_postgres_integration.sh
- tests/ci/integration/run_s2n_integration.sh
Resolves `CryptoAlg-1859`
We've recently resolved missing symbols for mySQL and are looking to add a CI dimension to ensure we don't break the build. This doesn't run the tests yet since there are test failures still pending investigation, so this just runs the build.
N/A
New CI dimension
> add integration build CI dimension for mySQL

- include/openssl/ssl.h
- include/openssl/x509.h
- ssl/internal.h
- ssl/ssl_test.cc
- ssl/ssl_x509.cc
Resolves CryptoAlg-1876
Add SSL_get0_verified_chain which returns the verified chain from an SSL. The built in X509 verifier is responsible for saving the reference to the verified chain if verification is successful.
Like other `get0` methods this does not increase the reference counter and the caller is not expected to free the chain when they are done with it. 
However, this change does use `X509_STORE_CTX_get1_chain` to get and own a reference to the chain so it persists after the verification is done. 
Add a new basic test that ensures only the chain needed for verification is returned. Still working on a full integration test.
> Add SSL_get0_verified_chain 

- include/openssl/ssl.h
- ssl/ssl_test.cc
Addresses CryptoAlg-1875
[OpenSSL uses this enum](https://github.com/openssl/openssl/blob/674b61ebd982d6a6564ac1f90d8cde22371564bc/include/openssl/ssl.h.in#L1011-L1066) for possible states returned from `SSL_get_state`.
[AWS-LC can only return these two values](https://github.com/aws/aws-lc/blob/main/ssl/ssl_lib.cc#L2585-L2587) so I only included them in this enum. 
Added a simple test that checks both states match.
> Add OSSL_HANDSHAKE_STATE enum for OpenSSL compatability

- crypto/x509/x509_test.cc
- crypto/x509/x509_vpm.c
- include/openssl/x509.h
Resolves `CryptoAlg-1865`
A dig into some of the mySQL/AWS-LC test failures revealed that this was the root cause.
* https://github.com/mysql/mysql-server/blob/8.0/router/src/harness/src/tls_client_context.cc#L100
* https://github.com/mysql/mysql-server/blob/8.0/vio/viosslfactories.cc#L709
BoringSSL briefly made this backwards compatible, but enforced the stricter check a week later since Chrome was not effected by this.
* https://github.com/aws/aws-lc/commit/e759a9cd84198613199259dbed401f4951747cff
* https://github.com/aws/aws-lc/commit/1902d818ac4fef9497dfe5d0ce6f2c99f585bdff
This doesn't apply to us however, so we're reverting the strict check in an attempt to be more compatible with OpenSSL.
I've reverted the check for `X509_VERIFY_PARAM_set1_email` while I was at it as well. …
> align X509_VERIFY_PARAM host and email behavior with OpenSSL

- crypto/x509/x509_vpm.c
- include/openssl/x509.h
V946151180
Use build-in memory copy function for a `string` type.
> Use build-in string-copy function

- BUILDING.md
Document and tidy up required dependency versions.
https://github.com/aws/aws-lc/pull/1075 will require Golang 1.18.
No code harmed.
> Light tidy up of required dependency versions

- crypto/x509v3/v3_conf.c
- crypto/x509v3/v3_lib.c
- crypto/x509v3/v3_prn.c
- include/openssl/x509v3.h
Resolves `CryptoAlg-1906`
This reapplies the commit that was reverted in https://github.com/aws/aws-lc/pull/1054. OCSP nonce extensions can't migrate directly to the "new-style" X509V3_EXT_METHODs, so there's still some code we have to keep around.
On the bright side, we can still enforce the new `ext->it` non-NULL requirement in `X509V3_EXT_add`  for external users. Not all of the code is used for OCSP nonce extensions, so I've kept most of the optimizations from the BoringSSL commit. Only the code necessary for OCSP is left.
Only the code in `crypto/x509v3/v3_conf.c` and `crypto/x509v3/v3_prn.c` was reverted back to the "old-style". 
Observable in this commit: https://github.com/aws/aws-lc/commit/3c1f8ade0df8cb5556480441919a455a807bb6e5
CI
By submitting this pull request, I confirm that …
> Reapply "Remove support for "old-style" X509V3_EXT_METHODs"

- crypto/fipsmodule/rand/urandom_test.cc
The way the PRNG model is written looks more complicated than what is actually needed. Attempt to re-write it. This also makes it slightly easier to amend with future potential changes.
Only tested on x86_64. Some surprises might arise when running through the CI dimensions.
> Make PRNG model slightly more readable

- ssl/internal.h
- ssl/ssl_cert.cc
- ssl/ssl_test.cc
- ssl/ssl_x509.cc
Resolves `CryptoAlg-1935`
This reverts some of the changes done in https://github.com/aws/aws-lc/commit/3a2b47ab5be5c75edacb8cdc246dc2dc8fb2c0cd. 
AWS-LC/BoringSSL also allows external data to be associated with the X509 structures with the same APIs. However, our SSL connections don't directly save the X509 certificate as a structure within `SSL_CTX`. We "fold" the certificate and convert it into a binary blob to maintain within `SSL_CTX`. The certificate is not parsed back into an `X509` until the user asks for it.
This creates issues when the user attempts to associate data with the certificate with `X509_set_ex_data` and passes the certificate into `SSL_CTX`. The data usually associated is not ASN.1 code, thus non-parsable, and the associated data gets lost during the translation to …
> Save leaf certificate in SSL early to avoid losing external data

- crypto/CMakeLists.txt
- ssl/CMakeLists.txt
Fixes an issue seen in aws-lc-rs where this would cause CMake to generate the makefile / ninja-build descriptions with the directory included using `-isystem` rather then `-I`. This affects resolution order for headers as system includes are ranked lower in priority then `-I` includes.
It seemed appropriate to fix this here, BoringSSL similarly has this marked as just public: https://github.com/google/boringssl/blob/master/crypto/CMakeLists.txt#L304
> Mark include as PUBLIC not SYSTEM PUBLIC

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
* Update CI README to include Valgrind on AArch64 by @nebeid in https://github.com/aws/aws-lc/pull/1066
* Additional tests for failure modes for KEM API by @dkostic in https://github.com/aws/aws-lc/pull/1048
* Fix potential NULL pointer dereference by @dkostic in https://github.com/aws/aws-lc/pull/1067
* add integration build CI dimension for mySQL by @samuel40791765 in https://github.com/aws/aws-lc/pull/1051
* add integration test CI dimension for MariaDB by @samuel40791765 in https://github.com/aws/aws-lc/pull/1046
* Add SSL_get0_verified_chain  by @andrewhop in https://github.com/aws/aws-lc/pull/1055
* Add OSSL_HANDSHAKE_STATE enum for OpenSSL compatability by @andrewhop in https://github.com/aws/aws-lc/pull/1070
* Upstream merge 2023-06-26 by @dkostic in …
> Release v1.12.0

- CMakeLists.txt
N/A
* Disables two warnings generated when compiling with "Visual Studio 17 2022".
* Build succeeds for both shared and static build on Windows/x86-64.
N/A
Tested on Windows Server 2019 EC2 instance:
```
\aws-lc\build> cmake -DBUILD_SHARED_LIBS=1 ..
-- Building for: Visual Studio 17 2022
-- The C compiler identification is MSVC 19.36.32535.0
...
repos\aws-lc\build> cmake --build .
MSBuild version 17.6.3+07e294721 for .NET Framework
Checking Build System
Building Custom Rule C:/Users/Administrator/repos/aws-lc/CMakeLists.txt
...
```
> Disable two "Visual Studio 17 2022" warnings

- crypto/ocsp/ocsp_test.cc
- crypto/ocsp/ocsp_verify.c
- include/openssl/ocsp.h
- sources.cmake
Resolves `CryptoAlg-1849`
Asides from the behavior fixed in https://github.com/aws/aws-lc/pull/1074, there was some slight OCSP errors when building with nginx's OCSP stapling tests. There are still a couple of tests failing due to us missing multiple certs support, but this should resolve all other issues with us failing the test.
* https://github.com/nginx/nginx-tests/blob/master/ssl_stapling.t
1. The NULL check in `ocsp_find_signer_sk` static function was a bit too pedantic, so I relaxed it. It's possible for the OCSP Basic response to be missing a cert stack, so we shouldn't be throwing an error on the stack if that happens.
2. Implemented functionality for the two OCSP flags, `OCSP_NOVERIFY` and `OCSP_TRUSTOTHER`
N/A
N/A
By submitting this pull request, I confirm that my contribution …
> Align OCSP behavior with OpenSSL for nginx

- include/openssl/ocsp.h
There were a few OCSP symbols that were accidentally not exported
> Missing export symbols for OCSP

- tests/ci/integration/run_haproxy_integration.sh
While working on the HAProxy CI change in https://github.com/andrewhop/haproxy/pull/1 the [HAProxy CI which uses a shared AWS-LC build found an issue](https://github.com/andrewhop/haproxy/actions/runs/5534691073/jobs/10099976679?pr=1#step:12:556) with three new OCSP functions not exported. Once those are exported this CI will pass and unblock their CI.
This will need to be updated with the OCSP header change from https://github.com/aws/aws-lc/pull/1091 to work.
This adds a new build for the existing HAProxy CI.
> Turn on shared library build with HAProxy

- .github/workflows/aws-lc-rs.yml
Pin the CI to use nightly due to changes introduced in aws-lc-rs: https://github.com/aws/aws-lc-rs/commit/3a454a77020b65ee13ff64abb35c7e12a5f64adf
> fix rust sanity check CI

- tool/speed.cc
V963870416
Attempts to silence the static analyser...
`EC_KEY_get0_public_key` doesn't validate the pointer argument and can de-reference `NULL`. This is common for the getters. Avoid changing that behaviour and just fix-up the speed tool code instead using a non-owning pointer.
> Silence static analyser by validating pointer prior to function call

- .github/CODEOWNERS
Configures GitHub CODEOWNERS file to be used with the branch protection rules.
See [About code owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) for more information. This is used over in aws-lc-rs as well.
> (fips-2022-11-02) Add GitHub CODEOWNERS

- .github/CODEOWNERS
Configures GitHub CODEOWNERS file to be used with the branch protection rules.
See [About code owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) for more information. This is used over in aws-lc-rs as well.
> (fips-2021-10-20-1MU) Add GitHub CODEOWNERS

- LICENSE
Address https://github.com/aws/aws-lc/issues/1099 by improving the readability of our LICENSE file.
> Improve LICENSE readability

- include/openssl/ssl.h
- ssl/internal.h
- ssl/ssl_cert.cc
- ssl/ssl_lib.cc
- ssl/ssl_privkey.cc
- ssl/ssl_x509.cc
- ssl/tls13_both.cc
Addresses `CryptoAlg-1844`
This doesn't actually implement multiple cert functionality, but sets up the structures to do so. All certs currently use the first index (`SSL_PKEY_RSA`) during the SSL connection. 
A subsequent PR will be introduced to implement usage of the new certificate slots.
Overall functionality of the code shouldn't be effected right now, this is just letting the code point to new pointers.
Original tests
> add back CERT_PKEY structure and refactor pointers

- crypto/dh_extra/dh_test.cc
- crypto/fipsmodule/dh/check.c
Addresses CVE-2023-3446 which was low severity issue reported to OpenSSL on July 13th 2023. (See [bulletin](https://www.openssl.org/news/secadv/20230719.txt).
Excessively long DH keys can be slow to check which may lead to denial of service.
> Fix DH_check() excessive time with oversized modulus

- .github/CODEOWNERS
Configures GitHub CODEOWNERS file to be used with the branch protection rules.
See [About code owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) for more information. This is used over in aws-lc-rs as well.
> Add GitHub CODEOWNERS

- crypto/fipsmodule/aes/asm/aesv8-armx.pl
- crypto/fipsmodule/aes/asm/vpaes-armv8.pl
- crypto/fipsmodule/cpucap/cpucap.c
- crypto/fipsmodule/modes/asm/aesv8-gcm-armv8-unroll8.pl
- crypto/fipsmodule/modes/asm/aesv8-gcm-armv8.pl
- crypto/fipsmodule/sha/asm/sha512-armv8.pl
- crypto/impl_dispatch_test.cc
- crypto/internal.h
- generated-src/ios-aarch64/crypto/fipsmodule/aesv8-armx.S
- generated-src/ios-aarch64/crypto/fipsmodule/aesv8-gcm-armv8-unroll8.S
- generated-src/ios-aarch64/crypto/fipsmodule/aesv8-gcm-armv8.S
- generated-src/ios-aarch64/crypto/fipsmodule/sha256-armv8.S
- generated-src/ios-aarch64/crypto/fipsmodule/sha512-armv8.S
- generated-src/ios-aarch64/crypto/fipsmodule/vpaes-armv8.S
- generated-src/linux-aarch64/crypto/fipsmodule/aesv8-armx.S
- generated-src/linux-aarch64/crypto/fipsmodule/aesv8-gcm-armv8-unroll8.S
- generated-src/linux-aarch64/crypto/fipsmodule/aesv8-gcm-armv8.S
- generated-src/linux-aarch64/crypto/fipsmodule/sha256-armv8.S
- generated-src/linux-aarch64/crypto/fipsmodule/sha512-armv8.S
- generated-src/linux-aarch64/crypto/fipsmodule/vpaes-armv8.S
- generated-src/win-aarch64/crypto/fipsmodule/aesv8-armx.S
- generated-src/win-aarch64/crypto/fipsmodule/aesv8-gcm-armv8-unroll8.S
- generated-src/win-aarch64/crypto/fipsmodule/aesv8-gcm-armv8.S
- generated-src/win-aarch64/crypto/fipsmodule/sha256-armv8.S
- generated-src/win-aarch64/crypto/fipsmodule/sha512-armv8.S
- generated-src/win-aarch64/crypto/fipsmodule/vpaes-armv8.S
Addresses CryptoAlg-1873 by unblocking https://github.com/aws/aws-lc/pull/1045
Currently AWS-LC only checks whether the correct hardware code is being reached on x86 and x86_64 and not aarch64. This PR fixes that so that we can ensure that the correct code path is taken whenever change OPENSSL_armcap on aarch64 systems.
N/A
Tests pass locally
> Add BoringSSL Dispatch Test for aarch64

- tests/ci/docker_images/linux-x86/ubuntu-22.04_base/Dockerfile
- tests/ci/integration/run_haproxy_integration.sh
This installs the remaining missing test dependencies so our CI agrees with HAProxy's CI and the only failing test is `ssl_dh.vtc` due to our libssl not supporting FFDH ciphersuites. My proposed change in https://github.com/andrewhop/haproxy/pull/1 will turn off this test when built with AWS-LC for now. 
Also removed the duplicate `curl` on line 28 and 50 of the Dockerfile.
The filtering can be removed if HAProxy takes the change proposed in https://github.com/andrewhop/haproxy/pull/1. 
Before:
```
0 tests failed, 23 tests skipped, 140 tests passed
```
After:
```
0 tests failed, 9 tests skipped, 165 tests passed
```
> Run additional HAProxy tests

- crypto/fipsmodule/FIPS.md
- crypto/fipsmodule/rand/rand.c
- util/fipstools/break-tests.sh
CryptoAlg-2001
CRNGT is not a requirement for FIPS 140-3.
FIPS 140-2 Section 4.9.2 required the execution of the Continuous Randomness Number Generation Test (CRNGT). However, this requirement is not present in FIPS 140-3. In addition, later stages of FIPS 140-2 this test was not mandatory in all cases either (cf. FIPS 140-2 IG 9.8).
Executing this test requires maintaining state, which inevitably introduces complexity. Given CRNGT is redundant with respect to compliance and really provides zero practical value (see, again, FIPS 140-2 IG 9.8), we axe it.
See CryptoAlg-2001.
> Remove CRNGT

- crypto/fipsmodule/aes/asm/aesv8-armx.pl
- crypto/fipsmodule/aes/asm/vpaes-armv8.pl
- crypto/fipsmodule/modes/asm/aesv8-gcm-armv8-unroll8.pl
- crypto/fipsmodule/modes/asm/aesv8-gcm-armv8.pl
- crypto/fipsmodule/sha/asm/sha512-armv8.pl
- generated-src/ios-aarch64/crypto/fipsmodule/aesv8-armx.S
- generated-src/ios-aarch64/crypto/fipsmodule/aesv8-gcm-armv8-unroll8.S
- generated-src/ios-aarch64/crypto/fipsmodule/aesv8-gcm-armv8.S
- generated-src/ios-aarch64/crypto/fipsmodule/sha256-armv8.S
- generated-src/ios-aarch64/crypto/fipsmodule/sha512-armv8.S
- generated-src/ios-aarch64/crypto/fipsmodule/vpaes-armv8.S
- generated-src/linux-aarch64/crypto/fipsmodule/aesv8-armx.S
- generated-src/linux-aarch64/crypto/fipsmodule/aesv8-gcm-armv8-unroll8.S
- generated-src/linux-aarch64/crypto/fipsmodule/aesv8-gcm-armv8.S
- generated-src/linux-aarch64/crypto/fipsmodule/sha256-armv8.S
- generated-src/linux-aarch64/crypto/fipsmodule/sha512-armv8.S
- generated-src/linux-aarch64/crypto/fipsmodule/vpaes-armv8.S
- generated-src/win-aarch64/crypto/fipsmodule/aesv8-armx.S
- generated-src/win-aarch64/crypto/fipsmodule/aesv8-gcm-armv8-unroll8.S
- generated-src/win-aarch64/crypto/fipsmodule/aesv8-gcm-armv8.S
- generated-src/win-aarch64/crypto/fipsmodule/sha256-armv8.S
- generated-src/win-aarch64/crypto/fipsmodule/sha512-armv8.S
- generated-src/win-aarch64/crypto/fipsmodule/vpaes-armv8.S
Addresses CryptoAlg-1873
Using registers x6 and x7 is risky because they can be used for input parameters.
Switching the dispatch tests to use x9 and x10 which are corruptible regitsters.
> Make dispatch tests use corruptible registers on aarch64.

- ssl/internal.h
- ssl/ssl_cert.cc
- ssl/ssl_cipher.cc
- ssl/ssl_privkey.cc
- ssl/ssl_test.cc
- ssl/ssl_x509.cc
Addresses `CryptoAlg-1844`
This builds upon the new framework in https://github.com/aws/aws-lc/pull/1086 to use the new multiple certificate slots available. The SSL connection should use the corresponding index of the certificate and pkey type assigned. As of now, the connection will directly use the last certificate that was set for it's connection. This corresponds with our original behavior before we reintroduced the multiple certificate slots framework, where we only maintained one `x509_leaf` and one `pkey per `CERT`.`
A subsequent PR will be introduced to allow the user to manually select which certificate slots they wish to use.
These functions change the certificate slot index:
* `SSL_CTX_use_certificate_ASN1` / `SSL_use_certificate_ASN1`/ `SSL_CTX_use_certificate` / …
> Allow `SSL_CTX` to use the new multiple certificate slots internally

- include/openssl/ssl.h
- ssl/ssl_stat.cc
- ssl/ssl_test.cc
Resolves `CryptoAlg-1995`
Tweak back string functions with exclamation marks.
Reverted from: https://github.com/aws/aws-lc/commit/c2ae53db6dff3b8a773c43e16e3efaf20ff4c7da
N/A
N/A
> tweak back error string functions with exclamation marks

- crypto/fipsmodule/CMakeLists.txt
- crypto/fipsmodule/bcm.c
- crypto/fipsmodule/cpucap/cpu_aarch64.c
- crypto/fipsmodule/cpucap/cpu_aarch64.h
- crypto/fipsmodule/cpucap/cpu_aarch64_apple.c
- crypto/fipsmodule/cpucap/cpu_aarch64_linux.c
- crypto/fipsmodule/cpucap/internal.h
Resolves CryptoAlg-1873
AWS-LC currently uses a static ARM capabilities variable for 64 bit ARM Apple devices, as we know that certain hardware features are always present on them. This change gives Apple ARM users an option to define at runtime the CPU capabilities through an environment variable to determine whether to run the hardware vs. non-hardware implementation of an algorithm is used.
Refactored `handle_cpu_env()` function in `cpu_aarch64_linux.c` to a general `cpu_aarch64.c` file to avoid duplicating the code in `cpu_aarch64_apple.c`. Modified CMakeFIle accordingly.
Tests pass locally, confirmed that non-hardware APIs are used when `OPENSSL_armcap=0:0` and that the correct hardware APIs are used when it is left unset. Behavior for testing this already exists in `all_tests.json`, …
> Support changing OPENSSL_armcap with environment variable on Apple 64-bit ARM systems

- crypto/fipsmodule/rand/rand.c
Draft for now.
Abstract getting data from the configured entropy source of FIPS. Atm, the configured source is hard-coded in multiple workflows. This allows adding another source more easily.
In addition, add some machinery to configure another source of build-time using the new define `FIPS_ENTROPY_SOURCE_JITTER_CPU`.
Depends on: https://github.com/aws/aws-lc/pull/1112.
This doesn't mutate any behaviour.
> Abstract fips entropy functions

- ssl/ssl_cert.cc
Resolves `V973158980`
Our static analyser caught some places where we weren't checking the return type before the value was used. Only the mssing check in `ssl_set_cert` was detected. The analyser didn't complain about `cert_set_chain_and_key`, but I added a comment there for clarification. 
> Silence static analyser with additional checks

- crypto/fipsmodule/aes/asm/aesv8-armx.pl
- crypto/fipsmodule/aes/asm/vpaes-armv8.pl
- crypto/fipsmodule/bcm.c
- crypto/fipsmodule/cpucap/cpu_aarch64.c
- crypto/fipsmodule/cpucap/cpu_aarch64.h
- crypto/fipsmodule/cpucap/cpu_aarch64_apple.c
- crypto/fipsmodule/cpucap/cpu_aarch64_linux.c
- crypto/fipsmodule/sha/asm/sha512-armv8.pl
- crypto/impl_dispatch_test.cc
- crypto/internal.h
- generated-src/ios-aarch64/crypto/fipsmodule/aesv8-armx.S
- generated-src/ios-aarch64/crypto/fipsmodule/sha256-armv8.S
- generated-src/ios-aarch64/crypto/fipsmodule/sha512-armv8.S
- generated-src/ios-aarch64/crypto/fipsmodule/vpaes-armv8.S
- generated-src/linux-aarch64/crypto/fipsmodule/aesv8-armx.S
- generated-src/linux-aarch64/crypto/fipsmodule/sha256-armv8.S
- generated-src/linux-aarch64/crypto/fipsmodule/sha512-armv8.S
- generated-src/linux-aarch64/crypto/fipsmodule/vpaes-armv8.S
- generated-src/win-aarch64/crypto/fipsmodule/aesv8-armx.S
- generated-src/win-aarch64/crypto/fipsmodule/sha256-armv8.S
- generated-src/win-aarch64/crypto/fipsmodule/sha512-armv8.S
- generated-src/win-aarch64/crypto/fipsmodule/vpaes-armv8.S
- tests/ci/devicefarm_job.py
- tests/ci/setup.py
Resolves CryptoAlg-1873
Addresses CryptoAlg-1764
Moves changes from PRs https://github.com/aws/aws-lc/pull/1093, https://github.com/aws/aws-lc/pull/1118, and https://github.com/aws/aws-lc/pull/1045 into the 1MU branch
It also contains https://github.com/aws/aws-lc/commit/d723334d7a26d2d981c6f63adf4f07b6fcd61bac, to fix the devicefarm CI failure on the 1MU branch since it hasn't been pulled in yet
For the dispatch tests, I had to remove tests for capabilities we don't have in the 1MU branch (e.g. lots of the arm GCM stuff)
Tests pass locally on aarch64 M1 mac and x86 Ubuntu
> Move OPENSSL_armcap changes and aarch64 dispatch tests to 1MU

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
* EVP API ECDHE speed tool support by @torben-hansen in https://github.com/aws/aws-lc/pull/1080
* fix rust sanity check CI by @samuel40791765 in https://github.com/aws/aws-lc/pull/1106
* Silence static analyser by validating pointer prior to function call by @torben-hansen in https://github.com/aws/aws-lc/pull/1107
* Improve LICENSE readability by @skmcgrail in https://github.com/aws/aws-lc/pull/1110
* add back CERT_PKEY structure and refactor pointers by @samuel40791765 in https://github.com/aws/aws-lc/pull/1086
* Turn on tests in CI dimension for mySQL  by @samuel40791765 in https://github.com/aws/aws-lc/pull/1063
* Fix DH_check() excessive time with oversized modulus by @skmcgrail in https://github.com/aws/aws-lc/pull/1109
* Add GitHub CODEOWNERS by @skmcgrail in …
> Release v1.13.0

- .github/CODEOWNERS
- crypto/dh_extra/dh_test.cc
- crypto/fipsmodule/dh/check.c
Backports CVE-2023-3446, CVE-2023-3817 fixes from main:
https://github.com/aws/aws-lc/pull/1109
https://github.com/aws/aws-lc/pull/1121
> [fips-2021-10-20] Backport CVE-2023-3446, CVE-2023-3817 fixes for DH_check

- crypto/dh_extra/dh_test.cc
- crypto/fipsmodule/dh/check.c
Backports CVE-2023-3446, CVE-2023-3817 fixes from main:
https://github.com/aws/aws-lc/pull/1109
https://github.com/aws/aws-lc/pull/1121
> [fips-2021-10-20-1MU] Backport CVE-2023-3446, CVE-2023-3817 fixes for DH_check

- crypto/dh_extra/dh_test.cc
- crypto/fipsmodule/dh/check.c
Backports CVE-2023-3446, CVE-2023-3817 fixes from main:
https://github.com/aws/aws-lc/pull/1109
https://github.com/aws/aws-lc/pull/1121
> [fips-2022-11-02] Backport CVE-2023-3446, CVE-2023-3817 fixes for DH_check

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
* Fix handling of EXFLAG_INVALID_POLICY on the leaf. by @andrewhop in https://github.com/aws/aws-lc/pull/913
* [fips-2021-10-20] Backport CVE-2023-3446, CVE-2023-3817 fixes for DH_check by @skmcgrail in https://github.com/aws/aws-lc/pull/1127
**Full Changelog**: https://github.com/aws/aws-lc/compare/AWS-LC-FIPS-1.1.0...AWS-LC-FIPS-1.1.1
> Release AWS-LC-FIPS-1.1.1

- crypto/internal.h
Addresses CryptoAlg-1764 and CryptoAlg-1873
The changes made to the ARM capability functions in PR https://github.com/aws/aws-lc/pull/1045 were lost when rebasing the changes to be moved into the 1MU branch in https://github.com/aws/aws-lc/pull/1124. This PR fixes that and makes the feature behave as expected.
N/A
Tests pass locally.
> Fix ARM capability functions that were reset after merge into 1MU branch

- .github/docker_images/abidiff/Dockerfile
- .github/docker_images/abidiff/build.sh
- .github/docker_images/abidiff/diff.sh
- .github/workflows/abidiff.yml
Uses [libabigail](https://sourceware.org/libabigail/), which is available in Amazon Linux repositories for doing simple ABI Diffing between a pull request and the target branch to be merged into.
* Currently just diffs the "standard" non-FIPS build, on x86-64 just to give some base coverage. We can expand this further at a later date.
* The comparison is between the PR branch and the target branch. In a future revision I intend to also have it diff the PR branch to the last tagged release.
> ABI Diff GitHub Action

- ssl/test/bssl_shim.cc
V980180360
`NULL` arguments to standard library functions is generally undefined behaviour. This is test code, but prevent it anyway.
One such occurrence is if `SSL_get_signature_algorithm_name( SSL_get_peer_signature_algorithm(ssl), 0)` ends up returning `NULL`:
```
CheckListContains("sigalg", SSL_get_all_signature_algorithm_names,  SSL_get_signature_algorithm_name( SSL_get_peer_signature_algorithm(ssl), 0))
```
> Avoid UB in test shim

- ssl/extensions.cc
- ssl/internal.h
- ssl/ssl_privkey.cc
- ssl/ssl_test.cc
- ssl/test/runner/runner.go
Addresses `CryptoAlg-1844`
This change is built on top of the multiple certificate slot change we did for TLS1.2/1.3: https://github.com/aws/aws-lc/pull/1120
TLS1.0/1.1 only supports two different signature algorithms and is much simpler. Either the RSA or ECDSA key type will indicate the use of it's corresponding signature. This was what we were originally doing, so we do the same for the private key slots, but with an additional check that the cipher suite allows the key type.
Same callouts as https://github.com/aws/aws-lc/pull/1120
Extended existing tests to use TLS1.0/1.1. More ssl runner tests will be added in a subsequent PR.
> Retrieve multiple certificate slot for TLS1.0/1.1 based on negotiated sigalgs

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
N/A
Prepare for release with the following changes:
* Fix formal verification CI by @samuel40791765 in https://github.com/aws/aws-lc/pull/1130
* Pull in the latest changes from s2n-bignum (2023-07-25)  by @aqjune-aws in https://github.com/aws/aws-lc/pull/1114
* Upstream merge 2023 07 28 by @samuel40791765 in https://github.com/aws/aws-lc/pull/1122
* Implementation passive entropy by @torben-hansen in https://github.com/aws/aws-lc/pull/1125
* add curl integration test CI dimension by @samuel40791765 in https://github.com/aws/aws-lc/pull/1134
* Retrieve multiple certificate slot for TLS1.2/1.3 based on negotiated sigalgs by @samuel40791765 in https://github.com/aws/aws-lc/pull/1120
* ABI Diff GitHub Action by @skmcgrail in https://github.com/aws/aws-lc/pull/1116
* Add vzeroupper instruction …
> Update for Release v1.14.0

- crypto/decrepit/evp/evp_do_all.c
- include/openssl/evp.h
Addresses CryptoAlg-2036
OpenSSL has a function `EVP_MD_do_all` that works the same way as `EVP_MD_do_all_sorted` (which AWS-LC currently provides), except that it gives no guarantees on the order in which it calls its input function over the digest collection. Presumably, OpenSSL separates these two functions out for performance reasons, as `EVP_MD_do_all_sorted` [performs a runtime quicksort](https://github.com/openssl/openssl/blob/master/crypto/objects/o_names.c#L291-L349) (see also [here](https://github.com/openssl/openssl/blob/f7b2942c041ee803557a009a4554760c56484c9d/crypto/evp/names.c#L229-L254)) on the collection. AWS-LC [does the "sort" manually at build time](https://github.com/aws/aws-lc/blob/9b323d575d6ad4771592e77083169416275b793d/crypto/decrepit/evp/evp_do_all.c#L70), so …
> Add EVP_MD_do_all

- ssl/test/bssl_shim.cc
N/A
* Fix compiler error
```
ssl/test/bssl_shim.cc:315:35: error: '%s' directive argument is null [-Werror=format-overflow=]
315 |   fprintf(stderr, "Unexpected %s: %s\n", type, str);
```
This was missed in previous PR review: https://github.com/aws/aws-lc/pull/1140
N/A
> error: '%s' directive argument is null

- tool/speed.cc
We recently had a team reach out to us about our broken build on gcc 4.8.3. This is due to a bug that we've previously encountered in this commit: https://github.com/aws/aws-lc/commit/65661035692572f9e399a162a4e908ad5b4bd509
N/A
We may have to add new CI to check for this, but it seems like this specific version is hard to find. We already have CI for gcc4.8.5.
> Fix build on gcc 4.8.3

- CMakeLists.txt
Remove duplicate handling of `OPENSSL_NO_ASM` from CMake.
`OPENSSL_NO_ASM` is handled a few lines below.
It looks like this block was added as part of a bad cherry-pick/merge (compare the original commit [boringssl@261ec612](https://github.com/google/boringssl/commit/261ec612e21b81a4c16bbda615d0850556483b4f)
with the cherry-pick [aws-lc@1da6816b](https://github.com/aws/aws-lc/commit/1da6816b658eed1336398406e30a0fc499bd4865)).
N/A
> Remove duplicate handling of OPENSSL_NO_ASM from CMake.

- SANDBOXING.md
- crypto/CMakeLists.txt
- crypto/fipsmodule/cpucap/cpu_aarch64_apple.c
- crypto/fipsmodule/hkdf/hkdf.c
- crypto/fipsmodule/rand/rand.c
- crypto/internal.h
- crypto/rand_extra/rand_test.cc
- crypto/refcount_lock.c
- crypto/refcount_win.c
- crypto/stack/stack.c
- include/openssl/stack.h
- include/openssl/x509.h
- ssl/ssl_test.cc
- util/fipstools/acvp/acvptool/acvp.go
- util/fipstools/acvp/acvptool/subprocess/subprocess.go
- util/fipstools/acvp/acvptool/subprocess/tls13.go
Merge upstream changes from https://github.com/google/boringssl/commit/706846d7a84c3ce8d089b7089c298bd7449227b3 to https://github.com/google/boringssl/commit/8c7e925b5dab1f826f08f38e4b9e1543b8413476
See internal document.
> Upstream merge 2023 08 09

- crypto/conf/conf.c
- crypto/decrepit/x509/x509_decrepit.c
- include/openssl/conf.h
- include/openssl/ssl.h
- include/openssl/x509v3.h
- ssl/CMakeLists.txt
- ssl/ssl_cert.cc
- ssl/ssl_test.cc
- ssl/ssl_text.cc
Resolves `CryptoAlg-1957`
This pulls in the missing symbols needed to integrate with SSLProxy.
1. I've followed the same pattern with `X509V3_EXT_conf_nid` and added the `X509V3_EXT_conf` version here as well. The goal is to only maintain it for basic compatibility and push users to use `X509V3_EXT_nconf*` instead.
2. Added `SSL_CTX_set_security_level` and `CONF_modules_finish` as no-ops. We don't support security levels and adding any configurations to do so should be it's own story.
3. Added tests and functionality for `SSL_SESSION_print`. Taken from: https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/ssl/ssl_txt.c#L32-L162
N/A
New unit test
> add missing symbols for SSLProxy support

- crypto/fipsmodule/modes/internal.h
* V1008777835
* https://github.com/aws/aws-lc-rs/pull/222
* Fixes build for ppc64le.
* This was broken when we merged this upstream commit: https://github.com/google/boringssl/commit/5b32e81407cd044e76c995eb99343dca954a17b8#diff-5ded05174f8be4359aeee63a4e1c84b83123cd6dec5e1a12afc9f7a8d1ec6a26
* Build and "crypto_test" succeed in both Debug and Release configurations.
> Fix build for ppc64le

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
Bump minor version number to prepare for the release.
List of changes to be included:
* Add EVP_MD_do_all by @WillChilds-Klein in https://github.com/aws/aws-lc/pull/1154
* error: '%s' directive argument is null by @justsmth in https://github.com/aws/aws-lc/pull/1158
* Fix build on gcc 4.8.3 by @samuel40791765 in https://github.com/aws/aws-lc/pull/1156
* Remove duplicate handling of OPENSSL_NO_ASM from CMake. by @PiotrSikora in https://github.com/aws/aws-lc/pull/1149
* Add -DBUILD_TOOL=OFF to CMake. by @PiotrSikora in https://github.com/aws/aws-lc/pull/1148
* Upstream merge 2023 08 09 by @justsmth in https://github.com/aws/aws-lc/pull/1152, https://github.com/aws/aws-lc/pull/1160, https://github.com/aws/aws-lc/pull/1161
* Add missing symbols for SSLProxy support by @samuel40791765 in …
> Preparing for release v1.15.0

- include/openssl/ssl.h
- ssl/ssl_cert.cc
A contributor pointed out that our default SSL settings don't quite align with OpenSSL's definition for different security levels.
* https://github.com/aws/aws-lc/pull/1002#issuecomment-1678675162
I've lowered the return number for `SSL_CTX_get_security_level`, but this function is still only for compatibility purposes.
N/A
N/A
> Lower returned number for SSL_CTX_get_security_level

- .github/workflows/integrations.yml
- tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml
- tests/ci/integration/run_haproxy_integration.sh
With the better AWS-LC support merged into HAProxy in https://github.com/haproxy/haproxy/commit/b3f94f8b3b6747eac1c22318d03bdb80e008d5c1 and https://github.com/haproxy/haproxy/commit/88988bb06ccadb1c5486d1e61d9aa6c75e36a404 we can now use the built in filters to run the expected development tests that shouldn't time out in our CI. 
* These are the recommended tests to run and will be the same ones run by HAProxy eventually.
* This migrates the HAProxy build and test to GitHub actions to avoid a CodeBuild process issue
> Simplify HAProxy integration tests by using built in filters

- crypto/fipsmodule/cpucap/cpu_aarch64.c
- tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml
- tests/ci/docker_images/linux-aarch/ubuntu-22.04_base/Dockerfile
- tests/ci/docker_images/linux-aarch/ubuntu-22.04_gcc-12x/Dockerfile
- tests/ci/integration/run_postgres_integration.sh
Postgres doesn't allow functions that call `exit` according to the documentation here:
* https://github.com/postgres/postgres/blob/master/src/interfaces/libpq/Makefile#L119
With the `exit` function called in `crypto/fipsmodule/cpucap/cpu_aarch64.c`, our build breaks prematurely when built with PostGres on ARM.
N/A
New CI dimension.
> Fix and add CI for postgres build on arm

- tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml
- tests/ci/codebuild/common/run_nonroot_target.yml
- tests/ci/docker_images/linux-aarch/ubuntu-22.04_base/Dockerfile
- tests/ci/docker_images/linux-x86/ubuntu-22.04_base/Dockerfile
- tests/ci/docker_images/linux-x86/ubuntu-22.04_gcc-12x/Dockerfile
- tests/ci/integration/nginx_patch/aws-lc-nginx.patch
- tests/ci/integration/nginx_tests_patch/aws-lc-nginx-tests.patch
- tests/ci/integration/run_nginx_integration.sh
Resolves `CryptoAlg-1961`
We've recently ironed out some of the gaps for nginx support. We're not 100% in line with what OpenSSL supports, but we're satisfied with what we have now. 
The remaining gaps are:
* Stateful Session Resumption (Session Caches)
* SSL_Conf commands
This adds a CI dimension to verify our newfound support.
We'll be looking to contribute this patch to nginx some time soon.
New CI dimension
> add integration CI dimension for nginx

- crypto/fipsmodule/rand/rand.c
- include/openssl/rand.h
Improves compatibility with strongSwan.
In OpenSSL, RAND_priv_bytes calls RAND_bytes using independently seeded
values to mitigate against situations where the "public" DRBG gets
compromised and random values can be predicted. It also defers to user
specified random methods if specified. Arguably, AWS-LC is always using
a user specified random method as it has a completely different
implementation from OpenSSL so this change is in-line with the original.
Check that adequate mitigations exist in AWS-LC's RAND_bytes implemenations that
we believe are sufficient to avoid replicating the independent seeding behavior
in OpenSSL.
CI
> Alias RAND_priv_bytes to RAND_bytes

- crypto/fipsmodule/bn/ctx.c
- include/openssl/bn.h
Helps with AWS-LC compatibility with strongSwan. [Discussion link](https://github.com/strongswan/strongswan/discussions/1878)
OpenSSL defines BN_CTX_secure_new which allocates BNs using
BN_secure_new. In LC, all BNs are allocated "securely" (i.e. they 0 out
memory during alloc/free).
We already define an alias for BN_secure_new like this, so we are just
completing the compatibility layer with this change.
- Double check that BN_CTX_secure_new doesn't do anything else noteworthy.
CI
> Add BN_CTX_secure_new alias for BN_CTX_new

- crypto/CMakeLists.txt
- crypto/decrepit/cast/cast.c
- crypto/decrepit/cast/internal.h
- crypto/fipsmodule/cpucap/cpu_aarch64_linux.c
- include/openssl/base.h
- include/openssl/cipher.h
- include/openssl/ssl.h
- tests/ci/cdk/cdk/codebuild/github_ci_linux_arm_omnibus.yaml
- tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
- tests/ci/codebuild/linux-x86/postgres_integration.yml
- tests/ci/docker_images/linux-x86/ubuntu-22.04_base/Dockerfile
- tests/ci/docker_images/linux-x86/ubuntu-22.04_gcc-12x/Dockerfile
- tests/ci/run_postgres_integration.sh
- tool/speed.cc
These changes are required to support Postgres on the future fips-2022-11-02 release. 
I had to make one small change to 3ffcd9755718c3b947aa48e614f3dbd6c265e394 to take out the AWS_LC_DEPRECATED which doesn't exist on this branch. I couldn't easily take https://github.com/aws/aws-lc/commit/4cb82544709ef22fb7608cb93836b7a2051729aa as the CI infrastructure has changed a lot between branches. I made a similar change in a new commit. 
Built locally, new CI will handle ARM.
> Update FIPS 2022 branch to support Postgres

- ssl/internal.h
- ssl/ssl_cert.cc
- ssl/ssl_privkey.cc
- ssl/ssl_test.cc
Resolves `V991528578`
Static analysis revealed that we were expecting a certificate to always exist with the paired private key. This may not always be the case however. Connecting with a private key set, but no certificate set will lead to a segfault. This commit resolves that and fails the connection accordingly.
N/A
New tests for missing cert and missing private key set.
> Check for unset certificates in servers

- CMakeLists.txt
N/A
Build was failing with error codes "C5266" and "C5267" using MS Visual Studio Community 2022. This change allows these errors to be ignored and the build to succeed.
* Neither of these error codes is fully documented. They should appear on [this page](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999).
* There is an open issue [here](https://github.com/MicrosoftDocs/cpp-docs/issues/4554) concerning C5266 not being documented.
* Built successfully completed using "Visual Studio Community 2022" on Windows Server 2019.
* crypto_test and ssl_test succeeded.
> MSVC 2022 - Ignore C5266 and C5267

- .gitignore
- crypto/fipsmodule/cpucap/internal.h
N/A
* We require all of the flags for AVX512F, AVX512DQ, AVX512BW and AVX512VL (not just one of them).
* The bit flags are shown on page 2-16 of [this reference](https://www.intel.com/content/dam/develop/external/us/en/documents/319433-024-697869.pdf#G6.2165065).
N/A
> Fix AVX512 capability check

- crypto/fipsmodule/aes/internal.h
- crypto/fipsmodule/modes/gcm.c
- crypto/impl_dispatch_test.cc
N/A
* Disable XTS's use of AVX-512 on Windows.
* Fix `ImplDispatchTest.AEAD_AES_GCM` which was failing on Windows hosts with AVX-512 capable CPUs.
N/A
Tests pass locally.
> Disable XTS use of AVX512 on Windows

- CMakeLists.txt
- crypto/fipsmodule/FIPS.md
- crypto/rand_extra/rand_test.cc
- tests/ci/run_fips_tests.sh
CryptoAlg-1953
Enables passive entropy method by default. In addition, adds a build-time config that can modify (at build-time) the entropy source method to CPU Jitter.
Follow-up to https://github.com/aws/aws-lc/pull/1125.
For both entropy methods, ran:
```
$ valgrind --trace-children=yes ./crypto/crypto_test --gtest_filter=RandTest.*
[...]
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
> Use passive entropy source method by default for FIPS build mode

- crypto/ecdh_extra/ecdh_test.cc
- crypto/fipsmodule/bn/bytes.c
- crypto/fipsmodule/bn/internal.h
- crypto/fipsmodule/ec/ec.c
- crypto/fipsmodule/ec/ec_test.cc
- crypto/fipsmodule/ec/internal.h
- crypto/fipsmodule/ec/p224-64.c
- crypto/fipsmodule/ec/p256-nistz.c
- crypto/fipsmodule/ec/p256-nistz_test.cc
- crypto/fipsmodule/ec/p256.c
- crypto/fipsmodule/ec/p384.c
- crypto/fipsmodule/ec/p521.c
- crypto/fipsmodule/ec/scalar.c
- crypto/fipsmodule/ec/simple.c
- crypto/fipsmodule/ecdsa/ecdsa.c
- crypto/internal.h
- crypto/trust_token/trust_token_test.cc
Relates to: CryptoAlg-1206 and CryptoAlg-2021
This a merge of an [upstream commit](https://github.com/google/boringssl/commit/227ff6e6425283b83594a91a1aa81cc78f1a88df) that transitions `EC_SCALAR` and `EC_FELEM` from unions to structs. Most of that commit was accepted.
Original commit message:
---------
---------
When introducing EC_SCALAR and EC_FELEM, I used unions as convenience for converting to and from the byte representation. However, type-punning with unions is not allowed in C++ and hard to use correctly in C. As I understand the rules, they are:
- The abstract machine knows what member of union was last written to.
- In C, reading from an inactive member is defined to type-pun. In C++, it is UB though some compilers promise the C behavior anyway.
- However, if you read or write …
> Upstream Merge - Remove unions in EC_SCALAR and EC_FELEM.

- .gitignore
- crypto/CMakeLists.txt
- tests/check_licenses.go
- tests/ci/README.md
N/Q
* Rust bindings were removed from this repo in https://github.com/aws/aws-lc/pull/850.  This PR removes a few lingering references to that code.
N/A
N/A
> Remove a few lingering references to Rust bindings

- tool/speed.cc
This FFDH benchmark is based on the ECDH benchmark: the timed code includes one key generation and the shared secret calculation.
Ran locally on an M1 mac:
```
./tool/bssl speed -filter FFDH
Did 221 FFDH 2048 operations in 1069156us (206.7 ops/sec)
Did 30 FFDH 4096 operations in 1036635us (28.9 ops/sec)
./tool/bssl speed -filter ECDH
Did 21550 ECDH P-224 operations in 1015522us (21220.6 ops/sec)
Did 22000 ECDH P-256 operations in 1035035us (21255.3 ops/sec)
Did 5313 ECDH P-384 operations in 1055558us (5033.4 ops/sec)
Did 3674 ECDH P-521 operations in 1038192us (3538.8 ops/sec)
```
> Add a FFDH benchmark to demonstrate how slow it is

- crypto/conf/conf_test.cc
V1027818360
Micro sanity check that we do not dereference NULL in test case.
> Add missing NULL check in conf test

- crypto/fipsmodule/ec/p224-64.c
- util/fipstools/delocate/delocate.go
- util/fipstools/delocate/testdata/aarch64-Basic/in.s
- util/fipstools/delocate/testdata/aarch64-Basic/out.s
When taking the commit: https://github.com/justsmth/aws-lc/commit/3800f0fcb53c3fc2bb2ffa5bba57de0a67774a5f gcc 11.4 emitted the following in the routine `ec_GFp_nistp224_felem_sqr()`:
```
adrp    x30, :got:__stack_chk_guard
```
This uncovered an unsupported case in the delocater. 
When seeing the line above, the delocater resolved the relocation like this:
```
// WAS adrp    x30, :got:__stack_chk_guard
sub sp, sp, 128
stp x0, lr, [sp, #-16]!
bl .Lboringssl_loadgot___stack_chk_guard
mov x30, x0
ldp x0, lr, [sp], #16
add sp, sp, 128
```
But `x30` is an alias for the aarch64 link register `lr`.  Hence, `mov x30, x0` would clobber `x30` that is used as a general-purpose register in the un-modified routine; the routine pushes the state onto the stack and pops before returning making x30 …
> Handle x30 target register in delocator for aarch64 to avoid clobbering the register

- crypto/curve25519/asm/x25519-asm-arm.S
- generated-src/linux-x86_64/crypto/fipsmodule/aesni-gcm-avx512.S
- generated-src/mac-x86_64/crypto/fipsmodule/aesni-gcm-avx512.S
- generated-src/win-x86_64/crypto/fipsmodule/aesni-gcm-avx512.asm
Ran `python3 util/generate_build_files.py` to pre-generate the assembly files. I also noticed we missed updating the old x25519 implementation. The prefix changes from https://github.com/aws/aws-lc/commit/093d713cd4f267aebe8788bcb8a9803133aea487 were based on the new new s2n-bignum implementation of x25519 which doesn't exist on the fips-2022-11-02 branch.
Built locally with and without a prefix.
> Update pre-generated sources from avx512 change with new prefix build

- include/openssl/ssl.h
- ssl/handshake_server.cc
- ssl/internal.h
- ssl/s3_both.cc
- ssl/ssl_lib.cc
- ssl/ssl_test.cc
- ssl/tls13_server.cc
Addresses CryptoAlg-2036
This commit implements `SSL_get_client_ciphers`, which returns a "stack" (really just a list) of `SSL_CIPHER` structs [presented by the client](https://github.com/openssl/openssl/blob/master/ssl/statem/statem_srvr.c#L2002) during the `|ssl|`'s most recent handshake. [Like OpenSSL](https://github.com/openssl/openssl/blob/e2972982c64f3f1ac10b3ebe1086d99ec67631bd/ssl/ssl_lib.c#L1433), we free this list when the connection is freed. OpenSSL [obtains this list](https://github.com/openssl/openssl/blob/7a5f58b2cf0d7b2fa0451603a88c3976c657dae9/ssl/ssl_lib.c#L3205-L3212) from from an `SSL_CONNECTION` object, something that we or BoringSSL appear to have removed.
So, we're left with the choice of where to store client ciphers. Options include internal/opaque structs …
> Implement SSL_get_client_ciphers

- include/openssl/ssl.h
- ssl/ssl_test.cc
- ssl/ssl_x509.cc
Resolves `CryptoAlg-2087`
This is a reimport of the code that was removed in https://github.com/google/boringssl/commit/b2a9d6ab788dffdfd804d8be231634d1ab470873.
Some of the function documentation was taken from OpenSSL's: https://www.openssl.org/docs/man3.1/man3/SSL_CTX_build_cert_chain.html
This change ties into some of the code changes for multiple certificate work that we had done recently. The code looks slightly different from the original due to the C->C++ translation and rearrangements for cleaner logic. 
N/A
Tests for the new build flags.
> Add back support for SSL_build_cert_chain

- CMakeLists.txt
- crypto/CMakeLists.txt
- crypto/bytestring/cbb.c
- crypto/bytestring/cbs.c
- crypto/compiler_test.cc
- crypto/digest_extra/digest_test.cc
- crypto/endian_test.cc
- crypto/fipsmodule/bcm.c
- crypto/fipsmodule/bn/bytes.c
- crypto/internal.h
- include/openssl/base.h
- util/fipstools/acvp/modulewrapper/main.cc
N/A
* Updates work done on previous PR: https://github.com/aws/aws-lc/pull/1133
* Adds `EndianTest` to test our support for little- and big-endian architectures.
* Adds macros for `OPENSSL_PPC64BE` and `OPENSSL_PPC32BE`.
* The FIPS build for ppc64be is failing - delocator.go cannot parse the assembly code.
* There's a lot more work to fully support big-endian
For ppc64be:
* All `EndianTest.*` tests pass except `EndianTest.AES`.
```
...
[----------] 16 tests from EndianTest (18 ms total)
[==========] 16 tests from 1 test suite ran. (23 ms total)
[  PASSED  ] 15 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] EndianTest.AES
1 FAILED TEST
```
* All 'BNTest.*` tests pass.
```
...
[----------] 36 tests from BNTest (935247 ms total) …
```
> Add BIGNUM support for big-endian architectures

- crypto/fipsmodule/ec/simple_mul.c
Addresses: #1185 
Some compilers (erroneously) warn that `neg_Y` might not be initialized prior to an in-place bit-wise operation on the value.
```
[00:20:47] In file included from /workspace/srcdir/aws-lc/crypto/fipsmodule/bcm.c:96:0:
[00:20:47] /workspace/srcdir/aws-lc/crypto/fipsmodule/ec/simple_mul.c: In function ‘ec_GFp_mont_batch_get_window’:
[00:20:47] /workspace/srcdir/aws-lc/crypto/fipsmodule/ec/felem.c:65:19: error: ‘neg_Y.words[0]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
[00:20:47]      out->words[i] &= mask;
[00:20:47]                    ^~
[00:20:47] cc1: all warnings being treated as errors
```
* I've not yet setup a host to test 32-bit ARM, so more changes might be needed to correct the build on the affected platform.
* The requester asks …
> For Issue-1185: Avoid 'may be used uninitialized' warning

- tool/speed.cc
Previously older versions of AWS-LC with API versions less than 22 would incorrectly attempt to build the FFDH benchmakrs. This is because it passed the first part of the or statement: `!defined(OPENSSL_1_0_BENCHMARK) && !defined(BORINGSSL_BENCHMARK)`. This fixes that so the canary can resume building the current version of speed.cc with older versions of AWS-LC. 
> Don't build FFDH benchmarks with AWS-LC API versions less than 22

- .gitignore
- crypto/ec_extra/hash_to_curve.c
- crypto/endian_test.cc
- crypto/fipsmodule/bn/bytes.c
- crypto/fipsmodule/bn/internal.h
- crypto/fipsmodule/ec/ec_test.cc
- crypto/fipsmodule/ec/p384.c
- crypto/fipsmodule/ec/p521.c
Resolves CryptoAlg-2021
* Due to being a big-endian CPU architecture, most of AWS-LC's algorithms are broken for PPC64.
* This PR addresses many of the issues related to Elliptic Curve algorithms when running on PPC64.
* AES for PPC64 will be address on this PR: #1213
I ran elliptic curve and bignum-related tests using qemu.  All tests pass except AES (which will be addressed on this PR: #1213)
PowerPC-64:
```
> ppc64-qemu.sh ./crypto/crypto_test --gtest_filter="*/EC*:EC*:Ed*:BNTest.*:EndianTest.*" 
Note: Google Test filter = */EC*:EC*:Ed*:BNTest.*:EndianTest.*
[==========] Running 211 tests from 9 test suites.
...
[==========] 211 tests from 9 test suites ran. (1036017 ms total)
[  PASSED  ] 210 …
```
> EC support for PPC64 big endian 

- crypto/bio/bio_test.cc
- crypto/bio/connect.c
- include/openssl/bio.h
N/A
* Fixes compile warning from GCC 13.2:
```
/tmp/aws-lc/crypto/bio/connect.c: In function 'conn_callback_ctrl':
/tmp/aws-lc/crypto/bio/connect.c:493:29: error: cast between incompatible function types from 'bio_info_cb' {aka 'long int (*)(struct bio_st *, int,  const char *, int,  long int,  long int)'} to 'int (*)(const struct bio_st *, int,  int)' [-Werror=cast-function-type]
493 |       data->info_callback = (int (*)(const struct bio_st *, int, int))fp;
|                             ^
```
* Updates `bio_info_cb` to align with its definition in OpenSSL 1.1.1 (and later).
N/A
* Added test to very callback function can successfully be invoked.
* Verified compilation succeeds with GCC 13.2.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> Update bio_info_cb to align with OpenSSL 3.x

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
We've been calling the second iteration of FIPS 2.0, so this is to align that.
> bump version to 2.0 for FIPS

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
This reverts commit 8772d197620f8aefd264b9f312716ee77e4ca5b4.
Versioning scheme needs more discussion before our next FIPS branch is cut.
> Revert "Bump version to 2.0 for FIPS"

- crypto/fipsmodule/CMakeLists.txt
- util/fipstools/inject_hash/inject_hash.go
Resolves CryptoAlg-1686
* Fixes the linking warnings seen previously
```
ld: warning: object file (/Users/runner/work/aws-lc/aws-lc/test_build_dir/crypto/fipsmodule/libbcm_library.a(bcm.c.o)) was built for newer macOS version (11.7) than being linked (11.0)
```
* There is a behavior change in AppleClang that is resulting in debugging symbols (GDB stabs) appearing for the `_BORINGSSL_bcm_text_start` and `_BORINGSSL_bcm_rodata_start` symbols. This updates the `inject-hash` utility to skip Mach-O symbols that are flagged with one or more of the debugging type bits.
> Fix AppleClang 15 FIPS Shared Library Build

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
Addresses CryptoAlg-1838
Our service indicator test vectors for RSA don't completely reflect the capabilities of our FIPS module. It'd be good to update it in order to reduce confusion for our customers.
N/A
Tests pass locally.
> Update rsa service indicator test vectors

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
Addresses CryptoAlg-1838
Moves changes from https://github.com/aws/aws-lc/pull/1230 into the FIPS 2022 branch
N/A
Tests passed locally
> Update rsa service indicator test vectors in FIPS 2022 branch (#1230)

- util/fipstools/acvp/acvptool/subprocess/rsa.go
Addresses CryptoAlg-1838
[FIPS 186-5](https://csrc.nist.gov/pubs/fips/186-5/final) updates some things related to RSA. For ACVP, it introduces a new capabilities registration. Luckily, the format of the vectors is largely the same, but we need to enable support for "AFT" tests in order to correctly parse FIPS 186-5 compatible test vectors.
N/A
Tool passes when running against ACVP demo server.
> Add support for RSA KeyGen AFT tests for FIPS186-5 to ACVP tool

- crypto/blake2/blake2.c
N/A
* Fixes the Blake2b digest for big-endian architectures.
* The problem was only with the final copying of the bytes to the destination buffer.
N/A
`DigestTest.*` and `BLAKE2B256Test.*` succeed for ppc and ppc64.
PPC64:
```
❯ file crypto/crypto_test  
crypto/crypto_test: ELF 64-bit MSB executable, 64-bit PowerPC or cisco 7500, Power ELF V1 ABI, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld64.so.1, for GNU/Linux 6.4.0, with debug_info, not stripped
...
❯ ppc64-qemu.sh ./crypto/crypto_test --gtest_filter="BLAKE2B256Test.*"
Note: Google Test filter = BLAKE2B256Test.*
[==========] Running 2 tests from 1 test suite.
[----------] 2 tests from BLAKE2B256Test
[ RUN      ] BLAKE2B256Test.ABC
[       OK ] BLAKE2B256Test.ABC (3 ms)
[ …
```
> Fix Blake2b for BigEndian

- tests/ci/cdk/cdk/ssm/general_test_run_ssm_document.yaml
- tests/ci/run_ec2_test_framework.sh
The new ec2 test framework doesn't mesh well with our job pruner. Codebuild just "stops" the instance without giving a signal to the executing script, so `trap cleanup` is not executed. This lets the ec2 self-terminate once a certain amount of time has passed.
> self destruct ec2 instances after certain amount of time

- crypto/fipsmodule/sshkdf/sshkdf.c
N/A
* Bad cast was causing SSHKDF to break on ppc64be.
* The [third parameter of `EVP_DigestFinal_ex`]https://github.com/aws/aws-lc/blob/bb1aabad676ccb61e195917452d8d90c86d73217/include/openssl/digest.h#L184 is expected to be an `unsigned int *`, but a `size_t*` was being passed.
N/A
```
❯ ppc64-qemu.sh ./crypto/crypto_test --gtest_filter="SSHKDFTest.*"  
Note: Google Test filter = SSHKDFTest.*
[==========] Running 2 tests from 1 test suite.
[----------] 2 tests from SSHKDFTest
[ RUN      ] SSHKDFTest.SSHKDF_INPUT_INSANITY
[       OK ] SSHKDFTest.SSHKDF_INPUT_INSANITY (3 ms)
[ RUN      ] SSHKDFTest.KAT
[       OK ] SSHKDFTest.KAT (388 ms)
[----------] 2 tests from SSHKDFTest (393 ms total) …
```
> Fix bad cast in SSHKDF

- .github/workflows/abidiff.yml
- .github/workflows/aws-lc-rs.yml
- .github/workflows/integrations.yml
- .github/workflows/osx.yml
Our wondrous Codebuild job pruner has been saving us quite a lot. I noticed Github Actions had something similar so I thought it'd be nice to apply here as well.
Tested in local fork: https://github.com/samuel40791765/aws-lc/actions
> Add Github actions job pruner

- crypto/fipsmodule/rand/rand.c
`PASSIVE_ENTROPY_LOAD_LENGTH` and `CTR_DRBG_ENTROPY_LEN` are currently equal. This assumption is used implicitly in `RAND_load_entropy()`. Statically ensure this continues to be true while assumed.
> Ensure array length assumption agree

- CMakeLists.txt
- crypto/CMakeLists.txt
- crypto/fipsmodule/bcm.c
- crypto/fipsmodule/rand/cpu_jitter_test.cc
- tool/speed.cc
Previously, we disabled jitter cpu by default; instead enabling the passive strategy by default. This is a build-time configuration. That is, if jitter cpu is not explicitly enabled, jitter cpu is not used as the source in FIPS mode and is redundant.
However, the previous work didn't completely remove jitter cpu object code from resulting library artifacts when FIPS is enabled:
```
$ ar -t crypto/libcrypto.a | grep jitter
jitterentropy-base.c.o
jitterentropy-gcd.c.o
jitterentropy-health.c.o
jitterentropy-noise.c.o
jitterentropy-sha3.c.o
jitterentropy-timer.c.o
```
There is no escaped issue, but it takes up space in the library artifact. In additional, it imposes jitter cpu latency at power-on time since the initialisation function is executed in `BORINGSSL_bcm_power_on_self_test()`.
The …
> Completely remove Jitter CPU from library artifact if not enabled

- crypto/curve25519/spake25519.c
N/A
* Fix Spake25519 for big-endian
N/A
PPC32
```
❯ ppc-qemu.sh ./crypto/crypto_test --gtest_filter="SPAKE25519Test.*"
Note: Google Test filter = SPAKE25519Test.*
[==========] Running 6 tests from 1 test suite.
[----------] 6 tests from SPAKE25519Test
[ RUN      ] SPAKE25519Test.SPAKE2
[       OK ] SPAKE25519Test.SPAKE2 (823 ms)
[ RUN      ] SPAKE25519Test.OldAlice
[       OK ] SPAKE25519Test.OldAlice (786 ms)
[ RUN      ] SPAKE25519Test.OldBob
[       OK ] SPAKE25519Test.OldBob (833 ms)
[ RUN      ] SPAKE25519Test.WrongPassword
[       OK ] SPAKE25519Test.WrongPassword (38 ms)
[ RUN      ] SPAKE25519Test.WrongNames
[       OK ] SPAKE25519Test.WrongNames (42 ms)
[ RUN      ] SPAKE25519Test.CorruptMessages
[       OK ] …
```
> Fix Spake25519 for big-endian

- crypto/fipsmodule/ec/ec_test.cc
- crypto/fipsmodule/ec/internal.h
- crypto/fipsmodule/ec/p384.c
- crypto/fipsmodule/ec/p521.c
N/A
* Fixes 32-bit big-endian bug in P521.
* `P521_NLIMBS` is 19, but the `EC_FELEM` type only contains `EC_MAX_WORDS` (= 17) words.
N/A
```
❮ ppc-qemu.sh ./crypto/crypto_test --gtest_filter="EC*.*:*/EC*.*"                         
Note: Google Test filter = EC*.*:*/EC*.*
[==========] Running 156 tests from 6 test suites.
[----------] 7 tests from ECDHTest
...
[----------] 80 tests from All/ECCurveTest (7543 ms total)
[==========] 156 tests from 6 test suites ran. (407363 ms total)
[  PASSED  ] 156 tests.
```
> Fix 32-bit big-endian p521 bug

- crypto/bio/bio_test.cc
- crypto/bio/file.c
- include/openssl/bio.h
Addresses CryptoAlg-2036
OpenSSL defines a "close flag" `BIO_FP_TEXT` which is used by callers to indicate that file-backed BIOs should be opened in "text" mode as opposed to the default of raw "binary" mode. Of platforms currently supported by AWS-LC, this is only meaningful on windows. From linux's `fopen` [man page](https://man7.org/linux/man-pages/man3/fopen.3.html):
```
The mode string can also include the letter 'b' either as a last
character or as a character between the characters in any of the
two-character strings described above.  This is strictly for
compatibility with ISO C and has no effect; the 'b' is ignored on
all POSIX conforming systems, including Linux.  (Other systems
may treat text files and binary files differently, and adding the
'b' may be a good idea if you do …
```
> Add support for BIO_FP_TEXT in file BIOs

- crypto/chacha/chacha.c
N/A
* Fix big-endian issue with (AEAD) XChaCha20Poly1305.
* When combined with #1213, all of our `PerAEADTest.TestVector` tests succeed.
N/A
PPC32:
```
❯ ppc-qemu.sh  ./crypto/crypto_test --gtest_filter="*/PerAEADTest.TestVector/*"
Note: Google Test filter = */PerAEADTest.TestVector/*
[==========] Running 24 tests from 1 test suite.
[----------] 24 tests from All/PerAEADTest
[ RUN      ] All/PerAEADTest.TestVector/AES_128_GCM
[       OK ] All/PerAEADTest.TestVector/AES_128_GCM (667 ms)
[ RUN      ] All/PerAEADTest.TestVector/AES_128_GCM_NIST
[       OK ] All/PerAEADTest.TestVector/AES_128_GCM_NIST (32982 ms)
[ RUN      ] All/PerAEADTest.TestVector/AES_192_GCM
[       OK ] All/PerAEADTest.TestVector/AES_192_GCM (391 ms)
[ RUN      ] …
```
> Fix XChaCha20Poly1305 for big-endian

- crypto/siphash/siphash.c
- crypto/siphash/siphash_test.cc
N/A
Fix SipHash implementation for big-endian architectures.
N/A
`SipHash.*` test pass for both ppc32 and ppc64.
ppc32:
```
❯ ppc-qemu.sh ./crypto/crypto_test --gtest_filter="SipHash.*"
Note: Google Test filter = SipHash.*
[==========] Running 2 tests from 1 test suite.
[----------] 2 tests from SipHash
[ RUN      ] SipHash.Basic
[       OK ] SipHash.Basic (3 ms)
[ RUN      ] SipHash.Vectors
[       OK ] SipHash.Vectors (115 ms)
[----------] 2 tests from SipHash (120 ms total)
[==========] 2 tests from 1 test suite ran. (129 ms total)
[  PASSED  ] 2 tests.
```
ppc64:
```
❯ ppc64-qemu.sh ./crypto/crypto_test --gtest_filter="SipHash.*"   
Note: Google Test filter = SipHash.*
[==========] Running 2 …
```
>  Fix SipHash for big-endian

- tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml
- tests/ci/integration/run_crt_integration.sh
The CRT uses AWS-LC indirectly though s2n-tls, and directly though the aws-c-cal. This adds a CI integration test to make sure everything works together. 
Built locally, CodeBuild will check the yaml is correct.
> Add CRT integration test

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
* Add a FFDH benchmark to demonstrate how slow it is by @andrewhop in https://github.com/aws/aws-lc/pull/1202
* Add missing NULL check in conf test by @torben-hansen in https://github.com/aws/aws-lc/pull/1208
* Add EVP support for SHA512-224 by @WillChilds-Klein in https://github.com/aws/aws-lc/pull/1170
* Handle x30 target register in delocator for aarch64 to avoid clobbering the register by @torben-hansen in https://github.com/aws/aws-lc/pull/1204
* Elaborate on whiten factor for passive entropy by @torben-hansen in https://github.com/aws/aws-lc/pull/1209
* Implement SSL_get_client_ciphers by @WillChilds-Klein in https://github.com/aws/aws-lc/pull/1159
* Add ARM dimensions for integration test CI  by @samuel40791765 in https://github.com/aws/aws-lc/pull/1206
* Add back support for …
> Bump version to 1.17.0

- crypto/curve25519/curve25519.c
Document Ed25519 workflow with respect to https://datatracker.ietf.org/doc/html/rfc8032.
Swapped the order of a few (data independent) operations. I see no cache impact.
Renamed few variables to align with naming in rfc8032.
> Document Ed25519 verification operation

- crypto/curve25519/curve25519.c
- crypto/curve25519/curve25519_nohw.c
- crypto/curve25519/internal.h
Refactors `ED25519_keypair` into a no-hardware and a hardware path. Existing backend is the former. Preparation for s2n-bignum ED25519.
s2n-bignum is lacking SHA512. So unfortunately, I can't punt this computation to s2n-bignum. 
PR chain:
1. (this PR) refactor `ED25519_keypair`
2. refactor `ED25519_sign`
3. refactor `ED25519_verify`
4. various small changes to improve code quality
5. import s2n-bignum Ed25519 routines
6. connect s2n-bignum Ed25519 backend to frontend
> Refactor ED25519_keypair into hw and nohw backend

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
Release patch version update
* Document Ed25519 verification operation by @torben-hansen in https://github.com/aws/aws-lc/pull/1256
* Fix AES on PPCBE (32-bit and 64-bit). by @nebeid in https://github.com/aws/aws-lc/pull/1213
* Upstream merge 2023-10-23 by @nebeid in https://github.com/aws/aws-lc/pull/1262
* Create dirs in cmake build dir with default permissions by @sfod in https://github.com/aws/aws-lc/pull/1269
* Refactor ED25519_keypair into hw and nohw backend by @torben-hansen in https://github.com/aws/aws-lc/pull/1271
* Run basic test run in GHA before using expensive runners by @samuel40791765 in https://github.com/aws/aws-lc/pull/1270
> Bump version to v1.17.1

- crypto/fipsmodule/evp/evp.c
- ssl/test/bssl_shim.cc
N/A
* Add assertions that EVP_PKEY methods are found. (This should always be true in a sane build.)
* Handle potential self-assignment of `OwnedSocket`
N/A
N/A
> EVP_PKEY assert that method is  found

- crypto/x509/internal.h
- crypto/x509/x509_lu.c
- crypto/x509/x509_test.cc
- include/openssl/x509.h
Addresses `CryptoAlg-2167`
* Monit depends on [these symbols](https://bitbucket.org/tildeslash/monit/src/a869c3aad38f34a3b24e9b510b9ee48e3d7b3d9f/src/ssl/Ssl.c?at=master#lines-436:448).
* `X509_OBJECT_free_contents` was removed from OpenSSL 1.0.2 -> 1.1.1 in https://github.com/openssl/openssl/commit/6ddbb4cd92ad8c9ebf874e5d9920c122696b7477. We already expose our version string as 1.1.1, so we can remove this.
* OpenSSL 1.1.1 renamed `X509_STORE_get_by_subject` to `X509_STORE_CTX_get_by_subject` and made an alias to the original: https://github.com/openssl/openssl/commit/6ddbb4cd92ad8c9ebf874e5d9920c122696b7477
N/A
Minor new test
> Rearrange X509 symbols for Monit support

- .github/workflows/actions-ci.yml
Update the windows instance type name in GHA now that Open Source has given us the green light to officially use these.
> Update gha windows instance type names

- tests/ci/docker_images/linux-x86/ubuntu-20.04_clang-10x_formal-verification/create_image.sh
None
A recent AWS-LC-verification [PR](https://github.com/awslabs/aws-lc-verification/pull/115) divides a single `Dockerfile` into two (`Dockerfile.saw` for the SAW proofs and `Dockerfile.coq` for the Coq proofs). `Dockerfile` file is no longer used. Update the create_image.sh script for formal verification to use the updated file `Dockerfile.saw`.
None
I tested that the current create_image.sh script will fail with the following error message:
```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /.../aws-lc/tests/ci/docker_images/linux-x86/ubuntu-20.04_clang-10x_formal-verification/aws-lc-verification/Dockerfile: no such file or directory
```
By updating to `Dockerfile.saw`, the run was successful.
By submitting this pull request, I confirm that my …
> Update create_image.sh for formal verification to fetch the updated Dockerfile

- crypto/fipsmodule/rand/rand.c
* Verified that the [aws-cpp-sdk-core](https://github.com/aws/aws-sdk-cpp/tree/main/tests/aws-cpp-sdk-core-tests) tests pass.
> Ensure rand_thread_state is always zerod in the event that CRYPTO_set_thread_local needs to call the deconstructor

- crypto/fipsmodule/rand/rand.c
- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- generated-src/ios-aarch64/crypto/fipsmodule/aesv8-gcm-armv8-unroll8.S
- generated-src/linux-aarch64/crypto/fipsmodule/aesv8-gcm-armv8-unroll8.S
- generated-src/win-aarch64/crypto/fipsmodule/aesv8-gcm-armv8-unroll8.S
- include/openssl/base.h
Backport https://github.com/aws/aws-lc/pull/1288 to 2022-11-02 branch.
> Backport rand_thread_state zero patch to 2022-11-02, bump version to 2.0.1.

- crypto/x509/internal.h
- crypto/x509/x509_lu.c
- crypto/x509/x509_test.cc
- crypto/x509/x509_vfy.c
- include/openssl/x509.h
Resolves `CryptoAlg-2052`
Some internal teams have ran into unsuspecting issues when migrating over to AWS-LC. If an expired cert was placed before a possible valid cert within the stack, AWS-LC would break and fail certificate verification. This would not happen if the valid certificate was placed first. The behavioral difference was pinned down to an older commit from OpenSSL 1.0.2 -> OpenSSL 1.1.1: https://github.com/openssl/openssl/commit/0930251df814f3993bf2c598761e0c7c6d0d62a2, that we didn't have support for.
Logic was applied from the original commit. 
New certificate test
> Don't use expired certificates if possible.

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
* EVP_PKEY assert that method is  found by @justsmth in https://github.com/aws/aws-lc/pull/1279
* Rearrange X509 symbols for Monit support by @samuel40791765 in https://github.com/aws/aws-lc/pull/1272
* Update gha windows instance type names by @samuel40791765 in https://github.com/aws/aws-lc/pull/1283
* Use uint8_t not u_int8_t by @justsmth in https://github.com/aws/aws-lc/pull/1287
* Update create_image.sh for formal verification to fetch the updated Dockerfile by @pennyannn in https://github.com/aws/aws-lc/pull/1281
* Ensure rand_thread_state is always zerod in the event that CRYPTO_set_thread_local needs to call the deconstructor by @skmcgrail in https://github.com/aws/aws-lc/pull/1288
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> Bump version to 1.17.2

- tool/digest.cc
For whatever reason while I was producing vectors for iOS and MacOS on the 1MU branch, I got the following build error:
```
error: variable 'bad_hash_lines' set but not used [-Werror,-Wunused-but-set-variable]
unsigned bad_hash_lines = 0;
```
I took a look and it appears this is cruft in one of the included tools, which is outside of the FIPS boundaries.
N/A
Changes build locally.
> Fix build error on Apple devices on 1MU branch

- crypto/fipsmodule/rand/rand.c
- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
Per David Benjamin's [comment](https://boringssl-review.googlesource.com/c/boringssl/+/63885/comment/5b05d928_cc807f04/) on the BoringSSL patch, there is an edge case around managing the invariant of the doubly linked-list of process rand_thread_state's. This list is maintained so that the state can be zerod on process exit, as the normal thread-local de-constructors aren't called on process exit. The invariant expected is that if `state->prev == NULL` then it must be the head of the list. This patch validates that when `rand_thread_state` is freed, if `state->prev == NULL` then it only updates the head of the list if the state pointed to is itself. Otherwise this implies that we are freeing a zerod / just initialized `rand_thread_state` that has not been added to the state list yet. …
> Only update thread_states_list if freed state is head when prev is NULL

- crypto/stack/stack.c
- crypto/stack/stack_test.cc
- crypto/x509/x509_test.cc
- include/openssl/x509.h
This reverts commit 1b87d59d7fdbcefc096965efb4af22068c491a08.
Resolves `P104663041`
There's the [existing issue](https://github.com/openssl/openssl/issues/18708) in AWS-LC/OpenSSL where certificate verification will fail depending on an invalid certificate in the trust store coming first. The new sorting introduced a rearrangement of identical certificates within the trust store. This could technically increase the chance of teams running into the existing AWS-LC/OpenSSL issue mentioned earlier, if their invalid identical certificate is rearranged to the top of the stack.
We will have to introduce this change sooner or later to get around the UB sanitizer issue this commit was trying to resolve. But we should do additional verification to make sure we aren't changing the original …
> Revert "Give up on qsort for sk_FOO_sort"

- crypto/fipsmodule/bcm.c
Previously bcm.c and inject_hash.go assumed both would run on little endian platforms. [inject_hash.go is explicit and always encoded the length in little](https://github.com/aws/aws-lc/blob/main/util/fipstools/inject_hash/inject_hash.go#L383), but [bcm.c would do whatever the host CPU was running in](https://github.com/aws/aws-lc/blob/main/crypto/fipsmodule/bcm.c#L327-L328). 
This change updates bcm.c to always hash the little endian encoded value of the length of the text/rodata sections.
This is a no-op for little endian platforms.
With this change in a BE PPC emulator `bssl isfips` works as expected, on little endian it continues to work. All of crypto_test built in FIPS mode is still running locally.
By submitting this pull request, I confirm that my contribution is made under the …
> Update the integrity hash calculation in bcm.c to handle big/little endian platforms

- crypto/curve25519/curve25519.c
- crypto/curve25519/curve25519_nohw.c
- crypto/curve25519/internal.h
Refactors `ED25519_sign` into a no-hardware and a hardware path. Existing backend is the former. Preparation for s2n-bignum Ee25519.
s2n-bignum is lacking SHA512. So unfortunately, I can't punt this computation to s2n-bignum. 
PR chain:
1. refactor `ED25519_keypair` https://github.com/aws/aws-lc/pull/1271
2. (this PR) refactor `ED25519_sign`
3. refactor `ED25519_verify`
4. various small changes to improve code quality
5. import s2n-bignum Ed25519 routines
6. connect s2n-bignum Ed25519 backend to frontend
> Refactor ED25519_sign into hw and nohw backend

- util/all_tests.json
I didn't notice this until touching the file in the upstream merge, but it seems like the OCSP integration test didn't get added to `all_tests.json`.
N/A
New test
> Add back OCSP integration test executing

- crypto/curve25519/curve25519.c
- crypto/curve25519/curve25519_nohw.c
- crypto/curve25519/internal.h
Refactors `ED25519_verify` into a no-hardware and a hardware path. Existing backend is the former. Preparation for s2n-bignum Ed25519.
s2n-bignum is lacking SHA512. So unfortunately, I can't punt this computation to s2n-bignum. 
PR chain:
1. refactor `ED25519_keypair` https://github.com/aws/aws-lc/pull/1271
2. refactor `ED25519_sign` https://github.com/aws/aws-lc/pull/1276
3. (this PR) refactor `ED25519_verify`
4. various small changes to improve code quality
5. import s2n-bignum Ed25519 routines
6. connect s2n-bignum Ed25519 backend to frontend
> Refactor ED25519_verify into hw and nohw backend

- crypto/dynamic_loading_test.c
Resolves `V1100763239`
This change is needed for the FIPS branch as well.
> Use uint8_t not u_int8_t

- crypto/curve25519/curve25519.c
- crypto/curve25519/curve25519_nohw.c
- crypto/curve25519/internal.h
Refactors curve25519 code to prepare for s2n-bignum Ed25519:
* generalise capability functions
* rename a variable to make it clear it is the value computed inline
* move some functions to internal linkage that no longer needs to be exposed.
PR chain:
1. refactor `ED25519_keypair` https://github.com/aws/aws-lc/pull/1271
2. refactor `ED25519_sign` https://github.com/aws/aws-lc/pull/1276
3. refactor `ED25519_verify` https://github.com/aws/aws-lc/pull/1305
4. (this PR) various small changes to improve code quality
5. import s2n-bignum Ed25519 routines
6. connect s2n-bignum Ed25519 backend to frontend
> Fix-up curve25519 code to prepare for s2n-bignum

- .github/codecov.yml
- .github/workflows/codecov-ci.yml
- CMakeLists.txt
- util/codecov-ci.sh
N/A
* Generates coverage data using `gcov` and uploads it to Codecov.
N/A
Initial testing produced this data: https://app.codecov.io/github/aws/aws-lc/tree/codecov-ci/
> Include Codecov in CI

- tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml
- tests/ci/docker_images/linux-x86/ubuntu-22.04_base/Dockerfile
- tests/ci/integration/run_monit_integration.sh
Resolves `CryptoAlg-2167`
Adding an integration CI for our recent support for Monit.
N/A
New CI dimension, time tests will fail on a non-CET timezone machine, so I removed the test. It's non-relevant to AWS-LC functionality.
> Add integration ci for Monit

- crypto/crypto_test.cc
- crypto/x509v3/v3_lib.c
- include/openssl/base.h
- include/openssl/cipher.h
- include/openssl/ec.h
- include/openssl/err.h
- include/openssl/x509v3.h
N/A
* Use same deprecation macros as BoringSSL.  This mechanism is superior as it also provides macros that allow use of a deprecated function w/o triggering the warning.
* Cherry-picked [commit from BoringSSL](https://github.com/google/boringssl/commit/ac6d55859a61f1316010890eee451f6b0930301d).
* Migrated existing uses of `AWS_LC_DEPRECATED` to `OPENSSL_DEPRECATED`.
N/A
N/A
> Use OPENSSL_DEPRECATED

- cmake/go.cmake
N/A
* Currently the setup of the FIPS build produces the following warning when using recent versions (> 3.19) of CMake:
```
CMake Warning (dev) at cmake/go.cmake:49 (add_custom_command):
Policy CMP0116 is not set: Ninja generators transform DEPFILEs from
add_custom_command().  Run "cmake --help-policy CMP0116" for policy
details.  Use the cmake_policy command to set the policy and suppress this
warning.
```
* This change explicitly sets the expected policy.
N/A
I successfully performed a FIPS build.
> Silence warning on CMP0116

- crypto/CMakeLists.txt
- crypto/fipsmodule/bn/bn_assert_test.cc
- crypto/fipsmodule/bn/internal.h
N/A
* Adds tests for `bn_assert_fits_in_bytes`
* Exports the `bn_assert_fits_in_bytes` symbol for testing, but its definition is only visible internally.
N/A
> Add BNAssertTest

- third_party/s2n-bignum/arm/curve25519/bignum_madd_n25519.S
- third_party/s2n-bignum/arm/curve25519/bignum_madd_n25519_alt.S
- third_party/s2n-bignum/arm/curve25519/edwards25519_scalarmulbase.S
- third_party/s2n-bignum/arm/curve25519/edwards25519_scalarmulbase_alt.S
- third_party/s2n-bignum/arm/curve25519/edwards25519_scalarmuldouble.S
- third_party/s2n-bignum/arm/curve25519/edwards25519_scalarmuldouble_alt.S
- third_party/s2n-bignum/arm/p384/Makefile
- third_party/s2n-bignum/arm/p521/Makefile
- third_party/s2n-bignum/x86_att/curve25519/bignum_madd_n25519.S
- third_party/s2n-bignum/x86_att/curve25519/bignum_madd_n25519_alt.S
- third_party/s2n-bignum/x86_att/curve25519/edwards25519_scalarmulbase.S
- third_party/s2n-bignum/x86_att/curve25519/edwards25519_scalarmulbase_alt.S
- third_party/s2n-bignum/x86_att/curve25519/edwards25519_scalarmuldouble.S
- third_party/s2n-bignum/x86_att/curve25519/edwards25519_scalarmuldouble_alt.S
Pull in the latest changes from s2n-bignum:
* Add missing files that I missed in https://github.com/aws/aws-lc/pull/1308
* Resolve duplicate labels
* Some typo fixes
The commands in the internal Quip document was used, with PATHS_TO_KEEP defined as follows:
```
PATHS_TO_KEEP="\
./arm/p384 ./x86_att/p384 ./arm/p521 ./x86_att/p521 \
./arm/fastmul/bignum_emontredc_8n.S \
./arm/fastmul/bignum_kmul_16_32.S \
./arm/fastmul/bignum_kmul_32_64.S \
./arm/fastmul/bignum_ksqr_16_32.S \
./arm/fastmul/bignum_ksqr_32_64.S \
./arm/generic/bignum_ge.S \
./arm/generic/bignum_mul.S \
./arm/generic/bignum_optsub.S \
./arm/generic/bignum_sqr.S \
./x86_att/curve25519/curve25519_x25519.S \
./x86_att/curve25519/curve25519_x25519base.S \
./x86_att/curve25519/curve25519_x25519_alt.S \ …
```
> Update s2n-bignum subtree 2023-11-19

- .github/workflows/codecov-ci.yml
- CMakeLists.txt
- util/codecov-ci.sh
N/A
* Include a `-DOPENSSL_NO_ASM=1` build in the coverage report.
* Include files that had no test coverage.
* Exclude test files from the coverage report.
* Improve support for running coverage report locally on Mac/Linux.
N/A
N/A
> Improve Codecov reporting

- crypto/ec_extra/ec_derive.c
- crypto/ec_extra/hash_to_curve.c
- crypto/ecdh_extra/ecdh_test.cc
- crypto/fipsmodule/bn/internal.h
- crypto/fipsmodule/bn/montgomery.c
- crypto/fipsmodule/ec/ec.c
- crypto/fipsmodule/ec/ec_key.c
- crypto/fipsmodule/ec/ec_montgomery.c
- crypto/fipsmodule/ec/ec_test.cc
- crypto/fipsmodule/ec/felem.c
- crypto/fipsmodule/ec/internal.h
- crypto/fipsmodule/ec/oct.c
- crypto/fipsmodule/ec/p224-64.c
- crypto/fipsmodule/ec/p256-nistz.c
- crypto/fipsmodule/ec/p256.c
- crypto/fipsmodule/ec/p384.c
- crypto/fipsmodule/ec/p521.c
- crypto/fipsmodule/ec/scalar.c
- crypto/fipsmodule/ec/simple.c
- crypto/fipsmodule/ec/simple_mul.c
- crypto/fipsmodule/ec/wnaf.c
- crypto/trust_token/pmbtoken.c
- crypto/trust_token/trust_token_test.cc
- crypto/trust_token/voprf.c
Take upstream commits.
See relevant document.
> Upstream merge 2023-11-20

- include/openssl/ssl.h
- ssl/ssl_lib.cc
- ssl/ssl_test.cc
Addresses CryptoAlg-2136
The primary motivation of this change is to match OpenSSL's behavior for these functions. Relevant links:
- [SSL_read_ex docs][1]
- [SSL_write_ex docs][2]
- [CPython update accounting for this behavior][3]
[1]: https://www.openssl.org/docs/man1.1.1/man3/SSL_read_ex.html
[2]: https://www.openssl.org/docs/man1.1.1/man3/SSL_write_ex.html
[3]: https://github.com/python/cpython/issues/75892#issuecomment-1093761352
- n/a
- CI checks
---
> Allow 0 byte read/write in SSL_{read,write}_ex

- include/openssl/ssl.h
- ssl/extensions.cc
- ssl/ssl_test.cc
Addresses CryptoAlg-2136
OpenSSL increments session hits in two places:
1. Handshake finish [on the client side](https://github.com/openssl/openssl/blob/1750689767cc922bdbe73358f7256475f0838c67/ssl/statem/statem_lib.c#L1494)
2. Fetching potentially pre-existing session [on the server side](https://github.com/openssl/openssl/blob/1750689767cc922bdbe73358f7256475f0838c67/ssl/ssl_sess.c#L665)
Prior to this change, we failed to increment the session "cache" hit counter for TLS 1.3 servers. I put "cache" in scare-quotes because whether that behavior is correct depends on how you define a cache, as TLS 1.3 ticket resumption is stateless and doesn't require a true session cache. Semantics aside, the change in this PR conforms to OpenSSL's behavior. OpenSSL …
> Increment session hit counter for ticket resumptions

- include/openssl/ssl.h
- ssl/CMakeLists.txt
- ssl/ssl_file.cc
- ssl/ssl_test.cc
- util/all_tests.json
Addresses `CryptoAlg-2165`
Librelp consumes this so we have to add it back. I translated the underlying function to C++ while I was at it. The function ([like it's OpenSSL version)](https://github.com/openssl/openssl/blob/fe487609c17dac049f867f230e09ee090b65e966/ssl/ssl_rsa.c#L437) has some `SSL_CTX` and `SSL` specific logic, so there needs to be a way to differentiate. 
N/A
New test for `SSL_use_certificate_chain_file` and `SSL_CTX_use_certificate_chain_file`.
> Add back SSL_use_certificate_chain_file

- CMakeLists.txt
- pkgconfig/libcrypto.pc.in
- pkgconfig/libssl.pc.in
- pkgconfig/openssl.pc.in
Resolves `CryptoAlg-2164`
librelp, bind, and other libraries use package config to detect OpenSSL support. This lets these projects find AWS-LC with their existing configuration.
Versioning still needs ironing out
This can be tested once we add CI for librelp. This passes locally but we haven't ironed out all the details for librelp just yet.
> Add support for building with pkgconfig

- ssl/ssl_test.cc
Despite silencing tmpname deprecation warnings, the warning still appears on Linux platforms when compiling tests.
> Use mkstemp instead of tmpname when available

- ssl/ssl_lib.cc
Add null-check for input args in SSL_{read|write}_ex to avoid potentially dereferencing nullptr.
> Add null-check for input args in SSL_{read|write}_ex

- include/openssl/ssl.h
- ssl/ssl_cert.cc
Backports the SSL_CTX security level APIs from main.
> Backport SSL_CTX_get_security_level / SSL_CTX_set_security_level symbols

- include/openssl/ssl.h
- ssl/internal.h
- ssl/ssl_lib.cc
- ssl/ssl_test.cc
- ssl/ssl_transfer_asn1.cc
- ssl/ssl_versions.cc
- ssl/tls_transfer.asn
Addresses CryptoAlg-2136
While both AWS-LC/BoringSSL and OpenSSL allow `0` to be used in `SSL_CTX_set_min_proto_version` and `SSL_CTX_set_max_proto_version` to configure an `SSL_CTX` to use default TLS versions for its TLS "method", the two libraries differ in the behavior of their corresponding getters. When configured to use default versions, OpenSSL returns `0`:
- [OpenSSL 1.1.1 docs](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_min_proto_version.html)
- [OpenSSL 3 docs](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_min_proto_version.html)
- relevant code pointers [here](https://github.com/openssl/openssl/blob/b0e9d0370262ade64c55f2385fbb09ec6aa81e76/ssl/ssl_lib.c#L3894) and [here](https://github.com/openssl/openssl/blob/master/ssl/statem/statem_lib.c#L2055-L2058) …
> Return 0 if using default proto min/max

- tests/ci/integration/run_postgres_integration.sh
https://github.com/postgres/postgres/commit/c82207a548db47623a2bfa2447babdaa630302b9 broke some of the error string expectations we have for postgres.
> Fix expected error string for Postgres integration

- ssl/ssl_transfer_asn1.cc
- ssl/tls_transfer.asn
Allows the parser to deserialise TLS transfer state as long as the state version is as old or older than the parser.
https://github.com/aws/aws-lc/pull/1322 added a few more (optional) fields to the TLS transfer format. We want this to impose a version bump. But the parser currently doesn't allow inputting state serialised through an older parser. Improve backwards compatibility to allow future version bumps.
This makes deploying to a large fleet with a long delta of software versions being out-of-sync much easier. 
> Improve backwards compatability for the TLS transfer parser

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
* Prepare release 1.18.0.
* Upstream merge 2023-11-20 by @torben-hansen in https://github.com/aws/aws-lc/pull/1315
* Wire up s2n-bignum Ed25519 backend by @torben-hansen in https://github.com/aws/aws-lc/pull/1309
* Allow 0 byte read/write in SSL_{read,write}_ex by @WillChilds-Klein in https://github.com/aws/aws-lc/pull/1316
* Increment session hit counter for ticket resumptions by @WillChilds-Klein in https://github.com/aws/aws-lc/pull/1320
* Add back SSL_use_certificate_chain_file by @samuel40791765 in https://github.com/aws/aws-lc/pull/1312
* Log symbol name for fips scope assertion error by @torben-hansen in https://github.com/aws/aws-lc/pull/1321
* Add support for building with pkgconfig by @samuel40791765 in https://github.com/aws/aws-lc/pull/1310
* Docker images for loongarch64, …
> Prepare release 1.18.0

- crypto/bio/bio.c
- crypto/bio/bio_test.cc
- include/openssl/bio.h
- tests/ci/run_postgres_integration.sh
Change is needed to support Postgres with AWS-LC-FIPS
> Backport "Give BIO an ex_data" for Postgres

- crypto/ocsp/ocsp_integration_test.cc
- util/all_tests.json
We've been getting very infrequent OCSP responder integration test failures. This updates the timeout during the OCSP responder ping to see if this lowers our failure rate.
CI
> Update OCSP responder integration test timeout

- crypto/CMakeLists.txt
- crypto/curve25519/curve25519.c
- crypto/curve25519/curve25519_nohw.c
- crypto/curve25519/curve25519_s2n_bignum_asm.c
- crypto/curve25519/internal.h
- include/openssl/curve25519.h
Finalise the 25519 refactoring by moving the machine-optimised implementations (from s2n-bignum) to its own compilation unit. This also aligns the s2n-bignum wrappers with the nohw wrappers, with common signatures and common function descriptions.
When https://github.com/aws/aws-lc/pull/1332 is merged I will further simplify the logic by joining `curve25519_s2n_bignum_capable` and `ed25519_s2n_bignum_capable` as well as removing the fips pre-compilation logic guarding the s2n-bignum implementation.
No code was really hurt in this PR. Moving things around and replacing magic values with descriptive constants.
> Factor out the machine-optimised backend for 25519 algorithms

- crypto/bio/bio.c
- crypto/bio/bio_test.cc
- crypto/engine/engine.c
- include/openssl/bio.h
- include/openssl/engine.h
- tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml
- tests/ci/docker_images/linux-x86/ubuntu-22.04_base/Dockerfile
- tests/ci/integration/librelp_patch/aws-lc-librelp.patch
- tests/ci/integration/run_librelp_integration.sh
Resolves `CryptoAlg-2165`
librelp relies on some ancient symbols that we can easily expose as no-ops. For certain symbols like `SSL_CONF` and `BIO_set_callback` we can leverage the existing ifdefs from LibreSSL.
There are two test failures that occur when enabling AWS-LC with librelp.
1. `tls-basic-anon`: Uses anonymous ciphersuites (DH or ECDH) that don't need certificates for authentication. AWS-LC does not support this behavior, so I've added an error message in the patch to indicate so.
2. `tls-wrong-signedcert.sh `: expects a specifc error message from OpenSSL. I've added AWS-LC's error message as a pattern.
N/A
New CI
> Add support and CI for building with librelp

- tests/ci/docker_images/linux-x86/ubuntu-20.04_clang-10x_formal-verification/create_image.sh
- tests/ci/run_formal_verification.sh
None
One pending merge PR (https://github.com/awslabs/aws-lc-verification/pull/128) in AWS-LC-verification will change the Dockerfile name for SAW proofs on X86_64 and will change where the shell scripts are for running the proofs. This is a coordination PR to make sure that once that PR is merged, AWS-LC CI will continue to run smoothly.
None
Changes are tested by downloading existing docker image `aws-lc-docker-images-linux-x86:ubuntu-20.04_clang-10x_formal-verification_latest`, and running the proofs in the AWS-LC-verification PR (https://github.com/awslabs/aws-lc-verification/pull/128) within the docker image using adjusted commands from the script `run_formal_verification.sh`.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> Dockerfile and structure change for SAW proofs on X86_64

- tests/ci/common_fuzz.sh
- tests/ci/common_posix_setup.sh
- tests/ci/docker_images/dependencies/build_cryptofuzz_modules.sh
- tests/ci/integration/run_crt_integration.sh
- tests/ci/integration/run_curl_integration.sh
- tests/ci/integration/run_haproxy_integration.sh
- tests/ci/integration/run_mariadb_integration.sh
- tests/ci/integration/run_monit_integration.sh
- tests/ci/integration/run_mysql_integration.sh
- tests/ci/integration/run_nginx_integration.sh
- tests/ci/integration/run_openssh_integration.sh
- tests/ci/integration/run_postgres_integration.sh
- tests/ci/integration/run_s2n_integration.sh
- tests/ci/integration/run_sslproxy_integration.sh
- tests/ci/run_cross_tests.sh
- tests/ci/run_cryptofuzz.sh
- tests/ci/run_install_shared_and_static.sh
N/A
Prevent accidental deletions (via `rm -rf`) when a variable is not defined.
* See Bash documentation for [parameter expansion](https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameter-Expansion).
> ${parameter:?word}
>
> If parameter is null or unset, the expansion of word (or a message to that effect if 
> word is not present) is written to the standard error and the shell, if it is not 
> interactive, exits. Otherwise, the value of parameter is substituted. 
N/A
> More caution with 'rm -rf'

- util/fipstools/delocate/delocate.go
- util/fipstools/delocate/testdata/aarch64-Basic/out.s
- util/fipstools/delocate/testdata/ppc64le-Sample/out.s
- util/fipstools/delocate/testdata/ppc64le-Sample2/out.s
- util/fipstools/delocate/testdata/x86_64-LabelRewrite/out.s
Today the `bcm_redirector_*` functions are symbols that are present in the bcm.o file, and are subject to potential collisions if they are not correctly "prefixed". Today since we have the odd behavior of prefixing symbols prior to running delocate this hasn't cause an issue as we would get redirect symbols like `bcm_redirector_myprefix_OPENSSL_malloc` etc. While working on https://github.com/aws/aws-lc/pull/1342 I realized a side-effect to prefixing after running the delocator would cause the `bcm_redirector_` functions to more then likely collide since they would no longer contain the prefix e.g. `bcm_redirector_OPENSSL_malloc`. Since these symbols are only referenced within the bcm.o file this PR marks these symbols as local so that they don't appear in the object file.
With the FIPS …
> Mark bcm_redirector functions as local

- ssl/internal.h
- ssl/ssl_lib.cc
Resolves an internal ticket.
Coverity didn't like the lack of initialization for our new variables.
- n/a
- CI tests
> Initialize min/max use_default values in SSL_CTX

- ssl/ssl_lib.cc
- ssl/ssl_test.cc
- n/a
Behavior added in commit [`89e1fd0d`][1] was accidentally removed in [`f3e49b01`][2]. This commit replaces that code.
[1]: https://github.com/aws/aws-lc/commit/89e1fd0d93360fee0b0ed54cd534ca44f6965367
[2]: https://github.com/aws/aws-lc/commit/f3e49b01fb9a58bddd5bac218d9369e36d5bfbd0
- n/a
- CI tests
---
> Fix accidental deletion in f3e49b01

- crypto/des/des.c
- crypto/digest_extra/digest_test.cc
- crypto/fipsmodule/evp/evp.c
- crypto/rand_extra/rand_extra.c
- include/openssl/des.h
- include/openssl/evp.h
- include/openssl/rand.h
Addresses CryptoAlg-2187
Add:
* EVP_MD_get_pkey_type
* EVP_MD_get0_name
* RAND_write_file
* DES_key_sched
AWS-LC doesn't support reading in entropy from a file with `RAND_load_file` so it seemed appropriate to not implement `RAND_write_file`. However, customers could try and use that with another library so we might want to implement it. For now it just returns an error and does nothing. At least for NTP they only use RAND load/write in the case that `RAND_status` returns 0, and for AWS-LC it always returns 1. 
EVP_MD_get_pkey_type is really weird, based on the [OpenSSL documentation](https://www.openssl.org/docs/manmaster/man3/EVP_MD_get_pkey_type.html) and reading [their code all current digests](https://github.com/openssl/openssl/blob/986c48c4eb26861f25bc68ea252d8f2aad592735/crypto/evp/ …
> Add helper functions needed for NTP

- crypto/dsa/dsa.c
- crypto/dsa/dsa_test.cc
- crypto/rsa_extra/rsa_print.c
- crypto/rsa_extra/rsa_test.cc
- include/openssl/dsa.h
- include/openssl/rsa.h
Addresses CryptoAlg-2187
Add the following 3 print functions.
* DSA_print
* DSA_print_fp
* RSA_print_fp
We already had an implementation of RSA_print. I tried to think of ways to share more code between DSA and RSA but I don't think it's worth the complexity to make the function work for both types.
OpenSSL has OPENSSL_NO_STDIO macro that AWS-LC has in some spots, but we already include stdio.h in other spots not guarded by this macro so I decided to always include it. 
Included new tests.
> Add print helper functions for RSA and DSA

- crypto/kyber/README.md
- crypto/kyber/pqcrystals_kyber_ref_common/poly.c
Fix taken from [this commit][1].
[1]: https://github.com/pq-crystals/kyber/commit/dda29cc63af721981ee2c831cf00822e69be3220
t/P109267011
- CI tests
---
> Update function to avoid division

- .github/workflows/integrations.yml
N/A
* Fix repeated failures of CI for tcpdump integ test
N/A
N/A
> tcpdump CI - 'apt-get update' before install

- include/openssl/base.h
- tests/ci/run_benchmark_build_tests.sh
- tool/CMakeLists.txt
- tool/internal.h
- tool/speed.cc
Bump API version for our new EVP_CIPHER version of ChaCha. Also add a test of speed.cc with the 2022 branch of AWS-LC. 
This adds a new build to make sure it continues to work. 
> Bump AWSLC_API_VERSION for EVP_chacha20_poly1305

- crypto/fipsmodule/modes/asm/aesni-gcm-avx512.pl
- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- crypto/kyber/README.md
- crypto/kyber/pqcrystals_kyber_ref_common/poly.c
- include/openssl/base.h
* Backport https://github.com/aws/aws-lc/pull/960
* Backport https://github.com/aws/aws-lc/pull/1360
* Bump version to 2.0.3
> Backport Perl Compat Fix and Division Fix to fips-2022-11-02, Bump Version to 2.0.3

- cmake/go.cmake
Support for `DEPFILE` argument for `add_custom_command` was not added till 3.7, gate the usage behind a version check.
```
ec2-user@devbox ~/aws-lc/build (cmake-compat) $ cmake --version
cmake version 3.2.3
CMake suite maintained and supported by Kitware (kitware.com/cmake).
ec2-user@devbox ~/aws-lc/build (cmake-compat) $ cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=0 -DFIPS=1 ..
-- The C compiler identification is GNU 11.4.1
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- FIPS build mode configured
-- FIPS entropy source method configured: Passive
-- The CXX compiler …
```
> Fix issue with older CMake when building FIPS static using Ninja buid system

- tool/speed.cc
Currently speed only supports running for a set number of integer seconds, which means the shortest time is 1 second. That's a good default but to generate a lot of data for various sizes (everything from 1 byte up to 1000) of symmetric ciphers this can end up taking hours.
I thought about changing the existing timeout option to take milliseconds but that might break other existing tools so I decided to add a new option. 
Tested that both can't be set:
```
./tool/bssl speed -timeout_ms 10 -timeout 10
'-timeout' and '-timeout_ms' are mutually exclusive
-filter A comma-separated list of filters on the speed tests to run. Each filter is applied in independent runs.
-timeout        The number of seconds to run each test for (default is 1)
-timeout_ms     The number of milliseconds to run each …
```
> Add option to run speed for specified milliseconds

- crypto/bio/bio_test.cc
- crypto/dsa/dsa_test.cc
- crypto/pem/pem_test.cc
- crypto/rsa_extra/rsa_test.cc
- crypto/test/test_util.h
Resolves `V1159778876`
Static Analysis was complaining about our lack of assertions. I also unified our usage of `tmpfile` deleters while I was at it.
> Add assertions and unify tmpfile uniqueptr

- crypto/kyber/README.md
- crypto/kyber/pqcrystals_kyber_ref_common/poly.c
- crypto/kyber/pqcrystals_kyber_ref_common/polyvec.c
This patch mirrors the technique used in the upstream Kyber reference code (commit [272125f](https://github.com/pq-crystals/kyber/commit/272125f6acc8e8b6850fd68ceb901a660ff48196)) to prevent the compiler from using the DIV instruction in `poly_compress` and `polyvec_compress`.
Addresses t/V1179892555.
CI testing
> Update poly_compress and polyvec_compress to prevent the compiler from using DIV

- tests/ci/run_benchmark_build_tests.sh
- tool/speed.cc
Addresses V1169792905
Run all benchmarks with all libcryptos as a part of the build but only run them for a few milliseconds so the CI finishes faster. This helps find any library specific memory issue with address sanitizer.
Fix a small memory leak in the AEAD init benchmark. The TLS specific AEAD_init function allocate a `AEAD_TLS_CTX`  and you need to call cleanup on each one. This get handled in the rest of the benchmark thanks to the use of `ScopedEVP_AEAD_CTX` 
Fix the race condition between the encode/decode PKCS8 benchmark. Currently the CBB/CBS grow based on the number of benchmark iterations and end up at 10s of thousands of bytes long. This causes two issues:
1. The benchmark includes the time to reallocate the buffers to be bigger and bigger
2. If the decode benchmark runs for …
> Fix memory leaks in speed.cc

- tool/speed.cc
Speed tool filtering functionality is case-sensitive.
Before
```
$ ./tool/bssl speed -filter SHA- -chunks 16                                                                                                                  
Did 13563000 SHA-1 (16 bytes) operations in 1000019us (13562742.3 ops/sec): 217.0 MB/s
Did 11213250 SHA-256 (16 bytes) operations in 1000022us (11213003.3 ops/sec): 179.4 MB/s
Did 3752750 SHA-384 (16 bytes) operations in 1000048us (3752569.9 ops/sec): 60.0 MB/s
Did 3727000 SHA-512 (16 bytes) operations in 1000029us (3726891.9 ops/sec): 59.6 MB/s
```
After
```
$ ./tool/bssl speed -filter SHA- -chunks 16
Did 13658000 SHA-1 (16 bytes) operations in 1000061us (13657166.9 ops/sec): 218.5 MB/s
Did 11268500 SHA-224 (16 bytes) operations in 1000009us (11268398.6 ops/sec): 180.3 …
```
> Fix case issue with sha-224 in speed tool

- tool/speed.cc
V1178638288
* Fix parsing of speed tool's timeout flag.
N/A
N/A
> Fix speed tool timeout flag

- crypto/fipsmodule/evp/digestsign.c
V1178638288
* Add check/assert to verify success of hmac_update.
* This matches a [check used for other digests](https://github.com/aws/aws-lc/blob/main/crypto/fipsmodule/digest/digests.c#L72).
N/A
N/A
> check/assert hmac_update success

- CMakeLists.txt
- crypto/CMakeLists.txt
- crypto/fipsmodule/modes/asm/aesni-gcm-avx512.pl
- crypto/fipsmodule/modes/gcm.c
- crypto/fipsmodule/modes/gcm_test.cc
- crypto/fipsmodule/modes/internal.h
- crypto/impl_dispatch_test.cc
- tests/ci/run_posix_tests.sh
Backports https://github.com/aws/aws-lc/pull/945 to the fips-2022-11-02 branch.
> [Backport] Provide a compile option to disable AVX512-specific optimizations.

- tests/ci/integration/run_haproxy_integration.sh
This updates the HAProxy test to follow our recent integration test best practice and adds a check that the shared library build of HAProxy is indeed loading AWS-LC. Quote variables to fix minor shellcheck warnings, and stop passing in the unused `HAPROXY_SRC` folder, the `build_and_test_haproxy` function already knows where the code is. 
Tested locally and in CI.
> Add an additional test that HAProxy is built with AWS-LC

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
New version number FIPS release with Kyber and AVX fixes. https://github.com/aws/aws-lc/releases/edit/untagged-6e40ce6d2c92d9afe58c
> FIPS 2.0.4 release version number update

- .github/workflows/actions-ci.yml
- .github/workflows/aws-lc-rs.yml
- .github/workflows/codecov-ci.yml
- .github/workflows/cross-test.yml
- .github/workflows/integrations.yml
We're getting a lot of failures like https://github.com/aws/aws-lc/actions/runs/7469118239/job/20325716833?pr=1390:
```
Err:3 http://security.ubuntu.com/ubuntu jammy-updates/universe amd64 qemu-user amd64 1:6.2+dfsg-2ubuntu6.15
404  Not Found [IP: 52.147.219.192 80]
```
which is similar to https://github.com/actions/runner-images/issues/7452 and the recommended fix is [always running apt-get-update](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners).
GHA will do it.
> Always run 'apt-get update' before 'installing'

- crypto/fipsmodule/ec/ec_test.cc
Resolves V1191422372
Before this change `group_` could be uninitialized, by adding `{}` it is always initialized to null.
> Initialize ECCurveTest values to null instead of relying on uninitialized value from default constructor

- .github/workflows/abidiff.yml
- .github/workflows/actions-ci.yml
- .github/workflows/cmake.yml
- .github/workflows/integrations.yml
Update GitHub Action name config:
1. The AWS-LC in the names are redundant and take up space in the table
2. Only use the CMake version name, not the entire url which gets truncated:
`AWS-LC CMake Compatability / CMake Version Build (3.28, https://cmake.org/files/v3.28/cmake-3.28.1.tar.gz, 15e94f83e647f7d620a...`
becomes:
`CMake Compatability / CMake 3.2 build with Unix Makefiles`.
None of these tests are required (yet) so it should be safe to just rename them. 
Waiting to see what happens in this PR. 
> Shorten cmake test names so they fit in GitHub

- tests/ci/integration/run_mariadb_integration.sh
Addresses P112867839
This test fails 80% of the time. It could have something to do with exact error code mismatch between OpenSSL and AWS-LC. Turning it off for now and tracking the fix in P112867839.
> Turn off flaky MariaDB test main.ssl_crl

- tests/ci/cdk/cdk/codebuild/ec2_test_framework_omnibus.yaml
- tests/ci/cdk/cdk/ssm/general_test_run_ssm_document.yaml
- tests/ci/run_ec2_test_framework.sh
1. Use latest ARM Ubuntu image
2. Tag instances with a name that links back to the requesting PR to make tracking leaks easier
3. Add a final log message to see if that shows up in CloudWatch logs
I think the older AMI just happened to have an SSM agent that couldn't handle the large output of the single "command" and crashed with `document process failed unexpectedly: document worker timed out` I haven't been able to reproduce that issue with this newer AMI.
Verified in the ec2 console the new name shows up `{Key="Name",Value="ec2-test-pr/1395"}`
Manually tested with SSM run command in my account, lets see what happens here.
> Update base ec2 test framework

- crypto/fipsmodule/CMakeLists.txt
- util/fipstools/inject_hash/inject_hash.go
Backport of https://github.com/aws/aws-lc/pull/1224
* Updated: Also cherry-picked #1245, but only took changes to `crypto/fipsmodule/CMakeLists.txt`.
Build succeeded on my Mac.
> Backport: Fix AppleClang 15 FIPS Shared Build (#1224)

- crypto/err/err.c
- crypto/err/err_test.cc
- crypto/fipsmodule/rand/rand.c
- crypto/fipsmodule/self_check/fips.c
- crypto/fipsmodule/service_indicator/service_indicator.c
- crypto/internal.h
- crypto/mem.c
- crypto/thread_pthread.c
- crypto/thread_win.c
- include/openssl/err.h
- include/openssl/mem.h
P111627750
* A cherry-pick of several commits related to using the system allocator for thread-local data:
* [Add OPENSSL_asprintf and friends for asprintf(3) functionality](https://github.com/aws/aws-lc/commit/5b0a47d43b4b9a54121030220382e3d9b860a570)
* [Make ERR and thread use system malloc](https://github.com/aws/aws-lc/commit/19bfabd93acefd9318910b0d885eedecc855ab46)
* #1397
* When resolving conflicts in `mem.c` for cherry-pick of [Add OPENSSL_asprintf and friends for asprintf(3) functionality](https://github.com/aws/aws-lc/commit/5b0a47d43b4b9a54121030220382e3d9b860a570), I only only took [the added headers and changes around `OPENSSL_vasprintf_internal`](https://github.com/aws/aws-lc/commit/e609ba5e6477bfb753ce64e7c30f8c4d6b64290a)
Tests pass locally …
> FIPS-2022-11-02: thread-local using system allocator

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
Preparing release of FIPS 2.0.5 with the following changes:
* Backport: Fix AppleClang 15 FIPS Shared Build (#1224) by @justsmth in https://github.com/aws/aws-lc/pull/1400
* FIPS-2022-11-02: thread-local using system allocator by @justsmth in https://github.com/aws/aws-lc/pull/1401
> FIPS 2.0.5 release version number update

- .github/workflows/actions-ci.yml
- util/all_tests.go
Windows SDE CI dimension seems to be failing since the original version was deprecated. This updates the version to the latest one.
From an initial triage, the jobs seem to "hang" and don't finish. This is similar to what was happening with [SDE+ASAN on Linux](https://github.com/aws/aws-lc/commit/a8b2a0c87b3a9e0913f18a5cb935f7b69b224850), so the same workaround has been helping us kill some of these hanging test runs. The workaround doesn't resolve all issues for Windows SDE 32-bit however, some of the test runs fail to print `"[ PASSED ]`" at the end of the test. There are some instances where the test seems to run out of memory?
It seems like this hadn't been an issue prior to last week. The Windows SDE 32-bit CI didn't have any hanging tests at well nor did any of these issues exist. …
> temporarily turn off 32-bit Windows SDE CI

- crypto/evp_extra/p_hmac_asn1.c
- crypto/fipsmodule/evp/evp.c
- crypto/fipsmodule/evp/internal.h
- crypto/hmac_extra/hmac_test.cc
Resolves `CryptoAlg-1704`
Follow up from https://github.com/aws/aws-lc/pull/1324#issuecomment-1832848738, Bind consumes `EVP_PKEY_HMAC` though this codepath, so we'll have to add support for this within the EVP_PKEY function pointers.
OpenSSL also encourages using `EVP_PKEY_new_raw_private_key` instead of `EVP_PKEY_new_mac_key`: https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_new_mac_key.html
N/A
New test for `EVP_PKEY_{new,get}_raw_private_key`
> allow HMAC via EVP_PKEY raw privkey functions

- tests/ci/integration/run_mariadb_integration.sh
Addresses P112867839
This test appears unrelated to crypto but happened to fail in this pr https://github.com/aws/aws-lc/pull/1410. Tracking all of these issues in P112867839.
> Skip another MariaDB test that appears to be flaky. P112867839

- .github/workflows/integrations.yml
- include/openssl/rsa.h
- tests/ci/integration/run_tpm2_tss_integration.sh
- tests/ci/integration/tpm2_tss_patch/aws-lc-tpm2-tss.patch
DRAFT: Integration tests will not pass until #1338 has been merged.
N/A
* Add integration test for [tpm2-tss](https://github.com/tpm2-software/tpm2-tss).
N/A
* Ran tests on ubuntu host (rebased on #1338)
```
============================================================================
Testsuite summary for tpm2-tss 4.0.1-96-g166a5538-dirty
============================================================================
============================================================================
```
> Integration with tpm2-tss

- .github/workflows/integrations.yml
- tests/ci/integration/run_socat_integration.sh
Resolves CryptoAlg-2188
I decided to skip the renegotiation tests for now. If a customer needs socat + AWS-LC we can investigate adding the support to socat by calling `SSL_set_renegotiate_mode` which is an AWS-LC specific API. Or we could change the default behavior and enable renegotiation by default to match OpenSSL.
New GHA that runs, tested run_socat_integration.sh locally. 
> Add socat integration test

- crypto/fipsmodule/CMakeLists.txt
- tool/CMakeLists.txt
Backports https://github.com/aws/aws-lc/pull/1416 to fips-2022-11-02.
> Backport: Fix issue with iOS FIPS builds. Requires -DCMAKE_SYSTEM_NAME=iOS

- crypto/fipsmodule/service_indicator/service_indicator_test.cc
- include/openssl/base.h
Preparing release of AWS-LC-FIPS-2.0.6:
* Backport: Fix issue with iOS FIPS builds. Requires -DCMAKE_SYSTEM_NAME=iOS by @skmcgrail in https://github.com/aws/aws-lc/pull/1417
> FIPS 2.0.6 release version number update

- crypto/CMakeLists.txt
- crypto/ec_extra/hash_to_curve.c
- crypto/ec_extra/internal.h
- crypto/fipsmodule/dh/dh.c
- crypto/fipsmodule/ec/ec_test.cc
- crypto/fipsmodule/modes/asm/aesni-gcm-x86_64.pl
- crypto/hpke/hpke.c
- crypto/hpke/hpke_test.cc
- crypto/obj/obj.c
- crypto/rand_extra/getentropy_test.cc
- crypto/test/test_util.h
- generated-src/linux-x86_64/crypto/fipsmodule/aesni-gcm-x86_64.S
- include/openssl/base.h
- include/openssl/ec.h
- include/openssl/hpke.h
- include/openssl/target.h
- ssl/ssl_test.cc
- ssl/test/settings_writer.cc
- ssl/test/ssl_transfer.cc
> Upstream merge 2024 01 17

- crypto/thread_test.cc
N/A
* Adds unit test coverage for `AWSLC_thread_local_clear`
* This function also gets tested by `dynamic_loading_test.c`, but that does not run as part of the `crypto_test` target.
Tested in dev environment on my Mac.
> More test coverage for AWSLC_thread_local_clear

- tests/ci/integration/tpm2_tss_patch/aws-lc-tpm2-tss.patch
P114987425
* Update tpm2-tss
N/A
N/A
> Update patch for tpm2-tss

- crypto/fipsmodule/aes/asm/aesni-xts-avx512.pl
- generated-src/linux-x86_64/crypto/fipsmodule/aesni-xts-avx512.S
- generated-src/mac-x86_64/crypto/fipsmodule/aesni-xts-avx512.S
- generated-src/win-x86_64/crypto/fipsmodule/aesni-xts-avx512.asm
A small patch to zero out the used stack frames in the AVX-512 XTS implementation.
---
> Zero the stack after AVX-512 XTS

- .github/workflows/integrations.yml
- .gitignore
- tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml
- tests/ci/integration/python_patch/3.10/aws-lc-cpython.patch
- tests/ci/integration/python_patch/3.11/aws-lc-cpython.patch
- tests/ci/integration/python_patch/3.12/aws-lc-cpython.patch
- tests/ci/integration/python_patch/main/aws-lc-cpython.patch
- tests/ci/integration/run_python_integration.sh
Addresses i/CryptoAlg-2136
This change adds an integration test for CPython versions 3.10 through tip-of-main. Running _all_ 3.10 python module tests on my AL2 dev machine takes ~5m:
```
$ time ./tests/ci/integration/run_python_integration.sh
...
== Tests result: FAILURE then SUCCESS ==
404 tests OK.
21 tests skipped:
test_bz2 test_ctypes test_devpoll test_idle test_ioctl test_kqueue
test_msilib test_ossaudiodev test_readline test_sqlite
test_startfile test_tcl test_tix test_tk test_ttk_guionly
test_ttk_textonly test_turtle test_winconsoleio test_winreg
test_winsound test_zipfile64
1 re-run test:
test___all__
```
However, in [CI testing](https://us-west-2.console.aws.amazon.com/codesuite/codebuild/620771051181/projects/aws-lc-ci-integration/build/aws-lc-ci-integration%3A35a4d7f1-c75f-4db5- …
>  Add cpython integration test

- crypto/CMakeLists.txt
* Cleanup for CMAKE_ASM_FLAGS. Also pass debug flag to clang.
> Cleanup for CMAKE_ASM_FLAGS

- tests/ci/integration/run_mariadb_integration.sh
P112867839
* Several MariaDB tests are failing, blocking our CI approval process.
* The 3 failing tests are reporting the error: `TLS/SSL error: unable to get local issuer certificate`
https://github.com/aws/aws-lc/blob/56def5a253d27280f3b7bd6564cfa5a11211aee8/crypto/x509/x509_vfy.c#L413
```
...
// If not explicitly trusted then indicate error unless it's a single
// self signed certificate in which case we've indicated an error already
// and set bad_chain == 1
if (trust != X509_TRUST_TRUSTED && !bad_chain) {
if ((chain_ss == NULL) || !ctx->check_issued(ctx, x, chain_ss)) {
if (ctx->last_untrusted >= num) {
ctx->error = X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY;  //  <<-- FROM THIS LINE 
} else {
ctx->error = X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT;
}
ctx->current_cert = x;
...
``` …
> Disable failing MariaDB tests

- tests/ci/cdk/cdk/codebuild/github_ci_integration_omnibus.yaml
- tests/ci/integration/run_mysql_integration.sh
- tests/ci/integration/run_openssh_integration.sh
- tests/ci/run_fuzz_tests.sh
1. Split OpenSSH into two jobs, one for main branch, and another for 8.9
2. Use RelWithDebInfo build for MySQL
3. Force MySQL to use double the number of jobs to run the tests
4. Update ARM fuzzer to run for a shorter period of time
The majority of the MySQL CI time is spent building (~50 minutes) and then running the tests (22 minutes). The build already uses all CPU cores, but the tests seem not take full advantage with the default `parallel=auto` which just uses 1 test per core (orange is CPU usage %, blue is memory usage %): 
Locally and in this CI. 
> Speed up CodeBuild CI

- crypto/stack/stack_test.cc
- crypto/x509/by_dir.c
- crypto/x509/policy.c
- crypto/x509/x509_lu.c
- crypto/x509/x509_trs.c
- crypto/x509/x_crl.c
- crypto/x509v3/v3_lib.c
- crypto/x509v3/v3_purp.c
- crypto/x509v3/v3_utl.c
- include/openssl/stack.h
- ssl/handoff.cc
- ssl/handshake_client.cc
- ssl/handshake_server.cc
- ssl/ssl_cipher.cc
- ssl/ssl_file.cc
- tests/ci/integration/python_patch/3.10/aws-lc-cpython.patch
- tests/ci/integration/python_patch/3.11/aws-lc-cpython.patch
- tests/ci/integration/python_patch/3.12/aws-lc-cpython.patch
- tests/ci/integration/python_patch/main/aws-lc-cpython.patch
OpenSSL [omits][1] the `|out_index|` parameter from `|sk_*_find|`. This (breaking) change conforms with that interface and exposes our old, 3-arg interface with `|out_index|` as `|sk_*_find_awslc|`.
[1]: https://www.openssl.org/docs/man1.1.1/man3/sk_TYPE_find.html
- This is a **breaking change** for consumers using the `|sk_*_find|` function. Consuming code will need to be updated to either use the new `|sk_*_find|` function or to drop the second positional `|out_index| `parameter from their function call(s).
- CI checks
---
> Change sk_*_find signature to 2-arg for OpenSSL comapat

- crypto/crypto.c
- crypto/crypto_test.cc
- n/a
This change includes FIPS mode information in the return value of `OpenSSL_version(OPENSSL_VERSION)`. This will allow consumers of CPython (and likely other tools or language runtimes) to detect FIPS mode without calling to an AWS-LC-specific API, which would require either patching or forking the language or tool in question.
* we don't modify `OPENSSL_VERSION_TEXT` in `crypto.h` as it's deprecated
* CI testing
* built cpython 3.10 against this before/after:
```
$ ./python -c 'import ssl; print(ssl.OPENSSL_VERSION)'
AWS-LC 1.20.0
$ ./python -c 'import ssl; print(ssl.OPENSSL_VERSION)'
AWS-LC FIPS 1.20.0
$ ./python -c 'import ssl; print(ssl.OPENSSL_VERSION)'
AWS-LC 1.20.0
```
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> Include FIPS mode in OpenSSL_version return value

- .github/workflows/integrations.yml
- include/openssl/objects.h
- include/openssl/ssl.h
- ssl/ssl_lib.cc
- ssl/ssl_test.cc
- tests/ci/docker_images/linux-x86/ubuntu-22.04_base/Dockerfile
- tests/ci/integration/bind9_patch/bind-fix.patch
- tests/ci/integration/python_patch/3.10/aws-lc-cpython.patch
- tests/ci/integration/python_patch/3.11/aws-lc-cpython.patch
- tests/ci/integration/python_patch/3.12/aws-lc-cpython.patch
- tests/ci/integration/python_patch/main/aws-lc-cpython.patch
- tests/ci/integration/run_bind9_integration.sh
- tests/ci/integration/run_python_integration.sh
Addresses `CryptoAlg-2162`
1. Integration CI dimension for Bind9
2. Resolved "cmocka unit tests" for Bind9
* Additional `<openssl/asn1.h>` import in `<openssl/objects.h>`: Bind depends on [some ASN1 functions](https://gitlab.isc.org/isc-projects/bind9/-/blob/4330014fce5ab2ac1a6e58cd330762318a34f8d9/lib/dns/rdata.c#L625), but does not directly import the corresponding header. OpenSSL imports the [asn1 header file](https://github.com/openssl/openssl/blob/master/include/openssl/objects.h#L21) in `objects.h` (which Bind is pulling [these symbols from](https://gitlab.isc.org/isc-projects/bind9/-/blob/4330014fce5ab2ac1a6e58cd330762318a34f8d9/lib/dns/rdata.c#L21)), so I've added the header file reference to `objects.h`.
* `SSL_get_error` error anticipation fixing: There were several failures …
> Slight tweaks and integration CI to support Bind9

- ssl/ssl_test.cc
P118709392
This PR is an attempt to fix a transient issue with gcc 9.5 compilation. This is a test workflow, so no hot-path performance regression concerns from me.
gcc 9.5 has a bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95189 that has not been backported. Essentially, the compiler will falsely reason that it's comparing a string and optimise out everything behind a null-character.
In the test fixture `SSLVersionTest.DefaultTicketKeyInitialization` it appears the gcc 9.5 compiler only compares the first byte and short-circuits there. What was observed:
```
4a6274:	394243e0 	ldrb	w0, [sp, #144] <-- first byte of ticket_key
4a6278:	b90043ff 	str	wzr, [sp, #64] <-- zeroise stack (kzerokey presumably)
4a627c:	b90053e0 	str	w0, [sp, #80] <-- Put w0 back on the stack(?)
4a6280:	34000240 …
```
> Reduce compiler ability to optimise to statisfy gcc 9.5

- util/fipstools/delocate/delocate.go
- util/fipstools/delocate/testdata/aarch64-Basic/out.s
- util/fipstools/delocate/testdata/generic-FileDirectives/out.s
- util/fipstools/delocate/testdata/ppc64le-GlobalEntry/out.s
- util/fipstools/delocate/testdata/ppc64le-LoadToR0/out.s
- util/fipstools/delocate/testdata/ppc64le-Sample/out.s
- util/fipstools/delocate/testdata/ppc64le-Sample2/out.s
- util/fipstools/delocate/testdata/ppc64le-TOCWithOffset/out.s
- util/fipstools/delocate/testdata/x86_64-BSS/out.s
- util/fipstools/delocate/testdata/x86_64-Basic/out.s
- util/fipstools/delocate/testdata/x86_64-GOTRewrite/out.s
- util/fipstools/delocate/testdata/x86_64-LabelRewrite/out.s
- util/fipstools/delocate/testdata/x86_64-LargeMemory/out.s
- util/fipstools/delocate/testdata/x86_64-Sections/out.s
- util/fipstools/delocate/testdata/x86_64-ThreeArg/out.s
Backports the previously reviewed https://github.com/aws/aws-lc/pull/1424 from main to fips-2022-11-02 branch.
> [fips-2022-11-02] Backport: Fix Clang-6 FIPS static build issue (#1424)

- crypto/asn1/a_object.c
- crypto/asn1/asn1_lib.c
- crypto/asn1/tasn_new.c
- crypto/bn_extra/convert.c
- crypto/cipher_extra/e_chacha20poly1305.c
- crypto/decrepit/bio/base64_bio.c
- crypto/evp_extra/p_kem.c
- crypto/evp_extra/print.c
- crypto/fipsmodule/bn/bn.c
- crypto/fipsmodule/bn/ctx.c
- crypto/fipsmodule/bn/exponentiation.c
- crypto/fipsmodule/cipher/aead.c
- crypto/fipsmodule/cipher/cipher.c
- crypto/fipsmodule/cmac/cmac.c
- crypto/fipsmodule/digest/digest.c
- crypto/fipsmodule/hmac/hmac.c
- crypto/hpke/hpke.c
- crypto/kem/kem.c
- crypto/lhash/lhash.c
- crypto/rsa_extra/rsassa_pss_asn1.c
- crypto/x509/x509_lu.c
- crypto/x509/x509_vfy.c
- crypto/x509/x_info.c
* Use `OPENSSL_zalloc` instead of `OPENSSL_malloc` when it makes subsequent initialization unnecessary. 
* If we either define an `OPENSSL_rezalloc` or modify `OPENSSL_realloc` to call `OPENSSL_zalloc`, there's a couple more places where we might avoid subsequent initializations.
Debug/FIPS build succeeded on my Mac.
> Use OPENSSL_zalloc in more places

- crypto/fipsmodule/digest/md32_common.h
Fixing a typo in the comment in md32_common.h
The <chaining length> is 32 bytes (= 256 bits) for SHA-224 and SHA-256, and 64 bytes (= 512 bits) for SHA-384 and SHA-512. See also https://github.com/aws/aws-lc/blob/0a470e450c6f5492478319abefc6daa0e9999954/include/openssl/sha.h#L174-L179 .
N/A
N/A
> Fixing typo in comment in md32_common.h

- crypto/fipsmodule/CMakeLists.txt
- util/fipstools/delocate/delocate.go
- util/fipstools/delocate/delocate_test.go
- util/fipstools/delocate/testdata/aarch64-Basic/out.s
- util/fipstools/delocate/testdata/generic-FileDirectives-no-start-end/in.s
- util/fipstools/delocate/testdata/generic-FileDirectives-no-start-end/out.s
- util/fipstools/delocate/testdata/generic-FileDirectives/out.s
- util/fipstools/delocate/testdata/generic-Includes/out.s
- util/fipstools/delocate/testdata/ppc64le-GlobalEntry/out.s
- util/fipstools/delocate/testdata/ppc64le-LoadToR0/out.s
- util/fipstools/delocate/testdata/ppc64le-Sample/out.s
- util/fipstools/delocate/testdata/ppc64le-Sample2/out.s
- util/fipstools/delocate/testdata/ppc64le-TOCWithOffset/out.s
- util/fipstools/delocate/testdata/x86_64-BSS/out.s
- util/fipstools/delocate/testdata/x86_64-Basic/out.s
- util/fipstools/delocate/testdata/x86_64-GOTRewrite/out.s
- util/fipstools/delocate/testdata/x86_64-LabelRewrite/out.s
- util/fipstools/delocate/testdata/x86_64-LargeMemory/out.s
- util/fipstools/delocate/testdata/x86_64-Sections/out.s
- util/fipstools/delocate/testdata/x86_64-ThreeArg/out.s
CRT team was seeing failures on Clang-8 with [this](https://github.com/aws/aws-lc/commit/f61870199f1bdfe3182e493231e60ea7243edbcb) change, even though we didn't have failures for clang-8 in our CI. Opting to gate this fix on detecting the clang compiler version being used. CRT reported clang-6 fix did address their issue.
I verified that on clang-6 it continues to not emit the directive. Then verified on clang-8 that it correctly defaults to the original behavior of emitting the `.file` directive for these symbols.
> Make the clang-6 bcm-delocated.S directive behavior for start/end symbols dynamic

- crypto/fipsmodule/CMakeLists.txt
- util/fipstools/delocate/delocate.go
- util/fipstools/delocate/delocate_test.go
- util/fipstools/delocate/testdata/aarch64-Basic/out.s
- util/fipstools/delocate/testdata/generic-FileDirectives-no-start-end/in.s
- util/fipstools/delocate/testdata/generic-FileDirectives-no-start-end/out.s
- util/fipstools/delocate/testdata/generic-FileDirectives/out.s
- util/fipstools/delocate/testdata/ppc64le-GlobalEntry/out.s
- util/fipstools/delocate/testdata/ppc64le-LoadToR0/out.s
- util/fipstools/delocate/testdata/ppc64le-Sample/out.s
- util/fipstools/delocate/testdata/ppc64le-Sample2/out.s
- util/fipstools/delocate/testdata/ppc64le-TOCWithOffset/out.s
- util/fipstools/delocate/testdata/x86_64-BSS/out.s
- util/fipstools/delocate/testdata/x86_64-Basic/out.s
- util/fipstools/delocate/testdata/x86_64-GOTRewrite/out.s
- util/fipstools/delocate/testdata/x86_64-LabelRewrite/out.s
- util/fipstools/delocate/testdata/x86_64-LargeMemory/out.s
- util/fipstools/delocate/testdata/x86_64-Sections/out.s
- util/fipstools/delocate/testdata/x86_64-ThreeArg/out.s
Backports https://github.com/aws/aws-lc/pull/1456 to fips-2022-11-02 branch.
> [Backport] Make the clang-6 bcm-delocated.S directive behavior for start/end symbols dynamic

- .github/workflows/aws-lc-rs.yml
- crypto/fipsmodule/sha/asm/sha256-armv4.pl
- generated-src/ios-arm/crypto/fipsmodule/sha256-armv4.S
- generated-src/linux-arm/crypto/fipsmodule/sha256-armv4.S
* Addresses failure [seen here](https://github.com/aws/aws-lc-rs/actions/runs/8019806331/job/21908336880?pr=340#step:8:480) on `arm-linux-androideabi`.
```
/tmp/sha256-armv4-f3213e.s:1455:2: error: out of range pc-relative fixup value
adr r14,K256
^
```
* Fix extracted from this [recent upstream commit](https://github.com/google/boringssl/commit/12316ab445eef5317391a94bef733fa6ff175173).
* Extended `aws-lc-rs` CI test to provide better coverage of the older arm (< v7) cpus.
> Avoid out of range pc-relative fixup value

- util/fipstools/delocate/delocate.go
- util/fipstools/delocate/testdata/aarch64-Basic/out.s
Cross-compiling with:
```
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/xcc/aarch64-unknown-linux-gnueabi/bin/aarch64-unknown-linux-gnueabi-gcc
```
Resulted in:
```
Scanning dependencies of target bcm_hashunset
[  6%] Building ASM object crt/aws-lc/crypto/fipsmodule/CMakeFiles/bcm_hashunset.dir/bcm-delocated.S.o
bcm.c: Assembler messages:
bcm.c:15025: Error: operand 2 must be an integer register -- `stp x0,lr,[sp,#-16]!'
bcm.c:15028: Error: operand 2 must be an integer register -- `ldp x0,lr,[sp],#16'
bcm.c:15084: Error: operand 2 must be an integer register -- `stp x0,lr,[sp,#-16]!'
bcm.c:15087: Error: operand 2 must be an integer register -- `ldp x0,lr,[sp],#16'
bcm.c:18003: Error: operand 2 must be an integer register -- `stp x0,lr,[sp,#-16]!' …
```
> Use x30 instead of lr which otherwise trip some versions of gcc

- crypto/fipsmodule/bcm.c
* Backport to the FIPS branch of: #1460
> [Backport] Android 14: Don't set execute-only on FIPS .text segment

- include/openssl/err.h
- n/a
Defining our various `ERR_LIB_*` as enum values rather than macros prevents the preprocessor (or other projects' preprocessors) from seeing them, potentially cuasing subtle and unexpected behavior at pre-process itme, then made even more subtle at build/run time. The macro-based approach requires manually providing integer values for individual error codes, but this inconvenience is worth if for [increased OpenSSL compatibility][1].
This issue was found due to a failing [test][2] in CPython that relies on an [array built at pre-process time][3]. Prior to this change, that array was not populated with any entries, as the preprocessor wasn't aware of the `enum` in our `err.h`, though obviously the compiler would would be aware.
[1]: …
> Convert ERR_LIB_* from enum to macros

- PORTING.md
- PORTING_TO_AWSLC.md
- docs/porting/configuration-differences.md
- docs/porting/functionality-differences.md
Update porting guide for AWS-LC. This is the first phase, which just includes the text and tables. Second phase will include links to the corresponding functions/sections for the tables along with updated function documentation.
There were some issues auto-generating the Markdown files with the internal docs. Apparently Markdown doesn't support merged row/columns, so I had to use html instead.
I'll write up a runbook on how to regenerate the files.
> Add updated porting guide for AWS-LC

- .github/workflows/cross-test.yml
- README.md
- tests/ci/README.md
* Add CI coverage for riscv64, armv6 and loongarch64.
* Update "Other Platforms" section of README.
> Add more platforms to CI

- .github/workflows/integrations.yml
- tests/ci/integration/run_strongswan_integration.sh
Resolves PQCrypto-7
This CI job tests AWS-LC against the tip of strongswan/master. We use
AWS-LC's shared library build and override the libcrypto used by
strongSwan by setting LD_LIBRARY_PATH. We also run through strongSwan's
unit test framework to make sure there are no correctness issues.
`act -W .github/workflows/integrations.yml -j strongswan`
By submitting this pull request, I confirm that …
> Adds CI job to test strongSwan integration

- cmake/go.cmake
Resolves P120917801
[CMAKE_SOURCE_DIR](https://cmake.org/cmake/help/latest/variable/CMAKE_SOURCE_DIR.html) points to the top of the CMake source tree, [PROJECT_SOURCE_DIR](https://cmake.org/cmake/help/latest/variable/PROJECT_SOURCE_DIR.html) points to the directory of the last `project()` call. When building AWS-LC by itself the two are the same directory. However, if a consumer builds AWS-LC with a call to `add_subdirectory` the paths will be different. With CMAKE_SOURCE_DIR the path to our go.mod will be wrong and point to the customer's root folder which doesn't have our go.mod and fails to build.
This shouldn't change the behavior when building AWS-LC directly. Besides the custom EC benchmark this is the last usage of CMAKE_SOURCE_DIR and everything else works for the SDK.
Manually …
> Update go.cmake to use PROJECT_SOURCE_DIR

- crypto/base64/base64.c
- crypto/base64/base64_test.cc
- crypto/decrepit/bio/base64_bio.c
- crypto/pem/pem_lib.c
- include/openssl/base64.h
tpm2-tools expects `EVP_EncodeUpdate` to return an integer, instead of being a void function: https://github.com/tpm2-software/tpm2-tools/commit/54a41786245de115c23a5163b631de8e1175940b.
Apparently the return type of this has been updated since OpenSSL 1.1.0: https://github.com/openssl/openssl/commit/cf3404fcc77aaf592c95326cbdd25612a8af6878 It seems worth updating to align with upstream. 
N/A
Slightly modified the existing test.
> Update return type for EVP_EncodeUpdate

- util/fipstools/delocate/delocate.go
- util/fipstools/delocate/testdata/aarch64-Basic/out.s
Backport to fips-2022-11-02:
* #1464 
["LR" is a synonym for the x30 register](https://developer.arm.com/documentation/dui0801/b/BABBDBAD), so this change has no impact on the resulting binary.  Specifically, this does not alter the hash used by the FIPS power-on-self-test.
Verified the hash (`BORINGSSL_bcm_text_hash`) values did not change before/after this PR.
> [Backport] Use x30 instead of lr which otherwise trip some versions of gcc

- crypto/fipsmodule/rsa/internal.h
- crypto/fipsmodule/rsa/rsa.c
- crypto/fipsmodule/rsa/rsa_impl.c
- crypto/rsa_extra/rsa_asn1.c
- crypto/rsa_extra/rsa_test.cc
- include/openssl/rsa.h
CryptoAlg-2280
This is the second PR in a series of PRs that will attempt to
consolidate the RSA key checking in AWS-LC. In this PR:
- replace RSA_check_key with the new implementation from #1349:
(0a470e450c6f5492478319abefc6daa0e9999954)
- add support for stripped private keys (JCA),
- remove RSA_validate_key
> RSA key check consolidation part 1b

- crypto/base64/base64.c
Resolves #P121857409
Coverity pointed that total was not used in this `if` statement which returns right away. It was because of introducing the return statements in https://github.com/aws/aws-lc/commit/6d9a7675d1f7c2f159b76e4ade309220d54d96f4.
The comments indicate that the intention is to update out_len as on line 180.
> Update return value from EVP_Encode_Update in one error case

- crypto/asn1/a_i2d_fp.c
- crypto/asn1/asn1_test.cc
- crypto/bio/bio.c
- include/openssl/asn1.h
- include/openssl/type_check.h
tmp2-tools defines some of it's own ASN1 structures and [depends](https://github.com/tpm2-software/tpm2-tools/blob/beaecabac2e9c1f26afcb5658c2cdf244c6ad8cc/tools/misc/tpm2_certifyX509certutil.c#L51) on some removed functions & macros.
The removal of these were spread across https://github.com/aws/aws-lc/commit/792c1dc43eb888470b2ecb162be2acc5e0e1d61b and https://github.com/aws/aws-lc/commit/419144adce049b5341bd94d355c52d099eac56e3. 
N/A
Parsing and verifying the contents against our existing ASN1 functions.
> Add ASN1_i2d_bio and ASN1_i2d_bio_of back

- tests/ci/cdk/cdk/codebuild/github_ci_linux_x86_omnibus.yaml
- tests/ci/run_benchmark_build_tests.sh
- tool/speed.cc
Handle newer versions of speed.cc being built with older versions of AWS-LC that don't have dilithium or secp256k1. This is the same check we have [down below](https://github.com/aws/aws-lc/blob/main/tool/speed.cc#L2718) but forgot this spot.
This is helpful for the canary.
Trying to test locally but running into compiler/delocate issues. The new check in the CI should handle this all.
> Only enable dilithium and secp256k1 benchmark if AWS-LC API supports it

- tests/ci/run_benchmark_build_tests.sh
BoringSSL does not install libdecrepit by default, so our benchmark patches the file to install it to simplify our testing. They recently moved this to sources.cmake and the top level CMakeList.txt in https://github.com/google/boringssl/commit/0cb032aa4c677ad432dc422276d7b963c6acbb58. This causes issues for CI which now doesn't install libdecrepit and then fails to link the AES XTS implementation from libdecrepit. This change updates that.
Ran locally
> Update the BoringSSL benchmark to install libdecrepit

- tests/ci/cdk/cdk/aws_lc_ec2_test_framework_ci_stack.py
- tests/ci/cdk/cdk/bm_framework_stack.py
- tests/ci/cdk/cdk/windows_docker_image_build_stack.py
- tests/ci/cdk/run-cdk.sh
- tests/ci/cdk/util/iam_policies.py
- tests/ci/run_ec2_test_framework.sh
Resolves `V1177876714`
There were a few overscoped IAM policies in our CI. Best practice is to minimize permissions, so we're enforcing that here.
* I've moved some of the ec2 resource creations to cdk instead of the original cli methods. The framework should be able to access these via Codebuild environment variables.
* I checked our S3 bucket policies, but discovered that the automated windows docker doesn't work anymore. This was due to docker not being installed by default. The new minimal S3 permissions work, but I've left a TODO to fix this later on.
N/A
"Works in my account": https://github.com/samuel40791765/aws-lc/pull/31
> Fix overscoped json policies in CI

- .github/workflows/integrations.yml
- tests/ci/integration/run_tpm2_tss_integration.sh
- tests/ci/integration/tpm2_tools_patch/aws-lc-tpm2-tools.patch
This builds upon the work we've done in https://github.com/aws/aws-lc/commit/c065ab2baa130de0d547b1064ca2fe904a83d547 and adds an integration CI for tpm2-tools.
This depends on https://github.com/aws/aws-lc/pull/1481 and https://github.com/aws/aws-lc/pull/1486 to work.
N/A
New CI dimension. Integration tests will be turned on once "tpm_server" is fixed ([test dependency requirement](https://github.com/tpm2-software/tpm2-tools/blob/c55288f0fab3d83ae1dee0bc022c393509f839fe/docs/INSTALL.md#optional-dependencies)).
> Add integration CI for tpm2-tools

- .github/workflows/aws-lc-rs.yml
Rust sanity check seems to be broken with removed docker functionalities from ubuntu-latest.
> Attempt to fix rust sanity check
